Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2022-09, with the labels that each got.

#854 Bug 2115280: Fix ci HCO version
  Dockerfile
  cypress/tests/catalog/filter.spec.ts
  cypress/utils/const/template.ts
  deploy-kubevirt-gating.sh
  test-prow-e2e.sh
Labels: lgtm, approved

#855 Bug 2111378: VM SSH command generated by UI points at api VIP
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
  src/utils/components/SSHAccess/components/SSHCheckbox.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#850 CNV18218: Add migration progress popover
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Timestamp/utils/datetime.ts
  src/utils/utils/units.ts
  src/views/catalog/utils/quantity.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/components/BandwidthConsumptionChart/BandwidthConsumptionChart.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/BandwidthConsumptionChart/utils.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationsTable.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineInstanceMigration.ts
  src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/MigrationProgressPopover/MigrationProgressPopover.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/MigrationProgressPopover/utils.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
  src/views/virtualmachines/utils/virtualMachineStatuses.ts
Labels: lgtm, approved

#857 Vertical align label
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/virtual-machine-page-title.scss
Labels: lgtm, approved

#856 CNV19691: Add table column management to VM list
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved

#809 check all pages can be loaded normally
  cypress/support/nav.ts
  cypress/support/project.ts
  cypress/support/selectors.ts
  cypress/tests/check-tabs.spec.ts
  cypress/tests/overview.spec.ts
  cypress/utils/const/index.ts
  cypress/views/selector.ts
  cypress/views/tab.ts
  cypress/views/vm.ts
Labels: lgtm, approved

#852 Improving virtual machine list performance
  src/views/virtualmachines/actions/components/VirtualMachineActions/VirtualMachineActions.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineInstanceMigration.ts
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/MigrationProgressPopover/MigrationProgressPopover.tsx
  src/views/virtualmachines/list/VirtualMachinesList.scss
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/list/hooks/utils/utils.ts
  src/views/virtualmachines/utils/index.ts
  src/views/virtualmachines/utils/utils.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved

#859 CNV-21029: Disable migration if its a single node cluster
  src/utils/hooks/useSingleNodeCluster.ts
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/VirtualMachineActions/VirtualMachineActions.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
Labels: lgtm, approved

#858 Fix namespace column management
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved

#862 Add column management
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationsRow.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationsTable.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/hooks/useVirtualMachineInstanceMigrationsColumns.ts
  src/views/datasources/list/DataSourcesList.tsx
  src/views/datasources/list/DataSourcesListRow.tsx
  src/views/datasources/list/hooks/useDataSourcesColumns.ts
  src/views/migrationpolicies/list/MigrationPoliciesList.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
  src/views/migrationpolicies/list/hooks/useMigrationPoliciesListColumns.ts
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
Labels: lgtm, approved

#863 Bug 2124594: Docker prefix - create datasource
  src/views/datasources/list/CreateDataSourceModal/CreateDataSourceForm.tsx
  src/views/datasources/list/CreateDataSourceModal/CreateDataSourceModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#861 Bug 2117813: Display 'Not available' for a stopped VM
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/GuestAgentIsRequiredText/GuestAgentIsRequiredText.tsx
  src/views/virtualmachines/actions/components/CloneVMModal/components/ConfigurationSummary.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#848 Create VM statuses card
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/vm/utils/constants.ts
  src/utils/resources/vm/utils/vmStatus.ts
  src/views/clusteroverview/OverviewTab/OverviewTab.tsx
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusesCard.scss
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusesCard.tsx
  src/views/clusteroverview/OverviewTab/vm-statuses-card/utils/constants.ts
  src/views/clusteroverview/OverviewTab/vm-statuses-card/utils/utils.ts
  src/views/virtualmachines/details/tabs/details/components/sections/UserList/ActiveUserListRowVm.tsx
Labels: lgtm, approved

#866 Bug 2124597: Datasource Typo
  locales/en/plugin__kubevirt-plugin.json
  src/views/datasources/list/DataSourcesList.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#865 Bug 2106963: Env bus type fix
  src/utils/components/EnvironmentEditor/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#867 Bug 2124565: Deleted datasource reappear in the ui
  src/views/datasources/hooks/useDataSourceActions.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#845 CNV-19687: Sidebar editor
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SidebarEditor/SidebarEditor.tsx
  src/utils/components/SidebarEditor/SidebarEditorContext.tsx
  src/utils/components/SidebarEditor/SidebarEditorSwitch.tsx
  src/utils/components/SidebarEditor/sidebar-editor.scss
  src/utils/components/SidebarEditor/utils.ts
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/tabs/details/VirtualMachineDetailsPage.tsx
  src/views/virtualmachines/details/tabs/details/components/sections/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/scheduling/VirtualMachineSchedulingPage.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/SchedulingSection/SchedulingSection.tsx
Labels: lgtm, approved

#864 Bug 2124582: Fix filter by OS - VM list
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#868 Bug 2124572: Datasource add annotations fix
  src/utils/components/AnnotationsModal/AnnotationsModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#869 Bug 2117549: Cannot edit cloud-init data after add ssh key
  src/utils/components/CloudinitModal/utils/useCloudInit.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#870 Bug 2108638: Last namespace path fix
  src/utils/hooks/useActiveNamespacePath.ts
  src/utils/hooks/useLastNamespacePath.ts
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/details/TemplatePageTitle.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
  src/views/virtualmachines/list/components/VirtualMachineBreadcrumb/VirtualMachineBreadcrumb.tsx
  src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceBreadcrumb/VirtualMachineInstanceBreadcrumb.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#871 Bug 2124557: Add description of migration policy to migration policy page
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyDescriptionItem.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#876 Match http path to nginix configuration path
  Dockerfile
Labels: lgtm, approved

#880 Make overview page namespace aware
  console-extensions.json
  package.json
  src/views/clusteroverview/ClusterOverviewPage.tsx
  yarn.lock
Labels: lgtm, approved

#875 CNV-19687: Sidebar editor in other vm page tabs
  src/utils/components/SidebarEditor/SidebarEditor.tsx
  src/views/virtualmachines/details/tabs/disk/DiskListPage.tsx
  src/views/virtualmachines/details/tabs/disk/disk-list-page.scss
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskList.tsx
  src/views/virtualmachines/details/tabs/network/NetworkInterfaceListPage.tsx
  src/views/virtualmachines/details/tabs/network/network-interface-list-page.scss
  src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx
  src/views/virtualmachines/details/tabs/scripts/scripts-tab.scss
Labels: lgtm, approved

#837 Refactor alerts card to work with overview page
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AlertsCard/AlertStatusItem.scss
  src/utils/components/AlertsCard/AlertStatusItem.tsx
  src/utils/components/AlertsCard/AlertsCard.scss
  src/utils/components/AlertsCard/AlertsCard.tsx
  src/utils/components/AlertsCard/AlertsCardAccordionItem.tsx
  src/utils/components/AlertsCard/AlertsDrawer.tsx
  src/utils/components/AlertsCard/utils/constants.ts
  src/utils/components/AlertsCard/utils/types.ts
  src/utils/components/AlertsCard/utils/utils.tsx
  src/utils/components/FormPFSelect/FormPFSelect.tsx
  src/utils/components/Timestamp/Timestamp.tsx
  src/utils/constants/constants.ts
  src/utils/hooks/useKubevirtAlerts.ts
  src/views/clusteroverview/MonitoringTab/top-consumers-card/TopConsumersCard.tsx
  src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/TopConsumerCard.tsx
  src/views/clusteroverview/OverviewTab/OverviewTab.tsx
  src/views/clusteroverview/OverviewTab/alerts-card/OverviewAlertsCard.scss
  src/views/clusteroverview/OverviewTab/alerts-card/OverviewAlertsCard.tsx
  src/views/clusteroverview/OverviewTab/alerts-card/hooks/useAlerts.ts
  src/views/clusteroverview/OverviewTab/status-card/utils/VirtualizationAlerts.tsx
  src/views/clusteroverview/OverviewTab/status-card/utils/hooks/useFilteredAlerts.ts
  src/views/clusteroverview/OverviewTab/status-card/utils/utils.tsx
  src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/VirtualMachinesOverviewTabAlerts.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/VirtualMachinesOverviewTabAlertsAccordionItem.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/virtual-machines-overview-tab-alerts.scss
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisks.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfaces.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/VirtualMachinesOverviewTabSnapshots.tsx
  src/views/virtualmachines/details/tabs/overview/utils/hook/useVMAlerts.tsx
  src/views/virtualmachines/details/tabs/overview/utils/url.ts
  src/views/virtualmachines/details/tabs/overview/utils/utils.tsx
Labels: lgtm, approved

#873 [release-4.11] Bug 2119607: Env save button fix
  src/views/catalog/wizard/tabs/environment/hook/useEnvironments.ts
  src/views/virtualmachines/details/tabs/environment/hooks/useEnvironments.ts
Labels: lgtm, approved, bugzilla/severity-high

#884 Bug 2124307: Fix crash/stuck of detaching disk
  src/views/virtualmachines/details/tabs/disk/modal/hooks/useVolumeOwnedResource.tsx
  src/views/virtualmachines/details/tabs/disk/modal/hooks/utils/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#878 CNV 19687: Sidebar editor in environment tab
  src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentEditor.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentFormTitle.tsx
  src/utils/components/EnvironmentEditor/constants.ts
  src/utils/components/EnvironmentEditor/hooks/useEnvironments.ts
  src/utils/components/EnvironmentEditor/tests/useEnvironments.test.tsx
  src/utils/components/EnvironmentEditor/tests/utils.test.ts
  src/utils/components/EnvironmentEditor/utils.ts
  src/utils/components/SidebarEditor/SidebarEditor.tsx
  src/utils/components/SidebarEditor/SidebarEditorContext.tsx
  src/utils/components/SidebarEditor/SidebarEditorSwitch.tsx
  src/views/virtualmachines/details/tabs/environment/VirtualMachineEnvironmentPage.tsx
Labels: lgtm, approved

#881 Bug 2127787: Adding source pvc to datasource details page
  src/views/datasources/details/components/DataSourceDetailsGrid.tsx/DataSourceDetailsGrid.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#882 CNV 21085: Adding disks interface column
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisksRow.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/hooks/useVirtualMachinesOverviewTabDisksColumns.ts
Labels: lgtm, approved

#885 Bug 2127931: Change top consumer metrics default to 30 minutes
  src/views/clusteroverview/MonitoringTab/top-consumers-card/TopConsumersCard.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#887 CNV 19687: SidebarEditor for templates
  src/utils/components/SidebarEditor/SidebarEditor.tsx
  src/utils/components/SidebarEditor/SidebarEditorContext.tsx
  src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
  src/views/templates/details/TemplateNavPage.tsx
  src/views/templates/details/tabs/details/TemplateDetailsPage.scss
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/disks/components/DiskRow.tsx
  src/views/templates/details/tabs/disks/template-disk-tab.scss
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/network/template-network-tab.scss
  src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
  src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
  src/views/templates/details/tabs/scripts/template-scripts-tab.scss
Labels: lgtm, approved

#838 Create resources inventory card
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/shared.ts
  src/utils/tests/resource.test.ts
  src/views/clusteroverview/OverviewTab/OverviewTab.tsx
  src/views/clusteroverview/OverviewTab/resources-inventory-card/ResourceInventoryItem.tsx
  src/views/clusteroverview/OverviewTab/resources-inventory-card/ResourcesInventoryCard.scss
  src/views/clusteroverview/OverviewTab/resources-inventory-card/ResourcesInventoryCard.tsx
  src/views/clusteroverview/OverviewTab/resources-inventory-card/hooks/useResourcesQuantities.ts
Labels: lgtm, approved

#888 CNV 19687: SidebarEditor for wizard overview & envs tabs
  src/utils/components/SidebarEditor/SidebarEditor.tsx
  src/utils/styles/_secondary-editor.scss
  src/utils/styles/secondary-editor.scss
  src/views/catalog/wizard/Wizard.scss
  src/views/catalog/wizard/Wizard.tsx
  src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
  src/views/catalog/wizard/tabs/environment/wizard-environment-tab.scss
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.scss
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
  src/views/templates/details/tabs/details/TemplateDetailsPage.scss
Labels: lgtm, approved

#877 Refactor VMs per template card to be namespaced
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsChartDonut/MigrationsChartDonut.tsx
  src/views/clusteroverview/OverviewTab/OverviewTab.tsx
  src/views/clusteroverview/OverviewTab/inventory-card/utils/vm-status-section/VMStatusSection.tsx
  src/views/clusteroverview/OverviewTab/running-vms-per-template-card/hooks/useRunningVMsPerTemplateResources.ts
  src/views/clusteroverview/OverviewTab/vms-per-template-card/VMsPerTemplateCard.scss
  src/views/clusteroverview/OverviewTab/vms-per-template-card/VMsPerTemplateCard.tsx
  src/views/clusteroverview/OverviewTab/vms-per-template-card/hooks/useVMsPerTemplateResources.ts
  src/views/clusteroverview/OverviewTab/vms-per-template-card/utils/EmptyStateNoVMs.tsx
  src/views/clusteroverview/OverviewTab/vms-per-template-card/utils/RunningVMsChartLegend.scss
  src/views/clusteroverview/OverviewTab/vms-per-template-card/utils/RunningVMsChartLegend.tsx
  src/views/clusteroverview/OverviewTab/vms-per-template-card/utils/RunningVMsChartLegendLabel.scss
  src/views/clusteroverview/OverviewTab/vms-per-template-card/utils/RunningVMsChartLegendLabel.tsx
  src/views/clusteroverview/OverviewTab/vms-per-template-card/utils/constants.ts
  src/views/clusteroverview/OverviewTab/vms-per-template-card/utils/utils.ts
Labels: lgtm, approved

#883 Bug 2127843: Fixed UI crash when selecting Live migration network
  src/views/clusteroverview/SettingsTab/LiveMigrationTab/Network/Network.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#889 CNV 19687: Sidebar editor in template parameters tab
  src/utils/components/SidebarEditor/SidebarEditor.tsx
  src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
  src/views/templates/details/tabs/parameters/template-parameters-page.scss
Labels: lgtm, approved

#886 Bug 2128002: Display VM Templates list after template deletion
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DeleteResourceMessage/DeleteResourceMessage.tsx
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#892 Bug 2129084: Fix vm status filters
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#891 Bug 2129301: Fix cloud-init add network data checkbox
  src/utils/components/CloudinitModal/utils/useCloudInit.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#895 Bug 2128948: Missing source at datasource yaml
  console-extensions.json
  src/templates/datasource-yaml.ts
  src/templates/index.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#897 Bug 2124555: View documentation link on MigrationPolicies page doesn't work
  src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#894 Add message alerting users to scope of the settings tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/SettingsTab/SettingsTab.tsx
  src/views/clusteroverview/SettingsTab/settings-tab.scss
Labels: lgtm, approved

#872 CNV 21087: Changes to the Review and create page when creating a VM
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
  src/utils/resources/template/utils/helpers.ts
  src/views/catalog/customize/CustomizeVirtualMachine.tsx
  src/views/catalog/customize/components/CustomizeForms/CustomizeForm.tsx
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
  src/views/catalog/customize/components/CustomizeVirtualMachineHeader.tsx
  src/views/catalog/customize/components/CustomizeVirtualMachineSkeleton.tsx
  src/views/catalog/customize/components/ExpandableOptionsFields.scss
  src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx
Labels: lgtm, approved

#896 Bug 2128949: Cannot create MigrationPolicy from example YAML
  console-extensions.json
  src/templates/index.ts
  src/templates/migrationpolicy-yaml.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified
