Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2022-06, with the labels that each got.

#528 remove mock cypress test
  cypress/tests/VirtualMachinesList.spec.ts
Labels: lgtm, approved

#478 Bug 2081182: change to use node IP in ssh command
  src/utils/components/UserCredentials/useSSHCommand.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#504 Bug 2090057: Make Help icon small in VM Environment, Disks tab
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskListTitle.tsx
  src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemListTitle.tsx
  src/views/virtualmachines/details/tabs/disk/tables/tables.scss
  src/views/virtualmachines/details/tabs/environment/components/VirtualMachineEnvironmentTabTitle.scss
  src/views/virtualmachines/details/tabs/environment/components/VirtualMachineEnvironmentTabTitle.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#519 Bug 2087583: Show more info about boot source in template list
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
  src/views/templates/list/hooks/useTemplatesWithAvailableSource.ts
  src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#526 Bug 2090043: fix boot order default display
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/BootOrder/EmptyBootSourceSummary.tsx
  src/views/virtualmachines/details/tabs/details/components/BootOrderSummary/BootOrderSummary.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/BootOrder/BootOrder.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#508 Bug 2091761: Miss "Edit labels" and "Edit annotations" in template kebab
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#513 Bug 2091762: Template alert on details title
  src/views/templates/details/NoEditableTemplateAlert.tsx
  src/views/templates/details/TemplatePageTitle.tsx
  src/views/templates/details/no-editable-template-alert.scss
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
  src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
  src/views/templates/details/tabs/scripts/TemplateYAMLPage.tsx
  src/views/templates/details/tabs/yaml/TemplateYAMLPage.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#532 Fix Missing i18n Keys and align i18n versions with console
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/CloneTemplateModal/SelectProject.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
  src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelectName.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelectNamespace.tsx
  src/utils/components/DiskModal/DiskFormFields/utils/constants.ts
  src/utils/components/PendingChanges/utils/constants.ts
  src/utils/hooks/useCDIUpload/useCDIUpload.ts
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
  src/views/templates/actions/components/SelectSourceOption.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineAnnotations/VirtualMachineAnnotations.tsx
  yarn.lock
Labels: lgtm, approved

#506 Bug 2089967: Adding network and model to VM overview network interfaces cards - popover
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfacesRow.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/virtual-machines-overview-tab-interfaces.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#509 Bug 2089877: Adding 5 minutes timespan utilization card VM overview
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/TimeDropdown.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#520 Bug 2091764: Clone a template should lead to the template details
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#523 Bug 2091945: delete a template should lead to templates list
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#530 Bug 2089979: adjust CPU|Memory pencil icon location
  src/views/virtualmachines/details/tabs/details/components/CPUMemory/CPUMemory.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#535 Bug 2091758: Rename OS to Operating system in filtering
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/TemplatesCatalogFilters.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#542 Bug 2091755: Change bottom "Save" to "Apply" on cloud-init script form
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloudinitModal/CloudinitModal.tsx
  src/utils/components/CloudinitModal/utils/cloudinit-utils.ts
  src/utils/components/CloudinitModal/utils/useCloudInit.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#540 Add quick starts section
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/getting-started-card/GettingStartedCard.tsx
  src/views/clusteroverview/overview/components/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
  src/views/clusteroverview/overview/components/getting-started-card/quick-starts-section/QuickStartsSection.tsx
  src/views/clusteroverview/overview/components/getting-started-card/quick-starts-section/utils.ts
  src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
  src/views/clusteroverview/overview/components/getting-started-card/utils/getting-started-content/GettingStartedLinkExtraContent.scss
  src/views/clusteroverview/overview/components/getting-started-card/utils/getting-started-content/GettingStartedLinkExtraContent.tsx
  src/views/clusteroverview/overview/components/getting-started-card/utils/getting-started-content/GettingStartedMoreLinkContent.tsx
  src/views/clusteroverview/overview/components/getting-started-card/utils/getting-started-content/GettingStartedSectionContents.scss
  src/views/clusteroverview/overview/components/getting-started-card/utils/getting-started-content/GettingStartedSectionContents.tsx
  src/views/clusteroverview/overview/components/getting-started-card/utils/getting-started-content/utils.tsx
  src/views/clusteroverview/overview/components/getting-started-card/utils/getting-started-grid/GettingStartedGrid.tsx
  src/views/clusteroverview/overview/components/getting-started-card/utils/hooks/useGettingStartedShowState.ts
  src/views/clusteroverview/overview/components/getting-started-card/utils/types.ts
  src/views/clusteroverview/overview/components/utils/PageHeader.tsx
  src/views/clusteroverview/overview/components/utils/RestoreGettingStartedButton.tsx
  src/views/clusteroverview/overview/components/utils/constants.ts
  yarn.lock
Labels: lgtm, approved

#544 Bug 2092306: VM is stucking with WaitingForVolumeBinding
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/customize/cd.ts
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/DiskSizeNumberInput.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/VolumeSize.tsx
  src/views/catalog/customize/components/CustomizeSource/utils.ts
  src/views/catalog/customize/constants.ts
  src/views/catalog/customize/utils.ts
  src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
  src/views/templates/actions/components/SelectSource.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#533 Bug 2092337: os is empty in VM details page
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#537 Bug 2091765: Prevent Edit boot source keeping in load
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/actions/VirtualMachineTemplatesActions.tsx
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/details/TemplateActions.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#541 Bug 2092052: Virtualization should be omitted in Calatog breadcrumbs
  src/views/catalog/customize/components/CustomizeVirtualMachineHeader.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
  src/views/catalog/wizard/components/WizardHeader.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#545 fix undefined edit disk modal data volume templates
  src/utils/components/DiskModal/utils/editDiskModalHelpers.ts
Labels: lgtm, approved

#547 Bug 2091754: making scheduling tab editable while VM is running- part 1
  src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
  src/utils/components/EvictionStrategyModal/EvictionStrategyModal.tsx
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/SchedulingSection/SchedulingSection.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingRightGrid.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#546 Bug 2081182: fix ssh string undefined
  src/utils/components/UserCredentials/useSSHCommand.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#550 Add missing title to Template Hardware devices field
  src/views/templates/details/tabs/details/components/DescriptionItem.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsRightGrid.tsx
Labels: lgtm, approved

#549 Bug 2089836: Add links to VM Overview card titles
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisks.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfaces.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/VirtualMachinesOverviewTabSnapshots.tsx
  src/views/virtualmachines/details/tabs/overview/utils/url.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#551 Bug 2092359: Data-test-id pvc name
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#557 Bug 2093691: Add left padding to VM create drawer content
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#521 Bug 2091003: Delete ssh service after vm delete
  src/utils/components/SSHAccess/SSHAccessModal.tsx
  src/utils/components/SSHAccess/utils.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/SSHAccess/SSHAccess.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#558 Bug 2091946: replace Gi with GiB
  src/utils/components/DiskModal/DiskFormFields/DiskSizeInput/DiskSizeNumberInput.tsx
  src/utils/resources/vm/utils/disk/size.ts
  src/views/catalog/customize/components/CustomizeSource/DiskSizeNumberInput.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/constants.ts
  src/views/catalog/utils/quantity.ts
  src/views/catalog/utils/tests/quantity.test.ts
  src/views/templates/actions/components/VolumeSize.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#561 Bug 2089942: Utilization chart links to metrics
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#500 Bug 2090035: Adding alerts card to VM overview page
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/VirtualMachinesOverviewTabAlerts.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/VirtualMachinesOverviewTabAlertsAccordionItem.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/hook/useVMAlerts.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/utils/utils.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/virtual-machines-overview-tab-alerts.scss
  yarn.lock
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#518 Bug 2090066: Improve guest login credentials
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/cloud-init-credentials.scss
  src/utils/components/Consoles/utils/constants.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#554 Bug 2092230: Template list deprecated badge
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/template/utils/constants.ts
  src/utils/resources/template/utils/helpers.ts
  src/views/templates/details/TemplatePageTitle.tsx
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#560 Bug 2091754: enable editable for scripts tab
  src/utils/components/CloudinitModal/CloudinitModal.tsx
  src/utils/components/NodeSelectorModal/utils/helpers.ts
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
  src/utils/components/VMAuthorizedSSHKeyModal/VMAuthorizedSSHKeyModal.tsx
  src/utils/components/VMAuthorizedSSHKeyModal/utils.ts
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert.tsx
  src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#562 Bug 2093773: Console crash when no serial at environment tab
  src/views/catalog/wizard/tabs/environment/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#563 Bug 2093716: Change CPU|Memory modal button to "Restore template settings"
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#565 Bug 2093772: add env resource changes boot order pending alert
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#566 Bug 2094465: Fix typo
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/customize/components/CustomizeSource/SelectCDSourceLabel.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectDiskSourceLabel.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#569 Bug 2094678: Secret or ConfigMap name replace dots
  src/views/catalog/wizard/tabs/environment/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#564 Bug 2094405: missing env resource from disks list
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/resources/vm/hooks/disk/useDisksTableData.ts
  src/views/virtualmachines/details/tabs/disk/tables/disk/hooks/useEditDiskStates.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#574 Bug 2094807: fix hw dropdown
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/HardwareDevices/form/DeviceNameSelect.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#570 Template Action: Add Edit boot source reference
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
Labels: lgtm, approved

#572 Bug 2094646: data-test-id missing on Scheduling tab
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingRightGrid.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#578 Bug 2094495: Descheduler modal has same text in two lines
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DeschedulerModal/DeschedulerModal.tsx
  src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#579 Bug 2094491: change affinity modal primary button text
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AffinityModal/AffinityModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#568 Bug 2086293: [Dark mode] Titles in Parameters tab are not visible enough
  src/views/templates/details/tabs/parameters/template-parameters-page.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#577 Bug 2093866: Make VM creation from template from default yaml work
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#567 Bug 2094440: Memory Utilization chart VM overview memory change
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#552 Bug 2091897: Cloud Init noCloud and ConfigDrive
  src/utils/resources/vmi/utils/cloud-init.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#580 Bug 2094665: dedicated resources modal stuck loading for non priv user
  src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingRightGrid.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#581 Bug 2091856: Edit Boot Source Ref
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/actions/components/EditBootSourceModal.tsx
  src/views/templates/actions/editBootSource.ts
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#583 Bug 2094222: Popover in formgroup with labelIcon
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectCDSourcePopOver.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectDiskSourcePopOver.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#584 Bug 2094481: tolerations modal show nodes link to non-priv user
  src/utils/components/TolerationsModal/TolerationsModal.tsx
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
  src/views/templates/details/tabs/scheduling/components/TolerationsModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#585 Bug 2094471: Node selector modal for non-privileged user
  src/utils/components/NodeSelectorModal/NodeSelectorModal.tsx
  src/views/templates/details/tabs/scheduling/components/NodeSelectorModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#587 Bug 2094451: Watch resource only with valid project name
  src/utils/components/DiskModal/DiskFormFields/hooks/useProjectsAndDataSources.ts
  src/utils/components/DiskModal/DiskFormFields/hooks/useProjectsAndPVCs.ts
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeClaimSelect.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeClainSelectSkeleton.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/utils.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#589 Bug 2095125: Display OS name in the Clone VM modal
  src/utils/resources/vm/utils/operation-system/operationSystem.ts
  src/views/virtualmachines/actions/components/CloneVMModal/components/ConfigurationSummary.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#588 Bug 2093867: OS for template 'vm-template-example' should matching the version of the image
  src/templates/vm-template-yaml.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#591 Bug 2095129: Display disk size units in Clone VM modal
  src/utils/resources/vm/utils/disk/size.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#593 Bug 2095532: Hide Node column in vm list if no-prov
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#575 Bug 2094813: Hide cloudinit password
  src/utils/components/CloudinitDescription/CloudInitDescription.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#594 Bug 2095570: No node in vm detail if no-priv
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#596 Bug 2096206: Consistent Template actions capitalization
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
  src/views/templates/actions/components/EditBootSourceModal.tsx
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#597 Fix VM Details blank name
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
Labels: lgtm, approved

#600 Bug 2096620: Update boot source reference modal title
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/actions/components/EditBootSourceModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#601 Bug 2096801: VM overview VNC autoconnect
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#603 Bug 2095955: Adding console screen1 and screen2 tabs
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
  src/utils/components/Consoles/components/vnc-console/vnc-console.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#599 Bug 2096333: Align releated opertors icon
  src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#529 Bug 2090037: Adding template link in single VM overview details card
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#602 Bug 2093713: fix custom wizard validation
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#604 Bug 2096492: No ownerReference in template
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#605 Bug 2095529: Fix action text Cancel Migration
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#477 Bug 2094323: Make Template Workload profile editable
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
  src/views/templates/details/tabs/details/components/WorkloadProfile.tsx
  src/views/templates/details/tabs/details/components/WorkloadProfileModal.tsx
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/hooks/useWorkloadProfile.ts
  src/views/templates/utils/constants.ts
  src/views/templates/utils/selectors.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#606 Bug 2096208: Templates in the catalog list are not sorted
  src/views/catalog/templatescatalog/utils/helpers.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#249 Add activity card to cluster overview
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/activity-card/ActivityCard.tsx
  src/views/clusteroverview/overview/components/activity-card/hooks/useDashboardActivities.ts
  src/views/clusteroverview/overview/components/activity-card/hooks/useDashboardK8sResources.ts
  src/views/clusteroverview/overview/components/activity-card/hooks/useDashboardPrometheusActivities.ts
  src/views/clusteroverview/overview/components/activity-card/utils/OngoingActivity.tsx
  src/views/clusteroverview/overview/components/activity-card/utils/RecentEvent.tsx
  src/views/clusteroverview/overview/components/activity-card/utils/constants.ts
  src/views/clusteroverview/overview/components/activity-card/utils/utils.ts
Labels: lgtm, approved

#590 Bug 2093715: Display Optional parameters correctly
  src/views/catalog/customize/components/ExpandableOptionalFields.tsx
  src/views/catalog/customize/components/ExpandableOptionsFields.scss
  src/views/catalog/customize/components/FieldGroup.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#608 Bug 2092663: no hyperlink for URL example in disk source
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#611 Bug 2093282: No inventory links for no-priv user
  src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#612 Bug 2096781: Remove provider input
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/actions/components/EditBootSourceModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#613 Bug 2096845: Windows templates scripts tab is crashed
  src/utils/components/CloudinitDescription/CloudInitDescription.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#614 Bug 2095953: Moving consoles buttons
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/access-consoles.scss
  src/utils/components/Consoles/components/vnc-console/VncConsoleActions.tsx
  src/utils/components/Consoles/components/vnc-console/vnc-console.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#615 Bug 2095530: fix empty column width
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/virtual-machine-row-layout.scss
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#616 Bug 2096511: Display Template's boot source availability correctly
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/template/utils/constants.ts
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#619 Bug 2096502: No 'Restore default settings' in template
  src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#620 Bug 2086286: [dark mode] The contrast of the Labels
  src/utils/components/LabelsModal/LabelsModal.tsx
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateCatalogDrawer.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#609 Bug 2094453: CD Source selection in VM creation flow is missing Upload option
  src/views/catalog/customize/cd.ts
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#621 Bug 2095573: Add label for env disk
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/vm/utils/disk/constants.ts
  src/utils/resources/vm/utils/disk/rowData.ts
  src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
  src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
  src/views/templates/details/tabs/disks/components/DiskRow.tsx
  src/views/templates/details/tabs/disks/hooks/useTemplateDisksTableData.ts
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/disk/DiskListPage.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRow.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#623 Bug 2092789: Overview learn more
  src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#625 Bug 2097370: Display titles in Optional parameters accordion in wizard customization page
  src/views/catalog/customize/components/FieldGroup.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#624 Bug 2096263: Display correct units for Disks size/Memory field
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
  src/utils/resources/vm/utils/disk/size.ts
  src/utils/utils/units.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogRow.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewDisksTable/WizardOverviewDisksTable.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
  src/views/templates/details/tabs/disks/components/DiskRow.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesCPUMemory.tsx
  src/views/virtualmachines/details/tabs/details/components/CPUMemory/CPUMemory.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRow.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisksRow.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#626 Bug 2094217: YAML view should reflect shanges in SSH form
  src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
  src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#628 add array fallback to environment utils
  src/views/catalog/wizard/tabs/environment/utils.ts
  src/views/virtualmachines/details/tabs/environment/utils/utils.ts
Labels: lgtm, approved

#627 Bug 2096510: VM can be created without any disk
  src/views/catalog/utils/useWizardSourceAvailable.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#632 Bug 2097586: AccessMode should stay on ReadWriteOnce
  src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
  src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#635 Bug 2092781: Hide the details card for non-admins
  src/views/clusteroverview/overview/components/details-card/DetailsCard.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#622 Bug 2092787: No operators links for no-priv user
  src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#631 Switch to useActiveNamespace
  src/utils/hooks/constants.ts
  src/utils/hooks/useActiveNamespacePath.ts
  src/utils/hooks/useLastNamespace.ts
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/details/TemplatePageTitle.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
  src/views/virtualmachines/list/components/VirtualMachineBreadcrumb/VirtualMachineBreadcrumb.tsx
  src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceBreadcrumb/VirtualMachineInstanceBreadcrumb.tsx
Labels: lgtm, approved

#633 Change ssh credentials in vm details
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHAccess/SSHAccess.tsx
  src/utils/components/UserCredentials/UserCredentials.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/SSHAccess/SSHAccess.tsx
Labels: lgtm, approved

#634 Bug 2092783: Hide the top consumers card for non-admins
  src/views/clusteroverview/overview/components/top-consumers-card/TopConsumersCard.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#639 Bug 2089825: Persist top consumer card settings
  src/utils/hooks/constants.ts
  src/utils/hooks/useLocalStorage.ts
  src/views/clusteroverview/overview/components/top-consumers-card/TopConsumersCard.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumerCard.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumersGridRow.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/constants.ts
  src/views/clusteroverview/overview/components/top-consumers-card/utils/topConsumerMetric.ts
  src/views/clusteroverview/overview/components/top-consumers-card/utils/topConsumerScope.ts
  src/views/clusteroverview/overview/components/top-consumers-card/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#638 Bug 2098135: Template replace workload label
  src/utils/resources/template/utils/constants.ts
  src/views/templates/details/tabs/details/components/WorkloadProfile.tsx
  src/views/templates/details/tabs/details/components/WorkloadProfileModal.tsx
  src/views/templates/utils/constants.ts
  src/views/templates/utils/selectors.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#637 Bug 2098134: Workload column more visible
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#636 Bug 2094848: Add view details link to details card
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/overview/components/details-card/DetailsCard.tsx
  src/views/clusteroverview/overview/components/details-card/utils/constants.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#629 Bug 2090042: Move pencil icon for BootOrder
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#640 Bug 2094208: Adding ssh public key validation to input field
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
  src/utils/components/VMAuthorizedSSHKeyModal/VMAuthorizedSSHKeyModal.tsx
  src/utils/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#642 Bug 2096510: template with no disks cant create VM
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#643 Message VM is down when vm is down or on stop state
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
Labels: lgtm, approved

#641 auto upload sholuld be auto import
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
  src/utils/resources/template/utils/constants.ts
  src/utils/resources/vm/utils/source.ts
  src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
  src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
  src/views/templates/details/tabs/disks/components/DiskRow.tsx
  src/views/templates/details/tabs/disks/hooks/useTemplateDisksTableData.ts
Labels: lgtm, approved

#646 CPU and Memory updates
  src/utils/resources/vmi/utils/cpu.ts
  src/utils/resources/vmi/utils/index.ts
  src/views/templates/list/hooks/useVirtualMachineTemplatesCPUMemory.tsx
  src/views/virtualmachines/details/tabs/details/components/CPUMemory/CPUMemory.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Scheduling/CPUMemory/CPUMemory.tsx
Labels: lgtm, approved

#647 Bug 2095537: Adjusting VM overview utilization card new design
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/VirtualMachinesOverviewTabUtilization.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/TimeDropdown.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/UtilizationThresholdCharts.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/virtual-machines-overview-tab-utilization.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#559 Bug 2086294: [Dark mode] - The number of vms per template in the donuts is visible in overview page
  package.json
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawer.tsx
  yarn.lock
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#645 Bug 2098282: Ensure onUploadedDataVolume exist
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/components/TabModal/TabModal.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#644 Bug 2092654: Add ssh auth key name with remove button
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/VMAuthorizedSSHKeyModal/SelectSecret.tsx
  src/utils/components/VMAuthorizedSSHKeyModal/VMAuthorizedSSHKeyModal.tsx
  src/utils/components/VMAuthorizedSSHKeyModal/utils.ts
  src/utils/components/VMAuthorizedSSHKeyModal/vm-auth-ssh-key-modal.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#335 Bug 2087547: Add the status card to cluster overview
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/details-card/utils/types.ts
  src/views/clusteroverview/overview/components/inventory-card/utils/vm-status-section/VMStatusSection.tsx
  src/views/clusteroverview/overview/components/status-card/StatusCard.tsx
  src/views/clusteroverview/overview/components/status-card/utils/NetworkingHealthItem.tsx
  src/views/clusteroverview/overview/components/status-card/utils/URLHealthItem.tsx
  src/views/clusteroverview/overview/components/status-card/utils/URLHealthItemPopup.tsx
  src/views/clusteroverview/overview/components/status-card/utils/VirtualizationAlerts.tsx
  src/views/clusteroverview/overview/components/status-card/utils/constants.ts
  src/views/clusteroverview/overview/components/status-card/utils/health-state-icons/BlueSyncIcon.tsx
  src/views/clusteroverview/overview/components/status-card/utils/health-state-icons/GrayUnknownIcon.tsx
  src/views/clusteroverview/overview/components/status-card/utils/hooks/useDashboardSubsystems.ts
  src/views/clusteroverview/overview/components/status-card/utils/hooks/useFilteredAlerts.ts
  src/views/clusteroverview/overview/components/status-card/utils/hooks/useKubevirtStorageOperatorCSVs.ts
  src/views/clusteroverview/overview/components/status-card/utils/storage-health-item/StatusStorageCardPopover.tsx
  src/views/clusteroverview/overview/components/status-card/utils/storage-health-item/StorageHealthItem.tsx
  src/views/clusteroverview/overview/components/status-card/utils/types.ts
  src/views/clusteroverview/overview/components/status-card/utils/utils.tsx
  src/views/clusteroverview/overview/components/utils/hooks/useDebounceCallback.ts
  src/views/clusteroverview/overview/components/utils/types.ts
  yarn.lock
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#648 Bug 2083595: DeschedulerModal is now enable even if vm is running
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#650 Bug 2093773: Console crash when no serial at environment tab VM page
  src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
  src/views/catalog/wizard/tabs/environment/utils.ts
  src/views/virtualmachines/details/tabs/environment/VirtualMachineEnvironmentPage.tsx
  src/views/virtualmachines/details/tabs/environment/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#651 Bug 2087616: Fix some css regarding utilization card
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/virtual-machines-overview-tab-utilization.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#653 Bug 2099443: Quick create for template examples
  src/templates/vm-template-yaml.ts
  src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
  src/utils/resources/vm/utils/disk/selectors.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#654 Bug 2099566: Cloudinit -> Cloud-init
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloudinitDescription/CloudinitInfoHelper.tsx
  src/utils/components/CloudinitModal/CloudinitForm.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#655 Bug 2099633: Doc links 4.9 -> 4.10
  src/utils/components/DiskModal/DiskFormFields/EnablePreallocationCheckbox.tsx
  src/utils/components/SSHAccess/constants.ts
  src/views/virtualmachines/details/tabs/snapshots/components/modal/SnapshotSupportLink/SnapshotSupportLink.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#656 Bug 2099539: Upload file storage option in edit modal
  src/utils/components/DiskModal/EditDiskModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#657 Bug 2095537: Utilization charts adding hours to charts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#652 Bug 2097586: fix storage profile settings checkbox
  src/utils/components/DiskModal/DiskFormFields/ApplyStorageProfileSettingsCheckbox.tsx
  src/utils/components/DiskModal/utils/helpers.ts
  src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
  src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#659 Bug 2099535: CDI certificate link will open in a new tab
  src/views/catalog/customize/components/FormError.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#658 Bug 2099639: remove ssh user line above ssh command
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/UserCredentials/UserCredentials.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#661 Bug 2099608: Display Dynamic instead of DynamicB for dynamic disk size
  src/utils/utils/units.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#665 Remove debugger command
  src/utils/components/AffinityModal/utils/helpers.ts
Labels: lgtm, approved

#649 Bug 2094202: cloudinit username default
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloudinitModal/CloudinitForm.tsx
  src/utils/components/CloudinitModal/CloudinitModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#660 Bug 2099573: Change text in uneditable templates alert message
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/NoEditableTemplateAlert.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#667 Bug 2099566: Cloud-init -> cloud-init text fix
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloudinitDescription/CloudinitInfoHelper.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#666 Bug 2099535: Adding target blank to error message href links
  src/utils/components/TabModal/TabModal.tsx
  src/views/catalog/customize/components/FormError.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#670 Bug 2097586: fix storage profile settings checkbox
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/AccessMode.tsx
  src/utils/components/DiskModal/DiskFormFields/ApplyStorageProfileSettingsCheckbox.tsx
  src/utils/components/DiskModal/DiskFormFields/VolumeMode.tsx
  src/utils/components/DiskModal/DiskFormFields/hooks/useStorageProfileClaimPropertySets.ts
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
  src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts
  src/views/virtualmachines/details/tabs/disk/tables/disk/hooks/useEditDiskStates.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#673 [release-4.11] Bug 2101192: fix StorageProfile settings checkbox
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/AccessMode.tsx
  src/utils/components/DiskModal/DiskFormFields/ApplyStorageProfileSettingsCheckbox.tsx
  src/utils/components/DiskModal/DiskFormFields/VolumeMode.tsx
  src/utils/components/DiskModal/DiskFormFields/hooks/useStorageProfileClaimPropertySets.ts
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
  src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts
  src/views/virtualmachines/details/tabs/disk/tables/disk/hooks/useEditDiskStates.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#674 Wizard auth secret selector
  src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
  src/utils/components/AuthorizedSSHKeyModal/SelectSecret.tsx
  src/utils/components/AuthorizedSSHKeyModal/auth-ssh-key-modal.scss
  src/utils/components/AuthorizedSSHKeyModal/utils.ts
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
Labels: lgtm, approved

#675 [release-4.11] Bug 2101485: Cloud-init -> cloud-init text fix
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloudinitDescription/CloudinitInfoHelper.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#669 Expose qemu machine type read-only in VM Details tab
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/vm/utils/selectors.ts
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved

#677 Bug 2101667: Move VMI CPU | Memory to details section, rename Operation System
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/CPUMemory/CPUMemory.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/CreateAt/CreateAt.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/OperatingSystem/OperatingSystem.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Scheduling/Scheduling.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#676 Bug 2096780: Template Auth SSH Service
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
  src/utils/components/AuthorizedSSHKeyModal/SelectSecret.tsx
  src/views/templates/details/hooks/useTemplateTabs.ts
  src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#679 hosts.yml file not a directory
  .devcontainer/docker-compose.yml
Labels: lgtm, approved

#682 Bug 2096780: Wizard Sysprep modal with existing sysprep selection
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SysprepModal/SelectSysprep.tsx
  src/utils/components/SysprepModal/SysprepModal.tsx
  src/utils/components/SysprepModal/sysprep-utils.ts
  src/utils/components/SysprepModal/sysprep.scss
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
  src/views/catalog/wizard/tabs/scripts/components/SysprepDescription.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#685 Bug 2101430: Fix customize form crash
  src/views/catalog/customize/components/ExpandableOptionalFields.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#684 Add metalice to approvers
  OWNERS
Labels: lgtm, approved

#696 Add avivtur to approvers
  OWNERS
Labels: lgtm, approved

#691 Bug 2101681: Template list fix source available
  src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
  src/views/templates/list/hooks/useTemplatesWithAvailableSource.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#695 Bug 2101667: Move VMI Scheduling section to a new tab
  src/views/virtualmachinesinstance/details/hooks/useVirtualMachinesInstanceTabs.ts
  src/views/virtualmachinesinstance/details/tabs/details/VirtualMachinesInstancePageDetailsTab.tsx
  src/views/virtualmachinesinstance/details/tabs/scheduling/Affinity/Affinity.tsx
  src/views/virtualmachinesinstance/details/tabs/scheduling/Descheduler/Descheduler.tsx
  src/views/virtualmachinesinstance/details/tabs/scheduling/DeticatedResources/DedicatedResources.tsx
  src/views/virtualmachinesinstance/details/tabs/scheduling/EvictionStrategy/EvictionStrategy.tsx
  src/views/virtualmachinesinstance/details/tabs/scheduling/NodeSelector/NodeSelector.tsx
  src/views/virtualmachinesinstance/details/tabs/scheduling/Tolerations/Tolerations.tsx
  src/views/virtualmachinesinstance/details/tabs/scheduling/VirtualMachinesInstancePageSchedulingTab.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#687 Bug 2101394: Changing the data-test-id
  src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#693 [release-4.11] Bug 2102129: Template list fix source available
  src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
  src/views/templates/list/hooks/useTemplatesWithAvailableSource.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#680 CNV 19411: Adding virtualization settings tabs
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/SettingsTab/SettingsTab.tsx
  src/views/clusteroverview/overview/components/SettingsTab/settings-tab.scss
Labels: lgtm, approved

#689 Bug 2102125: vm clone modal is displaying DV size instead of PVC size
  src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
  src/views/virtualmachines/actions/components/CloneVMModal/components/ConfigurationSummary.tsx
  src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#698 Expose qemu machine type read-only in VMI Details tab
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
Labels: lgtm, approved

#701 Bug 2101499: Template adding nic keep loading for test user
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceNetworkSelect.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
