Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2022-10, with the labels that each got.

#898 Bug 2129234: Add ownerReferences to template additional objects
  src/views/catalog/utils/quick-create-vm.ts
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#902 Bug 2101144: VM filter has two 'Other' checkboxes which are triggered together
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#903 Fix charts domain range
  src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
  src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChart.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
  src/utils/components/Charts/StorageUtil/StorageIOPSTotalThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageReadThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageWriteThresholdChart.tsx
  src/utils/components/Charts/utils/utils.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/components/BandwidthConsumptionChart/BandwidthConsumptionChart.tsx
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/hook/useNetworkData.tsx
  src/views/virtualmachines/details/tabs/metrics/hooks/useDuration.tsx
Labels: lgtm, approved

#901 Fix type of the t function as the argument of getDataImportCronFilter
  src/views/datasources/list/DataSourcesList.tsx
  src/views/datasources/list/DataSourcesListFilters.ts
Labels: lgtm, approved

#879 Bug 2124558: Allow MigrationPolicy creation only to privileged user
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx
  src/views/migrationpolicies/list/MigrationPoliciesList.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#908 Bug 2132932: VM disk size "dynamic" only on ephemeral
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
  src/utils/components/DiskModal/state/initialState.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#907 Bug 2132783: Template Source loaded with registry, URL, containerDisk
  src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#911 remove tests about vmi
  cypress/tests/check-tabs.spec.ts
Labels: lgtm, approved

#904 Disabled SSH command checkbox
  src/utils/components/SSHAccess/components/SSHCheckbox.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
Labels: lgtm, approved

#913 Bug 2132793: Load and show boot source reference
  src/views/templates/actions/components/EditBootSourceModal.scss
  src/views/templates/actions/components/EditBootSourceModal.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeClaimSelect.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/utils.tsx
  src/views/templates/actions/components/SelectSource.tsx
  src/views/templates/actions/components/SelectSourceSkeleton.tsx
  src/views/templates/actions/components/utils.ts
  src/views/templates/actions/editBootSource.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#910 Bug 2071491: Fix storage throughput value in Top Consumers card
  src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#905 Bug 2131157: Adding KV disk data rate to metrics tab
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChartDiskRate.tsx
  src/utils/components/Charts/utils/queries.ts
  src/views/virtualmachines/details/tabs/metrics/MigrationCharts/MigrationCharts.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#787 Bug 2101501: Display VM name in Create VM drawer according to the NAME
  cypress/tests/catalog/create-vm-from-catalog.spec.ts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/utils/utils.ts
  src/views/catalog/customize/components/CustomizeForms/CustomizeForm.tsx
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#915 Bug 2132682: Default YAML entity name convention.
  src/templates/vm-template-yaml.ts
  src/templates/vm-yaml.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#899 Bug 2093771: The disk source should be PVC if the template has no auto-update boot source
  cypress/utils/const/testVM.ts
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/customize/CustomizeVirtualMachine.tsx
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
  src/views/catalog/customize/tests/CustomizeSource.test.tsx
  src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#912 [release-4.11] CNV-19298: SSH access with virtctl command
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHAccess/SSHAccess.tsx
  src/utils/components/SSHAccess/SSHAccessModal.tsx
  src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
  src/utils/components/SSHAccess/components/SSHCheckbox.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
  src/utils/components/SSHAccess/useSSHCommand.ts
  src/utils/components/SSHAccess/utils.ts
  src/utils/components/UserCredentials/UserCredentials.tsx
  src/views/templates/utils/selectors.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/RunningVirtualMachineDetailsRightGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/SSHAccess/SSHAccess.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/SSHDetails/SSHDetails.tsx
Labels: lgtm, approved

#922 Bug 2132746: Background is broken in Virtualization Monitoring page
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/ClusterOverviewPage.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#917 Bug 2119615: The unit field doesn't change if the size number is big enough in Disk modal
  src/utils/components/CapacityInput/CapacityInput.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#923 Bug 2117803: Display correct command with username for SSH
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
  src/utils/components/SSHAccess/useSSHCommand.ts
  src/utils/resources/vmi/utils/cloud-init.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGrid.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#916 Bug 2131165: Fixed in virtual machine statuses card the dark mode and removing icons
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusesCard.scss
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusesCard.tsx
  src/views/clusteroverview/OverviewTab/vm-statuses-card/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#925 Bug 2137241: Checkbox about delete vm disks is not loaded while deleting VM
  src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDataVolumeConvertedVolumeNames.ts
  src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
  src/views/virtualmachines/details/tabs/disk/modal/hooks/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#927 Bug 2137349: Prevent "Manage source" action from loading infinitely
  src/views/datasources/dataimportcron/hooks/useDataImportCronActions.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#930 Bug 2137736: The column name "MigrationPolicy name" can just be "Name"
  src/views/migrationpolicies/list/hooks/useMigrationPoliciesListColumns.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#929 Bug 2137731: Overview links for VM status not working
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx
  src/views/clusteroverview/OverviewTab/vm-statuses-card/utils/utils.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
  src/views/virtualmachines/utils/virtualMachineStatuses.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#932 Bug 2136425: Windows 11 is detected as Windows 10
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#933 Bug 2132746: Background is broken in Virtualization Settings page
  src/views/clusteroverview/SettingsTab/settings-tab.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#934 Bug 2132744: Wrong casing in Live Migrations section
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/SettingsTab/LiveMigrationTab/Limits/Limits.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#931 Bug 2137243: Fixing registry input in Edit boot source reference
  src/views/templates/actions/components/SelectSource.tsx
  src/views/templates/actions/editBootSource.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#926 Bug 2132721: Add missing texts to Delete dialogs
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ConfirmActionMessage/ConfirmActionMessage.tsx
  src/utils/components/DeleteModal/DeleteModal.tsx
  src/utils/components/DeleteResourceMessage/DeleteResourceMessage.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/datasources/dataimportcron/hooks/useDataImportCronActions.tsx
  src/views/templates/actions/components/EditBootSourceModal.tsx
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
  src/views/virtualmachines/details/tabs/disk/modal/DeleteDiskModal.tsx
  src/views/virtualmachines/details/tabs/network/copmonents/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/component/SnapshotDeleteModal.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#937 Bug 2138664: Fix additional resources creation
  src/views/catalog/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#938 Bug 2138653: Prevent default on parameters form submit
  src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#935 Bug 2134672: Changing the data-test-id to the closest element
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#914 Bug 2119613: Fix disk size units display
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CapacityInput/CapacityInput.tsx
  src/utils/components/CapacityInput/utils.ts
  src/utils/components/DiskModal/DiskFormFields/DiskSizeInput/DiskSizeInput.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSizeInput/DiskSizeNumberInput.tsx
  src/utils/utils/units.ts
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/constants.ts
  src/views/catalog/customize/components/CustomizeSource/index.tsx
  src/views/catalog/utils/quantity.ts
  src/views/templates/actions/components/EditBootSourceModal.tsx
  src/views/templates/actions/components/SelectSource.tsx
  src/views/templates/actions/components/VolumeSize.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#893 Bug 2129235: Add "Copy SSH command" to VM actions
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloneTemplateModal/SelectProject.tsx
  src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
  src/utils/components/SSHAccess/useSSHCommand.ts
  src/utils/components/Timestamp/utils/datetime.ts
  src/utils/hooks/useKubevirtTranslation.ts
  src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
  src/utils/utils/utils.ts
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
  src/views/catalog/customize/utils.ts
  src/views/catalog/utils/WizardVMContext/utils/session.ts
  src/views/catalog/utils/useWizardSourceAvailable.ts
  src/views/catalog/wizard/tabs/environment/utils.ts
  src/views/templates/actions/components/SelectSource.tsx
  src/views/templates/actions/components/SelectSourceOption.tsx
  src/views/templates/actions/editBootSource.ts
  src/views/templates/details/tabs/parameters/ParameterValueEditor.tsx
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/VirtualMachineActions/VirtualMachineActions.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/tabs/environment/utils/utils.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/hooks/useVirtualMachinesOverviewTabInterfacesData.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/utils/utils.ts
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTableRow.tsx
  webpack.config.ts
Labels: lgtm, approved, bugzilla/severity-medium
