Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2022-07, with the labels that each got.

#702 [release-4.11] Bug 2102116: Adding data-test-id on Template Scheduling tab
  src/views/templates/details/tabs/scheduling/components/AffinityRules.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResources.tsx
  src/views/templates/details/tabs/scheduling/components/EvictionStrategy.tsx
  src/views/templates/details/tabs/scheduling/components/NodeSelector.tsx
  src/views/templates/details/tabs/scheduling/components/Tolerations.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#704 [rls-4.11] Bug 2102127: Template adding nic keep loading for test user
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceNetworkSelect.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#710 Bug 2100679: Display correct number of HW devices in VM Overview
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/HardwareDevices/HardwareDevicesTable.tsx
  src/utils/resources/vm/utils/selectors.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabHardwareDevices/VirtualMachinesOverviewTabHardwareDevices.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabHardwareDevices/hooks/useHardwareDevicesColumns.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#700 [release-4.11] Bug 2102117: Adding data-test-id on vm Scripts tab
  src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#713 Bug 2102475: Template example like fedora
  src/templates/vm-template-yaml.ts
  src/utils/resources/template/utils/selectors.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#714 Bug 2102737: On VM Clone redirect to vm details
  src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#711 Bug 2102131: Display correct number of HW devices in VM Overview
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/HardwareDevices/HardwareDevicesTable.tsx
  src/utils/resources/vm/utils/selectors.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabHardwareDevices/VirtualMachinesOverviewTabHardwareDevices.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabHardwareDevices/hooks/useHardwareDevicesColumns.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#716 Add Machine type field to Review and create VirtualMachine
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
Labels: lgtm, approved

#681 Expose DataSource List and Details Page
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/ConditionsTable/ConditionsTable.tsx
  src/utils/components/ConditionsTable/components/ConditionsTableRow.tsx
  src/utils/components/ConditionsTable/components/useConditionsTableColumns.ts
  src/utils/components/DescriptionItem/DescriptionItem.scss
  src/utils/components/DescriptionItem/DescriptionItem.tsx
  src/utils/components/DescriptionItem/DescriptionItemHeader.tsx
  src/utils/components/OwnerDetailsItem/OwnerDetailsItem.tsx
  src/views/clusteroverview/overview/components/getting-started-card/quick-starts-section/QuickStartsSection.tsx
  src/views/clusteroverview/overview/components/utils/RestoreGettingStartedButton.tsx
  src/views/datasources/actions/DataSourceActions.tsx
  src/views/datasources/details/DataSourceDetailsPage.tsx
  src/views/datasources/details/DataSourcePage.tsx
  src/views/datasources/details/DataSourcePageTitle.tsx
  src/views/datasources/details/DataSourceYamlPage.tsx
  src/views/datasources/details/components/DataSourceAnnotations/DataSourceAnnotations.tsx
  src/views/datasources/details/components/DataSourceDetailsGrid.tsx/DataSourceDetailsGrid.tsx
  src/views/datasources/details/components/DataSourceManagedByDescription/DataSourceManagedByDescription.tsx
  src/views/datasources/hooks/useDataSourceActions.tsx
  src/views/datasources/list/DataSourcesList.tsx
  src/views/datasources/list/DataSourcesListFilters.ts
  src/views/datasources/list/DataSourcesListRow.tsx
  src/views/datasources/list/hooks/useDataSourcesColumns.ts
  src/views/datasources/utils/index.ts
  yarn.lock
Labels: lgtm, approved

#724 CNV19599: Rename overview performance tab to monitoring
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/MonitoringTab.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/TopConsumersCard.scss
  src/views/clusteroverview/overview/components/top-consumers-card/TopConsumersCard.tsx
Labels: lgtm, approved

#717 Bug 2100436: VM list filter failed vms
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
  src/views/virtualmachines/utils/virtualMachineStatuses.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#718 Fix top consumer exception
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumerCard.tsx
Labels: lgtm, approved

#725 Bug 2100682: Delete only the appropriate HW device in the modal
  src/utils/components/HardwareDevices/HardwareDevicesModal.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#730 Bug 2102132: align utilization charts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/virtual-machines-overview-tab-utilization.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#728 CNV-19412: Add general tab , editing kubevirt csv hook
  src/views/clusteroverview/overview/components/OverviewTab/details-card/DetailsCard.tsx
  src/views/clusteroverview/overview/components/OverviewTab/details-card/hooks/useKubevirtCSVDetails.ts
  src/views/clusteroverview/overview/components/SettingsTab/General Tab/GeneralTab.tsx
  src/views/clusteroverview/overview/components/SettingsTab/SettingsTab.tsx
Labels: lgtm, approved

#737 Bug 2104422: Fix ODF operator status on overview page
  src/views/clusteroverview/overview/components/OverviewTab/status-card/utils/constants.ts
  src/views/clusteroverview/overview/components/OverviewTab/status-card/utils/hooks/useKubevirtStorageOperatorCSVs.ts
  src/views/clusteroverview/overview/components/OverviewTab/status-card/utils/storage-health-item/StorageHealthItem.tsx
  src/views/clusteroverview/overview/components/OverviewTab/status-card/utils/utils.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#741 Bug 2104617: Fix ODF status reporting on overview page
  src/views/clusteroverview/overview/components/status-card/utils/constants.ts
  src/views/clusteroverview/overview/components/status-card/utils/hooks/useKubevirtStorageOperatorCSVs.ts
  src/views/clusteroverview/overview/components/status-card/utils/storage-health-item/StorageHealthItem.tsx
  src/views/clusteroverview/overview/components/status-card/utils/utils.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#738 Bug 2101335: Clone action enabled for CrashLoopBackOff
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/utils/virtualMachineStatuses.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#743 Bug 2101167: Fix the clickable area for Edit buttons in VM pages
  src/utils/components/HardwareDevices/HardwareDeviceTitle.tsx
  src/views/catalog/wizard/components/WizardDescriptionItem/WizardDescriptionItem.tsx
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#747 Bug 2102074: Improve VM Creation time on VM Overview Details card
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Timestamp/Timestamp.tsx
  src/utils/components/Timestamp/utils/datetime.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#748 Bug 2104785: Disks wizard title in new line
  src/views/catalog/wizard/tabs/disks/components/DiskListTitle.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#740 Bug 2104402: Merge wizard and vm Environment editors
  src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentEditor.scss
  src/utils/components/EnvironmentEditor/components/EnvironmentEditor.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentFormActions.scss
  src/utils/components/EnvironmentEditor/components/EnvironmentFormActions.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentFormSkeleton.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentFormTitle.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentSelectOption.tsx
  src/utils/components/EnvironmentEditor/constants.ts
  src/utils/components/EnvironmentEditor/hooks/useEnvironments.ts
  src/utils/components/EnvironmentEditor/hooks/useEnvironmentsResources.ts
  src/utils/components/EnvironmentEditor/utils.ts
  src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
  src/views/catalog/wizard/tabs/environment/components/WizardEnvironmentTabFooter.scss
  src/views/catalog/wizard/tabs/environment/components/WizardEnvironmentTabFooter.tsx
  src/views/virtualmachines/details/tabs/environment/VirtualMachineEnvironmentPage.tsx
  src/views/virtualmachines/details/tabs/environment/components/EnvironmentEditor.scss
  src/views/virtualmachines/details/tabs/environment/components/EnvironmentEditor.tsx
  src/views/virtualmachines/details/tabs/environment/components/EnvironmentSelectOption.tsx
  src/views/virtualmachines/details/tabs/environment/components/VirtualMachineEnvironmentTabTitle.scss
  src/views/virtualmachines/details/tabs/environment/components/VirtualMachineEnvironmentTabTitle.tsx
  src/views/virtualmachines/details/tabs/environment/hooks/useEnvironments.ts
  src/views/virtualmachines/details/tabs/environment/hooks/useEnvironmentsResources.ts
  src/views/virtualmachines/details/tabs/environment/utils/constants.ts
  src/views/virtualmachines/details/tabs/environment/utils/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#712 Bug 2096780: Template sysprep selection
  src/utils/resources/template/utils/helpers.ts
  src/views/templates/details/tabs/scripts/SysPrepDescription.tsx
  src/views/templates/details/tabs/scripts/SysPrepItem.tsx
  src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
  src/views/templates/details/tabs/scripts/sysprep-utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#745 Bug 2102740: Rename Save button to Clone in Clone VM modal
  src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#749 CNV19601: create migrations sub tab layout
  locales/en/plugin__kubevirt-plugin.json
  src/utils/i18n.ts
  src/views/clusteroverview/MonitoringTab/MonitoringTab.scss
  src/views/clusteroverview/MonitoringTab/MonitoringTab.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/MigrationsCard.scss
  src/views/clusteroverview/MonitoringTab/migrations-card/MigrationsCard.tsx
  src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/DurationOption.ts
  src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/constants.ts
Labels: lgtm, approved

#746 CNV-19275: Add virtctl to overview
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/flags/consts.ts
  src/views/clusteroverview/ClusterOverviewPage.tsx
  src/views/clusteroverview/utils/PageHeader.tsx
  src/views/clusteroverview/utils/VirtctlPopup.scss
  src/views/clusteroverview/utils/VirtctlPopup.tsx
  src/views/clusteroverview/utils/constants.ts
  yarn.lock
Labels: lgtm, approved

#752 Bug 2106175: All pages are crashed after visit Virtualization -> Overview
  src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/DurationDropdown.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#732 Bug 2100684: Edit workload vm
  src/utils/components/WorkloadProfileModal/WorkloadProfileModal.tsx
  src/utils/resources/vm/utils/selectors.ts
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/templates/details/tabs/details/components/WorkloadProfile.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#754 Bug 2106258: add dropdown label safetynet 4.11
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumerCard.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#757 Change text 'boot method' to 'boot mode'
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
Labels: lgtm, approved

#744 CNV-19412: Content to general tab virtualization settings
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/OverviewTab/OverviewTab.tsx
  src/views/clusteroverview/OverviewTab/details-card/DetailsCard.tsx
  src/views/clusteroverview/OverviewTab/details-card/SourceMissingStatus/SourceMissingStatus.tsx
  src/views/clusteroverview/OverviewTab/details-card/SourceMissingStatus/SubscriptionStatus.tsx
  src/views/clusteroverview/OverviewTab/details-card/SourceMissingStatus/UpgradeApprovalLink.tsx
  src/views/clusteroverview/OverviewTab/status-card/utils/utils.tsx
  src/views/clusteroverview/SettingsTab/General Tab/GeneralTab.tsx
  src/views/clusteroverview/SettingsTab/GeneralTab/GeneralTab.tsx
  src/views/clusteroverview/SettingsTab/GeneralTab/components/SourceMissingStatus.tsx
  src/views/clusteroverview/SettingsTab/GeneralTab/components/SubscriptionStates/SubscriptionStateAtLatest.tsx
  src/views/clusteroverview/SettingsTab/GeneralTab/components/SubscriptionStates/SubscriptionStateDefault.tsx
  src/views/clusteroverview/SettingsTab/GeneralTab/components/SubscriptionStates/SubscriptionStateUpgradeAvailable.tsx
  src/views/clusteroverview/SettingsTab/GeneralTab/components/SubscriptionStates/SubscriptionStateUpgradePending.tsx
  src/views/clusteroverview/SettingsTab/GeneralTab/components/SubscriptionStatus.tsx
  src/views/clusteroverview/SettingsTab/GeneralTab/components/utils/utils.ts
  src/views/clusteroverview/SettingsTab/GeneralTab/general-tab.scss
  src/views/clusteroverview/SettingsTab/SettingsTab.tsx
  src/views/clusteroverview/SettingsTab/settings-tab.scss
  src/views/clusteroverview/utils/Components/BlueArrowCircleUpIcon.tsx
  src/views/clusteroverview/utils/hooks/useKubevirtCSVDetails.ts
  src/views/clusteroverview/utils/utils.ts
Labels: lgtm, approved

#758 Moving component from overview utils to components folder
  src/views/clusteroverview/ClusterOverviewPage.tsx
  src/views/clusteroverview/Header/ClusterOverviewPageHeader.tsx
  src/views/clusteroverview/Header/RestoreGettingStartedButton.tsx
  src/views/clusteroverview/Header/VirtctlPopup.tsx
  src/views/clusteroverview/Header/virtctl-popup.scss
  src/views/clusteroverview/utils/PageHeader.tsx
Labels: lgtm, approved

#753 CNV-19414: Templates project tab
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CreateProjectModal/CreateProjectModal.tsx
  src/views/clusteroverview/SettingsTab/LiveMigrationTab/LiveMigrationTab.tsx
  src/views/clusteroverview/SettingsTab/LiveMigrationTab/Network/Network.tsx
  src/views/clusteroverview/SettingsTab/LiveMigrationTab/utils/utils.ts
  src/views/clusteroverview/SettingsTab/SettingsTab.tsx
  src/views/clusteroverview/SettingsTab/TemplatesProjectTab/TemplatesProjectTab.tsx
  src/views/clusteroverview/SettingsTab/TemplatesProjectTab/templates-project-tab.scss
  src/views/clusteroverview/SettingsTab/TemplatesProjectTab/utils/utils.ts
  src/views/clusteroverview/SettingsTab/settings-tab.scss
  src/views/clusteroverview/utils/types.ts
  src/views/clusteroverview/utils/utils.ts
Labels: lgtm, approved

#761 Bug 2103807: Name PVC source same as VM name when creating VM quickly
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#760 Bug 2107279: Fix disk modal is boot source
  src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
  src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts
  src/views/virtualmachines/details/tabs/disk/tables/disk/hooks/useEditDiskStates.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#750 DataImportCron manage details and modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ConditionsTable/ConditionsTable.tsx
  src/utils/components/DescriptionItem/DescriptionItem.tsx
  src/views/datasources/dataimportcron/details/DataImportCronDetailsGrid.tsx
  src/views/datasources/dataimportcron/details/DataImportCronDetailsPage.tsx
  src/views/datasources/dataimportcron/details/DataImportCronManageDetails/DataImportCronManageDetails.scss
  src/views/datasources/dataimportcron/details/DataImportCronManageDetails/DataImportCronManageDetails.tsx
  src/views/datasources/dataimportcron/details/DataImportCronManageModal/DataImportCronManageModal.tsx
  src/views/datasources/dataimportcron/details/DataImportCronManageModal/utils.ts
  src/views/datasources/utils/index.ts
Labels: lgtm, approved

#768 fix vm list create dropdown margin
  src/views/virtualmachines/list/VirtualMachinesList.scss
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved

#759 CNV19658: Add migrations table
  locales/en/plugin__kubevirt-plugin.json
  src/utils/i18n.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/MigrationsCard.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationActionsDropdown.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationsRow.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationsTable.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/hooks/useVirtualMachineInstanceMigrationActionsProvider.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/hooks/useVirtualMachineInstanceMigrationsColumns.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/utils/filters.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/utils/statuses.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/utils/utils.ts
  src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/DurationOption.ts
  src/views/virtualmachines/actions/actions.ts
  tsconfig.json
Labels: lgtm, approved

#769 CNV-19841: Adding vm details page metrics tab
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/PendingChanges/utils/constants.ts
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/metrics/MigrationCharts/MigrationCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/StorageCharts/StorageCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/TimeRange/TimeRange.tsx
  src/views/virtualmachines/details/tabs/metrics/UtilizationCharts/UtilizationCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
  src/views/virtualmachines/details/tabs/metrics/utils/utils.ts
  src/views/virtualmachines/details/tabs/metrics/virtual-machine-metrics-tab.scss
Labels: lgtm, approved

#771 Bug 2106258: All pages are crashed after visit Virtualization -> Overview
  src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/TopConsumersChartList.tsx
  src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/queries.ts
  src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#774 Bug 2108253: Add safety nets to topconsumercard
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumerCard.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#756 Bug 2100442: show ssh service even without running vm
  src/utils/components/SSHAccess/SSHAccessModal.tsx
  src/utils/components/SSHAccess/constants.ts
  src/utils/components/SSHAccess/useSSHService.tsx
  src/utils/components/SSHAccess/utils.ts
  src/utils/resources/vmi/utils/services.ts
  src/utils/resources/vmi/utils/tests/services.test.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/RunningVirtualMachineDetailsRightGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/details/components/sections/ServicesSection.tsx
  src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#775 update DataSource modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ConditionsTable/ConditionsTable.tsx
  src/views/datasources/dataimportcron/details/DataImportCronManageModal/DataImportCronManageModal.tsx
  src/views/datasources/dataimportcron/details/DataImportCronPage.tsx
  src/views/datasources/list/CreateDataSourceModal/CreateDataSourceForm.tsx
  src/views/datasources/list/CreateDataSourceModal/utils.ts
Labels: lgtm, approved

#776 Add Description to Disabled DataSource manage action
  locales/en/plugin__kubevirt-plugin.json
  src/views/datasources/actions/DataSourceActions.tsx
  src/views/datasources/dataimportcron/details/DataImportCronManageDetails/DataImportCronManageDetails.tsx
  src/views/datasources/dataimportcron/details/DataImportCronManageModal/DataImportCronManageModal.tsx
  src/views/datasources/hooks/useDataSourceActions.tsx
  src/views/datasources/list/CreateDataSourceModal/CreateDataSourceForm.tsx
Labels: lgtm, approved

#778 CNV-19844: Adding utilization charts to vm metrics tab
  src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
  src/utils/components/Charts/ComponentReady/ComponentReady.tsx
  src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageThresholdChart.tsx
  src/utils/components/Charts/hooks/useResponsiveCharts.tsx
  src/utils/components/Charts/utils/queries.ts
  src/utils/components/Charts/utils/utils.ts
  src/views/virtualmachines/details/tabs/metrics/UtilizationCharts/UtilizationCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
  src/views/virtualmachines/details/tabs/metrics/hooks/useDuration.tsx
  src/views/virtualmachines/details/tabs/metrics/virtual-machine-metrics-tab.scss
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/VirtualMachinesOverviewTabUtilization.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/TimeDropdown.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/UtilizationThresholdCharts.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/virtual-machines-overview-tab-utilization.scss
Labels: lgtm, approved

#779 Add filters to migrations donut chart legend
  src/views/clusteroverview/MonitoringTab/migrations-card/MigrationsCard.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsChartDonut/MigrationChartLegend.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsChartDonut/MigrationsChartDonut.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationsTable.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/hooks/useMigrationCardData.ts
Labels: lgtm, approved

#780 CNV19954: Add MigrationPolicies
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/migrationpolicies/list/MigrationPoliciesList.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyMatchExpressionSelectorList/MigrationPolicyMatchExpressionSelectorLabel.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyMatchExpressionSelectorList/MigrationPolicyMatchExpressionSelectorList.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyMatchLabelSelectorList/MigrationPolicyMatchLabelSelectorLabel.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyMatchLabelSelectorList/MigrationPolicyMatchLabelSelectorList.tsx
  src/views/migrationpolicies/list/components/MigrationPolicySelectorLabel.scss
  src/views/migrationpolicies/list/hooks/useMigrationPoliciesListColumns.ts
Labels: lgtm, approved

#781 CNV-20011: Adding permisison tab - virtualization settings
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/OverviewTab/OverviewTab.tsx
  src/views/clusteroverview/OverviewTab/permissions-card/PermissionsCard.scss
  src/views/clusteroverview/OverviewTab/permissions-card/PermissionsCard.tsx
  src/views/clusteroverview/OverviewTab/permissions-card/PermissionsCardTitle.scss
  src/views/clusteroverview/OverviewTab/permissions-card/PermissionsCardTitle.tsx
  src/views/clusteroverview/OverviewTab/permissions-card/utils/PermissionsCardPopover.scss
  src/views/clusteroverview/OverviewTab/permissions-card/utils/PermissionsCardPopover.tsx
  src/views/clusteroverview/OverviewTab/permissions-card/utils/PermissionsCountItem.scss
  src/views/clusteroverview/OverviewTab/permissions-card/utils/PermissionsCountItem.tsx
  src/views/clusteroverview/OverviewTab/permissions-card/utils/PermissionsItem.scss
  src/views/clusteroverview/OverviewTab/permissions-card/utils/PermissionsItem.tsx
  src/views/clusteroverview/SettingsTab/PermissionsTab/PermissionsTab.tsx
  src/views/clusteroverview/SettingsTab/PermissionsTab/hooks/usePermissions.ts
  src/views/clusteroverview/SettingsTab/PermissionsTab/permissions-tab.scss
  src/views/clusteroverview/SettingsTab/PermissionsTab/utils/constants.ts
  src/views/clusteroverview/SettingsTab/SettingsTab.tsx
Labels: lgtm, approved

#772 Adding the ability to start in pause mode
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
  src/utils/components/StartPauseModal/StartPauseModal.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved

#782 CNV19956: Add search bar and actions to MigrationPolicies page
  locales/en/plugin__kubevirt-plugin.json
  src/views/migrationpolicies/actions/components/MigrationPoliciesActions.tsx
  src/views/migrationpolicies/actions/hooks/useMigrationPoliciesActionsProvider.tsx
  src/views/migrationpolicies/list/MigrationPoliciesList.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyMatchExpressionSelectorList/MigrationPolicyMatchExpressionSelectorList.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyMatchLabelSelectorList/MigrationPolicyMatchLabelSelectorList.tsx
Labels: lgtm, approved

#783 Bug 2102138: Remove "new" from "Create new VirtualMachine from catalog"
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#785 fix eslint warnings 0722
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/StartPauseModal/StartPauseModal.tsx
  src/utils/resources/shared.ts
  src/views/clusteroverview/OverviewTab/activity-card/hooks/useDashboardPrometheusActivities.ts
  src/views/clusteroverview/OverviewTab/status-card/utils/hooks/useDashboardSubsystems.ts
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved

#786 Bug 2103806: PVC 404
  src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
  src/views/templates/details/tabs/disks/components/DiskRow.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRow.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTableRow.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#788 Edit metrics queries and rearrange structure
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
  src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageReadThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageWriteThresholdChart.tsx
  src/utils/components/Charts/utils/queries.ts
  src/utils/components/Charts/utils/utils.ts
  src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/DurationOption.ts
  src/views/virtualmachines/details/tabs/metrics/MigrationCharts/MigrationCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/StorageCharts/StorageCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/TimeRange/TimeRange.tsx
  src/views/virtualmachines/details/tabs/metrics/UtilizationCharts/UtilizationCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
  src/views/virtualmachines/details/tabs/metrics/hooks/useDuration.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/TimeDropdown.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/UtilizationThresholdCharts.tsx
Labels: lgtm, approved

#789 Moving durationoption to share location
  src/utils/components/Charts/utils/utils.ts
  src/utils/components/DurationOption/DurationDropdown.tsx
  src/utils/components/DurationOption/DurationOption.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/MigrationsCard.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/utils/utils.ts
  src/views/clusteroverview/MonitoringTab/top-consumers-card/TopConsumersCard.tsx
  src/views/virtualmachines/details/tabs/metrics/TimeRange/TimeRange.tsx
  src/views/virtualmachines/details/tabs/metrics/hooks/useDuration.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/TimeDropdown.tsx
Labels: lgtm, approved

#790 Fix vm list crash
  src/utils/resources/vmi/utils/ips.ts
Labels: lgtm, approved

#793 fix labels modal height
  src/utils/components/LabelsModal/LabelsModal.scss
  src/utils/components/LabelsModal/LabelsModal.tsx
Labels: lgtm, approved

#791 Bug 2104424: Check Descheduler Operator and enable/disable on pages
  src/utils/hooks/useDeschedulerInstalled.ts
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/details/TemplatePageTitle.tsx
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
  src/views/templates/details/tabs/details/components/BootMethod/BootMethod.tsx
  src/views/templates/details/tabs/details/components/CPUMemory.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
  src/views/templates/details/tabs/details/components/DisplayName.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsRightGrid.tsx
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
  src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResources.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx
  src/views/templates/details/tabs/scheduling/components/Descheduler.tsx
  src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
  src/views/templates/details/tabs/scheduling/components/DeschedulerModalButton.tsx
  src/views/templates/details/tabs/scripts/SysPrepItem.tsx
  src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
  src/views/templates/utils/utils.ts
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx
  src/views/virtualmachinesinstance/details/tabs/scheduling/Descheduler/Descheduler.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#799 [CNV-20217] Migrate various static extensions to dynamic
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/HardwareDevices/HardwareDevicesPage.tsx
  src/utils/extensions/dashboard/dashboardHealth.ts
  src/utils/extensions/dashboard/index.ts
  src/utils/extensions/index.ts
  src/utils/i18n.ts
  src/utils/icons.tsx
Labels: lgtm, approved

#800 Bug 2101445: Pending changes should not appear if nothing relevant has changed
  src/utils/components/BootOrderModal/BootOrderModalBody.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug
