Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2022-12, with the labels that each got.

#993 CNV-22029: Adding the option to edit the Hostname
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloudinitModal/CloudinitForm.tsx
  src/utils/components/HostnameModal/HostnameModal.tsx
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
Labels: lgtm, approved

#999 Update filter.spec.ts
  cypress/tests/catalog/filter.spec.ts
Labels: lgtm, approved

#995 CNV-21086: Add new Live migratable column to VMs list
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/utils/constants.ts
  src/views/virtualmachines/utils/index.ts
  src/views/virtualmachines/utils/utils.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved

#997 Bug 2151427: Virtualization -> Overview is crashed when creating VM in other browser session
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#987 Bug 2139574: blank vm name in customize
  src/views/catalog/customize/components/CustomizeForms/CustomizeForm.tsx
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1000 CNV-23014: Paste clipboard into VNC
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/InlineCodeClipboardCopy.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsoleActions.tsx
  src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
  src/utils/components/Consoles/components/vnc-console/utils/util.ts
Labels: lgtm, approved

#998 Bug 2087540: Adding popover to the CPU | Memory
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CPUDescription/CPUDescription.tsx
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
  src/utils/components/Charts/ComponentReady/ComponentReady.tsx
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
  src/views/templates/details/tabs/details/components/CPUMemory.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/CPUMemory/CPUMemory.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1002 Bug 2149897: The context menu of the serial console does not contain a paste command
  src/utils/components/Consoles/components/SerialConsole/SerialConsole.scss
  src/utils/components/Consoles/components/SerialConsole/SerialConsole.tsx
  src/utils/components/Consoles/components/SerialConsole/SerialConsoleActions.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#986 CNV-21974: Part I - watch boot source in template list
  src/views/catalog/templatescatalog/hooks/useAvailableDataSourcesAndPVCs.ts
Labels: lgtm, approved

#1003 Bug 2155409: PVC details page crashing
  src/views/cdi-upload-provider/PVCAlertExtension.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified
