Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2022-04, with the labels that each got.

#194 Add confirm prompts to wizard exit
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/wizard/components/WizardFooter.tsx
  src/views/catalog/wizard/tabs.tsx
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
Labels: lgtm, approved

#196 Adding Hardware devices card - vm overview page
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabHardwareDevices/VirtualMachinesOverviewTabHardwareDevices.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabHardwareDevices/VirtualMachinesOverviewTabHardwareDevicesRow.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabHardwareDevices/hooks/useHardwareDevicesColumns.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabHardwareDevices/virtual-machines-overview-tab-hardware-devices.scss
Labels: lgtm, approved

#179 Adding serial console
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/virtualmachinesinstance/details/tabs/console/VirtualMachinesInstancePageConsoleTab.tsx
  src/views/virtualmachinesinstance/details/tabs/console/components/AccessConsoles/AccessConsoles.tsx
  src/views/virtualmachinesinstance/details/tabs/console/components/AccessConsoles/utils/accessConsoles.tsx
  src/views/virtualmachinesinstance/details/tabs/console/components/SerialConsole/SerialConsole.tsx
  src/views/virtualmachinesinstance/details/tabs/console/components/SerialConsole/SerialConsoleActions.tsx
  src/views/virtualmachinesinstance/details/tabs/console/components/SerialConsole/SerialConsoleConnector.tsx
  src/views/virtualmachinesinstance/details/tabs/console/components/SerialConsole/Xterm/Xterm.tsx
  src/views/virtualmachinesinstance/details/tabs/console/components/SerialConsole/Xterm/utils/Xterm.ts
  src/views/virtualmachinesinstance/details/tabs/console/components/SerialConsole/utils/serialConsole.ts
  src/views/virtualmachinesinstance/details/tabs/console/components/utils/ConsoleConsts.ts
  src/views/virtualmachinesinstance/details/tabs/console/components/vnc-console/VncConsole.tsx
  src/views/virtualmachinesinstance/details/tabs/console/components/vnc-console/utils/VNCConsoleConsts.ts
  yarn.lock
Labels: lgtm, approved

#202 Add list view to templates catalog
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilters.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogRow.tsx
  src/views/catalog/templatescatalog/hooks/useTemplatesCatalogColumns.ts
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/catalog/templatescatalog/utils/consts.ts
Labels: lgtm, approved

#208 Adding labels modal to vmi details tab
  src/utils/components/LabelsModal/LabelsModal.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Labels/Labels.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Labels/labels.scss
Labels: lgtm, approved

#204 move annotaions modal to shared
  src/utils/components/AnnotationsModal/AnnotationsModal.scss
  src/utils/components/AnnotationsModal/AnnotationsModal.tsx
  src/utils/components/AnnotationsModal/AnnotationsModalRow.tsx
  src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
Labels: lgtm, approved

#185 add secheduling section to VM details tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/details/VirtualMachineDetailsPage.tsx
  src/views/virtualmachines/details/tabs/details/components/Affinity/Affinity.tsx
  src/views/virtualmachines/details/tabs/details/components/Affinity/AffinityModal.tsx
  src/views/virtualmachines/details/tabs/details/components/DedicatedResources/DedicatedResources.tsx
  src/views/virtualmachines/details/tabs/details/components/Descheduler/Descheduler.tsx
  src/views/virtualmachines/details/tabs/details/components/EvictionStrategy/EvictionStrategy.tsx
  src/views/virtualmachines/details/tabs/details/components/Flavor/Flavor.tsx
  src/views/virtualmachines/details/tabs/details/components/NodeSelector/NodeSelector.tsx
  src/views/virtualmachines/details/tabs/details/components/Tolerations/Tolerations.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineSchedulingLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineSchedulingRightGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/sections/SchedulingSection.tsx
Labels: lgtm, approved

#200 Storage Customization new design
  src/views/catalog/customize/CustomizeVirtualMachine.tsx
  src/views/catalog/customize/cd.ts
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithCD.tsx
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeSource/BootCDCheckboxLabel.tsx
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.scss
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectCDSourceLabel.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectDiskSourceLabel.tsx
  src/views/catalog/customize/components/CustomizeSource/utils.ts
  src/views/catalog/customize/drivers.ts
  src/views/catalog/customize/overrides.ts
  src/views/catalog/customize/tests/CustomizeSource.test.tsx
  src/views/catalog/customize/utils.ts
  src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
Labels: lgtm, approved

#207 Adding description modal to vmi details tab
  src/utils/components/DescriptionModal/DescriptionModal.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Description/Description.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Description/description.scss
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
Labels: lgtm, approved

#205 consume useModal hook
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskList.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRowActions.tsx
  src/views/virtualmachines/details/tabs/network/NetworkInterfaceListPage.tsx
  src/views/virtualmachines/details/tabs/network/copmonents/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotRow.tsx
Labels: lgtm, approved

#210 Add projects dropdown to templates catalog
  src/utils/resources/template/hooks/useVmTemplates.tsx
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/TemplatesCatalogFilters.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/TemplatesCatalogFiltersGroup.scss
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/TemplatesCatalogFiltersGroup.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogProjectsDropdown/TemplatesCatalogProjectsDropdown.scss
  src/views/catalog/templatescatalog/components/TemplatesCatalogProjectsDropdown/TemplatesCatalogProjectsDropdown.tsx
  src/views/catalog/templatescatalog/hooks/useAvailableSourceTemplates.ts
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
  src/views/catalog/templatescatalog/utils/consts.ts
Labels: lgtm, approved

#201 Add filtering by OS and Workload profile to VM Templates list
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/template/utils/constants.ts
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
  src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts
  src/views/templates/list/hooks/useWorkloadProfile.ts
  src/views/templates/utils/selectors.ts
Labels: lgtm, approved

#214 move HardwareDeviceModal to utils/src/components
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/HardwareDevices/HardwareDevicesModal.tsx
  src/utils/components/HardwareDevices/form/DeviceNameSelect.tsx
  src/utils/components/HardwareDevices/form/NameFormField.tsx
  src/utils/components/HardwareDevices/form/PlainIconButton.tsx
  src/utils/components/HardwareDevices/hooks/useHCPermittedHostDevices.ts
  src/utils/components/HardwareDevices/list/HardwareDeviceRow.tsx
  src/utils/components/HardwareDevices/list/HardwareDevicesList.tsx
  src/utils/components/HardwareDevices/list/hooks/useHardwareDevicesColumns.tsx
  src/utils/components/HardwareDevices/utils/constants.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
Labels: lgtm, approved

#206 Adding delete + labels modals to vmi list
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DeleteModal/DeleteModal.tsx
  src/utils/components/TabModal/TabModal.tsx
  src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx
Labels: lgtm, approved

#215 Adding annotations modal to vmi details tab + change other modals to use createModal
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Annotations/Annotations.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Description/Description.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Labels/Labels.tsx
Labels: lgtm, approved

#169 VMI details tab - details section - second half
  locales/en/plugin__kubevirt-plugin.json
  src/utils/hooks/usePods.ts
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/BootOrder/BootOrder.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/HadwareDevices/HardwareDevices.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Hostname/Hostname.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/IP/IP.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Node/Node.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Pods/Pods.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Timezone/Timezone.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/WorkloadProfile/WorkloadProfile.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/hooks/useFileSystemTableGuestOS.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTable.tsx
Labels: lgtm, approved

#211 consume edit labels and edit annotations modals
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineInstanceMigration.ts
  src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineLabels/VirtualMachineLabels.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved

#217 remove redundant line in useVmTemplates
  src/utils/resources/template/hooks/useVmTemplates.tsx
Labels: lgtm, approved

#218 Approximated disk quantity in list
  src/utils/components/DiskModal/DiskFormFields/DiskSizeInput/DiskSizeNumberInput.tsx
  src/views/catalog/customize/components/CustomizeSource/VolumeSize.tsx
  src/views/catalog/customize/components/CustomizeSource/constants.ts
  src/views/catalog/customize/components/CustomizeSource/quantity.ts
  src/views/catalog/customize/tests/CustomizeSource.test.tsx
  src/views/catalog/customize/tests/quantity.test.ts
  src/views/catalog/utils/quantity.ts
  src/views/catalog/utils/tests/quantity.test.ts
  src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
Labels: lgtm, approved

#213 Move DeleteResourceMessege to separate file
  src/utils/components/DeleteModal/DeleteModal.tsx
  src/utils/components/DeleteResourceMessage/DeleteResourceMessage.tsx
  src/utils/components/TabModal/TabModal.tsx
  src/views/virtualmachines/details/tabs/network/copmonents/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
Labels: lgtm, approved

#223 remove vm error from disks tab table
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
Labels: lgtm, approved

#224 fix eslint ignoring utils, components
  src/utils/.eslintrc.json
  src/utils/components/BootOrder/EmptyBootSourceSummary.tsx
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
  src/utils/components/CPUMemoryModal/utils/CpuMemoryUtils.ts
  src/utils/components/DeleteModal/DeleteModal.tsx
  src/utils/components/DeleteResourceMessage/DeleteResourceMessage.tsx
  src/utils/components/DescriptionModal/DescriptionModal.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUrlInput.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/utils/constants.ts
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/LabelsModal/LabelsModal.tsx
  src/utils/components/LabelsModal/utils.ts
  src/utils/components/ModalProvider/ModalProvider.tsx
  src/utils/components/TabModal/TabModal.tsx
  src/utils/hooks/usePods.ts
  src/utils/resources/vm/utils/boot-order/bootOrder.ts
  src/utils/resources/vm/utils/operation-system/operationSystem.ts
  src/utils/resources/vmi/utils/affinity.ts
  src/utils/resources/vmi/utils/cpu.ts
  src/utils/resources/vmi/utils/flavor.ts
  src/utils/resources/vmi/utils/ips.ts
  src/utils/resources/vmi/utils/nodeSelector.ts
Labels: lgtm, approved

#225 copy gh authentication to dev container
  .devcontainer/docker-compose.yml
Labels: lgtm, approved

#221 Overview Hardware Devices
  src/utils/components/HardwareDevices/HardwareDeviceTitle.tsx
  src/utils/components/HardwareDevices/HardwareDevices.tsx
  src/utils/components/HardwareDevices/HardwareDevicesModal.tsx
  src/utils/components/HardwareDevices/HardwareDevicesTable.tsx
  src/utils/components/HardwareDevices/hardware-devices-table.scss
  src/utils/components/HardwareDevices/hooks/useHCPermittedHostDevices.ts
  src/utils/components/HardwareDevices/list/HardwareDevicesList.tsx
  src/utils/components/HardwareDevices/list/hooks/useHardwareDevicesColumns.tsx
  src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
Labels: lgtm, approved

#226 replace i18next-parser with i18next-scanner
  i18next-parser.config.js
  i18next-scanner.config.js
  locales/en/plugin__kubevirt-plugin.json
  package.json
  yarn.lock
Labels: lgtm, approved

#228 Add console.flag extension for kubevirt dynamic plugin
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/flags/consts.ts
  src/utils/flags/enableKubevirtDynamicFlag.ts
  src/utils/flags/index.ts
Labels: lgtm, approved

#231 update scripts tab section design
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.scss
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
Labels: lgtm, approved

#133 Add details card to the cluster overview
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/utils/debounce.ts
  src/utils/utils/utils.ts
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/details-card/DetailsCard.tsx
  src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/BlueArrowCircleUpIcon.tsx
  src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/SourceMissingStatus.tsx
  src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/SubscriptionStatus.tsx
  src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/UpgradeApprovalLink.tsx
  src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/WarningStatus.tsx
  src/views/clusteroverview/overview/components/details-card/hooks/useDebounceCallback.ts
  src/views/clusteroverview/overview/components/details-card/hooks/useKubevirtCSVDetails.ts
  src/views/clusteroverview/overview/components/details-card/utils/types.ts
  src/views/clusteroverview/overview/components/getting-started-card/GettingStartedCard.tsx
  yarn.lock
Labels: lgtm, approved

#233 add test for vm catalog filter
  cypress/support/login.ts
  cypress/tests/catalog/filter.spec.ts
  cypress/tests/overview.spec.ts
  cypress/utils/const/index.ts
  cypress/utils/const/template.ts
  cypress/views/catalog.ts
Labels: lgtm, approved

#234 Moving console into utils folder
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/utils/accessConsoles.tsx
  src/utils/components/Consoles/components/SerialConsole/SerialConsole.tsx
  src/utils/components/Consoles/components/SerialConsole/SerialConsoleActions.tsx
  src/utils/components/Consoles/components/SerialConsole/SerialConsoleConnector.tsx
  src/utils/components/Consoles/components/SerialConsole/Xterm/Xterm.tsx
  src/utils/components/Consoles/components/SerialConsole/Xterm/utils/Xterm.ts
  src/utils/components/Consoles/components/SerialConsole/utils/serialConsole.ts
  src/utils/components/Consoles/components/utils/ConsoleConsts.ts
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsoleActions.tsx
  src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
  src/utils/components/Consoles/utils/constants.ts
  src/utils/components/Consoles/utils/utils.ts
  src/views/virtualmachinesinstance/details/tabs/console/VirtualMachinesInstancePageConsoleTab.tsx
Labels: lgtm, approved

#235 Update SDK and PF pkgs
  package.json
  src/utils/components/DiskModal/DiskFormFields/DiskSizeInput/DiskSizeInput.tsx
  yarn.lock
Labels: lgtm, approved

#237 Moving vmi status to utils
  src/utils/resources/vm/hooks/index.ts
  src/utils/resources/vm/hooks/useVMIAndPodsForVM.ts
  src/utils/resources/vmi/hooks/index.ts
  src/utils/resources/vmi/hooks/useGuestOS.ts
  src/utils/resources/vmi/utils/index.ts
  src/utils/resources/vmi/utils/status.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/RunningVirtualMachineDetailsRightGrid.tsx
  src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemListLayout.tsx
  src/views/virtualmachinesinstance/components/VirtualMachinesInstancesStatus.tsx
  src/views/virtualmachinesinstance/details/hooks/useGuestOS.tsx
  src/views/virtualmachinesinstance/list/utils/index.ts
  src/views/virtualmachinesinstance/list/utils/virtualMachinesInstancesRowFilter.ts
Labels: lgtm, approved

#238 Adding gutter to vmi details tab
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Scheduling/Scheduling.tsx
Labels: lgtm, approved

#197 Delete disk modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/utils/constants.ts
  src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/resources/shared.ts
  src/views/virtualmachines/actions/actions.ts
  src/views/virtualmachines/details/tabs/disk/modal/DeleteDiskModal.tsx
  src/views/virtualmachines/details/tabs/disk/modal/hooks/useVolumeOwnedResource.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRowActions.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/utils/helpers.ts
Labels: lgtm, approved

#239 Pull latest console image with every run
  .devcontainer/init.sh
  start-console.sh
Labels: lgtm, approved

#243 Sort i18n translations
  i18next-scanner.config.js
  locales/en/plugin__kubevirt-plugin.json
Labels: lgtm, approved

#240 Add Wizard YAML tab
  i18next-scanner.config.js
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.scss
  src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx
Labels: lgtm, approved

#241 Update catalog search input
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
Labels: lgtm, approved

#245 add YAML editor and Console to VM details tabs
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
  src/views/virtualmachines/details/tabs/yaml/VirtualMachineYAMLPage.tsx
Labels: lgtm, approved

#246 Add skeleton to Wizard Environment tab
  src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
  src/views/catalog/wizard/tabs/environment/components/WizardEnvironmentTabSkeleton.tsx
  src/views/catalog/wizard/tabs/environment/components/WizardEnvironmentTabTitle.tsx
Labels: lgtm, approved

#216 Add Memory&CPU\DedicatedResources\Eviction modals
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
  src/utils/components/CPUMemoryModal/hooks/useTemplateDefaultCpuMemory.ts
  src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
  src/utils/components/DedicatedResourcesModal/utils/constants.ts
  src/utils/components/EvictionStrategyModal/EvictionStrategyModal.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineSchedulingRightGrid.tsx
Labels: lgtm, approved

#250 Customize Form New Design
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/customize/CustomizeVirtualMachine.scss
  src/views/catalog/customize/CustomizeVirtualMachine.tsx
  src/views/catalog/customize/cd.ts
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeSource/BootCDCheckboxLabel.tsx
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.scss
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
  src/views/catalog/customize/components/CustomizeSource/VolumeSize.tsx
  src/views/catalog/customize/components/CustomizeSource/constants.ts
  src/views/catalog/customize/components/CustomizeSource/utils.ts
  src/views/catalog/customize/components/RightHeading.tsx
  src/views/catalog/customize/constants.ts
  src/views/catalog/customize/drivers.ts
  src/views/catalog/customize/tests/CustomizeSource.test.tsx
Labels: lgtm, approved

#248 update wizard footer css
  src/views/catalog/wizard/Wizard.scss
Labels: lgtm, approved

#252 Add breadcrumbs to catalog and wizard views
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/customize/CustomizeVirtualMachine.tsx
  src/views/catalog/customize/components/CustomizeVirtualMachineHeader.tsx
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
  src/views/catalog/wizard/Wizard.tsx
  src/views/catalog/wizard/components/WizardHeader.tsx
Labels: lgtm, approved

#253 Add dedicated, eviction modals to wizard scheduling tab
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
Labels: lgtm, approved

#244 Fix wrong translation hooks
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
  src/utils/components/HardwareDevices/list/hooks/useHardwareDevicesColumns.tsx
  src/utils/components/TabModal/TabModal.tsx
  src/views/catalog/customize/components/FormActionGroup.tsx
  src/views/catalog/wizard/tabs/network/hooks/useNetworkColumns.ts
  src/views/templates/list/components/VirtualMachineTemplateSupport.tsx
  src/views/virtualmachines/details/tabs/network/hooks/useNetworkColumns.ts
Labels: lgtm, approved

#254 Fix expandable sections
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
  src/views/catalog/customize/components/ExpandableOptionalFields.tsx
Labels: lgtm, approved

#255 Fix Scripts Tab default expanded section on Windows VMs
  src/utils/resources/template/utils/selectors.ts
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
  src/views/catalog/wizard/tabs/scripts/components/cloud-init.scss
Labels: lgtm, approved

#256 Add helper text to Customization form
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/template/utils/annotations.ts
  src/utils/resources/template/utils/selectors.ts
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/utils.ts
  src/views/catalog/customize/tests/CustomizeSource.test.tsx
  src/views/catalog/customize/tests/mocks.ts
  src/views/catalog/customize/utils.ts
Labels: lgtm, approved

#258 Add Success Alert on YAML Wizard
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.scss
  src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx
Labels: lgtm, approved

#259 Remove redundant wizard logic
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/wizard/Wizard.tsx
  src/views/catalog/wizard/components/WizardFooter.tsx
  src/views/catalog/wizard/tabs.tsx
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
  src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
  src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
  src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx
Labels: lgtm, approved

#261 Scrollable table and grid
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
Labels: lgtm, approved

#264 Add running VMs per template card to overview
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/utils/utils.ts
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/getting-started-card/running-vms-per-template-card/RunningVMsPerTemplateCard.scss
  src/views/clusteroverview/overview/components/getting-started-card/running-vms-per-template-card/RunningVMsPerTemplateCard.tsx
  src/views/clusteroverview/overview/components/getting-started-card/running-vms-per-template-card/hooks/useRunningVMsPerTemplateResources.ts
  src/views/clusteroverview/overview/components/getting-started-card/running-vms-per-template-card/utils/EmptyStateNoVMs.tsx
  src/views/clusteroverview/overview/components/getting-started-card/running-vms-per-template-card/utils/RunningVMsChartLegend.scss
  src/views/clusteroverview/overview/components/getting-started-card/running-vms-per-template-card/utils/RunningVMsChartLegend.tsx
  src/views/clusteroverview/overview/components/getting-started-card/running-vms-per-template-card/utils/RunningVMsChartLegendLabel.scss
  src/views/clusteroverview/overview/components/getting-started-card/running-vms-per-template-card/utils/RunningVMsChartLegendLabel.tsx
  src/views/clusteroverview/overview/components/getting-started-card/running-vms-per-template-card/utils/constants.ts
  src/views/clusteroverview/overview/components/getting-started-card/running-vms-per-template-card/utils/utils.ts
  yarn.lock
Labels: lgtm, approved

#263 Add no available source modal to vm wizard creation
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/vm/utils/source.ts
  src/views/catalog/utils/useWizardSourceAvailable.ts
  src/views/catalog/wizard/components/WizardFooter.tsx
  src/views/catalog/wizard/components/WizardNoBootModal.tsx
Labels: lgtm, approved

#268 fix datavolume find inside getTemplateBootSourceType
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
Labels: lgtm, approved

#267 Template tabs page
  console-extensions.json
  package.json
  src/views/templates/details/TemplateNavPage.tsx
  src/views/templates/details/TemplatePageTitle.tsx
  src/views/templates/details/hooks/useTemplateTabs.ts
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
  src/views/templates/details/tabs/disk/TemplateDisksPage.tsx
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/yaml/TemplateYAMLPage.tsx
Labels: lgtm, approved

#270 Template yaml Editor
  src/views/templates/details/tabs/yaml/TemplateYAMLPage.tsx
Labels: lgtm, approved

#266 Fix handling of undefined template annotations
  src/utils/resources/template/utils/selectors.ts
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/templatescatalog/tests/mocks.ts
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
Labels: lgtm, approved

#236 VMI details page will now show one pod
  src/utils/resources/vmi/utils/index.ts
  src/utils/resources/vmi/utils/pod.ts
  src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Pods/Pods.tsx
Labels: lgtm, approved

#274 Template network tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceList.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx
  src/views/templates/details/tabs/network/components/modal/EditNetworkInterfaceModal.tsx
  src/views/templates/details/tabs/network/components/modal/NetworkInterfaceModal.tsx
  src/views/templates/details/tabs/network/components/modal/components/NameFormField.tsx
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceMacAddressInput.tsx
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceModelSelect.tsx
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceNetworkSelect.tsx
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceTypeSelect.tsx
  src/views/templates/details/tabs/network/components/modal/utils/constants.ts
  src/views/templates/details/tabs/network/components/modal/utils/helpers.ts
  src/views/templates/details/tabs/network/hooks/useNetworkColumns.ts
  src/views/templates/details/tabs/network/hooks/useNetworkRowFilters.ts
  src/views/templates/details/tabs/network/template-network-page.scss
  src/views/templates/details/tabs/network/utils.ts
Labels: lgtm, approved

#212 Adding snapshot card vm overview
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/VirtualMachinesOverviewTabSnapshots.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/VirtualMachinesOverviewTabSnapshotsRow.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/component/SnapshotDeleteModal.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/utils/snapshotStatus.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/utils/url.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/virtual-machines-overview-tab-snapshots.scss
Labels: lgtm, approved

#219 Adding details card to vm overview
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
  src/utils/components/Consoles/components/vnc-console/vnc-console.scss
  src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/virtual-machines-overview-tab-details.scss
  yarn.lock
Labels: lgtm, approved

#272 Adding YAML editor to YAML Tab VMI
  src/views/virtualmachinesinstance/details/tabs/yaml/VirtualMachinesInstancePageYAMLTab.tsx
Labels: lgtm, approved

#276 Update tab modal
  src/utils/components/AnnotationsModal/AnnotationsModalRow.tsx
  src/utils/components/TabModal/TabModal.tsx
  src/views/catalog/wizard/components/WizardNoBootModal.tsx
Labels: lgtm, approved

#277 fix catalog breadcrumb css
  src/views/catalog/customize/components/CustomizeVirtualMachineHeader.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
  src/views/catalog/wizard/components/WizardHeader.tsx
Labels: lgtm, approved

#273 Adding services table to vmi details tab
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/vmi/utils/index.ts
  src/utils/resources/vmi/utils/services.ts
  src/views/virtualmachinesinstance/details/tabs/details/VirtualMachinesInstancePageDetailsTab.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Services/Services.tsx
Labels: lgtm, approved

#260 Add NodeSelector modal to utils/components
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/NodeSelectorModal/NodeSelectorModal.tsx
  src/utils/components/NodeSelectorModal/components/LabelList.tsx
  src/utils/components/NodeSelectorModal/components/LabelRow.tsx
  src/utils/components/NodeSelectorModal/components/NodeCheckerAlert.tsx
  src/utils/components/NodeSelectorModal/hooks/useIDEntities.ts
  src/utils/components/NodeSelectorModal/hooks/useNodeLabelQualifier.ts
  src/utils/components/NodeSelectorModal/utils/helpers.ts
  src/utils/components/NodeSelectorModal/utils/types.ts
  src/utils/resources/vm/utils/selectors.ts
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineSchedulingLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/sections/SchedulingSection.tsx
Labels: lgtm, approved

#281 add node selector modal to wizard scheduling
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
Labels: lgtm, approved

#278 Improve `useVmTemplates`
  cypress/cypress.json
  cypress/reporter-config.json
  cypress/tests/catalog/filter.spec.ts
  src/utils/resources/template/hooks/useVmTemplates.tsx
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogItems.tsx
Labels: lgtm, approved

#199 Add Actions column to VM Templates list
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/actions/VirtualMachineTemplatesActions.tsx
  src/views/templates/actions/components/CloneTemplateModal.tsx
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
Labels: lgtm, approved

#280 adding services table to vm details tab
  src/views/virtualmachines/details/tabs/details/VirtualMachineDetailsPage.tsx
  src/views/virtualmachines/details/tabs/details/components/sections/ServicesSection.tsx
Labels: lgtm, approved

#271 VM overview utilization card - donuts charts
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/VirtualMachinesOverviewTabUtilization.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/TimeDropdown.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/utils/queries.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/utils/utils.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/virtual-machines-overview-tab-utilization.scss
  tsconfig.json
  yarn.lock
Labels: lgtm, approved

#279 Stop disabling static plugin
  package.json
Labels: lgtm, approved

#242 add delete VM modal
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/components/DeleteOwnedResourcesMessage.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
  src/views/virtualmachines/actions/components/DeleteVMModal/utils/helpers.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
Labels: lgtm, approved

#283 compress catalog svgs and add img loading
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/templatescatalog/utils/svg/bsd.svg
  src/views/catalog/templatescatalog/utils/svg/linux.svg
  src/views/catalog/templatescatalog/utils/svg/ubuntu.svg
  src/views/catalog/templatescatalog/utils/svg/windows.svg
Labels: lgtm, approved

#284 fix disks tab crashing when disks array is empty
  src/views/catalog/utils/useWizardSourceAvailable.ts
  src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
  src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
  src/views/catalog/wizard/tabs/scripts/components/CloudInit.tsx
Labels: lgtm, approved

#262 Add permissions card to overview
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/SerialConsole/Xterm/Xterm.tsx
  src/utils/flags/consts.ts
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/permissions-card/PermissionsCard.scss
  src/views/clusteroverview/overview/components/permissions-card/PermissionsCard.tsx
  src/views/clusteroverview/overview/components/permissions-card/hooks/useOverviewPermissions.ts
  src/views/clusteroverview/overview/components/permissions-card/utils/PermissionsCardPopover.scss
  src/views/clusteroverview/overview/components/permissions-card/utils/PermissionsCardPopover.tsx
  src/views/clusteroverview/overview/components/permissions-card/utils/PermissionsCountItem.scss
  src/views/clusteroverview/overview/components/permissions-card/utils/PermissionsCountItem.tsx
  src/views/clusteroverview/overview/components/permissions-card/utils/PermissionsItem.scss
  src/views/clusteroverview/overview/components/permissions-card/utils/PermissionsItem.tsx
  src/views/clusteroverview/overview/components/permissions-card/utils/constants.ts
Labels: lgtm, approved

#285 fix customize skeleton and upload button
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
  src/views/catalog/customize/components/CustomizeVirtualMachineSkeleton.tsx
  src/views/catalog/customize/tests/CustomizeSource.test.tsx
  src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx
Labels: lgtm, approved

#287 fix boot source selector
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/utils/resources/vm/utils/selectors.ts
  src/utils/resources/vm/utils/source.ts
Labels: lgtm, approved

#282 Affinity modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AffinityModal/AffinityModal.tsx
  src/utils/components/AffinityModal/components/AddAffinityRuleButton.tsx
  src/utils/components/AffinityModal/components/AffinityDescriptionText.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityEditModal.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/AffinityForm.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityConditionSelect.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityEditList.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityEditRow.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityTypeSelect.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/ErrorHelperText.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/ExpressionEditList.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/FieldsEditList.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/NodeExpressionDescriptionText.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/NodeFieldsDescriptionText.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/PrefferedAffinityWeightInput.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/TopologyKeyInput.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/WorkloadExpressionDescriptionText.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/hooks/useNodeFieldQualifier.ts
  src/utils/components/AffinityModal/components/AffinityEditModal/hooks/useNodeLabelQualifier.ts
  src/utils/components/AffinityModal/components/AffinityEmptyState.tsx
  src/utils/components/AffinityModal/components/AffinityList/AffinityList.tsx
  src/utils/components/AffinityModal/components/AffinityList/components/AffinityRow.tsx
  src/utils/components/AffinityModal/components/AffinityList/components/AffinityRowActionsDropdown.tsx
  src/utils/components/AffinityModal/components/AffinityList/hooks/useAffinityColumns.ts
  src/utils/components/AffinityModal/components/AffinityList/utils/constants.ts
  src/utils/components/AffinityModal/hooks/useAffinitiesQualifiedNodes.ts
  src/utils/components/AffinityModal/hooks/useRequiredAndPrefferedQualifiedNodes.ts
  src/utils/components/AffinityModal/utils/constants.ts
  src/utils/components/AffinityModal/utils/helpers.ts
  src/utils/components/AffinityModal/utils/types.ts
  src/utils/components/NodeSelectorModal/components/NodeCheckerAlert.tsx
  src/views/virtualmachines/details/tabs/details/components/Affinity/AffinityModal.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineSchedulingLeftGrid.tsx
Labels: lgtm, approved

#290 chainging the space in vmi console tab and in vm console tab
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
  src/views/virtualmachinesinstance/details/tabs/console/VirtualMachinesInstancePageConsoleTab.tsx
Labels: lgtm, approved

#288 add affinity modal to scheduling tab
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
Labels: lgtm, approved

#289 Tolerations modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/TolerationsModal/TolerationEditRow.tsx
  src/utils/components/TolerationsModal/TolerationListHeaders.tsx
  src/utils/components/TolerationsModal/TolerationModalDescriptionText.tsx
  src/utils/components/TolerationsModal/TolerationsModal.tsx
  src/utils/components/TolerationsModal/utils/constants.ts
  src/utils/components/TolerationsModal/utils/helpers.ts
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineSchedulingLeftGrid.tsx
Labels: lgtm, approved

#291 fix hardware modal title
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/HardwareDevices/HardwareDevices.tsx
  src/utils/components/HardwareDevices/HardwareDevicesModal.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabHardwareDevices/VirtualMachinesOverviewTabHardwareDevices.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/HadwareDevices/HardwareDevices.tsx
Labels: lgtm, approved

#293 Add boot source logic to disks tables and modals
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/BootSourceCheckbox/BootSourceCheckbox.scss
  src/utils/components/DiskModal/DiskFormFields/BootSourceCheckbox/BootSourceCheckbox.tsx
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/components/DiskModal/state/actions.ts
  src/utils/components/DiskModal/state/initialState.ts
  src/utils/components/DiskModal/state/reducers.ts
  src/utils/components/DiskModal/utils/editDiskModalHelpers.ts
  src/utils/resources/vm/hooks/disk/useDisksTableData.ts
  src/utils/resources/vm/utils/disk/constants.ts
  src/utils/resources/vm/utils/disk/rowData.ts
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
  src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
  src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRow.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/hooks/useEditDiskStates.ts
Labels: lgtm, approved

#294 adding title status in vmi
  src/views/virtualmachinesinstance/details/VirtualMachinesInstancePage.tsx
  src/views/virtualmachinesinstance/details/VirtualMachinesInstancePageHeader.tsx
Labels: lgtm, approved

#298 Add inventory card to overview
  locales/en/plugin__kubevirt-plugin.json
  src/utils/utils/utils.ts
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/inventory-card/InventoryCard.scss
  src/views/clusteroverview/overview/components/inventory-card/InventoryCard.tsx
  src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.scss
  src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx
  src/views/clusteroverview/overview/components/inventory-card/utils/constants.ts
  src/views/clusteroverview/overview/components/inventory-card/utils/flattenTemplates.ts
  src/views/clusteroverview/overview/components/inventory-card/utils/types.ts
  src/views/clusteroverview/overview/components/inventory-card/utils/utils.ts
  src/views/clusteroverview/overview/components/inventory-card/utils/vm-status-section/VMStatusInventoryItem.scss
  src/views/clusteroverview/overview/components/inventory-card/utils/vm-status-section/VMStatusInventoryItem.tsx
  src/views/clusteroverview/overview/components/inventory-card/utils/vm-status-section/VMStatusSection.scss
  src/views/clusteroverview/overview/components/inventory-card/utils/vm-status-section/VMStatusSection.tsx
  src/views/clusteroverview/overview/components/inventory-card/utils/vm-status-section/VMStatusSectionSkeleton.scss
  src/views/clusteroverview/overview/components/inventory-card/utils/vm-status-section/VMStatusSectionSkeleton.tsx
  src/views/clusteroverview/overview/utils/utils.ts
Labels: lgtm, approved

#295 Fix VM action font weight on VM details header
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
Labels: lgtm, approved

#300 [e2e] test navigate to virtualization overview
  cypress/support/login.ts
Labels: lgtm, approved

#301 Template disk tab
  src/utils/components/TemplateNameTableData/TemplateNameTableData.tsx
  src/utils/components/TemplateNameTableData/template-name-table-data.scss
  src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx
  src/views/clusteroverview/overview/components/inventory-card/utils/utils.ts
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/details/hooks/useTemplateTabs.ts
  src/views/templates/details/tabs/disk/TemplateDisksPage.tsx
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/disks/components/DiskListTitle.tsx
  src/views/templates/details/tabs/disks/components/DiskRow.tsx
  src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
  src/views/templates/details/tabs/disks/hooks/useDiskColumns.ts
  src/views/templates/details/tabs/disks/hooks/useDisksFilters.ts
  src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts
  src/views/templates/details/tabs/disks/hooks/useTemplateDisksTableData.ts
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx
  src/views/templates/details/tabs/network/template-network-page.scss
Labels: lgtm, approved

#299 Add top consumers card to overview
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/ExternalLink/ExternalLink.tsx
  src/utils/utils/ObjectEnum.ts
  src/utils/utils/humanize.js
  src/utils/utils/utils.ts
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/TopConsumersCard.scss
  src/views/clusteroverview/overview/components/top-consumers-card/TopConsumersCard.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/FormPFSelect.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/NoDataAvailableMessage.scss
  src/views/clusteroverview/overview/components/top-consumers-card/utils/NoDataAvailableMessage.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumerCard.scss
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumerCard.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumersChartList.scss
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumersChartList.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumersGridRow.scss
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumersGridRow.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumersProgressChart.scss
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumersProgressChart.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/constants.ts
  src/views/clusteroverview/overview/components/top-consumers-card/utils/queries.ts
  src/views/clusteroverview/overview/components/top-consumers-card/utils/topConsumerMetric.ts
  src/views/clusteroverview/overview/components/top-consumers-card/utils/topConsumerScope.ts
  src/views/clusteroverview/overview/components/top-consumers-card/utils/utils.ts
  yarn.lock
Labels: lgtm, approved

#303 fix edit disk modal #1
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/components/DiskModal/utils/editDiskModalHelpers.ts
  src/utils/components/DiskModal/utils/helpers.ts
Labels: lgtm, approved

#297 Utilization card vm overview
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/VirtualMachinesOverviewTabUtilization.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/ComponentReady/ComponentReady.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageThresholdChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/virtual-machines-overview-tab-utilization.scss
Labels: lgtm, approved

#305 Adding console standalone route and fix links and actions
  console-extensions.json
  package.json
  src/utils/components/Consoles/ConsoleStandAlone.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
  src/views/virtualmachinesinstance/actions/VirtualMachinesInstanceActions.tsx
  src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx
Labels: lgtm, approved

#310 Adding descheduler modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DeschedulerModal/DeschedulerModal.tsx
  src/views/virtualmachines/details/tabs/details/components/Descheduler/Descheduler.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineSchedulingLeftGrid.tsx
Labels: lgtm, approved

#306 Added ctrl+alt+1 ctrl+alt+2 keys combination console:
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsoleActions.tsx
  src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
Labels: lgtm, approved

#302 Adding cloud int credentials to console component
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
  src/utils/components/Consoles/utils/constants.ts
  src/utils/components/Consoles/utils/utils.ts
Labels: lgtm, approved

#307 Common Template No Editable
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/disks/components/DiskRow.tsx
  src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx
Labels: lgtm, approved

#308 Move running VMs directory to proper level
  src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
  src/views/clusteroverview/overview/components/inventory-card/utils/vm-status-section/VMStatusSection.tsx
  src/views/clusteroverview/overview/components/running-vms-per-template-card/RunningVMsPerTemplateCard.scss
  src/views/clusteroverview/overview/components/running-vms-per-template-card/RunningVMsPerTemplateCard.tsx
  src/views/clusteroverview/overview/components/running-vms-per-template-card/hooks/useRunningVMsPerTemplateResources.ts
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/EmptyStateNoVMs.tsx
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/RunningVMsChartLegend.scss
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/RunningVMsChartLegend.tsx
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/RunningVMsChartLegendLabel.scss
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/RunningVMsChartLegendLabel.tsx
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/constants.ts
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/utils.ts
Labels: lgtm, approved

#312 Add Template Details tab content
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/details/tabs/details/TemplateDetailsPage.scss
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
  src/views/templates/details/tabs/details/components/Annotations.tsx
  src/views/templates/details/tabs/details/components/BootOrderItem.tsx
  src/views/templates/details/tabs/details/components/BootSource.tsx
  src/views/templates/details/tabs/details/components/DescriptionItem.tsx
  src/views/templates/details/tabs/details/components/HardwareDevices.tsx
  src/views/templates/details/tabs/details/components/Labels.tsx
  src/views/templates/details/tabs/details/components/Name.tsx
  src/views/templates/details/tabs/details/components/Namespace.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsRightGrid.tsx
  src/views/templates/utils/constants.ts
  src/views/templates/utils/index.ts
  src/views/templates/utils/selectors.ts
Labels: lgtm, approved

#314 Wizard Overview Toleration
  src/utils/components/Tolerations/Tolerations.tsx
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineSchedulingLeftGrid.tsx
Labels: lgtm, approved

#315 adding virtual machine instance empty state
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachinesinstance/list/VirtualMachinesInstancesList.tsx
  src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceEmptyState/VirtualMachineInstanceEmptyState.tsx
Labels: lgtm, approved

#316 wizard- move tolerations to scheduling
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
Labels: lgtm, approved

#317 update sdk 0.0.8
  package.json
  yarn.lock
Labels: lgtm, approved

#309 adding actions to vmi page
  src/views/virtualmachinesinstance/details/VirtualMachinesInstancePage.tsx
  src/views/virtualmachinesinstance/details/VirtualMachinesInstancePageHeader.tsx
  src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceActions/VirtualMachineInstanceAction.tsx
Labels: lgtm, approved

#318 Disable scheduling modal while VM is running
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineSchedulingLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineSchedulingRightGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/sections/SchedulingSection.tsx
Labels: lgtm, approved

#319 fixes #2
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/resources/template/utils/selectors.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
Labels: lgtm, approved

#322 Add Base template, Created at, Owner to Template Details
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/details/components/BaseTemplate.tsx
  src/views/templates/details/tabs/details/components/CreatedAt.tsx
  src/views/templates/details/tabs/details/components/Owner.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
  src/views/templates/utils/constants.ts
  src/views/templates/utils/selectors.ts
Labels: lgtm, approved

#324 Improve useGuestOS hook with guest agent check
  src/utils/resources/vmi/utils/guest-agent.ts
  src/utils/resources/vmi/utils/index.ts
  src/views/virtualmachinesinstance/details/hooks/useGuestOS.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/UserList/ActiveUserList.tsx
Labels: lgtm, approved

#320 Adding console remote desktop for windows machines
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/Detail.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/ManualConnection.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/MoreInformationDefault.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/MultusNetwork.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RDP.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RDPConnector.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RdpServiceNotConfigured.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RemoteViewer.tsx
  src/utils/components/Consoles/components/DesktopViewer/DesktopViewer.tsx
  src/utils/components/Consoles/components/DesktopViewer/utils/constants.ts
  src/utils/components/Consoles/components/DesktopViewer/utils/types.ts
  src/utils/components/Consoles/components/DesktopViewer/utils/utils.ts
  src/utils/components/Consoles/components/utils/ConsoleConsts.ts
  src/utils/resources/vm/utils/operation-system/operationSystem.ts
  yarn.lock
Labels: lgtm, approved

#325 Add Boot Order Modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityEditRow.tsx
  src/utils/components/BootOrderModal/BootOrderEmptyState.tsx
  src/utils/components/BootOrderModal/BootOrderModal.tsx
  src/utils/components/BootOrderModal/BootOrderModalBody.tsx
  src/utils/components/BootOrderModal/add-device-button.tsx
  src/utils/components/BootOrderModal/add-device-form-select.tsx
  src/utils/components/BootOrderModal/add-device.tsx
  src/utils/components/BootOrderModal/boot-order.scss
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
Labels: lgtm, approved

#313 VM SSH Access and User Credentials
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
  src/utils/components/Consoles/utils/utils.ts
  src/utils/components/SSHAccess/SSHAccess.tsx
  src/utils/components/SSHAccess/SSHAccessModal.tsx
  src/utils/components/SSHAccess/constants.ts
  src/utils/components/SSHAccess/utils.ts
  src/utils/components/UserCredentials/UserCredentials.tsx
  src/utils/components/UserCredentials/useSSHCommand.ts
  src/utils/resources/vmi/utils/cloud-init.ts
  src/utils/resources/vmi/utils/index.ts
  src/utils/utils/utils.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/RunningVirtualMachineDetailsRightGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/details/hooks/useSSHService.tsx
  src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/SSHAccess/SSHAccess.tsx
Labels: lgtm, approved

#326 add descheduler to wizard scheduling tab
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
  src/views/catalog/wizard/tabs/scheduling/components/Descheduler.tsx
Labels: lgtm, approved

#323 Fixed a bug in vmi creation
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachinesinstance/list/VirtualMachinesInstancesList.tsx
  src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceEmptyState/VirtualMachineInstanceEmptyState.tsx
Labels: lgtm, approved

#321 Adding pending changes alerts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/BootOrderModal/BootOrderModal.tsx
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
  src/utils/components/HardwareDevices/HardwareDevicesModal.tsx
  src/utils/components/PendingChanges/ModalPendingChangesAlert/ModalPendingChangesAlert.tsx
  src/utils/components/PendingChanges/PendingChangesAlert/PendingChangesAlert.scss
  src/utils/components/PendingChanges/PendingChangesAlert/PendingChangesAlert.tsx
  src/utils/components/PendingChanges/PendingChangesBreadcrumb/PendingChangesBreadcrumb.tsx
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/utils/constants.ts
  src/utils/components/PendingChanges/utils/helpers.ts
  src/utils/components/PendingChanges/utils/types.ts
  src/utils/utils/utils.ts
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert.tsx
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/RunningVirtualMachineDetailsRightGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineSchedulingRightGrid.tsx
  src/views/virtualmachines/details/tabs/network/NetworkInterfaceListPage.tsx
  src/views/virtualmachines/details/tabs/network/copmonents/modal/NetworkInterfaceModal.tsx
Labels: lgtm, approved

#332 Connecting copy ssh command button in vm overview tab
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
Labels: lgtm, approved

#333 Bug 2071488: "Migrate Node to Node" is confusing.
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#331 Template parameters in tables
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/BootOrder/BootableDevicesList.tsx
  src/utils/components/TemplateValue/TemplateValue.tsx
  src/utils/components/TemplateValue/template-value.scss
  src/utils/resources/template/utils/flavor.ts
  src/utils/resources/template/utils/selectors.ts
  src/utils/utils/utils.ts
  src/views/templates/details/tabs/disks/components/DiskRow.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesCPUMemory.ts
  src/views/templates/list/hooks/useVirtualMachineTemplatesCPUMemory.tsx
Labels: lgtm, approved

#339 Changing the events tab with the disks tab in vmi
  src/views/virtualmachinesinstance/details/hooks/useVirtualMachinesInstanceTabs.ts
Labels: lgtm, approved

#304 adding breadcrumb to vm and vmi
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/list/components/VirtualMachineBreadcrumb/VirtualMachineBreadcrumb.tsx
  src/views/virtualmachinesinstance/details/VirtualMachinesInstancePageHeader.tsx
  src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceBreadcrumb/VirtualMachineInstanceBreadcrumb.tsx
Labels: lgtm, approved

#336 Bug 2074337: Missing docker:// prefix in vm creation from registry
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/utils.ts
  src/views/catalog/customize/tests/CustomizeSource.test.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#338 Fix Template's URL at Virtualization overview inventory card
  src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx
Labels: lgtm, approved

#341 Determine if template has editable Boot Source
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/utils/resources/template/utils/helpers.ts
  src/utils/resources/template/utils/index.ts
  src/views/templates/actions/VirtualMachineTemplatesActions.tsx
  src/views/templates/actions/editBootSource.ts
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/details/TemplateActions.tsx
Labels: lgtm, approved

#342 Add Scheduling tab to VM Template details page
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/hooks/useTemplateTabs.ts
  src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
  src/views/templates/details/tabs/scheduling/components/AffinityRules.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResources.tsx
  src/views/templates/details/tabs/scheduling/components/EvictionStrategy.tsx
  src/views/templates/details/tabs/scheduling/components/NodeSelector.tsx
  src/views/templates/details/tabs/scheduling/components/TemplateSchedulingLeftGrid.tsx
  src/views/templates/details/tabs/scheduling/components/TemplateSchedulingRightGrid.tsx
  src/views/templates/details/tabs/scheduling/components/Tolerations.tsx
  src/views/templates/utils/index.ts
  src/views/templates/utils/selectors.ts
Labels: lgtm, approved

#340 Bug 2065019: 'Running VMs per template' in the new overview tab counts VMs that are not running
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/overview/components/running-vms-per-template-card/RunningVMsPerTemplateCard.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#343 Remove extra space in VM Template Details tab
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
Labels: lgtm, approved

#344 Bug 2079783: Actions are broken in topology view
  src/utils/resources/shared.ts
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#269 Add 'Edit boot source' modal to VM Templates actions
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/actions/components/EditBootSourceModal.scss
  src/views/templates/actions/components/EditBootSourceModal.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeClaimSelect.scss
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeClaimSelect.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeClainSelectSkeleton.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/index.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/utils.tsx
  src/views/templates/actions/components/SelectSource.tsx
  src/views/templates/actions/components/SelectSourceOption.tsx
  src/views/templates/actions/components/VolumeSize.tsx
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/utils/constants.ts
Labels: lgtm, approved

#346 Move VM Template's Scheduling tab next to YAML tab
  src/views/templates/details/hooks/useTemplateTabs.ts
Labels: lgtm, approved

#347 Edit Boot Source
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/views/templates/actions/components/EditBootSourceModal.scss
  src/views/templates/actions/components/EditBootSourceModal.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
  src/views/templates/actions/components/SelectSourceOption.tsx
  src/views/templates/actions/constants.ts
  src/views/templates/actions/editBootSource.ts
Labels: lgtm, approved
