Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2022-02, with the labels that each got.

#58 new structure
  README.md
  console-extensions.json
  cypress/tests/VirtualMachinesList.spec.ts
  package.json
  src/constants/index.ts
  src/constants/vm-status.ts
  src/models/index.ts
  src/types/index.ts
  src/utils/i18n.ts
  src/views/catalog/README.md
  src/views/catalog/actions/README.md
  src/views/catalog/tileview/README.md
  src/views/catalog/wizard/README.md
  src/views/clusteroverview/README.md
  src/views/clusteroverview/actions/README.md
  src/views/clusteroverview/metrics/README.md
  src/views/clusteroverview/overview/README.md
  src/views/templates/README.md
  src/views/templates/actions/README.md
  src/views/templates/details/README.md
  src/views/templates/list/README.md
  src/views/templates/metrics/README.md
  src/views/virtualmachines/README.md
  src/views/virtualmachines/actions/README.md
  src/views/virtualmachines/details/README.md
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VMStatusConditionLabel/VMStatusConditionLabel.tsx
  src/views/virtualmachines/list/components/VMStatusConditionLabel/index.ts
  src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/VMStatusConditionLabel.test.tsx
  src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/VMStatusConditionLabelList.test.tsx
  src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/__snapshots__/VMStatusConditionLabel.test.tsx.snap
  src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/__snapshots__/VMStatusConditionLabelList.test.tsx.snap
  src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/mocks.ts
  src/views/virtualmachines/metrics/README.md
  src/views/virtualmachinesInstance/README.md
  src/views/virtualmachinesInstance/actions/README.md
  src/views/virtualmachinesInstance/details/README.md
  src/views/virtualmachinesInstance/metrics/README.md
  yarn.lock
Labels: lgtm, approved, size/L

#59 Add nav items
  console-extensions.json
Labels: lgtm, approved

#60 Add VM Catalog Tile View
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/hooks/useEventListener.ts
  src/utils/hooks/useInputDebounce.ts
  src/utils/hooks/useIsAdmin.ts
  src/utils/hooks/useURLParams.ts
  src/utils/i18n.ts
  src/utils/selectors.ts
  src/views/catalog/README.md
  src/views/catalog/actions/README.md
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilterGroup.scss
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilterGroup.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilters.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogSkeleton.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/templatescatalog/hooks/useVmTemplates.tsx
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/catalog/templatescatalog/types/template.ts
  src/views/catalog/templatescatalog/utils/annotations.ts
  src/views/catalog/templatescatalog/utils/constants.ts
  src/views/catalog/templatescatalog/utils/helpers.ts
  src/views/catalog/templatescatalog/utils/os-icons.tsx
  src/views/catalog/templatescatalog/utils/svg/bsd.svg
  src/views/catalog/templatescatalog/utils/svg/centos.svg
  src/views/catalog/templatescatalog/utils/svg/debian.svg
  src/views/catalog/templatescatalog/utils/svg/fedora.svg
  src/views/catalog/templatescatalog/utils/svg/linux.svg
  src/views/catalog/templatescatalog/utils/svg/opensuse.svg
  src/views/catalog/templatescatalog/utils/svg/rhel.svg
  src/views/catalog/templatescatalog/utils/svg/ubuntu.svg
  src/views/catalog/templatescatalog/utils/svg/windows.svg
  src/views/catalog/tileview/README.md
Labels: lgtm, approved

#64 add i18n test to github actions
  .github/workflows/ci_checks.yml
  locales/en/plugin__kubevirt-plugin.json
Labels: approved

#67 Add logo to readme
  README.md
  images/logos.png
Labels: lgtm, approved

#66 add unit-test to templates catalog
  __mocks__/react-i18next.ts
  __mocks__/react-router-dom.ts
  jest.config.ts
  package.json
  src/utils/models/index.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilterGroup.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilters.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/templatescatalog/hooks/useVmTemplates.tsx
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
  src/views/catalog/templatescatalog/tests/mocks.ts
  src/views/catalog/templatescatalog/types/template.ts
  src/views/catalog/templatescatalog/utils/helpers.ts
  tsconfig.json
  yarn.lock
Labels: lgtm, approved

#72 Upgrade Yarn v1 to Yarn v3
  .gitignore
  .yarn/releases/yarn-3.1.1.cjs
  .yarnrc.yml
  Dockerfile.ci
  package.json
  test-prow-e2e.sh
  webpack.config.ts
  yarn.lock
Labels: lgtm, approved

#75 Routing and structure of VMI page
  console-extensions.json
  package.json
  src/views/virtualmachinesinstances/page/VirtualMachinesInstancesPage.tsx
  src/views/virtualmachinesinstances/page/VirtualMachinesInstancesPageHeader.tsx
  src/views/virtualmachinesinstances/page/hooks/useVirtualMachinesInstancesTabs.ts
  src/views/virtualmachinesinstances/page/tabs/console/VirtualMachinesInstancesPageConsoleTab.tsx
  src/views/virtualmachinesinstances/page/tabs/details/VirtualMachinesInstancesPageDetailsTab.tsx
  src/views/virtualmachinesinstances/page/tabs/disks/VirtualMachinesInstancesPageDisksTab.tsx
  src/views/virtualmachinesinstances/page/tabs/events/VirtualMachinesInstancesPageEventsTab.tsx
  src/views/virtualmachinesinstances/page/tabs/network/VirtualMachinesInstancesPageNetworkTab.tsx
  src/views/virtualmachinesinstances/page/tabs/yaml/VirtualMachinesInstancesPageYAMLTab.tsx
Labels: lgtm, approved

#76 added 'plugin__kubevirt-plugin' as default namespace
  README.md
  i18next-parser.config.js
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilters.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved

#78 Add network interfaces tab
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/VirtualMachinePage.tsx
  src/views/virtualmachines/details/components/network/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/components/network/NetworkInterfaceList.tsx
  src/views/virtualmachines/details/components/network/NetworkInterfaceListPage.tsx
  src/views/virtualmachines/details/components/network/NetworkInterfaceRow.tsx
  src/views/virtualmachines/details/components/network/hooks/useNetworkColumns.ts
  src/views/virtualmachines/details/components/network/utils.ts
  src/views/virtualmachines/details/tabs.tsx
  src/views/virtualmachines/utils/selectors.ts
Labels: lgtm, approved

#80 add useKubevirtTranslation hook
  README.md
  src/utils/hooks/useKubevirtTranslation.ts
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilters.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachinesinstances/page/VirtualMachinesInstancesPageHeader.tsx
  src/views/virtualmachinesinstances/page/hooks/useVirtualMachinesInstancesTabs.ts
Labels: lgtm, approved

#71 Add template catalog drawer
  __mocks__/react-router-dom.ts
  jest-setup.ts
  jest.config.ts
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/hooks/useInputDebounce.ts
  src/utils/hooks/useURLParams.ts
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateCatalogDrawer.scss
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawer.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogEmptyState.tsx
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
  src/views/catalog/templatescatalog/tests/mocks.ts
  src/views/catalog/templatescatalog/utils/constants.ts
  src/views/catalog/templatescatalog/utils/flavor.ts
  src/views/catalog/templatescatalog/utils/helpers.ts
  src/views/catalog/templatescatalog/utils/os-icons.tsx
  yarn.lock
Labels: lgtm, approved

#83 bump sdk versions
  package.json
  yarn.lock
Labels: lgtm, approved

#77 Change vmi folder
  console-extensions.json
  package.json
  src/views/virtualmachinesinstance/README.md
  src/views/virtualmachinesinstance/actions/README.md
  src/views/virtualmachinesinstance/details/README.md
  src/views/virtualmachinesinstance/details/VirtualMachinesInstancePage.tsx
  src/views/virtualmachinesinstance/details/VirtualMachinesInstancePageHeader.tsx
  src/views/virtualmachinesinstance/details/hooks/useVirtualMachinesInstanceTabs.ts
  src/views/virtualmachinesinstance/details/tabs/console/VirtualMachinesInstancePageConsoleTab.tsx
  src/views/virtualmachinesinstance/details/tabs/details/VirtualMachinesInstancePageDetailsTab.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/VirtualMachinesInstancePageDisksTab.tsx
  src/views/virtualmachinesinstance/details/tabs/events/VirtualMachinesInstancePageEventsTab.tsx
  src/views/virtualmachinesinstance/details/tabs/network/VirtualMachinesInstancePageNetworkTab.tsx
  src/views/virtualmachinesinstance/details/tabs/yaml/VirtualMachinesInstancePageYAMLTab.tsx
  src/views/virtualmachinesinstance/metrics/README.md
  src/views/virtualmachinesinstances/page/VirtualMachinesInstancesPage.tsx
  src/views/virtualmachinesinstances/page/hooks/useVirtualMachinesInstancesTabs.ts
  src/views/virtualmachinesinstances/page/tabs/console/VirtualMachinesInstancesPageConsoleTab.tsx
  src/views/virtualmachinesinstances/page/tabs/details/VirtualMachinesInstancesPageDetailsTab.tsx
  src/views/virtualmachinesinstances/page/tabs/disks/VirtualMachinesInstancesPageDisksTab.tsx
  src/views/virtualmachinesinstances/page/tabs/events/VirtualMachinesInstancesPageEventsTab.tsx
  src/views/virtualmachinesinstances/page/tabs/network/VirtualMachinesInstancesPageNetworkTab.tsx
  src/views/virtualmachinesinstances/page/tabs/yaml/VirtualMachinesInstancesPageYAMLTab.tsx
Labels: lgtm, approved

#86 update codecov.yaml
  codecov.yml
Labels: approved

#82 Add hook that checks if Template supports QuickCreate
  jest.config.ts
  package.json
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawer.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/templatescatalog/hooks/useProcessedTemplate.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
  webpack.config.ts
  yarn.lock
Labels: lgtm, approved

#88 Add VM Template Source utils and hook
  src/views/catalog/templatescatalog/utils/flavor.ts
  src/views/catalog/templatescatalog/utils/helpers.ts
  src/views/catalog/utils/vm-template-source/useVmTemplateSource.ts
  src/views/catalog/utils/vm-template-source/utils.ts
  tsconfig.json
Labels: lgtm, approved

#87 update template catalog to latest design
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateCatalogDrawer.scss
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawer.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
  src/views/catalog/templatescatalog/utils/constants.ts
  src/views/catalog/utils/vm-template-source/useVmTemplateSource.ts
Labels: lgtm, approved

#91 add getResourceUrl method
  src/utils/resource.ts
  src/utils/tests/resource.test.ts
Labels: lgtm, approved

#90 Add vm quick create function
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved

#95 codecov don't wait for CI to finish before PR status check
  codecov.yml
Labels: lgtm, approved

#94 Add review page router
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/catalog/wizard/README.md
  src/views/catalog/wizard/Wizard.tsx
  src/views/catalog/wizard/tabs.tsx
  src/views/catalog/wizard/tabs/advanced/WizardAdvancedTab.tsx
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
  src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
  src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx
  src/views/catalog/wizard/tests/Wizard.test.tsx
Labels: lgtm, approved

#96 No loading spinner on error
  src/views/catalog/customize/components/CustomizeForm.tsx
  src/views/catalog/customize/tests/CustomizeForm.test.tsx
Labels: lgtm, approved

#89 Add VM actions example PR
  console-extensions.json
  package.json
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/actions.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineInstanceMigration.ts
  src/views/virtualmachines/actions/tests/actions.test.ts
  src/views/virtualmachines/actions/tests/mocks.ts
  src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
  yarn.lock
Labels: lgtm, approved

#62 VMI list
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/virtualmachinesinstance/list/VirtualMachinesInstancesList.tsx
  src/views/virtualmachinesinstance/list/VirtualMachinesInstancesRow.tsx
  src/views/virtualmachinesinstance/list/VirtualMachinesInstancesStatus.tsx
  src/views/virtualmachinesinstance/list/hooks/useVirtualMachinesInstancesColumns.tsx
  src/views/virtualmachinesinstance/list/utils/index.ts
  src/views/virtualmachinesinstance/list/utils/virtualMachinesInstancesConstants.ts
  src/views/virtualmachinesinstance/list/utils/virtualMachinesInstancesRowFilter.ts
  src/views/virtualmachinesinstance/list/utils/virtualMachinesInstancesStatuses.ts
Labels: lgtm, approved

#97 Combine Catalog routes to one Switch
  console-extensions.json
  package.json
  src/views/catalog/Catalog.tsx
Labels: lgtm, approved

#99 Add standalone i18n github action
  .github/workflows/ci_checks.yml
Labels: lgtm, approved

#100 lower codecov target threshold
  codecov.yml
Labels: lgtm, approved

#92 vmi disk tab
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/virtualmachinesinstance/details/tabs/disks/VirtualMachinesInstancePageDisksTab.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/hooks/useDisksTableColumns.ts
  src/views/virtualmachinesinstance/details/tabs/disks/hooks/useDisksTableDisks.ts
  src/views/virtualmachinesinstance/details/tabs/disks/hooks/useFileSystemTableColumns.ts
  src/views/virtualmachinesinstance/details/tabs/disks/hooks/useFileSystemTableGuestOS.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTable.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTableRow.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTableTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTable.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTableRow.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTableTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/utils/virtualMachinesInstancePageDisksTabUtils.ts
  src/views/virtualmachinesinstance/details/tabs/disks/virtual-machines-insance-page-disks-tab.scss
  yarn.lock
Labels: lgtm, approved

#102 Change sorting on disk tab
  src/views/virtualmachinesinstance/details/tabs/disks/hooks/useDisksTableColumns.ts
  src/views/virtualmachinesinstance/details/tabs/disks/hooks/useDisksTableDisks.ts
  src/views/virtualmachinesinstance/details/tabs/disks/hooks/useFileSystemTableColumns.ts
  src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTable.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/utils/virtualMachinesInstancePageDisksTabUtils.ts
Labels: lgtm, approved

#101 Adding sorting to VMI list
  package.json
  src/views/virtualmachinesinstance/list/VirtualMachinesInstancesRow.tsx
  src/views/virtualmachinesinstance/list/hooks/useVirtualMachinesInstancesColumns.tsx
  yarn.lock
Labels: lgtm, approved

#104 Missing OS annotation on VMI
  src/views/virtualmachinesinstance/list/utils/virtualMachinesInstancesRowFilter.ts
  src/views/virtualmachinesinstance/list/utils/virtualMachinesInstancesStatuses.ts
Labels: lgtm, approved
