Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2022-05, with the labels that each got.

#327 Adding events tab to vm and vmi
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/events/VirtualMachinePageEvents.tsx
  src/views/virtualmachinesinstance/details/tabs/events/VirtualMachinesInstancePageEventsTab.tsx
Labels: lgtm, approved

#348 Add Descheduler to VM Template's Scheduling tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.scss
  src/views/templates/details/tabs/scheduling/components/Descheduler.tsx
  src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
  src/views/templates/details/tabs/scheduling/components/TemplateSchedulingLeftGrid.tsx
  src/views/templates/utils/constants.ts
  src/views/templates/utils/index.ts
Labels: lgtm, approved, do-not-merge/hold

#350 fix slow SVG load in template catalog
  package.json
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  webpack.config.ts
  yarn.lock
Labels: lgtm, approved

#345 Bug 2079366: rootdisk is not able to edit
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceDataSourceSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceDataSourceSelectName.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceDataSourceSelectNamespace.tsx
  src/utils/components/DiskModal/DiskFormFields/hooks/useProjectsAndDataSources.ts
  src/utils/components/DiskModal/DiskFormFields/utils/constants.ts
  src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
  src/utils/components/DiskModal/state/actions.ts
  src/utils/components/DiskModal/state/initialState.ts
  src/utils/components/DiskModal/state/reducers.ts
  src/utils/components/DiskModal/utils/helpers.ts
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
  src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#352 Add filter by template to VM list view
  src/utils/resources/template/utils/constants.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved

#351 Fixing the conditions column in vm
  src/views/virtualmachines/list/components/VMStatusConditionLabel/VMStatusConditionLabel.tsx
  src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/VMStatusConditionLabel.test.tsx
  src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/__snapshots__/VMStatusConditionLabel.test.tsx.snap
  src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/__snapshots__/VMStatusConditionLabelList.test.tsx.snap
Labels: lgtm, approved

#355 switch back to new i18next-parser
  i18next-parser.config.js
  i18next-scanner.config.js
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/SSHAccess/SSHAccessModal.tsx
  yarn.lock
Labels: lgtm, approved

#357 Improve available source catalog performance
  src/utils/resources/template/hooks/useVmTemplates.tsx
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/hooks/useAvailableSourceTemplates.ts
Labels: lgtm, approved

#359 Bug 2070864: non-privileged user cannot see catalog tiles
  src/utils/resources/template/hooks/useVmTemplates.tsx
  src/views/catalog/templatescatalog/hooks/useAvailableSourceTemplates.ts
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#356 fix overview page crashing
  src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/SubscriptionStatus.tsx
Labels: lgtm, approved

#362 switch scripts tab ssh to new api
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/wizard/tabs/scripts/components/CloudInit.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx
  src/views/catalog/wizard/tabs/scripts/utils/cloudint-utils.ts
Labels: lgtm, approved

#363 Clone Template Modal select project
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
  src/utils/components/CloneTemplateModal/SelectProject.tsx
  src/utils/components/CloneTemplateModal/utils.ts
  src/utils/utils/utils.ts
Labels: lgtm, approved

#360 fix useIsAdmin to use `useFlag`
  src/utils/hooks/useIsAdmin.ts
  src/utils/resources/template/hooks/useVmTemplates.tsx
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
Labels: lgtm, approved

#349 [e2] added test for inclusive language
  .gitignore
  cypress/tests/inclusive-language.spec.ts
Labels: lgtm, approved, ok-to-test

#366 Fix Clone Template Modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloneTemplateModal/CloneStorageCheckbox.tsx
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
  src/utils/components/CloneTemplateModal/utils.ts
Labels: lgtm, approved

#367 create DebouncedTextInput component
  src/utils/components/DebouncedTextInput/DebouncedTextInput.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx
Labels: lgtm, approved

#365 Display the popovers in VM Template Details tab correctly
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/details/components/Annotations.tsx
  src/views/templates/details/tabs/details/components/BaseTemplate.tsx
  src/views/templates/details/tabs/details/components/CreatedAt.tsx
  src/views/templates/details/tabs/details/components/Labels.tsx
  src/views/templates/details/tabs/details/components/Name.tsx
  src/views/templates/details/tabs/details/components/Namespace.tsx
  src/views/templates/details/tabs/details/components/Owner.tsx
Labels: lgtm, approved

#368 fix wizard header title
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/wizard/components/WizardHeader.tsx
Labels: lgtm, approved

#369 fix templates list filters and namespace changing
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts
Labels: lgtm, approved

#353 add network form to wizard cloudinit
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/wizard/tabs/scripts/components/CloudInit.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudInitNetworkForm.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx
  src/views/catalog/wizard/tabs/scripts/utils/cloud-init-data-helper.tsx
Labels: lgtm, approved

#372 bump kubevirt-api
  package.json
  yarn.lock
Labels: lgtm, approved

#370 Remove text in vm and vmi details tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/components/CloneVMModal/components/ConfigurationSummary.tsx
  src/views/virtualmachines/details/tabs/details/components/CPUMemory/CPUMemory.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineSchedulingRightGrid.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Scheduling/CPUMemory/CPUMemory.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Scheduling/Scheduling.tsx
Labels: lgtm, approved

#374 Template Parameters Tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/hooks/useTemplateTabs.ts
  src/views/templates/details/tabs/parameters/ParameterEditor.tsx
  src/views/templates/details/tabs/parameters/ParameterValueEditor.tsx
  src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
  src/views/templates/details/tabs/parameters/constants.ts
  src/views/templates/details/tabs/parameters/template-parameters-page.scss
  src/views/templates/details/tabs/parameters/utils.ts
Labels: lgtm, approved

#373 Move VM Details' Scheduling section to new Scheduling tab
  src/utils/components/PendingChanges/utils/constants.ts
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/details/VirtualMachineDetailsPage.tsx
  src/views/virtualmachines/details/tabs/scheduling/VirtualMachineSchedulingPage.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/Affinity.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/DedicatedResources.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/Descheduler.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/EvictionStrategy.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/NodeSelector.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/SchedulingSection/SchedulingSection.scss
  src/views/virtualmachines/details/tabs/scheduling/components/SchedulingSection/SchedulingSection.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingRightGrid.tsx
Labels: lgtm, approved

#381 Bug 2081409: Template tabs with alert for common templates
  src/views/templates/details/tabs/NoEditableTemplateAlert.tsx
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/parameters/ParameterEditor.tsx
  src/views/templates/details/tabs/parameters/ParameterValueEditor.tsx
  src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
  src/views/templates/details/tabs/parameters/template-parameters-page.scss
  src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
  src/views/templates/details/tabs/yaml/TemplateYAMLPage.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#378 Bug 2080833: Add cloudinit script editor
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudInit.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudInitEditor/CloudInitEditor.scss
  src/views/catalog/wizard/tabs/scripts/components/CloudInitEditor/CloudInitEditor.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudInitEditor/index.ts
  src/views/catalog/wizard/tabs/scripts/components/CloudInitNetworkForm.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx
  src/views/catalog/wizard/tabs/scripts/components/cloud-init.scss
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#382 Clone template modal in common template alert
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
  src/views/templates/details/tabs/NoEditableTemplateAlert.tsx
  src/views/templates/details/tabs/no-editable-template-alert.scss
Labels: lgtm, approved

#385 fix template details page crash if no description available
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
Labels: lgtm, approved

#386 Bug 2081831: [RFE] Improve disk hotplug UX
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/DetachHotplugDiskCheckbox.tsx
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/components/DiskModal/state/actions.ts
  src/utils/components/DiskModal/state/initialState.ts
  src/utils/components/DiskModal/state/reducers.ts
  src/utils/components/DiskModal/utils/helpers.ts
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
  src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
  src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
  src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts
  src/views/virtualmachines/actions/actions.ts
  src/views/virtualmachines/details/tabs/disk/modal/DeleteDiskModal.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRowActions.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/hooks/useEditDiskStates.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#377 fix loading error for overview resources
  src/views/clusteroverview/overview/components/inventory-card/InventoryCard.tsx
  src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx
  src/views/clusteroverview/overview/components/running-vms-per-template-card/RunningVMsPerTemplateCard.tsx
  src/views/clusteroverview/overview/components/running-vms-per-template-card/hooks/useRunningVMsPerTemplateResources.ts
  src/views/clusteroverview/overview/utils/utils.ts
Labels: lgtm, approved

#387 Changing in vmi page the console and event tabs location
  src/views/virtualmachinesinstance/details/hooks/useVirtualMachinesInstanceTabs.ts
Labels: lgtm, approved

#384 show ssh form in cloudinit editor view
  src/views/catalog/wizard/tabs/scripts/components/CloudInit.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx
  src/views/catalog/wizard/tabs/scripts/components/cloud-init.scss
Labels: lgtm, approved

#375 Add OS and Node filter to VM list view
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved

#379 Add migration tool page
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/globals.d.ts
  src/views/migration/MigrationToolPage.tsx
  src/views/migration/constant.ts
  src/views/migration/migration-illustration.png
  src/views/migration/migration-tool-page.scss
  src/views/migration/useMTVResources.tsx
  src/views/migration/utils.ts
Labels: lgtm, approved

#389 Bug 2083100: Something keeps loading in the 'node selector' modal
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#391 Bug 2083093: VM overview tab is crashed
  package.json
  src/utils/resources/vm/utils/operation-system/operationSystem.ts
  src/views/clusteroverview/overview/components/details-card/DetailsCard.tsx
  src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumersChartList.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
  src/views/virtualmachinesinstance/details/tabs/events/VirtualMachinesInstancePageEventsTab.tsx
  webpack.config.ts
  yarn.lock
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#388 Fix template's page to load templates for non-priv user
  src/utils/resources/template/hooks/useVmTemplates.tsx
  src/views/templates/list/VirtualMachineTemplatesList.tsx
Labels: lgtm, approved

#364 Display Tooltip when VM Template Descheduler not installed
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/scheduling/components/Descheduler.tsx
  src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
  src/views/templates/utils/index.ts
Labels: lgtm, approved

#390 Bug 2081671: Find SSH VMI Service by port
  src/utils/components/SSHAccess/SSHAccessModal.tsx
  src/utils/components/SSHAccess/constants.ts
  src/utils/components/SSHAccess/useSSHService.tsx
  src/utils/components/SSHAccess/utils.ts
  src/utils/components/UserCredentials/UserCredentials.tsx
  src/utils/components/UserCredentials/useSSHCommand.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/RunningVirtualMachineDetailsRightGrid.tsx
  src/views/virtualmachines/details/tabs/details/hooks/useSSHService.tsx
  src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#393 Wizard Customize boot order
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
  src/views/catalog/customize/cd.ts
  src/views/catalog/customize/constants.ts
Labels: lgtm, approved

#394 No namespace template list when in project
  src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
Labels: lgtm, approved

#396 Fix Windows drivers in customize wizard
  src/views/catalog/customize/drivers.ts
  src/views/catalog/customize/utils.ts
Labels: lgtm, approved

#395 move wizard create logic
  src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
  src/views/catalog/utils/tests/vm-produce.test.ts
  src/views/catalog/utils/useWizardVmCreate.ts
Labels: lgtm, approved

#399 Blank disk source on bootfromcd checkbox checked
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/utils.ts
  src/views/catalog/customize/components/ExpandableOptionalFields.tsx
  src/views/catalog/customize/tests/CustomizeForm.test.tsx
  src/views/catalog/customize/tests/CustomizeSource.test.tsx
  src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx
Labels: lgtm, approved

#400 Clone Template Modal re-align to design
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloneTemplateModal/CloneStorageCheckbox.tsx
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
  src/utils/components/CloneTemplateModal/clone-template-modal.scss
Labels: lgtm, approved

#401 VM Scripts tab
  src/utils/components/PendingChanges/utils/constants.ts
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx
  src/views/virtualmachines/details/tabs/scripts/components/CloudInit.tsx
  src/views/virtualmachines/details/tabs/scripts/components/CloudInitAuthKeyHelp.tsx
  src/views/virtualmachines/details/tabs/scripts/components/CloudInitEditor/CloudInitEditor.scss
  src/views/virtualmachines/details/tabs/scripts/components/CloudInitEditor/CloudInitEditor.tsx
  src/views/virtualmachines/details/tabs/scripts/components/CloudInitEditor/index.ts
  src/views/virtualmachines/details/tabs/scripts/components/CloudInitNetworkForm.tsx
  src/views/virtualmachines/details/tabs/scripts/components/CloudinitForm.tsx
  src/views/virtualmachines/details/tabs/scripts/components/CloudinitInfoHelper.tsx
  src/views/virtualmachines/details/tabs/scripts/components/CloudinitSSHKeyForm/CloudInitSSHKeyForm.tsx
  src/views/virtualmachines/details/tabs/scripts/components/CloudinitSSHKeyForm/SSHPopover/SSHPopover.tsx
  src/views/virtualmachines/details/tabs/scripts/components/CloudinitSSHKeyForm/SSHPopover/ssh-popover.scss
  src/views/virtualmachines/details/tabs/scripts/components/CloudinitSSHKeyForm/ssh-form-key.scss
  src/views/virtualmachines/details/tabs/scripts/components/ScriptsTabFooter.tsx
  src/views/virtualmachines/details/tabs/scripts/components/cloud-init.scss
  src/views/virtualmachines/details/tabs/scripts/utils/cloud-init-data-helper.tsx
  src/views/virtualmachines/details/tabs/scripts/utils/cloudint-utils.ts
  src/views/virtualmachines/details/tabs/scripts/utils/use-cloudinit-validations.ts
Labels: lgtm, approved

#398 Improve performance of template boot source availability
  locales/en/plugin__kubevirt-plugin.json
  src/utils/i18n.ts
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/utils/resources/template/hooks/useVmTemplates.tsx
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogEmptyState.tsx
  src/views/catalog/templatescatalog/hooks/useAvailableDataSourcesAndPVCs.ts
  src/views/catalog/templatescatalog/hooks/useAvailableSourceTemplates.ts
  src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts
  src/views/catalog/templatescatalog/hooks/utils.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
Labels: lgtm, approved

#407 add source available badge to catalog tiles
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogEmptyState.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogItems.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
Labels: lgtm, approved

#404 Display Template Descheduler ON according to annotation
  src/views/templates/details/tabs/scheduling/components/Descheduler.tsx
  src/views/templates/details/tabs/scheduling/components/DeschedulerModalButton.tsx
  src/views/templates/utils/index.ts
Labels: lgtm, approved

#405 VM Scripts tab: Auth SSH Key creation
  src/utils/components/CloudInit/CloudInit.tsx
  src/utils/components/CloudInit/cloud-init.scss
  src/utils/components/CloudInit/components/CloudInitAuthKeyHelp.tsx
  src/utils/components/CloudInit/components/CloudInitEditor/CloudInitEditor.scss
  src/utils/components/CloudInit/components/CloudInitEditor/CloudInitEditor.tsx
  src/utils/components/CloudInit/components/CloudInitEditor/index.ts
  src/utils/components/CloudInit/components/CloudInitNetworkForm.tsx
  src/utils/components/CloudInit/components/CloudinitForm.tsx
  src/utils/components/CloudInit/components/CloudinitInfoHelper.tsx
  src/utils/components/CloudInit/components/CloudinitSSHKeyForm/CloudInitSSHKeyForm.tsx
  src/utils/components/CloudInit/components/CloudinitSSHKeyForm/SSHPopover/SSHPopover.tsx
  src/utils/components/CloudInit/components/CloudinitSSHKeyForm/SSHPopover/ssh-popover.scss
  src/utils/components/CloudInit/components/CloudinitSSHKeyForm/ssh-form-key.scss
  src/utils/components/CloudInit/utils/cloud-init-data-helper.tsx
  src/utils/components/CloudInit/utils/cloudint-utils.ts
  src/utils/components/CloudInit/utils/use-cloudinit-validations.ts
  src/views/templates/details/tabs/NoEditableTemplateAlert.tsx
  src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx
  src/views/virtualmachines/details/tabs/scripts/components/ScriptsTabFooter.tsx
  src/views/virtualmachines/details/tabs/scripts/scripts-tab.scss
Labels: lgtm, approved

#402 Bug 2081202: cloudinit undefined for windows vms
  src/views/catalog/wizard/tabs/scripts/components/CloudInitEditor/CloudInitEditor.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudInitNetworkForm.tsx
  src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#403 Add BIOS/UEFI support
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
  src/utils/components/FirmwareBootloaderModal/utils/constants.ts
  src/utils/components/FirmwareBootloaderModal/utils/utils.ts
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved

#406 Bug 2076908: Fix overview urls
  src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx
  src/views/clusteroverview/overview/components/inventory-card/utils/vm-status-section/VMStatusInventoryItem.tsx
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/RunningVMsChartLegendLabel.tsx
  src/views/clusteroverview/overview/utils/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#409 Bug 2084476: VM scripts tab Auth SSH Key fetch
  src/utils/components/CloudInit/components/CloudInitNetworkForm.tsx
  src/utils/components/CloudInit/components/CloudinitForm.tsx
  src/utils/components/CloudInit/utils/cloudint-utils.ts
  src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx
  src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx
  src/views/virtualmachines/details/tabs/scripts/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#411 Migration Tool Doc Team fix
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  src/utils/i18n.ts
  src/views/migration/MigrationToolPage.tsx
  src/views/migration/constant.ts
Labels: lgtm, approved

#412 Customize Form other fixes
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
  src/views/catalog/customize/components/CustomizeSource/VolumeSize.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeClaimSelect.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
  src/views/catalog/customize/tests/PersistentVolumeClaimSelect.test.tsx
Labels: lgtm, approved

#413 update catalog table view
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
  src/views/catalog/templatescatalog/components/TemplateRowAvailableSource.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogItems.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogRow.tsx
  src/views/catalog/templatescatalog/hooks/useTemplatesCatalogColumns.ts
  src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts
Labels: lgtm, approved

#414 Bug 2085320: Tolerations rules is not adding correctly
  src/utils/components/TolerationsModal/TolerationsModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#415 Bug 2085322: Not able to stop/restart VM if the VM is staying in "Starting"
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#416 Bug 2079674: Configuring preferred node affinity in the console results in wrong yaml and unschedulable VM
  src/utils/components/AffinityModal/utils/helpers.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#408 Bug 2071488: "Migrate Node to Node" is confusing.
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/list/components/VirtualMachineActions/VirtualMachineActions.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#417 Bug 2086303: non-priv user can't create VM when namespace is not selected
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/template/hooks/useProcessedTemplate.ts
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#418 display default templates for non priv user
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
Labels: lgtm, approved

#419 Add custom templates to 'Default template' filter
  src/utils/resources/template/utils/selectors.ts
  src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
  src/views/catalog/templatescatalog/utils/helpers.ts
Labels: lgtm, approved

#424 Remove title in some of the VM Template tabs pages
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/details/TemplateDetailsPage.scss
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
  src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
  src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
  src/views/templates/details/tabs/scheduling/components/Descheduler.tsx
Labels: lgtm, approved

#425 fix cloudinit editor css overriding other editors
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloudinitModal/CloudInitEditor/CloudInitEditor.scss
  src/utils/components/SysprepModal/SysprepInfo.tsx
Labels: lgtm, approved

#426 Bug 2083101: Restore CPU/Memory default settings
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
  src/utils/components/CPUMemoryModal/constants.ts
  src/utils/components/CPUMemoryModal/hooks/useTemplateDefaultCpuMemory.ts
  src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#427 Bug 2086769: Adding labels during wizard vm creation
  src/utils/resources/template/utils/constants.ts
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#428 Make Node selector field in VM Template's Scheduling tab editable
  src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
  src/views/templates/details/tabs/scheduling/components/NodeSelector.tsx
  src/views/templates/details/tabs/scheduling/components/NodeSelectorModal.tsx
  src/views/templates/details/tabs/scheduling/components/TemplateSchedulingLeftGrid.tsx
  src/views/templates/details/tabs/scheduling/components/TemplateSchedulingRightGrid.tsx
Labels: lgtm, approved

#422 Add BIOD/UEFI support for templates
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/details/components/BootMethod/BootMethod.tsx
  src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved

#429 Make Tolerations and Affinity in Template's Scheduling tab editable
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/scheduling/components/AffinityRules.tsx
  src/views/templates/details/tabs/scheduling/components/AffinityRulesModal.tsx
  src/views/templates/details/tabs/scheduling/components/NodeSelector.tsx
  src/views/templates/details/tabs/scheduling/components/TemplateSchedulingLeftGrid.tsx
  src/views/templates/details/tabs/scheduling/components/Tolerations.tsx
  src/views/templates/details/tabs/scheduling/components/TolerationsModal.tsx
  src/views/templates/utils/selectors.ts
Labels: lgtm, approved

#431 add custom css to wizard editor buttons
  src/utils/components/CloudinitModal/CloudInitEditor/CloudInitEditor.scss
  src/utils/styles/_secondary-editor.scss
  src/views/catalog/wizard/Wizard.scss
Labels: lgtm, approved

#430 Bug 2086803: Update VM Labels on template cloning
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
  src/utils/resources/template/utils/constants.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#432 fix cloudinit modal overriding chpasswd value
  src/utils/components/CloudinitModal/CloudinitModal.tsx
  src/utils/components/CloudinitModal/utils/cloudinit-utils.ts
  src/utils/components/CloudinitModal/utils/useCloudInit.ts
Labels: lgtm, approved

#436 Bug 2086479: Use "Save" submit button text in all modals
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AffinityModal/AffinityModal.tsx
  src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
  src/utils/components/CloudinitModal/CloudinitModal.tsx
  src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
  src/utils/components/SSHAccess/SSHAccessModal.tsx
  src/utils/components/SysprepModal/SysprepModal.tsx
  src/utils/components/TabModal/TabModal.tsx
  src/utils/components/TolerationsModal/TolerationsModal.tsx
  src/views/templates/actions/components/EditBootSourceModal.tsx
  src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
  src/views/templates/details/tabs/scheduling/components/AffinityRulesModal.tsx
  src/views/templates/details/tabs/scheduling/components/TolerationsModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#434 Bug 2086849: Create VM yaml with something working
  console-extensions.json
  package.json
  src/templates/index.ts
  src/templates/vm-template-yaml.ts
  src/templates/vm-yaml.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#440 Bug 2078703: Cloudint password will now be hidden and revel upon click
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloudinitModal/CloudinitForm.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#442 fix linux svg
  src/views/catalog/templatescatalog/utils/svg/linux.svg
Labels: lgtm, approved

#376 Bug 2087570: Delete unnecessary spaces in the words vm and vmi
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/BootOrder/EmptyBootSourceSummary.tsx
  src/utils/components/BootOrderModal/BootOrderModal.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RdpServiceNotConfigured.tsx
  src/utils/components/DeschedulerModal/DeschedulerModal.tsx
  src/utils/components/TemplateValue/TemplateValue.tsx
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
  src/views/catalog/customize/components/CustomizeVirtualMachineHeader.tsx
  src/views/catalog/customize/components/FormActionGroup.tsx
  src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx
  src/views/catalog/customize/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawer.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/wizard/components/WizardEmptyState.tsx
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/EmptyStateNoVMs.tsx
  src/views/templates/actions/components/SelectSourceOption.tsx
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/details/tabs/scheduling/components/Descheduler.tsx
  src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/actions.ts
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert.tsx
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
  src/views/virtualmachines/details/tabs/details/components/sections/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
  src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemList.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotRow.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/modal/alerts/SupportedVolumesAlert.tsx
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineEmptyState/VirtualMachineEmptyState.tsx
  src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/list/VirtualMachinesInstancesList.tsx
  src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceEmptyState/VirtualMachineInstanceEmptyState.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#443 Template Scripts Tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/hooks/useTemplateTabs.ts
  src/views/templates/details/tabs/scripts/TemplateYAMLPage.tsx
Labels: lgtm, approved

#438 Bug 2087582: Remove MTV and VMI mneu items
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/globals.d.ts
  src/views/migration/MigrationToolPage.tsx
  src/views/migration/constant.ts
  src/views/migration/migration-illustration.png
  src/views/migration/migration-tool-page.scss
  src/views/migration/useMTVResources.tsx
  src/views/migration/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#435 Make Template's Description field editable
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
  src/views/templates/details/tabs/details/components/Description.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
Labels: lgtm, approved

#446 Bug 2087584: Template provider should not be mandatory
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#444 Bug 2078700: PVC (auto upload) fix
  src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
  src/utils/resources/template/utils/constants.ts
  src/utils/resources/vm/utils/source.ts
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogItems.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogRow.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/templatescatalog/hooks/useAvailableDataSourcesAndPVCs.ts
  src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
  src/views/catalog/utils/useWizardSourceAvailable.ts
  src/views/templates/list/hooks/useTemplatesWithAvailableSource.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#445 Bug 2084532: Console is crashed while detaching disk
  src/utils/resources/vm/hooks/disk/useDisksTableData.ts
  src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemList.tsx
  src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemListLayout.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#448 Bug 2087593: "Boot method" is not a good name in overview tab
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/templates/details/tabs/details/components/BootMethod/BootMethod.tsx
  src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#447 Bug 2087701: [RFE] Missing a link to VMI from running VM details page
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#449 Bug 2088034: Add optional chaining to getTemplateToVMCountMap
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#451 Bug 2088355: disk modal shows all storage classes as default
  src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#454 Add help popover to permissions card
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/overview/components/permissions-card/PermissionsCard.scss
  src/views/clusteroverview/overview/components/permissions-card/PermissionsCard.tsx
  src/views/clusteroverview/overview/components/permissions-card/PermissionsCardTitle.scss
  src/views/clusteroverview/overview/components/permissions-card/PermissionsCardTitle.tsx
  src/views/clusteroverview/overview/components/permissions-card/utils/PermissionsCardPopover.scss
Labels: lgtm, approved

#453 Bug 2086486: Update recommended operators section
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/overview/components/getting-started-card/GettingStartedCard.tsx
  src/views/clusteroverview/overview/components/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
  src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.scss
  src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
  src/views/clusteroverview/overview/components/getting-started-card/utils/constants.ts
  src/views/clusteroverview/overview/components/getting-started-card/utils/getting-started-content/GettingStartedContent.scss
  src/views/clusteroverview/overview/components/getting-started-card/utils/getting-started-content/GettingStartedContent.tsx
  src/views/clusteroverview/overview/components/getting-started-card/utils/getting-started-content/GettingStartedLinkExtraContent.tsx
  src/views/clusteroverview/overview/components/getting-started-card/utils/hooks/useMTVResources.ts
  src/views/clusteroverview/overview/components/getting-started-card/utils/types.ts
  src/views/clusteroverview/overview/components/top-consumers-card/utils/topConsumerMetric.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#455 Make Template's Labels, Annotations fields editable
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/details/TemplateDetailsPage.scss
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
  src/views/templates/details/tabs/details/components/Annotations.tsx
  src/views/templates/details/tabs/details/components/Labels.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
Labels: lgtm, approved

#437 Bug 2084102: Adding data-test-id to elements
  src/utils/components/DiskModal/DiskFormFields/DiskInterfaceSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceContainer.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUrlInput.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskTypeSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/StorageClassSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/utils/Filters.tsx
  src/views/catalog/customize/components/CustomizeSource/BootCDCheckboxLabel.tsx
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
  src/views/catalog/customize/components/CustomizeSource/VolumeSize.tsx
  src/views/catalog/customize/components/FieldGroup.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#460 Bug 2088407: Create Template button
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  src/templates/vm-template-yaml.ts
  src/views/templates/list/VirtualMachineTemplatesList.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#459 update dockerfile - improve security and reduce size
  Dockerfile
  Dockerfile.ci
  README.md
  default.conf
  oc-manifest.yaml
  openshift-ci/template.yaml
  test-prow-e2e.sh
Labels: lgtm, approved

#461 Bug 2089376: No exception on Virtual Machine Template without boot source
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/utils/resources/template/utils/constants.ts
  src/utils/resources/vm/utils/source.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#450 Bug 2087232: all-namespace back to template list
  console-extensions.json
  src/utils/hooks/constants.ts
  src/utils/hooks/useLastNamespace.ts
  src/views/templates/details/TemplatePageTitle.tsx
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/list/components/VirtualMachineBreadcrumb/VirtualMachineBreadcrumb.tsx
  src/views/virtualmachinesinstance/details/VirtualMachinesInstancePageHeader.tsx
  src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceBreadcrumb/VirtualMachineInstanceBreadcrumb.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#452 Bug 2087603: Align single vm details card with updated design
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsoleConnect.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/virtual-machines-overview-tab-details.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#457 Bug 2087559: template in "VMs per template" should take user to vm list
  src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/RunningVMsChartLegendLabel.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#462 Bug 2086488: Cannot cancel vm migration
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#466 Bug 2084431: no ssh service edit if no running vm
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#456 Bug 2087589: Fix customize form errors
  package.json
  src/utils/components/FormTextInput/FormTextInput.tsx
  src/views/catalog/customize/components/CustomizeForms/CustomizeForm.tsx
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
  src/views/catalog/customize/tests/CustomizeForm.test.tsx
  src/views/catalog/customize/tests/CustomizeSource.test.tsx
  src/views/catalog/customize/tests/PersistentVolumeClaimSelect.test.tsx
  src/views/catalog/customize/utils.ts
  yarn.lock
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#472 Bug 2089745: When removing all disk from VM customized wizard is crashing
  src/utils/resources/vm/utils/source.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#473 Bug 2087578: Changing VM to VirtualMachine
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/BootOrderModal/BootOrderModalBody.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RdpServiceNotConfigured.tsx
  src/utils/components/TolerationsModal/TolerationModalDescriptionText.tsx
  src/views/catalog/customize/components/CustomizeSource/BootCDCheckboxLabel.tsx
  src/views/catalog/wizard/tabs/network/components/modal/components/NetworkInterfaceTypeSelect.tsx
  src/views/clusteroverview/overview/components/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
  src/views/clusteroverview/overview/components/permissions-card/hooks/useOverviewPermissions.ts
  src/views/clusteroverview/overview/components/running-vms-per-template-card/RunningVMsPerTemplateCard.tsx
  src/views/templates/details/tabs/NoEditableTemplateAlert.tsx
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceTypeSelect.tsx
  src/views/virtualmachines/actions/components/CloneVMModal/components/CloneRunningVMAlert.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRowActions.tsx
  src/views/virtualmachines/details/tabs/network/copmonents/modal/NetworkInterfaceFormFields/NetworkInterfaceTypeSelect.tsx
  src/views/virtualmachinesinstance/details/VirtualMachinesInstancePageHeader.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#463 Bug 2087577: 'VMs per template' load time is a bit long
  src/views/clusteroverview/overview/components/inventory-card/InventoryCard.tsx
  src/views/clusteroverview/overview/components/inventory-card/hooks/useProjectNames.ts
  src/views/clusteroverview/overview/components/inventory-card/hooks/useWatchedResourcesInventoryCard.ts
  src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx
  src/views/clusteroverview/overview/components/inventory-card/utils/flattenTemplates.ts
  src/views/clusteroverview/overview/components/inventory-card/utils/types.ts
  src/views/clusteroverview/overview/components/inventory-card/utils/utils.ts
  src/views/clusteroverview/overview/components/running-vms-per-template-card/RunningVMsPerTemplateCard.tsx
  src/views/clusteroverview/overview/components/running-vms-per-template-card/hooks/useRunningVMsPerTemplateResources.ts
  src/views/clusteroverview/overview/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#475 Bug 2086272: Changing the colors of the titles in Overview for the dark mode
  src/views/clusteroverview/overview/components/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
  src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#476 Bug 2089789: windows drivers checkbox for all templates
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#465 Add Template's Boot order popover to edit in Disks tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/details/components/BootOrderItem.tsx
Labels: lgtm, approved

#471 Bug 2084102: Adding more data-test-id to elements
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineActions/VirtualMachineActions.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#481 Bug 2087717: Message when editing template boot source is wrong
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/actions/components/EditBootSourceModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#479 Bug 2089477: Add Upload Image Source to Disk/Edit modal
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUploadPVC.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUploadPVCProgress.tsx
  src/utils/components/DiskModal/DiskFormFields/utils/constants.ts
  src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/components/DiskModal/state/actions.ts
  src/utils/components/DiskModal/state/initialState.ts
  src/utils/components/DiskModal/state/reducers.ts
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/hooks/useCDIUpload/consts.ts
  src/utils/hooks/useCDIUpload/useCDIUpload.ts
  src/utils/hooks/useCDIUpload/utils.ts
  src/utils/models/index.ts
  src/utils/resources/shared.ts
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/utils/WizardVMContext/WizardVMContext.tsx
  src/views/catalog/utils/WizardVMContext/useWizardVMEffects.ts
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/wizard/components/WizardFooter.tsx
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
  src/views/templates/actions/components/SelectSourceOption.tsx
  yarn.lock
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#482 Bug 2088379: Create VM from catalog does not respect the storageclass
  src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#484 Bug 2089963: Add VM os label and annotations from template
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#485 Bug 2087590: "Upload a new file to a PVC" should not open the form in a new tab
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/components/DiskModal/utils/editDiskModalHelpers.ts
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/hooks/useCDIUpload/utils.ts
  src/views/catalog/customize/cd.ts
  src/views/catalog/customize/components/CustomizeForms/CustomizeForm.tsx
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSourceUploadPVCProgress.tsx
  src/views/catalog/customize/tests/CustomizeForm.test.tsx
  src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#486 fix upload in wizard not adding owner references
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/hooks/useCDIUpload/useCDIUpload.ts
  src/utils/hooks/useCDIUpload/utils.ts
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/customize/components/FormActionGroup.tsx
  src/views/catalog/customize/tests/CustomizeForm.test.tsx
  src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx
  src/views/catalog/utils/WizardVMContext/WizardVMContext.tsx
  src/views/catalog/utils/WizardVMContext/useWizardVMEffects.ts
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
Labels: lgtm, approved

#487 Bug 2090131: Affinity chips style
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityEditRow.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/affinity-edit-row.scss
Labels: lgtm, approved

#488 Bug 2090046: Same HardwareDevice for all resources
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/HardwareDevices/HardwareDevicesModal.tsx
  src/views/templates/details/tabs/details/components/HardwareDevices.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsRightGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/HadwareDevices/HardwareDevices.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#491 Bug 2089972: Rename VM Overview 'Disk' to 'Disks' card
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisks.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#495 fix upload disk hotplug promise
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/components/DiskModal/utils/editDiskModalHelpers.ts
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
Labels: lgtm, approved

#492 Bug 2090056: "Something went wrong" shows on VM "Environment" tab
  src/utils/resources/vm/utils/selectors.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#490 Bug 2091058: same namespace in vm delete
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#494 Bug 2087578: Changing VM to VirtualMachine
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/overview/components/inventory-card/InventoryCard.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#496 Bug 2091406: Fixing the namespace label when customize new vm
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#493 Bug 2090054: Services “kubernetes" and "openshift" should be hidden
  src/utils/resources/vmi/utils/services.ts
  src/utils/resources/vmi/utils/tests/mocks.ts
  src/utils/resources/vmi/utils/tests/services.test.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#501 fix wizard disks tab not showing URL source
  src/utils/components/DiskModal/DiskModal.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
  src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
Labels: lgtm, approved

#498 Bug 2090055: Adding link to vm template in vm details page
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#503 Bug 2089982: Remove VM name from SSH modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHAccess/SSHAccessModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug
