Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2022-11, with the labels that each got.

#920 Bug 2136051: Fix Name jumping and fill generatable parameters
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
  src/views/catalog/customize/CustomizeVirtualMachine.tsx
  src/views/catalog/customize/components/CustomizeForms/CustomizeForm.tsx
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/customize/tests/CustomizeForm.test.tsx
  src/views/catalog/customize/tests/CustomizeSource.test.tsx
  src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx
  src/views/catalog/customize/tests/data/projects.json
  src/views/catalog/customize/tests/data/pvcs.json
  src/views/catalog/customize/tests/data/template.json
  src/views/catalog/customize/tests/mocks.ts
  src/views/catalog/customize/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#939 Bug 2138199: Add 'Red Hat - Tech Preview' provider filter
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#919 Bug 2128554: Backporting default storage class usage in quick create
  src/utils/hooks/useDefaultStorageClass/constants.ts
  src/utils/hooks/useDefaultStorageClass/useDefaultStorageClass.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#928 Bug 2023393: Adding info message when boot source SC is different from default SC
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/StorageClassSelect.tsx
  src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#941 Bug 2139306: Process template on selected project
  src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#936 Bug 2138112: Unsupported S3 endpoint option in Add disk modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
  src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
  src/views/templates/actions/components/SelectSourceOption.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#943 Bug 2139293: Non-admin user cannot load VM list page
  src/utils/hooks/useSingleNodeCluster.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#944 Bug 2139296: Non-admin cannot load MigrationPolicies page
  console-extensions.json
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#945 Bug 2139479: virtualization overview crashes for non-priv user
  console-extensions.json
  src/views/clusteroverview/ClusterOverviewPage.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#942 Bug 2139260: Fixing the clone button will be enable while the vm is running
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#947 Bug 2139687: catalog shows template list for non-priv users
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogEmptyState.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#946 Bug 2139651: non-priv user can click create when have no permissions
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#948 Bug 2139257: cant edit root disk to use existing PVC
  src/utils/components/CapacityInput/CapacityInput.tsx
  src/utils/components/DiskModal/DiskFormFields/utils/constants.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#949 Bug 2139820: cant reach vm details
  src/utils/hooks/useLastNamespacePath.ts
  src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
  src/views/templates/details/TemplatePageTitle.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
  src/views/virtualmachines/list/components/VirtualMachineBreadcrumb/VirtualMachineBreadcrumb.tsx
  src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceBreadcrumb/VirtualMachineInstanceBreadcrumb.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#940 Bug 2134668: Display correct command with username for SSH
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
  src/utils/components/SSHAccess/components/SSHCheckbox.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
  src/utils/components/SSHAccess/useSSHCommand.ts
  src/utils/resources/vmi/utils/cloud-init.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGrid.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#951 Bug 2140521: Fixed the breadcrumbs for VirtualMachines that the vm switched to a defined project.
  src/utils/hooks/useLastNamespacePath.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#952 Bug 2139574: Fix catalog for template no bootsource
  src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
  src/views/catalog/customize/components/CustomizeForms/CustomizeForm.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#955 Bug 2140627: Allow to select storageClass in Add disk modal
  src/utils/components/DiskModal/DiskFormFields/StorageClassSelect.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#954 Bug 2138119: Rename "Review and create VirtualMachine" to "Next"
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/customize/components/FormActionGroup.tsx
Labels: lgtm, approved, bugzilla/severity-unspecified

#953 Bug 2137591: Make dialogs' headings consistent
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/DesktopViewer/Components/RDPServiceModal.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RDPServiceNotConfigured.tsx
  src/utils/components/HardwareDevices/HardwareDevices.tsx
  src/utils/components/NodeSelectorModal/components/NodeCheckerAlert.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
  src/views/catalog/wizard/components/WizardEmptyState.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/datasources/hooks/useDataSourceActions.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/MigrationPolicyFormFooter/MigrationPolicyFormFooter.tsx
  src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/details/tabs/disk/modal/DeleteDiskModal.tsx
  src/views/virtualmachines/details/tabs/network/copmonents/list/NetworkInterfaceActions.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Labels/Labels.tsx
Labels: lgtm, approved, bugzilla/severity-low

#956 Bug 2139687: catalog shows template list for non-priv users
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogEmptyState.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#958 Bug 2140730: Make links to resources on Overview page work correctly
  src/utils/resources/shared.ts
  src/views/clusteroverview/OverviewTab/resources-inventory-card/ResourcesInventoryCard.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#960 Bug 2140998: Display correct number of Nodes and NADs in the Overview
  src/views/clusteroverview/OverviewTab/resources-inventory-card/ResourcesInventoryCard.tsx
  src/views/clusteroverview/OverviewTab/resources-inventory-card/hooks/useResourcesQuantities.ts
Labels: lgtm, approved, bugzilla/severity-medium

#959 Bug 2140534: Disable VNC play button and the standalone view button in overview tab
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#961 Bug 2140982: The base template of cloned template is "Not available"
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
  src/views/templates/utils/constants.ts
  src/views/templates/utils/selectors.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#962 Improve getResourceUrl to accept an object instead of separate args
  src/utils/resources/shared.ts
  src/utils/tests/resource.test.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/wizard/components/WizardFooter.tsx
  src/views/clusteroverview/OverviewTab/resources-inventory-card/ResourcesInventoryCard.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/MigrationProgressPopover/MigrationProgressPopover.tsx
Labels: lgtm, approved

#963 Bug 2141494: Adding the "Start in pause mode" option to review page
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#964 Bug 2141711: Node column selector is redundant for non-priv user
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#966 Bug 2142468: Fixing the stop action to be enabled while vm is in pause mode
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#967 Update SDK packages
  package.json
  yarn.lock
Labels: lgtm, approved

#968 Bug 2142647: Delete modal lead to wrong URL
  src/utils/components/DeleteModal/DeleteModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#973 ' Bug 2143498: Could not load template while creating VM from catalog'
  src/utils/resources/template/hooks/useProcessedTemplate.ts
  src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
  src/views/catalog/customize/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#969 Change migration bandwidth consumption charts
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/ClusterOverviewPage.tsx
  src/views/clusteroverview/MigrationsTab/MigrationsTab.scss
  src/views/clusteroverview/MigrationsTab/MigrationsTab.tsx
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/BandwidthConsumptionCharts.tsx
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsTimeAxis.tsx
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsUtilizationChart.tsx
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/constants.ts
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/useMigrationChartsData.ts
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/utils.ts
  src/views/clusteroverview/MigrationsTab/components/MigrationEmptyState/MigrationEmptyState.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/MigrationChartLegend.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/MigrationsChartDonut.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsLimitionsPopover/MigrationsLimitionsPopover.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsLimitionsPopover/hooks/useHCMigrations.ts
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationActionsDropdown.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationsRow.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationsTable.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/components/MigrationPolicyTooltip/MigrationPolicyTooltip.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/components/MigrationPolicyTooltip/utils.ts
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/hooks/useVirtualMachineInstanceMigrationActionsProvider.ts
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/hooks/useVirtualMachineInstanceMigrationsColumns.ts
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/utils/filters.ts
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/utils/statuses.ts
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/utils/utils.ts
  src/views/clusteroverview/MigrationsTab/hooks/useMigrationCardData.ts
  src/views/clusteroverview/MigrationsTab/utils/constants.ts
  src/views/clusteroverview/MonitoringTab/MonitoringTab.scss
  src/views/clusteroverview/MonitoringTab/MonitoringTab.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/BandwidthConsumptionChart/BandwidthConsumptionChart.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/BandwidthConsumptionChart/utils.ts
  src/views/clusteroverview/TopConsumersTab/TopConsumersTab.scss
  src/views/clusteroverview/TopConsumersTab/TopConsumersTab.tsx
  src/views/clusteroverview/TopConsumersTab/utils/NoDataAvailableMessage.scss
  src/views/clusteroverview/TopConsumersTab/utils/NoDataAvailableMessage.tsx
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumerCard.scss
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumerCard.tsx
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumersChartList.scss
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumersChartList.tsx
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumersGridRow.scss
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumersGridRow.tsx
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumersProgressChart.scss
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumersProgressChart.tsx
  src/views/clusteroverview/TopConsumersTab/utils/constants.ts
  src/views/clusteroverview/TopConsumersTab/utils/queries.ts
  src/views/clusteroverview/TopConsumersTab/utils/topConsumerMetric.ts
  src/views/clusteroverview/TopConsumersTab/utils/topConsumerScope.ts
  src/views/clusteroverview/TopConsumersTab/utils/utils.ts
Labels: lgtm, approved

#981 Bug 2144580: Make Help icon small in VM Template's Disks tab
  src/views/templates/details/tabs/disks/components/DiskListTitle.tsx
  src/views/templates/details/tabs/disks/template-disk-tab.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#977 Bug 2143498: Could not load template while creating VM from catalog
  src/utils/constants/constants.ts
  src/utils/resources/template/hooks/useProcessedTemplate.ts
  src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
  src/utils/tests/resource.test.ts
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/customize/components/CustomizeVirtualMachineHeader.tsx
  src/views/catalog/customize/constants.ts
  src/views/catalog/customize/utils.ts
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
  src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
  src/views/catalog/utils/quick-create-vm.ts
  src/views/catalog/wizard/components/WizardHeader.tsx
  src/views/datasources/dataimportcron/details/DataImportCronPageTitle.tsx
  src/views/datasources/details/DataSourcePageTitle.tsx
  src/views/datasources/list/CreateDataSourceModal/CreateDataSourceModal.tsx
  src/views/datasources/list/DataSourcesList.tsx
  src/views/templates/actions/components/SelectSourceOption.tsx
  src/views/templates/actions/editBootSource.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachinesinstance/list/VirtualMachinesInstancesList.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#978 Bug 2143216: Template with no edit permission
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/CommonTemplateAlert.tsx
  src/views/templates/details/NoPermissionTemplateAlert.tsx
  src/views/templates/details/TemplatePageTitle.tsx
  src/views/templates/details/TooltipNoEditPermissions.tsx
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
  src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
  src/views/templates/details/tabs/scripts/components/SysPrepItem/SysPrepItem.tsx
  src/views/templates/details/template-header-alert.scss
  src/views/templates/details/tooltip-no-edit-permissions.scss
  src/views/templates/utils/constants.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#976 Bug 2142511: Fixing the alerts card dropdown on the overview page
  src/utils/components/AlertsCard/AlertsDrawer.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#983 [release-4.11] Bug 2145030: ssh service on vm stopped
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHAccess/SSHAccessModal.tsx
  src/utils/components/SSHAccess/constants.ts
  src/utils/components/SSHAccess/useSSHService.tsx
  src/utils/components/SSHAccess/utils.ts
  src/utils/resources/vmi/utils/services.ts
  src/utils/resources/vmi/utils/tests/services.test.ts
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/details/components/sections/ServicesSection.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#975 [release-4.12] Bug 2144839: Display correct number of Alerts on Overview page
  src/utils/components/AlertsCard/AlertsCard.tsx
  src/utils/hooks/useKubevirtAlerts.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#984 Bug 2136425: Windows 11 is detected as Windows 10
  src/utils/components/Timestamp/utils/datetime.ts
  src/utils/resources/vm/hooks/useVMIAndPodsForVM.ts
  src/utils/resources/vmi/utils/guest-agent.ts
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/StatusPopoverButton/StatusPopoverButton.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineOverviewStatus/VirtualMachineOverviewStatus.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/OperatingSystem/OperatingSystem.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#988 Bug 2143216: Template disable pencil instead of remove it
  src/utils/components/HardwareDevices/HardwareDeviceTitle.tsx
  src/views/templates/details/tabs/details/components/Annotations.tsx
  src/views/templates/details/tabs/details/components/BootMethod/BootMethod.tsx
  src/views/templates/details/tabs/details/components/CPUMemory.tsx
  src/views/templates/details/tabs/details/components/Description.tsx
  src/views/templates/details/tabs/details/components/DisplayName.tsx
  src/views/templates/details/tabs/details/components/Labels.tsx
  src/views/templates/details/tabs/details/components/WorkloadProfile.tsx
  src/views/templates/details/tabs/scheduling/components/AffinityRules.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResources.tsx
  src/views/templates/details/tabs/scheduling/components/EvictionStrategy.tsx
  src/views/templates/details/tabs/scheduling/components/NodeSelector.tsx
  src/views/templates/details/tabs/scheduling/components/Tolerations.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#979 Moving extension upload pvc
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
  src/utils/resources/template/utils/constants.ts
  src/views/cdi-upload-provider/PVCAlertExtension.tsx
  src/views/cdi-upload-provider/PVCDeleteAlertExtension.tsx
  src/views/cdi-upload-provider/hooks/useBaseImages.ts
  src/views/cdi-upload-provider/hooks/useCDIUpload.tsx
  src/views/cdi-upload-provider/hooks/useMultipleAccessReviews.ts
  src/views/cdi-upload-provider/popover/UploadPVCPopover.tsx
  src/views/cdi-upload-provider/popover/UploadPVCPopoverProgressStatus.tsx
  src/views/cdi-upload-provider/popover/UploadPVCPopoverUploadStatus.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVC.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCButtonBar.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCErrorMessage.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCForm.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormAccessMode.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormGoldenImage.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormMode.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormPVCName.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormPVCNamespace.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormSize.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormStatus.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormStorageClass.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormVolumeMode.tsx
  src/views/cdi-upload-provider/upload-pvc-form/statuses/AllocatingStatus.tsx
  src/views/cdi-upload-provider/upload-pvc-form/statuses/CDIInitErrorStatus.tsx
  src/views/cdi-upload-provider/upload-pvc-form/statuses/CancellingStatus.tsx
  src/views/cdi-upload-provider/upload-pvc-form/statuses/ClonePVCStatus.tsx
  src/views/cdi-upload-provider/upload-pvc-form/statuses/ErrorStatus.tsx
  src/views/cdi-upload-provider/upload-pvc-form/statuses/UploadingStatus.tsx
  src/views/cdi-upload-provider/upload-pvc-form/upload-pvc-form.scss
  src/views/cdi-upload-provider/utils/consts.ts
  src/views/cdi-upload-provider/utils/context.tsx
  src/views/cdi-upload-provider/utils/selectors.ts
  src/views/cdi-upload-provider/utils/types.ts
  src/views/cdi-upload-provider/utils/utils.tsx
Labels: lgtm, approved

#971 Add metric charts to cluster overview page
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/clusteroverview/OverviewTab/OverviewTab.tsx
  src/views/clusteroverview/OverviewTab/metric-charts-card/components/ChartCard.scss
  src/views/clusteroverview/OverviewTab/metric-charts-card/components/ChartCard.tsx
  src/views/clusteroverview/OverviewTab/metric-charts-card/components/ChartsCard.scss
  src/views/clusteroverview/OverviewTab/metric-charts-card/components/ChartsCard.tsx
  src/views/clusteroverview/OverviewTab/metric-charts-card/components/MetricChart.scss
  src/views/clusteroverview/OverviewTab/metric-charts-card/components/MetricChart.tsx
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/constants.ts
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/constants.ts
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/types.ts
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/useMetricChartData.ts
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/useXAxisTicks.ts
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/useYAxisTicks.ts
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/utils.ts
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/metricQueries.ts
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/types.ts
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/utils.ts
  yarn.lock
Labels: lgtm, approved

#989 Bug 2148849: Make help text links work, in VM & DataSource details pages
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DescriptionItem/DescriptionItem.scss
  src/utils/components/DescriptionItem/DescriptionItemHeader.tsx
  src/utils/components/OwnerDetailsItem/OwnerDetailsItem.tsx
  src/views/templates/details/tabs/details/components/Owner.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.scss
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
