Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2022-08, with the labels that each got.

#797 Bug 2060499: Replace vm object correctly into template
  src/views/catalog/customize/cd.ts
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsRightGrid.tsx
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/templates/details/tabs/network/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#798 Bug 2111328: kubevirt plugin console crashed after visit vmi page
  src/utils/hooks/useKubevirtWatchResource.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#796 CNV-20182: Adding network by nic charts to metrics tab
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
  src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
  src/utils/components/Charts/StorageUtil/StorageReadThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageWriteThresholdChart.tsx
  src/utils/components/Charts/utils/queries.ts
  src/utils/components/Charts/utils/utils.ts
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/NetworkCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/NetworkChartsByNIC.tsx
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/hook/useNetworkData.tsx
  src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
  src/views/virtualmachines/details/tabs/metrics/utils/utils.ts
  src/views/virtualmachines/details/tabs/metrics/virtual-machine-metrics-tab.scss
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
Labels: lgtm, approved

#802 fix environments tab skeleton
  src/utils/components/EnvironmentEditor/components/EnvironmentFormSkeleton.tsx
Labels: lgtm, approved

#805 CNV-19842: adding storage charts metrics tab
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Charts/StorageUtil/StorageIOPSTotalThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
  src/views/virtualmachines/details/tabs/metrics/StorageCharts/StorageCharts.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/UtilizationThresholdCharts.tsx
Labels: lgtm, approved

#803 Fix vm list stuck loading
  src/utils/hooks/useKubevirtWatchResource.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved

#808 Bug 2114516: Open website after clicking on Fedora cloud image list link
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUrlInput.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#794 Bug 2060499: Quick create - template with multiple objects
  jest.config.ts
  src/utils/resources/template/utils/helpers.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#795 Bug 2060499: getTemplateVirtualMachineObject instead of objects[0]
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
  src/views/catalog/customize/drivers.ts
  src/views/catalog/customize/utils.ts
  src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
  src/views/templates/details/tabs/scheduling/components/AffinityRulesModal.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx
  src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
  src/views/templates/details/tabs/scheduling/components/EvictionStrategyModal.tsx
  src/views/templates/details/tabs/scheduling/components/NodeSelectorModal.tsx
  src/views/templates/details/tabs/scheduling/components/TolerationsModal.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#812 Create additional template objects in wizard
  src/utils/resources/template/utils/helpers.ts
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/utils/quick-create-vm.ts
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/utils/utils.ts
Labels: lgtm, approved

#801 Bug 2111240: Fix units display bug
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CapacityInput/CapacityInput.tsx
  src/utils/components/CapacityInput/utils.ts
  src/utils/components/DiskModal/DiskFormFields/DiskSizeInput/DiskSizeInput.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/constants.ts
  src/views/catalog/customize/components/CustomizeSource/index.tsx
  src/views/catalog/utils/quantity.ts
  src/views/datasources/list/CreateDataSourceModal/CreateDataSourceForm.tsx
  src/views/templates/actions/components/EditBootSourceModal.tsx
  src/views/templates/actions/components/SelectSource.tsx
  src/views/templates/actions/components/VolumeSize.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#810 Bug 2060499: Template additional resources
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AdditionalResources/AdditionalResources.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsRightGrid.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#811 CNV20021: Add create MigrationPolicy form
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/utils/units.ts
  src/views/migrationpolicies/list/MigrationPoliciesList.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/MigrationPolicyCreateForm.scss
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/MigrationPolicyCreateForm.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/BandwidthInput/BandwidthInput.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/CompletionTimeoutInput/CompletionTimeoutInput.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/MigrationPolicyCreateFormHeader/MigrationPolicyCreateFormHeader.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/MigrationPolicyFormDescription/MigrationPolicyFormDescription.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/MigrationPolicyFormFooter/MigrationPolicyFormFooter.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/SelectorLabelMatchGroup/SelectorLabelMatchGroup.scss
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/SelectorLabelMatchGroup/SelectorLabelMatchGroup.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/SelectorLabelMatchGroup/utils.ts
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/utils/utils.ts
  src/views/migrationpolicies/list/components/MigrationPolicyMatchLabelSelectorList/MigrationPolicyMatchLabelSelectorList.tsx
  src/views/migrationpolicies/list/utils/constants.ts
Labels: lgtm, approved

#813 reinforcing negative values inputs for migration per cluster and node
  src/views/clusteroverview/SettingsTab/LiveMigrationTab/Limits/Limits.tsx
Labels: lgtm, approved

#814 Bug 2112900: Change button texts to Sentence case
  cypress/views/tab.ts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/DesktopViewer/DesktopViewer.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentFormTitle.tsx
  src/utils/components/PendingChanges/utils/constants.ts
  src/utils/resources/template/utils/constants.ts
  src/views/catalog/customize/components/CustomizeSource/SelectCDSourceLabel.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectCDSourcePopOver.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectDiskSourceLabel.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectDiskSourcePopOver.tsx
  src/views/catalog/wizard/tabs.tsx
  src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
  src/views/catalog/wizard/tabs/network/components/modal/EditNetworkInterfaceModal.tsx
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/templates/details/hooks/useTemplateTabs.ts
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/network/components/modal/EditNetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/network/NetworkInterfaceListPage.tsx
  src/views/virtualmachines/details/tabs/network/copmonents/modal/EditNetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/VirtualMachinesOverviewTabSnapshots.tsx
  src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/modal/RestoreModal.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/modal/SnapshotModal.tsx
  src/views/virtualmachinesinstance/details/hooks/useVirtualMachinesInstanceTabs.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#818 Bug 2111744: change cloned template label
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
  src/utils/resources/template/utils/constants.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#816 CNV20023: MigrionPolicy details page
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/LabelsModal/LabelsModal.tsx
  src/views/migrationpolicies/components/MigrationPolicyMatchExpressionSelectorList/MigrationPolicyMatchExpressionSelectorLabel.tsx
  src/views/migrationpolicies/components/MigrationPolicyMatchExpressionSelectorList/MigrationPolicyMatchExpressionSelectorList.tsx
  src/views/migrationpolicies/components/MigrationPolicyMatchLabelSelectorList/MigrationPolicyMatchLabelSelectorLabel.tsx
  src/views/migrationpolicies/components/MigrationPolicyMatchLabelSelectorList/MigrationPolicyMatchLabelSelectorList.tsx
  src/views/migrationpolicies/components/MigrationPolicySelectorLabel.scss
  src/views/migrationpolicies/details/MigrationPolicyDetailsNav.tsx
  src/views/migrationpolicies/details/components/MigrationPolicyBreadcrumb/MigrationPolicyBreadcrumb.scss
  src/views/migrationpolicies/details/components/MigrationPolicyBreadcrumb/MigrationPolicyBreadcrumb.tsx
  src/views/migrationpolicies/details/components/MigrationPolicyDetailsNavTitle/MigrationPolicyDetailsNavTitle.scss
  src/views/migrationpolicies/details/components/MigrationPolicyDetailsNavTitle/MigrationPolicyDetailsNavTitle.tsx
  src/views/migrationpolicies/details/hooks/useMigrationPolicyTabs.ts
  src/views/migrationpolicies/details/tabs/details/MigrationPolicyDetailsPage.scss
  src/views/migrationpolicies/details/tabs/details/MigrationPolicyDetailsPage.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.scss
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyDescriptionItem.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyProjectLabels.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyVirtualMachineLabels.tsx
  src/views/migrationpolicies/details/tabs/yaml/MigrationPolicyYAMLPage.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
  src/views/migrationpolicies/utils/utils.ts
Labels: lgtm, approved

#817 Bug 2114683: Overview crash -milliseconds time
  src/utils/components/DurationOption/DurationOption.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#815 Bug 2096780: Add Sysprep in template Objects array
  src/utils/components/SysprepModal/SysprepModal.tsx
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
  src/views/templates/details/tabs/scripts/SysPrepItem.tsx
  src/views/templates/details/tabs/scripts/sysprep-utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#820 Bug 2115258: Quick create -default storage class name
  src/utils/hooks/useDefaultStorage/constants.ts
  src/utils/hooks/useDefaultStorage/useDefaultStorageClass.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#821 CNV20022: Edit MigrationPolicy action and modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DeleteModal/DeleteModal.tsx
  src/views/migrationpolicies/actions/hooks/useMigrationPoliciesActionsProvider.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurationsFormGroup/BandwidthInput/BandwidthInput.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurationsFormGroup/CompletionTimeoutInput/CompletionTimeoutInput.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurationsFormGroup/MigrationPolicyConfigurationsFormGroup.tsx
  src/views/migrationpolicies/components/MigrationPolicyEditModal/MigrationPolicyEditModal.tsx
  src/views/migrationpolicies/components/MigrationPolicyEditModal/utils/constants.ts
  src/views/migrationpolicies/components/MigrationPolicyEditModal/utils/utils.ts
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyProjectLabels.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyVirtualMachineLabels.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/MigrationPolicyCreateForm.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/utils/utils.ts
  src/views/migrationpolicies/utils/utils.ts
Labels: lgtm, approved

#823 Bug 2114636: Update VM/VMI Details/Scheduling/Disks tabs' texts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloudinitModal/CloudInitNetworkForm.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/MultusNetwork.tsx
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/WorkloadProfileModal/WorkloadProfileModal.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
  src/views/catalog/wizard/tabs/scheduling/components/DedicatedResources.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResources.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/details/components/sections/UserList/ActiveUserListSection.tsx
  src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
  src/views/virtualmachines/details/tabs/disk/hooks/useFilesystemListColumns.ts
  src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemListTitle.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfacesRow.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/DedicatedResources.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx
  src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingRightGrid.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
  src/views/virtualmachinesinstance/components/VirtualMachinesInstanceIP.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Hostname/Hostname.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/IP/IP.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Timezone/Timezone.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/UserList/ActiveUserList.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/hooks/useFileSystemTableColumns.ts
  src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTableTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/scheduling/DeticatedResources/DedicatedResources.tsx
  src/views/virtualmachinesinstance/details/tabs/scheduling/VirtualMachinesInstancePageSchedulingTab.tsx
  src/views/virtualmachinesinstance/list/hooks/useVirtualMachinesInstancesColumns.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#807 Bug 2101423: Display user name on using ignition
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
  src/utils/components/UserCredentials/useSSHCommand.ts
  src/utils/resources/vmi/utils/cloud-init.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#827 Adding migration chart to metrics tab - vm
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChart.tsx
  src/utils/components/Charts/utils/queries.ts
  src/views/virtualmachines/details/tabs/metrics/MigrationCharts/MigrationCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
Labels: lgtm, approved

#828 Descheduling page crash
  src/views/templates/utils/utils.ts
  src/views/virtualmachinesinstance/details/tabs/scheduling/Descheduler/Descheduler.tsx
Labels: lgtm, approved

#829 Bug 2116225: Changing link from OCS to ODF
  src/views/clusteroverview/OverviewTab/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#825 CNV20024: Add MigrationPolicies list empty state
  images/globals.d.ts
  images/migrationPoliciesEmptyState.png
  locales/en/plugin__kubevirt-plugin.json
  src/views/migrationpolicies/components/MigrationPolicyEditModal/utils/utils.ts
  src/views/migrationpolicies/components/MigrationPolicyMatchExpressionSelectorList/MigrationPolicyMatchExpressionSelectorLabel.tsx
  src/views/migrationpolicies/components/MigrationPolicyMatchExpressionSelectorList/MigrationPolicyMatchExpressionSelectorList.tsx
  src/views/migrationpolicies/components/MigrationPolicyMatchLabelSelectorList/MigrationPolicyMatchLabelSelectorLabel.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyProjectLabels.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyVirtualMachineLabels.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/utils/utils.ts
  src/views/migrationpolicies/list/MigrationPoliciesList.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
  tsconfig.json
Labels: lgtm, approved

#755 Bug 2104402: Envs Save button fix
  .github/workflows/ci_checks.yml
  package.json
  src/utils/components/EnvironmentEditor/components/EnvironmentEditor.tsx
  src/utils/components/EnvironmentEditor/hooks/useEnvironments.ts
  src/utils/components/EnvironmentEditor/tests/mocks.ts
  src/utils/components/EnvironmentEditor/tests/useEnvironments.test.tsx
  src/utils/components/EnvironmentEditor/tests/utils.test.ts
  src/utils/components/EnvironmentEditor/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#830 Update kubevirt-api version
  package.json
  src/utils/components/DeleteModal/DeleteModal.tsx
  src/utils/components/SSHAccess/utils.ts
  src/views/migrationpolicies/components/MigrationPolicyMatchLabelSelectorList/MigrationPolicyMatchLabelSelectorList.tsx
  src/views/migrationpolicies/components/MigrationPolicySelectorList/MigrationPolicySelector.tsx
  src/views/migrationpolicies/components/MigrationPolicySelectorList/MigrationPolicySelectorList.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyProjectLabels.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyVirtualMachineLabels.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/utils/utils.ts
  src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/utils/utils.ts
  yarn.lock
Labels: lgtm, approved

#832 Bug 2099556: Adding the option to enable Rdp service in one click to windows vm
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Charts/ComponentReady/ComponentReady.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RDPConnector.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RDPServiceModal.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RDPServiceNotConfigured.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/RdpServiceNotConfigured.tsx
  src/utils/components/Consoles/components/DesktopViewer/Components/rdp-service.scss
  src/utils/components/Consoles/components/DesktopViewer/DesktopViewer.tsx
  src/utils/components/Consoles/components/DesktopViewer/utils/constants.ts
  src/utils/components/Consoles/components/DesktopViewer/utils/types.ts
  src/utils/components/Consoles/components/DesktopViewer/utils/utils.ts
  src/utils/components/TabModal/TabModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#835 Change toleration modal link
  src/utils/components/TolerationsModal/TolerationModalDescriptionText.tsx
Labels: lgtm, approved

#836 Bug 2092796: Change cpu and memory appearance values
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#826 Bug 2114636: Change "File system" title to plural in VM Disks tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemListTitle.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#834 Change edit config design
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DeleteModal/DeleteModal.tsx
  src/utils/hooks/useKubevirtTranslation.ts
  src/views/migrationpolicies/components/MigrationPolicyConfigurations/MigrationPolicyConfigurations.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurations/compnents/BandwidthInput/BandwidthInput.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurations/compnents/CompletionTimeout/CompletionTimeout.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurations/compnents/MigrationPolicyConfigurationDropdown/MigrationPolicyConfigurationDropdown.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurations/compnents/YesNoDropdown/YesNoDropdown.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurations/utils/constants.ts
  src/views/migrationpolicies/components/MigrationPolicyConfigurations/utils/utils.ts
  src/views/migrationpolicies/components/MigrationPolicyConfigurationsFormGroup/CompletionTimeoutInput/CompletionTimeoutInput.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurationsFormGroup/MigrationPolicyConfigurationsFormGroup.tsx
  src/views/migrationpolicies/components/MigrationPolicyEditModal/MigrationPolicyEditModal.tsx
  src/views/migrationpolicies/components/MigrationPolicyEditModal/utils/constants.ts
  src/views/migrationpolicies/components/MigrationPolicyEditModal/utils/utils.ts
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/MigrationPolicyCreateForm.scss
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/MigrationPolicyCreateForm.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/utils/utils.ts
  src/views/migrationpolicies/utils/constants.ts
  src/views/migrationpolicies/utils/utils.ts
Labels: lgtm, approved

#839 Update start-console.sh
  start-console.sh
Labels: lgtm, approved

#840 Bug 2100290: Fix when creating a new vm the error doesn't dismissed
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#842 Remove reselect dev dep
  console-extensions.json
  package.json
  src/views/clusteroverview/OverviewTab/getting-started-card/quick-starts-section/utils.ts
  webpack.config.ts
  yarn.lock
Labels: lgtm, approved

#843 Fix template console-extensions model
  console-extensions.json
Labels: lgtm, approved

#833 Bug 2096780: Wizard with sysprep in additionalResources
  src/utils/components/SysprepModal/sysprep-utils.ts
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
  src/views/catalog/wizard/tabs/scripts/components/Sysprep.tsx
  src/views/catalog/wizard/tabs/scripts/components/sysprep-utils.ts
  src/views/templates/details/tabs/scripts/components/SysPrepItem/sysprep-utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#841 Monitoring migrations empty state
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/MonitoringTab/migrations-card/MigrationsCard.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationEmptyState/MigrationEmptyState.tsx
Labels: lgtm, approved

#831 Bug 2096780: Wizard with ssh key in additionalResources
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
  src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
  src/views/catalog/wizard/tabs/scripts/components/sshkey-utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#844 Add migration policy tooltip
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationsRow.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/components/MigrationPolicyTooltip/MigrationPolicyTooltip.tsx
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/components/MigrationPolicyTooltip/utils.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/utils/utils.ts
  src/views/clusteroverview/MonitoringTab/migrations-card/hooks/useMigrationCardData.ts
Labels: lgtm, approved

#846 CNV-19298: SSH access with virtctl command
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHAccess/SSHAccess.tsx
  src/utils/components/SSHAccess/SSHAccessModal.tsx
  src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
  src/utils/components/SSHAccess/components/SSHCheckbox.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
  src/utils/components/SSHAccess/useSSHCommand.ts
  src/utils/components/SSHAccess/utils.ts
  src/utils/components/UserCredentials/UserCredentials.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/SSHDetails/SSHDetails.tsx
Labels: lgtm, approved

#822 Bug 2104859: Add "Copy SSH command" to VM actions
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/DesktopViewer/Components/RDPServiceNotConfigured.tsx
  src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
  src/utils/components/SSHAccess/useSSHCommand.ts
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/VirtualMachineActions/VirtualMachineActions.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#853 Bug 2120907: Remove the option to filter by label in the Disks tabs
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskList.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTable.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug
