Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2023-04, with the labels that each got.

#1231 Bug 2180666: Display PVC size correctly in Add disk modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/DiskSizeInput/DiskSizeInput.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelect.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1233 Bug 2184098: Fix size in add volume modal
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeDestination/VolumeDestination.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1234 Bug 2184058: Display 'Add network interface' button only once
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/list/AutoAttachedNetworkEmptyState.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/list/NetworkInterfaceList.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1232 Bug 2175990: Improve Default InstanceType field in Edit modal
  locales/en/plugin__kubevirt-plugin.json
  src/views/bootablevolumes/actions/BootableVolumesActions.tsx
  src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
  src/views/bootablevolumes/actions/hooks/useBootableVolumesActions.tsx
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
  src/views/bootablevolumes/utils/types.ts
  src/views/bootablevolumes/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeSelect/InstanceTypeSelect.tsx
Labels: lgtm, approved, do-not-merge/hold, bugzilla/severity-medium, bugzilla/valid-bug

#1200 Bug 2145101: Fixing the StorageClass warning
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/StorageClass/DefaultStorageClassAlert.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1236 Bug 2181920: Disable Secure Boot for UEFI Boot mode
  src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1240 Bug 2176932: Add title to Virtualization status in OCP dashboard
  console-extensions.json
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1235 Bug 2183979: Console page - disable only vnc console in headless mode
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1242 Bug 2177888: false pending nic state
  src/utils/components/PendingChanges/utils/helpers.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1245 Bug 2027959: Stop with grace period
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/GracePeriodInput/GracePeriodInput.tsx
  src/utils/components/GracePeriodInput/grace-period-input.scss
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/actions.ts
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
  src/views/virtualmachines/actions/components/StopVMModal/StopVMModal.tsx
  src/views/virtualmachines/actions/components/StopVMModal/constants.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1246 Bug 2184063: Display titles in VM Diagnostic tab smaller
  src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabConditions.tsx
  src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabVolumeStatus.tsx
  src/views/virtualmachines/details/tabs/diagnostic/virtual-machine-diagnostic-tab.scss
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1248 Bug 2186462: Fix Add network interface modal for non-admin user
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect.tsx
  src/utils/components/NetworkInterfaceModal/components/hooks/useNADListPermissions.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1249 Bug 2186592: Display titles in VMI Disks tab in correct size
  src/utils/components/DiskListTitle/DiskListTitle.scss
  src/utils/components/DiskListTitle/DiskListTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/VirtualMachinesInstancePageDisksTab.scss
  src/views/virtualmachinesinstance/details/tabs/disks/VirtualMachinesInstancePageDisksTab.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTable.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTableTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTable.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTableTitle.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/virtual-machines-insance-page-disks-tab.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1250 Bug 2182000: Display VM Metrics graphs with Y-Axis
  src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
  src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/NetworkCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/NetworkChartsByNIC.tsx
  src/views/virtualmachines/details/tabs/metrics/UtilizationCharts/UtilizationCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1251 Bug 2186462: Update fixes from premature merge
  src/utils/components/NetworkInterfaceModal/components/hooks/types.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/useNADListPermissions.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1244 [release-4.12] Bug 2186132: Backport false pending state
  src/utils/components/PendingChanges/utils/helpers.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1228 fix: push on quay also for tags
  .github/workflows/deploy.yml
Labels: lgtm, approved

#1254 Bump kubevirt-api to v0.0.51
  package.json
  yarn.lock
Labels: lgtm, approved

#1264 Update cypress tests
  cypress/support/nav.ts
  cypress/tests/catalog/filter.spec.ts
  cypress/tests/check-tabs.spec.ts
  src/views/templates/details/CommonTemplateAlert.tsx
Labels: lgtm, approved

#1253 Bug 2177977: Move pagination to created/selected volume from modals
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/ShowAllBootableVolumesButton/ShowAllBootableVolumesButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1241 Bug 2173525: Disk and net icons for boot order modal
  src/utils/components/BootOrderModal/BootOrderModalBody.tsx
  src/utils/components/BootOrderModal/DeviceTypeIcon.tsx
  src/utils/components/BootOrderModal/boot-order.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1260 Bug 2151237: "404: Not Found" appears before the VMIM details is loaded
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationsRow.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1247 Fix missing CPU memory info in the instance type VM create details section
  src/utils/hooks/useKubevirtTranslation.ts
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsLeftGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts
Labels: lgtm, approved

#1237 Remove extra buttons to create VM or MigrationPolicy
  src/utils/components/ExternalLink/ExternalLink.tsx
  src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
  src/views/clusteroverview/OverviewTab/getting-started-card/utils/getting-started-content/GettingStartedLinkExtraContent.tsx
  src/views/migrationpolicies/list/MigrationPoliciesList.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesCreateButton/MigrationPoliciesCreateButton.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx
  src/views/migrationpolicies/list/utils/constants.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineEmptyState/VirtualMachineEmptyState.tsx
  src/views/virtualmachines/list/components/VirtualMachinesCreateButton/VirtualMachinesCreateButton.tsx
Labels: lgtm, approved

#1269 CNV-27319: Add VirtualMachineClusterInstacetype list view
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/templates/clusterinstancetype-yaml.ts
  src/templates/index.ts
  src/views/instancetypes/actions/ClusterInstancetypeActions.tsx
  src/views/instancetypes/actions/hooks/useClusterInstancetypeActionsProvider.tsx
  src/views/instancetypes/list/ClusterInstancetypeList.tsx
  src/views/instancetypes/list/components/ClusterInstancetypeRow.tsx
  src/views/instancetypes/list/hooks/useClusterInstancetypeListColumns.ts
  src/views/migrationpolicies/list/MigrationPoliciesList.tsx
Labels: lgtm, approved

#1271 Bug 2188010: Rename VM "Diagnostic" tab to "Diagnostics"
  cypress/tests/check-tabs.spec.ts
  cypress/views/tab.ts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/constants/tabs-constants.ts
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1280 Bug 2187242: Increase Utilization pie charts popovers font size
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/VirtualMachinesOverviewTabUtilization.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1274 Bug 2187664: vm with no namespace means default
  src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
  src/views/templates/details/tabs/scripts/components/SysPrepItem/SysPrepItem.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1270 Bug 2187971: guard for template parameter on disk moda
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/resources/template/utils/helpers.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1273 Bug 2188886: Pending loading on detach modal
  src/utils/components/TabModal/TabModal.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/modal/DeleteDiskModal.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/modal/hooks/useVolumeOwnedResource.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1276 CNV-27327: Implement the UI to enable users to create a VM from a PVC
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeFilters.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SectionListItem/SectionListItem.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/VMDetailsBody.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsLeftGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
  src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved

#1263 Bug 2176797: Move YAML switcher out of VM tabs
  cypress/tests/check-tabs.spec.ts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentFormSkeleton.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentFormTitle.tsx
  src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/DiskListPage.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/disk-list-page.scss
  src/views/virtualmachines/details/tabs/configuration/disk/tables/disk/DiskList.tsx
  src/views/virtualmachines/details/tabs/configuration/network/NetworkInterfaceListPage.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/AddNetworkInterfaceButton.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/AutoAttachedNetworkEmptyState.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceRow.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesEditNetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesNetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/network-interface-list-page.scss
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection/SchedulingSection.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/scripts-tab.scss
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
  src/views/virtualmachines/details/tabs/console/components/VirtualMachineConsolePageTitle.scss
  src/views/virtualmachines/details/tabs/console/components/VirtualMachineConsolePageTitle.tsx
  src/views/virtualmachines/details/tabs/details/components/sections/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineDiagnosticTab.tsx
  src/views/virtualmachines/details/tabs/diagnostic/virtual-machine-diagnostic-tab.scss
  src/views/virtualmachines/details/tabs/events/VirtualMachinePageEvents.tsx
  src/views/virtualmachines/details/tabs/events/VirtualMachinePageEventsTab.scss
  src/views/virtualmachines/details/tabs/metrics/TimeRange/TimeRange.tsx
  src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
  src/views/virtualmachines/details/tabs/metrics/virtual-machine-metrics-tab.scss
  src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.scss
  src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotList.tsx
  src/views/virtualmachines/details/utils/constants.ts
  src/views/virtualmachines/details/virtual-machine-page.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1281 CNV-28327: User settings hook infrastracture
  src/utils/hooks/useUserSettings/useUserSettings.ts
Labels: lgtm, approved
