Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2023-03, with the labels that each got.

#1084 Bug 2173593: Display 'No data available' helper text correctly
  src/utils/components/HelpTextIcon/HelpTextIcon.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1082 [release-4.12] Bug 2173574: take namespace from vm instead of useParams
  src/utils/components/SysprepModal/SelectSysprep.tsx
  src/utils/components/SysprepModal/SysprepModal.tsx
  src/views/catalog/wizard/tabs/scripts/components/Sysprep.tsx
  src/views/templates/details/tabs/scripts/components/SysPrepItem/SysPrepItem.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1088 Enable column sorting for bootable volumes list
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts
Labels: lgtm, approved

#1087 Create VM from boot source with correct SC
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/VMDetailsBody.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsRightGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved

#1092 Fix OS display name
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts
Labels: lgtm, approved

#1089 Bug 2168490: Changing the font size in the Bandwidth consumption graph
  src/views/clusteroverview/MonitoringTab/migrations-card/components/BandwidthConsumptionChart/BandwidthConsumptionChart.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1090 Bug 2158424: nads different namespaces
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
  src/utils/components/NetworkInterfaceModal/components/NameFormField.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceMacAddressInput.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceModelSelect.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceTypeSelect.tsx
  src/utils/components/NetworkInterfaceModal/components/hooks/useNadsData.ts
  src/utils/components/NetworkInterfaceModal/utils/constants.ts
  src/utils/components/NetworkInterfaceModal/utils/helpers.ts
  src/utils/components/NetworkInterfaceModal/utils/mac-validation.ts
  src/utils/resources/vm/utils/network/selectors.ts
  src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/catalog/wizard/tabs/network/components/modal/EditNetworkInterfaceModal.tsx
  src/views/catalog/wizard/tabs/network/components/modal/NetworkInterfaceModal.tsx
  src/views/catalog/wizard/tabs/network/components/modal/WizardEditNetworkInterfaceModal.tsx
  src/views/catalog/wizard/tabs/network/components/modal/WizardNetworkInterfaceModal.tsx
  src/views/catalog/wizard/tabs/network/components/modal/components/NetworkInterfaceMacAddressInput.tsx
  src/views/catalog/wizard/tabs/network/components/modal/components/NetworkInterfaceNetworkSelect.tsx
  src/views/catalog/wizard/tabs/network/components/modal/utils/helpers.ts
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/templates/details/tabs/network/components/modal/EditNetworkInterfaceModal.tsx
  src/views/templates/details/tabs/network/components/modal/NetworkInterfaceModal.tsx
  src/views/templates/details/tabs/network/components/modal/TemplatesEditNetworkInterfaceModal.tsx
  src/views/templates/details/tabs/network/components/modal/TemplatesNetworkInterfaceModal.tsx
  src/views/templates/details/tabs/network/components/modal/components/NameFormField.tsx
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceMacAddressInput.tsx
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceModelSelect.tsx
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceNetworkSelect.tsx
  src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceTypeSelect.tsx
  src/views/templates/details/tabs/network/components/modal/utils/constants.ts
  src/views/templates/details/tabs/network/components/modal/utils/helpers.ts
  src/views/virtualmachines/details/tabs/configuration/network/NetworkInterfaceListPage.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/EditNetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/NetworkInterfaceFormFields/NetworkInterfaceModelSelect.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/NetworkInterfaceFormFields/NetworkInterfaceTypeSelect.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/NetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/VirtualMachinesEditNetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/VirtualMachinesNetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/utils/constants.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1093 Bug 2174324: Rename Add to Add volume button for Bootable volumes
  locales/en/plugin__kubevirt-plugin.json
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1096 Bug 2174636: Visit Virtualization -> Overview -> Migrations crashes the app
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1091 Bug 2151053: Cloud init fix
  src/utils/components/CloudinitModal/utils/useCloudInit.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1097 Bug 2151521: add user on vm template example
  src/templates/vm-template-yaml.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1095 Bug 2159975: Fixing the prefix docker while editing the regstiry
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
  src/views/catalog/customize/components/CustomizeSource/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1100 Remove alerts with health impact of none from health status popup chart
  src/utils/hooks/useInfrastructureAlerts/useInfrastructureAlerts.ts
  src/utils/hooks/useInfrastructureAlerts/utils/utils.ts
Labels: lgtm, approved

#1101 Bug 2173527: Add help text to Machine type field
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
  src/views/templates/details/tabs/details/components/DescriptionItem.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1105 Bug 2175274: Display Edit CPU | Memory modal in VM Details
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
  src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1104 Bug 2175256: Display Catalog page correctly, fix TypeError when accessing Catalog
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1106 Bug 2168486: Enable Restore template settings by fixing templates link
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1094 Bug 2174288: No storageClass is selected by default while adding/editing a disk
  src/utils/components/DiskModal/DiskFormFields/StorageClassSelect.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1076 Bug 2155403: Adding labels for Linux only and Windows only next to the "SSH" and "Sysprep"
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DescriptionItem/DescriptionItemHeader.tsx
  src/utils/components/Labels/LinuxLabel.tsx
  src/utils/components/Labels/WindowsLabel.tsx
  src/utils/components/Labels/labels.scss
  src/views/catalog/wizard/components/WizardDescriptionItem/WizardDescriptionItem.tsx
  src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
  src/views/catalog/wizard/tabs/scripts/components/Sysprep.tsx
  src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
  src/views/templates/details/tabs/scripts/components/SysPrepItem/SysPrepItem.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1107 Bug 2168561: Changing iosp to uppercase letters in metrics tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/metrics/StorageCharts/StorageCharts.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1103 Bug 2167226: Make sorting NICs by Type work correctly
  src/utils/resources/vm/utils/network/utils.ts
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceList.tsx
  src/views/catalog/wizard/tabs/network/hooks/useNetworkColumns.ts
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceList.tsx
  src/views/templates/details/tabs/network/hooks/useNetworkColumns.ts
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/list/NetworkInterfaceList.tsx
  src/views/virtualmachines/details/tabs/configuration/network/hooks/useNetworkColumns.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1083 [release-4.11] Bug 2173589: CNV-23494 Ssh select load balancer
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHAccess/SSHAccessModal.tsx
  src/utils/components/SSHAccess/components/SSHCheckbox.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
  src/utils/components/SSHAccess/components/SSHServiceSelect.tsx
  src/utils/components/SSHAccess/constants.ts
  src/utils/components/SSHAccess/useSSHCommand.ts
  src/utils/components/SSHAccess/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1108 Bug 2172842: Changing "Templates catalog / project" to "Template catalog / project"
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogProjectsDropdown/TemplatesCatalogProjectsDropdown.tsx
  src/views/clusteroverview/SettingsTab/SettingsTab.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1115 Bug 2175651: Sending props to isEdit on network modal
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1113 Bug 2172371: Disable "Restore template settings" for VM without template
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1114 Add sorting Bootable volumes by Operating system
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
  src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
  src/views/bootablevolumes/utils/utils.ts
Labels: lgtm, approved

#1117 Update text for Developer preview and Clone existing PVC
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DeveloperPreviewLabel/DeveloperPreviewLabel.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
Labels: lgtm, approved

#1121 Bug 2176353: Fix headless mode in catalog
  src/utils/components/HardwareDevices/HardwareDevices.tsx
  src/utils/components/HardwareDevices/HardwareDevicesHeadlessMode.tsx
  src/utils/components/HardwareDevices/modal/HardwareDevicesHeadlessModeModal.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1098 Bug 2168488: add descriptions to workloads
  __mocks__/react-i18next.ts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/WorkloadProfileModal/WorkloadProfileModal.tsx
  src/utils/resources/template/utils/constants.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1102 Bug 2174619: render any device as bootable
  src/utils/components/BootOrderModal/BootOrderModalBody.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1112 Add size and StorageClass columns to bootable volumes list
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/TableData.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
  src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
Labels: lgtm, approved

#1118 Bug 2175601: Nads loading - non admin user
  src/utils/components/NetworkInterfaceModal/components/hooks/useNadsData.ts
  src/utils/constants/constants.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1123 Bug 2173562: show msg when headless mode in on and remove play button
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/utils/utils.ts
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsoleConnect.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1124 Bug 2176804: VM created with instanceType from UI cannot be started due to secret missing
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/SSHKeySection.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1119 small doc fix
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHAccess/components/SSHServiceSelect.tsx
Labels: lgtm, approved

#1120 Bug 2175641: Add volume from existing PVC not working
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/constants.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1125 Bug 2175054: Delete bootable volume modal crash the page
  src/views/bootablevolumes/utils/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1129 Bug 2176843 - 'No bootable device' shows in VM console if it's created with instanceType
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved

#1122 Bug 2175985: Make Clone existing PVC checkbox help icon enabled
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/HelpTextIcon/HelpTextIcon.scss
  src/utils/components/HelpTextIcon/HelpTextIcon.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.scss
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1126 Bug 2175571: Sort Catalog templates in grid view
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogItems.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1127 Bug 2176753: Remove dashed line from Configurations subtitle
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1128 Bug 2175988: Remove descriptive text of the volume name
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1130 Disable create VM button when cant create VM
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
Labels: lgtm, approved

#1135 Remove glekner from OWNERS
  OWNERS
Labels: lgtm, approved

#1136 Bug 2175643: Remove loading from add volume button
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1138 Add hstastna and upalatucci to approvers
  OWNERS
Labels: lgtm, approved

#1116 Add new SSH section
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AuthorizedSSHKeyModal/SelectSecret.tsx
  src/utils/components/SSHSecretSection/SSHSecretSection.scss
  src/utils/components/SSHSecretSection/SSHSecretSection.tsx
  src/utils/components/SSHSecretSection/utils/components/SSHKeyUpload/SSHKeyUpload.scss
  src/utils/components/SSHSecretSection/utils/components/SSHKeyUpload/SSHKeyUpload.tsx
  src/utils/components/SSHSecretSection/utils/components/SecretDropdown/SecretDropdown.tsx
  src/utils/components/SSHSecretSection/utils/components/SecretDropdown/components/SecretSelectOption.tsx
  src/utils/components/SSHSecretSection/utils/components/SecretSelectionRadioGroup.tsx
  src/utils/components/SSHSecretSection/utils/types.ts
  src/utils/components/SSHSecretSection/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/VMDetailsBody.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsLeftGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsRightGrid.tsx
Labels: lgtm, approved

#1109 Bug 2170703: Fix template catalog search
  cypress/tests/catalog/filter.spec.ts
  package.json
  src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/SelectorLabelMatchGroup/SelectorLabelMatchGroup.tsx
  yarn.lock
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1142 Bug 2176706: Fix inner tabs routing
  src/utils/components/PendingChanges/utils/constants.ts
  src/utils/components/PendingChanges/utils/helpers.ts
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/modal/MakePersistentModal.tsx
  src/views/virtualmachines/details/tabs/configuration/utils/utils.ts
  src/views/virtualmachines/details/virtual-machine-page-title.scss
  src/views/virtualmachines/details/virtual-machine-page.scss
  src/views/virtualmachines/utils/constants.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1132 Bug 2158079: Align Storage expandable section with HelpIcon
  src/utils/components/HelpTextIcon/HelpTextIcon.scss
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.scss
  src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1140 Bug 2173563: Add titles to VM Environment and Scripts tabs
  src/utils/components/EnvironmentEditor/EnvironmentForm.scss
  src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentFormTitle.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection/SchedulingSection.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1144 Bug 2175976: 'Select InstanceType' should show the volume's default instanceType
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsLeftGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1145 Bug 2176353: remove headless mode in catalog drawer
  src/utils/components/HardwareDevices/HardwareDevices.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1151 Bug 2175986: Improve message for different StorageClass
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/StorageClassSelect.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1137 Bug 2174334: VM's disk is not deleted along with the VM if the VM is created from upload image
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/hooks/useCDIUpload/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1149 Bug 2158424: Replace name and namespace places
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1133 Bug 2176725: Carry over "Start this VirtualMachine after creation" value
  src/views/catalog/customize/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/wizard/components/WizardFooter.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1139 Bug 2177589: Sort Preferences in Add volume modal
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1143 Include silenced alerts in health popup
  src/utils/constants/prometheus.ts
  src/utils/hooks/useAlerts.ts
  src/utils/hooks/useAlerts/useAlerts.ts
  src/utils/hooks/useAlerts/utils/constants.ts
  src/utils/hooks/useAlerts/utils/utils.ts
  src/utils/hooks/useInfrastructureAlerts/useInfrastructureAlerts.ts
  src/utils/hooks/useInfrastructureAlerts/utils/constants.ts
  src/utils/hooks/useInfrastructureAlerts/utils/utils.ts
  src/utils/hooks/useKubevirtAlerts.ts
  src/utils/hooks/useSilences/useSilences.ts
  src/utils/hooks/useSilences/utils/constants.ts
  src/utils/types/prometheus.ts
  src/utils/utils/prometheus.ts
  src/views/clusteroverview/OverviewTab/alerts-card/hooks/useSimplifiedAlerts.ts
  src/views/clusteroverview/OverviewTab/status-card/utils/VirtualizationAlerts.tsx
  src/views/clusteroverview/OverviewTab/status-card/utils/constants.ts
  src/views/clusteroverview/OverviewTab/status-card/utils/utils.tsx
  src/views/dashboard-extensions/KubevirtHealthPopup/utils/utils.ts
  src/views/virtualmachines/details/tabs/overview/utils/hook/useVMAlerts.tsx
  src/views/virtualmachines/details/tabs/overview/utils/utils.tsx
Labels: lgtm, approved

#1146 Addin an icon to configuration tab - vm details
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/virtual-machine-page.scss
Labels: lgtm, approved

#1152 Bug 2168480: Correct the link for Virtualization dashboard
  src/views/virtualmachines/details/tabs/metrics/TimeRange/TimeRange.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1153 Bug 2158060: Fix sorting pvcs, ds, projects
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/hooks/useProjectsAndDataSources.ts
  src/utils/components/DiskModal/DiskFormFields/hooks/useProjectsAndPVCs.ts
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/utils.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/utils.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1150 Bug 2175983: Update text on Delete modal for bootable volumes
  locales/en/plugin__kubevirt-plugin.json
  src/views/bootablevolumes/actions/components/DeleteBootableVolumesModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1155 Bug 2177973: Display cloning bootable volumes, add "Clone in progress"
  src/utils/resources/shared.ts
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1160 Bug 2179226: Rename 'Name' to 'Secret name' field in Advanced settings
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHSecretSection/SSHSecretSection.scss
  src/utils/components/SSHSecretSection/SSHSecretSection.tsx
  src/utils/components/SSHSecretSection/utils/components/SSHKeyUpload/SSHKeyUpload.scss
  src/utils/components/SSHSecretSection/utils/components/SSHKeyUpload/SSHKeyUpload.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.scss
Labels: lgtm, approved, bugzilla/severity-medium

#1157 fix: editor height
  src/views/virtualmachines/details/virtual-machine-page.scss
Labels: lgtm, approved

#1161 Bug 2166507: Improving setting tab loading speed
  src/views/clusteroverview/SettingsTab/GeneralTab/GeneralTab.tsx
  src/views/clusteroverview/utils/constants.ts
  src/views/clusteroverview/utils/hooks/useKubevirtCSVDetails.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1147 Bug 2159715: Instancetype cpu memory
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/details/components/CPUMemory/CPUMemory.tsx
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/EditButtonWithTooltip.tsx
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.scss
  src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1166 Bug 2176706: Fix netwrok routhing
  src/utils/components/PendingChanges/utils/constants.ts
  src/utils/components/PendingChanges/utils/helpers.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1163 Bug 2179225: removing link from secret list
  src/utils/components/SSHSecretSection/utils/components/SecretDropdown/SecretDropdown.tsx
  src/utils/components/SSHSecretSection/utils/components/SecretDropdown/components/SecretSelectOption.tsx
  src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1169 Update SSH key popover in InstanceType create VM flow
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/SSHSecretSection/SSHSecretSection.tsx
  src/utils/components/SSHSecretSection/utils/components/SSHKeyUpload/SSHKeyUpload.tsx
  src/utils/components/VMAuthorizedSSHKeyModal/VMAuthorizedSSHKeyModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/SSHKeySection.tsx
  src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
  src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
Labels: lgtm, approved

#1168 Bug 2179626: Removing filtering from diagnostic volume status
  src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticVolumeStatusTableColumns.ts
  src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabVolumeStatus.tsx
  src/views/virtualmachines/details/tabs/diagnostic/virtual-machine-diagnostic-tab.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1173 fix not migratable label
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.scss
Labels: lgtm, approved

#1165 Bug 2179811: Sometimes the preference list is empty in Bootable volumes -> Add volume modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/StorageClass/AlertedStorageClassSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/StorageClass/DefaultStorageClassAlert.tsx
  src/utils/components/DiskModal/DiskFormFields/StorageClass/StorageClassSelect.tsx
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/hooks/useCDIUpload/useCDIUpload.ts
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeDestination/VolumeDestination.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/VolumeMetadata.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeSelect/InstanceTypeSelect.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1167 Bug 2174619: all devices are boot source, just needs to arrange them
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/BootOrderModal/BootOrderModalBody.tsx
  src/utils/components/BootOrderModal/add-device.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1170 Bug 2177578: Set columns' width for volumes in Catalog > InstanceTypes
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/TableData.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1175 Bug 2172375: Error on deleting secret
  src/utils/components/TabModal/TabModal.tsx
  src/utils/components/VMAuthorizedSSHKeyModal/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1181 Bug 2180279: VM cannot be started while creating from a template which has 2nd disk added
  src/utils/components/DiskModal/utils/helpers.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1158 Bug 2175977: Disable Create VM button if not everything selected
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
Labels: lgtm, approved, bugzilla/severity-medium

#1182 Bug 2175979: Change Cores to CPUs in InstanceTypes pages
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeSelect/InstanceTypeSelect.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/CategoryCard/CategoryCard.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/InstanceTypesMenu/InstanceTypesMenu.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/types.ts
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1183 Bug 2175974: Show 8 rows in bootable volumes list
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1177 Bug 2177091: hide edit buttons on catalog drawer
  src/utils/components/HardwareDevices/HardwareDeviceTitle.tsx
  src/utils/components/HardwareDevices/HardwareDevices.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1186 Update texts in Edit,Delete modals in Bootable volumes list
  locales/en/plugin__kubevirt-plugin.json
  src/views/bootablevolumes/actions/components/DeleteBootableVolumesModal.tsx
  src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
  src/views/bootablevolumes/actions/hooks/useBootableVolumesActions.tsx
Labels: lgtm, approved

#1185 Bug 2168749: disable network renaming on already created vm
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
  src/utils/components/NetworkInterfaceModal/components/NameFormField.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/VirtualMachinesEditNetworkInterfaceModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1188 Bug 2174744: Fix bootable volumes filter chips alignment
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.scss
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1190 Bug 2180931: Truncate long text in Description column for boot volumes
  src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1196 Bug 2179225: Remove append to parent from ssh select instancetypes
  src/utils/components/SSHSecretSection/utils/components/SecretDropdown/SecretDropdown.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1192 Bug 2177977: The volume in instanceTypes page should be selected automatically just after it's been added
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsRightGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1197 Bug 2181515: spec.firmware.bootloader is not copied while cloning a UEFI VM
  src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1204 Bug 2180719: Provide username in "Copy SSH command" of a VM
  src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
  src/utils/components/SSHAccess/utils.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1206 Move StorageClass field to Destination details
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeDestination/VolumeDestination.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
Labels: lgtm, approved

#1199 Bug 2182317: Restore vm's pretty names
  src/utils/resources/template/hooks/useProcessedTemplate.ts
  src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
  src/utils/resources/template/utils/constants.ts
  src/utils/resources/template/utils/helpers.ts
  src/utils/resources/template/utils/selectors.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1201 Bug 2182056: Cloned VM should not use the same PVC of the source VM
  src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
  src/views/virtualmachines/actions/components/CloneVMModal/hooks/useCloneVMResources.tsx
  src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1141 Bug 2167608: highlight parts
  src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
  src/utils/components/SidebarEditor/SidebarEditor.tsx
  src/utils/components/SidebarEditor/useEditorHighlighter.ts
  src/utils/components/SidebarEditor/utils.ts
  src/utils/resources/vm/utils/constants.ts
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
  src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
  src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/DiskListPage.tsx
  src/views/virtualmachines/details/tabs/configuration/network/NetworkInterfaceListPage.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/VirtualMachineSchedulingPage.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
  src/views/virtualmachines/details/tabs/details/VirtualMachineDetailsPage.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1191 Bug 2176745: Align badges in Boot source column
  src/views/catalog/templatescatalog/components/TemplateRowAvailableSource/TemplateRowAvailableSource.scss
  src/views/catalog/templatescatalog/components/TemplateRowAvailableSource/TemplateRowAvailableSource.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogRow.tsx
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/templates/list/components/VirtualMachineTemplateSupport/VirtualMachineTemplateSupport.scss
  src/views/templates/list/components/VirtualMachineTemplateSupport/VirtualMachineTemplateSupport.tsx
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/components/VirtualMachineTemplatesSource/VirtualMachineTemplatesSource.scss
  src/views/templates/list/components/VirtualMachineTemplatesSource/VirtualMachineTemplatesSource.tsx
Labels: lgtm, approved

#1203 Bug 2182362: no dedicated resources with instancetype
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/VirtualMachineSchedulingRightGrid.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1189 Bug 2158550: Display MigrationPolicy page after renaming correctly
  src/views/migrationpolicies/components/MigrationPolicyEditModal/MigrationPolicyEditModal.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1205 Update text in 'Add volume', 'Edit volume metadata' modals
  locales/en/plugin__kubevirt-plugin.json
  src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
  src/views/bootablevolumes/actions/hooks/useBootableVolumesActions.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.scss
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
Labels: lgtm, approved

#1211 Bug 2180664: Console is almost frozen if scroll down and up in VM metrics tab
  src/utils/components/Charts/utils/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1215 Bug 2181323: Select 'Size' automatically if 'Default InstanceType' chosen
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeSelect/InstanceTypeSelect.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1217 Bug 2177977: The volume in instanceTypes page should be selected automatically just after it's been added
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/shared.ts
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1223 [release-4.13] Bug 2182536: The volume in instanceTypes page should be selected automatically just after it's been added
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/shared.ts
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsRightGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1219 Bug 2182233: Enforcing ssh secret name to be 51 chars or less
  src/views/catalog/wizard/tabs/scripts/components/sshkey-utils.ts
  src/views/templates/details/tabs/scripts/components/SSHKey/sshkey-utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1220 CNV-23614: Change uppercase - Make Persistent to Make persistent
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/tables/disk/DiskRowActions.tsx
Labels: lgtm, approved

#1221 Bug 2183076: Adjust configuration inner tab apperance
  src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss
  src/views/virtualmachines/details/virtual-machine-page.scss
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1229 Bug 2167660: Fix overview trend charts for All Projects namespace
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/useMetricChartData.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
