Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2023-02, with the labels that each got.

#1034 CNV-21974: clone in progress label
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/views/catalog/templatescatalog/hooks/useAvailableDataSourcesAndPVCs.ts
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
  src/views/templates/list/hooks/useTemplatesWithAvailableSource.ts
Labels: lgtm, approved

#1037 Adding a check for getDay in metric virtualization
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/utils.ts
Labels: lgtm, approved

#1044 fix: move ensurePath to utils
  src/utils/components/BootOrderModal/BootOrderModal.tsx
  src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
  src/utils/components/DeschedulerModal/DeschedulerModal.tsx
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/components/EnvironmentEditor/hooks/useEnvironments.ts
  src/utils/components/EvictionStrategyModal/EvictionStrategyModal.tsx
  src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
  src/utils/components/HostnameModal/HostnameModal.tsx
  src/utils/components/NodeSelectorModal/NodeSelectorModal.tsx
  src/utils/components/StartPauseModal/StartPauseModal.tsx
  src/utils/components/TolerationsModal/TolerationsModal.tsx
  src/utils/utils/utils.test.ts
  src/utils/utils/utils.ts
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
  src/views/catalog/utils/utils.ts
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
  src/views/datasources/dataimportcron/details/DataImportCronManageModal/utils.ts
  src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
  src/views/templates/details/tabs/details/components/DisplayName.tsx
  src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
  src/views/templates/utils/utils.ts
  src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved

#1038 Bug 2166165: Changing the data-test-id on VM creation page
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsLeftGrid.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1039 Display only available DataSources for VM creation
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUploadPVC.tsx
  src/utils/resources/shared.ts
  src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/bootablevolumes/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
Labels: lgtm, approved

#1041 Bug 2166508: Setting page doesn't crash when the user doesn't have permission
  src/views/clusteroverview/SettingsTab/LiveMigrationTab/Network/Network.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1035 CNV-21086: Change Not migratable label style
  src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.scss
  src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.tsx
Labels: lgtm, approved

#1043 fix: create ssh service with no labels obj
  src/utils/components/SSHAccess/utils.ts
Labels: lgtm, approved

#1046 Update 'Developer preview' label colors
  src/utils/components/DeveloperPreviewLabel/DeveloperPreviewLabel.scss
  src/utils/components/DeveloperPreviewLabel/DeveloperPreviewLabel.tsx
Labels: lgtm, approved

#1045 CNV-22306: mount window drivers on wizard and vm disk tab
  src/utils/components/WindowsDrivers/WindowsDrivers.tsx
  src/utils/components/WindowsDrivers/utils.ts
  src/utils/resources/template/utils/drivers.ts
  src/utils/resources/vm/utils/disk/constants.ts
  src/utils/resources/vm/utils/disk/drivers.ts
  src/views/catalog/customize/constants.ts
  src/views/catalog/customize/utils.ts
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskList.tsx
Labels: lgtm, approved

#1049 CNV-20215: Moving dashboard extension from old console to ours
  console-extensions.json
  package.json
  src/views/dashboard-extensions/Activity.tsx
  src/views/dashboard-extensions/ActivityProgress.tsx
  src/views/dashboard-extensions/Inventory.tsx
  src/views/dashboard-extensions/inventory.scss
  src/views/dashboard-extensions/utils.ts
Labels: lgtm, approved

#1040 Update Bootable volume's related strings
  cypress/views/vm.ts
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved

#1042 CNV-23614: Adding an option to make disk persistent in disk table
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
  src/utils/resources/vmi/utils/selectors.ts
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert.tsx
  src/views/virtualmachines/details/tabs/disk/modal/MakePersistentModal.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRowActions.tsx
Labels: lgtm, approved

#1050 Bug 2168859: useParams under HorizontalNav does not give namespace
  src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
  src/utils/components/AuthorizedSSHKeyModal/SelectSecret.tsx
  src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
  src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1047 CNV-5451: Adding the option to start VM in headless mode
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/HardwareDevices/HardwareDevices.tsx
  src/utils/components/HardwareDevices/HardwareDevicesHeadlessMode.tsx
  src/utils/components/HardwareDevices/modal/HardwareDevicesHeadlessModeModal.tsx
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
Labels: lgtm, approved

#1033 CNV-16653: Statistics of secondary network interfaces
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
  src/utils/components/Charts/utils/queries.ts
  src/utils/components/Charts/utils/utils.ts
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/NetworkCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/NetworkChartsByNIC.tsx
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/hook/useNetworkData.tsx
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/hook/useQuery.ts
  src/views/virtualmachines/details/tabs/metrics/UtilizationCharts/UtilizationCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
  src/views/virtualmachines/details/tabs/metrics/utils/constants.ts
  src/views/virtualmachines/details/tabs/metrics/virtual-machine-metrics-tab.scss
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
Labels: lgtm, approved

#1058 CNV-21086: Display "Not migratable" only for running VMs
  src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.tsx
Labels: lgtm, approved

#1056 CNV-18014: Update text in Add volume modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelectName.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelectNamespace.tsx
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUploadPVC.tsx
  src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/FormSelectionRadio/FormSelectionRadio.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.scss
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsLeftGrid.tsx
  src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
  src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
Labels: lgtm, approved

#1057 CNV-18014: Update Delete action for Bootable volumes
  locales/en/plugin__kubevirt-plugin.json
  src/views/bootablevolumes/actions/components/DeleteBootableVolumesModal.tsx
  src/views/bootablevolumes/actions/hooks/useBootableVolumesActions.tsx
  src/views/bootablevolumes/utils/utils.ts
Labels: lgtm, approved

#1061 Bug 2151831: Changing the time format in charts
  src/utils/components/Charts/utils/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1048 Bug 2151508: Adding user name to virtctl ssh command
  src/utils/components/SSHAccess/SSHAccess.tsx
  src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
  src/utils/components/SSHAccess/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1062 Bug 2167661: Changing the Alerts card if there are no alerts
  src/utils/components/AlertsCard/AlertsDrawer.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1063 CNV-21086: Change Not migratable label to blue
  src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.scss
Labels: lgtm, approved

#1060 CNV-24126: Adding diagnostic tab to VM details page
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/PendingChanges/utils/constants.ts
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineDiagnosticTab.tsx
  src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineDiagnosticTabRow.tsx
  src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticColumns.ts
  src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticFilter.ts
  src/views/virtualmachines/details/tabs/diagnostic/hooks/useDianosticData.ts
  src/views/virtualmachines/details/tabs/diagnostic/utils/types.ts
  src/views/virtualmachines/details/tabs/diagnostic/utils/utils.ts
  src/views/virtualmachines/details/tabs/diagnostic/virtual-machine-diagnostic-tab.scss
  src/views/virtualmachines/list/hooks/utils/utils.ts
  src/views/virtualmachines/utils/constants.ts
Labels: lgtm, approved

#1065 Bug 2151759: Remove adding DV ownership when creating VM
  src/utils/hooks/useCDIUpload/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1069 Bug 2158362: filtering PVCs that are in terminate state
  src/views/catalog/customize/components/PersistentVolumeClaimSelect/utils.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1066 Bug 2151766: No boot source available for existing pvc
  src/utils/resources/vm/utils/source.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1067 CNV-24126: Rearrange vm tabs
  cypress/tests/check-tabs.spec.ts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/PendingChanges/utils/constants.ts
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/DiskListPage.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/disk-list-page.scss
  src/views/virtualmachines/details/tabs/configuration/disk/hooks/useDiskColumns.ts
  src/views/virtualmachines/details/tabs/configuration/disk/hooks/useDisksFilters.ts
  src/views/virtualmachines/details/tabs/configuration/disk/hooks/useFilesystemListColumns.ts
  src/views/virtualmachines/details/tabs/configuration/disk/modal/DeleteDiskModal.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/modal/MakePersistentModal.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/modal/hooks/useVolumeOwnedResource.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/modal/hooks/utils/utils.ts
  src/views/virtualmachines/details/tabs/configuration/disk/tables/disk/DiskList.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/tables/disk/DiskListTitle.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/tables/disk/DiskRow.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/tables/disk/DiskRowActions.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/tables/disk/HotplugLabel.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/tables/disk/utils/getEditDiskStates.ts
  src/views/virtualmachines/details/tabs/configuration/disk/tables/disk/utils/helpers.ts
  src/views/virtualmachines/details/tabs/configuration/disk/tables/filesystem/FilesystemList.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/tables/filesystem/FilesystemListLayout.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/tables/filesystem/FilesystemListTitle.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/tables/filesystem/FilesystemRow.tsx
  src/views/virtualmachines/details/tabs/configuration/disk/tables/tables.scss
  src/views/virtualmachines/details/tabs/configuration/environment/VirtualMachineEnvironmentPage.tsx
  src/views/virtualmachines/details/tabs/configuration/network/NetworkInterfaceListPage.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/list/NetworkInterfaceList.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/list/NetworkInterfaceRow.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/EditNetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/NetworkInterfaceFormFields/NetworkInterfaceMacAddressInput.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/NetworkInterfaceFormFields/NetworkInterfaceModelSelect.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/NetworkInterfaceFormFields/NetworkInterfaceNetworkSelect.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/NetworkInterfaceFormFields/NetworkInterfaceTypeSelect.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/NetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/utils/constants.ts
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/utils/helpers.ts
  src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/utils/mac-validation.ts
  src/views/virtualmachines/details/tabs/configuration/network/hooks/useNetworkColumns.ts
  src/views/virtualmachines/details/tabs/configuration/network/hooks/useNetworkRowFilters.ts
  src/views/virtualmachines/details/tabs/configuration/network/network-interface-list-page.scss
  src/views/virtualmachines/details/tabs/configuration/scheduling/VirtualMachineSchedulingPage.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/Affinity.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/DedicatedResources.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/Descheduler.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/EvictionStrategy.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/NodeSelector.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection/SchedulingSection.scss
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection/SchedulingSection.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/VirtualMachineSchedulingRightGrid.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/components/ScriptsTabFooter.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/scripts-tab.scss
  src/views/virtualmachines/details/tabs/configuration/utils/utils.ts
  src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss
Labels: lgtm, approved

#1072 [release-4.12] Bug 2169371: useParams under HorizontalNav does not gi…
  src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
  src/utils/components/AuthorizedSSHKeyModal/SelectSecret.tsx
  src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
  src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1074 Bug 2150364: External Secret should not have vm as owner
  src/utils/components/VMAuthorizedSSHKeyModal/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1071 Bug 2169699: Add ssh select id for testing purposes
  src/utils/components/SSHAccess/components/SSHServiceSelect.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1073 [release-4.12] Bug 2172832: CNV-23494 Ssh select load balancer
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHAccess/components/SSHCheckbox.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
  src/utils/components/SSHAccess/components/SSHServiceSelect.tsx
  src/utils/components/SSHAccess/constants.ts
  src/utils/components/SSHAccess/useSSHCommand.ts
  src/utils/components/SSHAccess/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1077 Bug 2159975: Remove the "docker://" prefix while editing the rootdisk (registry)
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
  src/utils/components/DiskModal/utils/helpers.ts
  src/views/catalog/customize/components/CustomizeSource/utils.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1059 CNV-25234: Add kubevirt health status popup
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/Consoles/components/SerialConsole/SerialConsole.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/LoadingEmptyState/LoadingEmptyState.tsx
  src/utils/extensions/dashboard/dashboardHealth.ts
  src/utils/extensions/dashboard/index.ts
  src/utils/extensions/dashboard/types.ts
  src/utils/hooks/useAlerts.ts
  src/utils/hooks/useInfrastructureAlerts/useInfrastructureAlerts.ts
  src/utils/hooks/useInfrastructureAlerts/utils/constants.ts
  src/utils/hooks/useInfrastructureAlerts/utils/utils.ts
  src/utils/hooks/useKubevirtAlerts.ts
  src/views/clusteroverview/OverviewTab/alerts-card/OverviewAlertsCard.tsx
  src/views/clusteroverview/OverviewTab/alerts-card/hooks/useSimplifiedAlerts.ts
  src/views/clusteroverview/OverviewTab/vms-per-template-card/VMsPerTemplateCard.tsx
  src/views/dashboard-extensions/KubevirtHealthPopup/KubevirtHealthPopup.scss
  src/views/dashboard-extensions/KubevirtHealthPopup/KubevirtHealthPopup.tsx
  src/views/dashboard-extensions/KubevirtHealthPopup/components/EmptyStateNoAlerts.tsx
  src/views/dashboard-extensions/KubevirtHealthPopup/components/HealthPopupChart.tsx
  src/views/dashboard-extensions/KubevirtHealthPopup/utils/types.ts
  src/views/dashboard-extensions/KubevirtHealthPopup/utils/utils.ts
Labels: lgtm, approved

#1075 CNV-18014: Rename Upload to Save in Add volume modal
  src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
  src/views/bootablevolumes/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.scss
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
Labels: lgtm, approved

#1081 adjust tests as VM tabs changed
  cypress/tests/check-tabs.spec.ts
  cypress/views/tab.ts
Labels: lgtm, approved

#1086 Bug 2173595: Fixed the vm list page stuck loading for reader user
  src/utils/hooks/useKubevirtWatchResource.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
