Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2023-01, with the labels that each got.

#1007 CNV-21086: Add 'Live migratable' field to the VM Overview tab
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
Labels: lgtm, approved

#1008 CNV-21086: Add Live migratable to VM Details tab
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
Labels: lgtm, approved

#1006 [release-4.11] Bug 2119724: Customizing VM creation via template sets storageclass configuration to default
  src/utils/hooks/useDefaultStorageClass/constants.ts
  src/utils/hooks/useDefaultStorageClass/useDefaultStorageClass.ts
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/severity-high

#1009 Improve help text of DataImportCron field
  locales/en/plugin__kubevirt-plugin.json
  src/views/datasources/details/components/DataSourceImportCronDescription/DataSourceImportCronDescription.tsx
Labels: lgtm, approved

#1001 CNV-23376: Create new page for InstanceTypes VM creation flow
  console-extensions.json
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/Catalog.tsx
  src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.scss
  src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/CreateFromInstanceType.scss
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.scss
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/SectionListItem/SectionListItem.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/constants.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateVMTabTitle/CreateVMTabTitle.tsx
  src/views/catalog/CreateVMHorizontalNav/constants.ts
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved

#1005 Bug 2154257: 'Quick create VirtualMachine' does no show up when upgrade OCP 4.11 to OCP 4.12
  src/utils/resources/template/hooks/useProcessedTemplate.ts
  src/views/catalog/customize/utils.ts
  src/views/catalog/utils/quick-create-vm.ts
Labels: lgtm, approved, bugzilla/severity-medium

#1010 Bug 2145092: Display migrationPoliciesEmptyState image for slow network
  images/globals.d.ts
  images/migrationPoliciesEmptyState.png
  images/migrationPoliciesEmptyState.svg
  src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.scss
  src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1013 CNV-21086: Add new 'Not migratable' badge to VMs list
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineStatus/VirtualMachineStatus.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved

#1012 CNV-23983: Create a modal form to add a boot volume
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/constants/constants.ts
  src/utils/resources/shared.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/components/FilterSelect/FilterSelect.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/components/FilterSelect/components/FilterSelectOption/FilterSelectOption.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/components/FilterSelect/components/FilterSelectOptions/FilterSelectOptions.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/components/FormSelectionRadio/FormSelectionRadio.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/utils/constants.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/SectionListItem/SectionListItem.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/constants.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/hooks/useInstanceTypesAndPreferences.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/utils/constants.ts
  src/views/catalog/utils/tests/vm-produce.test.ts
  src/views/clusteroverview/OverviewTab/inventory-card/utils/constants.ts
  src/views/clusteroverview/OverviewTab/inventory-card/utils/utils.ts
  src/views/clusteroverview/SettingsTab/PermissionsTab/hooks/usePermissions.ts
  src/views/clusteroverview/SettingsTab/PermissionsTab/utils/constants.ts
  yarn.lock
Labels: lgtm, approved

#1014 CNV-21086: Add 'Not migratable' badge to VM Overview tab
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/list/components/VMNotMigratableBadge/VMNotMigratableBadge.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineStatus/VirtualMachineStatus.tsx
Labels: lgtm, approved

#1015 CNV-21086: Add 'Not migratable' badge to VM title
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
Labels: lgtm, approved

#1011 Bug 2148850: Display help texts in MigrationPolicy details
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DescriptionItem/DescriptionItemHeader.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx
  src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyDescriptionItem.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1016 Add StorageClass input to 'Add bootable Volume' modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/StorageClassSelect.tsx
  src/utils/components/DiskModal/DiskFormFields/hooks/useStorageProfileClaimPropertySets.ts
  src/utils/components/DiskModal/DiskFormFields/utils/Filters.tsx
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/EditDiskModal.tsx
  src/utils/components/DiskModal/utils/helpers.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/components/FilterSelect/components/FilterSelectOptions/FilterSelectOptions.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/utils/constants.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/hooks/useInstanceTypesAndPreferences.ts
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormStorageClass.tsx
  src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts
Labels: lgtm, approved

#1019 Bug 2160298: Simplify YAML Switcher text to "YAML"
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SidebarEditor/SidebarEditorSwitch.tsx
  src/utils/components/SidebarEditor/sidebar-editor.scss
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1018 CNV-21086: Replace 'Not migratable' badge with label
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.tsx
  src/views/virtualmachines/list/components/VirtualMachineStatus/VirtualMachineStatus.tsx
Labels: lgtm, approved

#1023 CNV-23377: Create 'Select Bootable Image' section
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/shared.ts
  src/utils/resources/template/utils/constants.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.scss
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/BootableVolumeList/components/ShowAllBootableVolumesButton/ShowAllBootableVolumesButton.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeFilters.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/BootableVolumeList/utils/utils.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
  src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts
Labels: lgtm, approved

#1021 CNV-23379: Create Select InstanceTypes section
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.scss
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/CategoryCard/CategoryCard.scss
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/CategoryCard/CategoryCard.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/InstanceTypesMenu/InstanceTypesMenu.scss
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/InstanceTypesMenu/InstanceTypesMenu.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/InstanceTypesMenu/components/CustomMenu.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/InstanceTypesMenu/components/CustomMenuRenderer.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/InstanceTypesMenu/components/CustomToggle.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/InstanceTypesMenu/components/EnhancedMenuToggle.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/types.ts
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/utils.ts
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/CreateFromInstanceType.tsx
Labels: lgtm, approved

#1024 Moving 'CreateFromInstanceType' dir under catalog
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelectName.tsx
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.scss
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/FilterSelect/FilterSelect.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/FilterSelect/components/FilterSelectOption/FilterSelectOption.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/FormSelectionRadio/FormSelectionRadio.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.scss
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/ShowAllBootableVolumesButton/ShowAllBootableVolumesButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeFilters.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.scss
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SectionListItem/SectionListItem.tsx
  src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
  src/views/catalog/CreateFromInstanceTypes/hooks/useInstanceTypesAndPreferences.ts
  src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
  src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
  src/views/catalog/CreateVMHorizontalNav/components/CreateFromInstanceTypes/components/AddBootableVolumeButton/components/AddBootableVolumeModal/components/FilterSelect/components/FilterSelectOption/FilterSelectOption.tsx
Labels: lgtm, approved

#1025 Introduce VM create with instance type and preference
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.tsx
  src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
  src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
  src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.scss
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
Labels: lgtm, approved

#1026 CNV-23381: Make necessary changes to VM details tabs
  src/utils/resources/vm/utils/disk/rowData.ts
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGrid.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRowActions.tsx
  src/views/virtualmachines/details/tabs/disk/tables/disk/utils/getEditDiskStates.ts
Labels: lgtm, approved

#1027 Add VirtualMachine Details section to Instancetypes tab
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/CategoryCard/CategoryCard.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/category-card/components/InstanceTypesMenu/InstanceTypesMenu.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/types.ts
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.scss
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/VMDetailsBody.scss
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/VMDetailsBody.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsLeftGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsRightGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
Labels: lgtm, approved

#1029 Change namespace to default when All namespaces is selected
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
Labels: lgtm, approved

#1028 Add SSH section to VM Details section of Instancetypes tab
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/SSHKeySection.scss
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/SSHKeySection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/utils/types.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved

#1030 Bug 2150832: Fix vCPU query in cluster overview metrics card
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/metricQueries.ts
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1031 CNV-21086: Remove Live migratable from VM Details
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
Labels: lgtm, approved

#1022 Adding the option to start console locally in auth mode
  .gitignore
  oc-manifest.yaml
  scripts/oauth-client.yaml
  start-console-auth-mode.sh
Labels: lgtm, approved
