Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2023-05, with the labels that each got.

#1283 CNV-28334: Adding ability to user settings column management
  src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
  src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettingsTableColumns.ts
  src/utils/hooks/useKubevirtUserSettings/utils/userSettingsInitialState.ts
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved

#1285 Fix i18n script
  i18n-scripts/build-i18n.sh
  i18next-parser.config.js
  package.json
Labels: lgtm, approved

#1277 Bug 2189744: no docker prefix for container image
  src/views/catalog/customize/cd.ts
  src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/customize/components/CustomizeSource/BootCDCheckboxLabel.tsx
  src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
  src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
  src/views/catalog/customize/components/CustomizeSource/utils.ts
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1286 CNV-28334: Adding ability to user settings column managment - part 2
  src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettingsTableColumns.ts
  src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/hooks/useVirtualMachineInstanceMigrationsColumns.ts
  src/views/datasources/list/hooks/useDataSourcesColumns.ts
  src/views/instancetypes/list/hooks/useClusterInstancetypeListColumns.ts
  src/views/migrationpolicies/list/hooks/useMigrationPoliciesListColumns.ts
  src/views/preferences/list/hooks/useClusterPreferenceListColumns.ts
  src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
  src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticConditionsTableColumns.ts
  src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticVolumeStatusTableColumns.ts
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved

#1224 Bug 2182938: clone revisions alongside vm
  src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
  src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1279 Bug 2182172: Add alert for clound init and ssh auth keys
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AlertScripts/AlertScripts.tsx
  src/utils/components/AlertScripts/index.tsx
  src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1284 Add global state to VM create with IT
  package.json
  src/utils/components/SSHSecretSection/SSHSecretSection.tsx
  src/utils/components/SSHSecretSection/components/SSHKeyUpload/SSHKeyUpload.scss
  src/utils/components/SSHSecretSection/components/SSHKeyUpload/SSHKeyUpload.tsx
  src/utils/components/SSHSecretSection/components/SecretDropdown/SecretDropdown.tsx
  src/utils/components/SSHSecretSection/components/SecretSelectionRadioGroup.tsx
  src/utils/resources/shared.ts
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/ShowAllBootableVolumesButton/ShowAllBootableVolumesButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeFilters.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/SSHKeySection.scss
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/SSHKeySection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/utils/types.ts
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/VMDetailsBody.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsLeftGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsRightGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/state/hooks/useBootableVolumes.ts
  src/views/catalog/CreateFromInstanceTypes/state/hooks/useInstanceTypeVMInitialStore.ts
  src/views/catalog/CreateFromInstanceTypes/state/hooks/useInstanceTypesAndPreferences.ts
  src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
  src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
  src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
  src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/utils/types.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
  yarn.lock
Labels: lgtm, approved

#1288 CNV-28335: Connecting top consumer cards to persistent user settings
  src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
  src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettingsTopConsumerCards.ts
  src/utils/hooks/useKubevirtUserSettings/utils/const.ts
  src/utils/hooks/useKubevirtUserSettings/utils/types.ts
  src/utils/hooks/useKubevirtUserSettings/utils/utils.ts
  src/utils/hooks/useLocalStorage.ts
  src/views/clusteroverview/TopConsumersTab/TopConsumersTab.tsx
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumerCard.tsx
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumersChartList.tsx
  src/views/clusteroverview/TopConsumersTab/utils/TopConsumersGridRow.tsx
Labels: lgtm, approved

#1287 Bug 2181920: Display "UEFI" for Boot mode for "efi: {}" in yaml
  cypress/utils/const/index.ts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
  src/utils/components/FirmwareBootloaderModal/utils/constants.ts
  src/utils/components/FirmwareBootloaderModal/utils/types.ts
  src/utils/components/FirmwareBootloaderModal/utils/utils.ts
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
  src/views/templates/details/tabs/details/components/BootMethod/BootMethod.tsx
  src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#1292 Bug 2188502: Move SSH section to VM details on instancetype page
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SSHSecretSection/SSHSecretModal.tsx
  src/utils/components/SSHSecretSection/SSHSecretSection.scss
  src/utils/components/SSHSecretSection/SSHSecretSection.tsx
  src/utils/components/SSHSecretSection/components/SSHKeyUpload/SSHKeyUpload.scss
  src/utils/components/SSHSecretSection/components/SSHKeyUpload/SSHKeyUpload.tsx
  src/utils/components/SSHSecretSection/components/SecretDropdown/SecretDropdown.tsx
  src/utils/components/SSHSecretSection/components/SecretSelectionRadioGroup.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.scss
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsLeftGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsRightGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/VMDetailsBody.scss
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/VMDetailsBody.tsx
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1295 CNV-27319: Add pagination to IT and Pref list views
  src/utils/hooks/usePagination/usePagination.ts
  src/utils/hooks/usePagination/utils/constants.ts
  src/utils/hooks/usePagination/utils/types.ts
  src/utils/styles/list-managment-group.scss
  src/utils/utils/utils.ts
  src/views/bootablevolumes/list/BootableVolumesList.scss
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/state/hooks/useInstanceTypeVMInitialStore.ts
  src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
  src/views/catalog/CreateFromInstanceTypes/state/utils/utils.ts
  src/views/instancetypes/list/ClusterInstancetypeList.tsx
  src/views/instancetypes/list/hooks/useClusterInstancetypeListColumns.ts
  src/views/preferences/list/ClusterPreferenceList.tsx
  src/views/preferences/list/hooks/useClusterPreferenceListColumns.ts
  src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabConditions.tsx
  src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabVolumeStatus.tsx
  src/views/virtualmachines/list/VirtualMachinesList.scss
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/list/hooks/utils/utils.ts
  src/views/virtualmachines/utils/constants.ts
Labels: lgtm, approved

#1289 CNV-27313: create VMs from custom instancetypes and preferences - part 1
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
  src/utils/resources/template/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/VolumeMetadata.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/InstanceTypeDrilldownSelect.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/ComposableDrilldownSelect/ComposableDrilldownSelect.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/ComposableDrilldownSelect/hooks/useClickOutside.ts
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/DrilldownMenuItem/DrilldownMenuItem.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/RedHatInstanceTypeSeriesMenu/RedHatInstanceTypeSeriesMenu.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/RedHatInstanceTypeSeriesMenu/RedHatInstanceTypeSeriesSizesMenuItem.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/SelectInstanceTypeToggle/SelectInstanceTypeToggle.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/UserInstanceTypeMenu/UserInstanceTypeMenu.tsx
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/types.ts
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeSelect/InstanceTypeSelect.tsx
Labels: lgtm, approved

#1275 Bug 2172390: Enable CPU, Memory editing in the drawer
  src/utils/components/CPUMemory/CPUMemory.tsx
  src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
  src/utils/components/VirtualMachineDescriptionItem/EditButtonWithTooltip.tsx
  src/utils/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.scss
  src/utils/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsLeftGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsRightGrid.tsx
  src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateExpandableDescription.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawer.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
  src/views/catalog/templatescatalog/utils/helpers.ts
  src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
  src/views/virtualmachines/actions/components/CloneVMModal/components/ConfigurationSummary.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/VirtualMachineSchedulingRightGrid.tsx
  src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1299 Bug 2196765: Sort project names in Clone VM modal
  src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
  src/views/virtualmachines/actions/components/CloneVMModal/hooks/useCloneVMResources.tsx
Labels: lgtm, approved, bugzilla/severity-medium, bugzilla/valid-bug

#1302 CNV-16349: Adding Force stop action
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/StopVMModal/StopVMModal.tsx
  src/views/virtualmachines/actions/components/StopVMModal/constants.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
Labels: lgtm, approved

#1303 Bug 2207916: Change button text to 'Select' in 'Available volumes' modal
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
Labels: lgtm, approved

#1307 Fix memory metric query
  src/utils/components/Charts/utils/queries.ts
Labels: lgtm, approved

#1308 Fix memory usage metric query
  src/utils/components/Charts/utils/queries.ts
Labels: lgtm, approved

#1298 CNV-23128: Add OpenShift Virtualization Welcome modal
  images/openCulture.svg
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/ClusterOverviewPage.tsx
  src/views/welcome/WelcomeModal.scss
  src/views/welcome/WelcomeModal.tsx
  src/views/welcome/components/WelcomeButtons.tsx
  src/views/welcome/utils/constants.ts
  src/views/welcome/utils/types.ts
  src/views/welcome/utils/utils.ts
Labels: lgtm, approved

#1306 CNV-27319: Add clone action and provider label for IT and prefs
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloneResourceModal/CloneResourceModal.tsx
  src/utils/components/RedHatLabel/RedHatLabel.tsx
  src/views/instancetypes/actions/hooks/useClusterInstancetypeActionsProvider.tsx
  src/views/instancetypes/list/components/ClusterInstancetypeRow.tsx
  src/views/preferences/actions/hooks/useClusterPreferenceActionsProvider.tsx
  src/views/preferences/list/components/ClusterPreferenceRow.tsx
Labels: lgtm, approved

#1317 CNV-29220: Remove VM's access credentials if ssh is not configured
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved

#1313 Show running networks when VMI exists
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx
Labels: lgtm, approved

#1311 Bug 2203187: Make adding disk by cloning PVC work
  src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelect.tsx
  src/utils/utils/units.ts
  src/views/catalog/utils/quantity.ts
Labels: lgtm, approved

#1318 Bug 2189312: Add missing titles to Templates tabs
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/details/TemplateDetailsPage.scss
  src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
  src/views/templates/details/tabs/disks/TemplateDisksPage.scss
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/network/template-network-tab.scss
  src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
  src/views/templates/details/tabs/parameters/template-parameters-page.scss
  src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.scss
  src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
  src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
  src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
  src/views/templates/details/tabs/scripts/components/SysPrepItem/SysPrepItem.tsx
  src/views/templates/details/tabs/scripts/template-scripts-tab.scss
Labels: lgtm, approved
