Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2024-11, with the labels that each got.

#2241 CNV-50471: show/hide namespace bootablevolume column
  src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
  src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
Labels: lgtm, approved, jira/valid-reference

#2244 CNV-47149: Update webpack and dynamic plugin packages
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2246 CNV-36070: Storageclass migration select volumes
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/migrate/VirtualMachineMigration.tsx
  src/views/virtualmachines/migrate/tabs/VirtualMachineMigrationDetails.tsx
  src/views/virtualmachines/migrate/tabs/components/SelectMigrationDisksTable.tsx
  src/views/virtualmachines/migrate/tabs/components/constants.ts
  src/views/virtualmachines/migrate/tabs/components/utils.ts
  src/views/virtualmachines/migrate/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2249 CNV-50786: fix accessReview on migration action
  src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
Labels: lgtm, approved, jira/valid-reference

#2250 CNV-48466: Removing console title
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
  src/views/virtualmachines/details/tabs/console/components/VirtualMachineConsolePageTitle.scss
  src/views/virtualmachines/details/tabs/console/components/VirtualMachineConsolePageTitle.tsx
Labels: lgtm, approved, jira/valid-reference

#2251 CNV-50293: fix icon button actions disabled when should not
  src/views/virtualmachines/actions/components/VMActionsIconBar/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2252 CNV-50567: fix diskmodal hotplugging a containerdisk
  src/utils/components/DiskModal/utils/submit.ts
Labels: lgtm, approved, jira/valid-reference

#2245 CNV-46447: Export modal part 1
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ExportModal/ExportModal.tsx
  src/utils/components/ExportModal/constants.ts
  src/utils/components/ExportModal/utils.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2242 CNV-48279: Create bootable volume from disk
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AddBootableVolumeModal/utils/constants.ts
  src/utils/components/AddBootableVolumeModal/utils/utils.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/CreateBootableVolumeModal.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2240 CNV-43052: Select multiple vms at a time
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/ActionsDropdown/ActionsDropdown.tsx
  src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.ts
  src/views/virtualmachines/list/VirtualMachinesList.scss
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineActionButton.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/selectedVMs.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2262 CNV-51085: add data key to user settings configmap if no data
  src/utils/hooks/useKubevirtUserSettings/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2263 refactor download virtctl tool if needed
  deploy-kubevirt-gating.sh
Labels: lgtm, approved, ok-to-test

#2268 Unset KUBERNETES_* vars
  test-prow-e2e.sh
Labels: lgtm, approved, ok-to-test

#2270 CNV-50655: fix useComputed is not updated properly
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved, jira/valid-reference

#2264 CNV-46447: do not add securty context
  src/utils/components/ExportModal/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2265 update cypress version to 13
  cypress/cypress.config.js
  cypress/cypress.json
  cypress/support/index.ts
  cypress/tests/catalog/create-vm-from-catalog.cy.ts
  cypress/tests/catalog/filter.cy.ts
  cypress/tests/check-tabs.cy.ts
  cypress/tests/inclusive-language.spec.ts
  cypress/tests/overview.cy.ts
  cypress/views/vm.ts
  package.json
  yarn.lock
Labels: lgtm, approved

#2273 CNV-49651: put a default disk size if user have no access to the pvcs
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DiskSize.tsx
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2274 CNV-51122: fix cloud init default name
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2267 CNV-36070: Switch storage migration from fullpage to modall
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/StateHandler/StateHandler.tsx
  src/utils/resources/vm/hooks/disk/useDisksSources.ts
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationDestinationTab.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationDetails.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationReviewTab.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/components/SelectMigrationDisksTable.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/components/constants.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/components/utils.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/virtual-machine-migration-modal.scss
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/extensions.ts
  src/views/virtualmachines/migrate/VirtualMachineMigration.tsx
Labels: lgtm, approved, jira/valid-reference

#2272 CNV-46447: We don't want to upload the disk to registry anymore
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2277 CNV-41812: Add uncategorized VMs option to the VirtualMachines per resource char…
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/OverviewTab/vms-per-resource-card/RunningVMsChartLegendLabel.tsx
  src/views/clusteroverview/OverviewTab/vms-per-resource-card/utils/constants.ts
  src/views/clusteroverview/OverviewTab/vms-per-resource-card/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2279 CNV-51588: Fix network selection behavior change in Add network interface modal
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
Labels: lgtm, approved, jira/valid-reference

#2280 CNV-50957: make disk persistent after hotplug
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/MakePersistentModal.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2281 CNV-51418: disable delete on running vm
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
Labels: lgtm, approved, jira/valid-reference

#2248 CNV-45822: Tree view part 1
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/tree/VirtualMachineTreeView.scss
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
  src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
  src/views/virtualmachines/tree/hooks/useHideNamespaceBar.ts
  src/views/virtualmachines/tree/hooks/useSyncClicksEffects.ts
  src/views/virtualmachines/tree/hooks/useTreeViewData.ts
  src/views/virtualmachines/tree/hooks/useTreeViewSearch.ts
  src/views/virtualmachines/tree/icons/PausedVirtualMachineIcon.tsx
  src/views/virtualmachines/tree/icons/RunningVirtualMachineIcon.tsx
  src/views/virtualmachines/tree/icons/StoppedVirtualMachineIcon.tsx
  src/views/virtualmachines/tree/icons/utils.ts
  src/views/virtualmachines/tree/utils/constants.ts
  src/views/virtualmachines/tree/utils/utils.tsx
Labels: lgtm, approved, jira/valid-reference

#2286 CNV-50655: fix VirtualMachineList columns width with checkbox
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved, jira/valid-reference

#2284 CNV-46447: progress steps for upload to registry modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ExportModal/ExportModal.tsx
  src/utils/components/ExportModal/ShowProgress.tsx
  src/utils/components/ExportModal/ViewPodLogLink.tsx
  src/utils/components/ExportModal/constants.ts
  src/utils/components/ExportModal/export-modal.scss
  src/utils/components/ExportModal/utils.ts
  src/utils/components/TabModal/TabModal.scss
  src/utils/components/TabModal/TabModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2287 CNV-39556: Fix pending changes message for hot-plug NIC
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/LiveMigratePendingChanges.tsx
Labels: lgtm, approved, jira/valid-reference

#2283 CNV-50655: hide nonsense actions
  src/views/virtualmachines/actions/hooks/constants.ts
  src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.ts
Labels: lgtm, approved

#2271 CNV-41403: resolve disk list flickering loading
  src/utils/components/WindowsDrivers/WindowsDrivers.tsx
  src/utils/components/WindowsDrivers/drivers.ts
  src/utils/components/WindowsDrivers/utils.ts
  src/utils/store/drivers.ts
Labels: lgtm, approved, jira/valid-reference

#2282 CNV-45822: Vm tree view 2
  locales/en/plugin__kubevirt-plugin.json
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusesCard.tsx
  src/views/clusteroverview/OverviewTab/vm-statuses-card/utils/utils.ts
  src/views/virtualmachines/list/VirtualMachinesList.scss
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.scss
  src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.tsx
  tsconfig.json
Labels: lgtm, approved, jira/valid-reference
