Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2024-10, with the labels that each got.

#2208 OCPONZ-4464: docker image support for s390x
  .github/workflows/deploy.yml
Labels: lgtm, approved, ok-to-test

#2209 CNV-48180: edit rootdisk causes VM create to fail
  src/utils/components/DiskModal/utils/helpers.ts
Labels: lgtm, approved, jira/valid-reference

#2200 CNV-43785: fix quickstart links using new sdk
  package.json
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumesPipelinesHint/QuickStartLauncherLink/QuickStartLauncherLink.tsx
  src/views/clusteroverview/OverviewTab/getting-started-card/quick-starts-section/QuickStartsSection.tsx
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2211 CNV-49374: Fix bootloader efi and bios
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2212 [release-4.17] CNV-49374: Fix bootloader efi and bios
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2216 [release-4.15] CNV-46751: Prevent deletion of pod network on Instancetype VM
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2220 CNV-49577: nodeSelector and tolerations edit shows alert
  src/utils/components/NodeSelectorModal/NodeSelectorModal.tsx
  src/utils/components/TolerationsModal/TolerationsModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2218 CNV-47477: fix switching project from all-namespaces
  src/views/instancetypes/list/InstanceTypePage.tsx
  src/views/preferences/list/PreferencePage.tsx
Labels: lgtm, approved, jira/valid-reference

#2221 CNV-41403: localize loading
  src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentEditor.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentSelectResource.tsx
  src/utils/resources/vm/hooks/disk/useDisksSources.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskList.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2201 CNV-48184: Snapshot are automatically deleted when their original vm is deleted
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/components/DeleteOwnedResourcesMessage.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/components/DeleteResourceCheckbox.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/components/DeleteVolumeCheckbox.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/utils/helpers.ts
Labels: lgtm, approved, jira/valid-reference

#2228 Fix nginx config for okd installation
  default.conf
Labels: lgtm, approved

#2227 Make kubevirt works with okd
  src/utils/hooks/useFeatures/constants.ts
  src/utils/hooks/useFeatures/useFeatures.ts
  src/utils/hooks/useFeatures/useFeaturesConfigMap.ts
  src/utils/hooks/useKubevirtHyperconvergeConfiguration.ts/index.ts
  src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
  src/utils/hooks/useKubevirtUserSettings/utils/const.ts
  src/utils/utils/utils.ts
  src/views/clusteroverview/utils/constants.ts
  src/views/clusteroverview/utils/hooks/useKubevirtCSVDetails.ts
Labels: lgtm, approved

#2229 CNV-45435: Migrate all `.spec.running` usages to `.spec.runStrategy`
  src/utils/components/CloneVMModal/utils/helpers.tsx
  src/utils/components/EnvironmentEditor/tests/mocks.ts
  src/utils/components/GuidedTour/utils/constants.tsx
  src/utils/constants/constants.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useDrawerContext.tsx
  src/views/catalog/wizard/components/WizardFooter.tsx
  src/views/virtualmachines/actions/tests/mocks.ts
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2223 CNV-49347: snapshot upgrade to v1beta1
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2222 CNV-49906: fix docker image builder
  Dockerfile
Labels: lgtm, approved, jira/valid-reference

#2217 CNV-49299: use runStrategy on cloning
  src/utils/components/CloneVMModal/CloneVMModal.tsx
  src/utils/components/CloneVMModal/utils/helpers.tsx
Labels: lgtm, approved, jira/valid-reference

#2231 CNV-36070: Create initial migration interface
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
  src/utils/components/ActionDropdownItem/action-dropdown-item.scss
  src/utils/components/ActionsDropdown/ActionsDropdown.tsx
  src/utils/components/ActionsDropdown/constants.ts
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/VirtualMachineActions/VirtualMachineActions.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
  src/views/virtualmachines/extensions.ts
  src/views/virtualmachines/migrate/VirtualMachineMigration.tsx
  src/views/virtualmachines/migrate/tabs/VirtualMachineMigrationDestinationTab.tsx
  src/views/virtualmachines/migrate/tabs/VirtualMachineMigrationReviewTab.tsx
  src/views/virtualmachines/migrate/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2233 CNV-48466: Changing apperance of console - part 1
  src/utils/components/Consoles/ConsoleStandAlone.tsx
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/utils/accessConsoles.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
  src/utils/components/Consoles/components/DesktopViewer/utils/types.ts
  src/utils/components/Consoles/components/utils/ConsoleConsts.ts
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsoleActions.tsx
  src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
  src/utils/components/Consoles/components/vnc-console/vnc-console.scss
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
Labels: lgtm, approved, jira/valid-reference

#2230 CNV-48562: select nads with typing
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
  src/utils/components/NetworkInterfaceModal/utils/helpers.ts
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
  src/utils/components/SelectTypeahead/Toggle.tsx
  src/utils/components/SelectTypeahead/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2235 CNV-48466: Changing apperance of console - part 2
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/ConsoleStandAlone.tsx
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/access-consoles.scss
  src/utils/components/Consoles/components/AccessConsoles/utils/accessConsoles.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/cloud-init-credentials.scss
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsoleActions.tsx
  src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
  src/utils/components/Consoles/components/vnc-console/vnc-console.scss
  src/utils/components/Consoles/consoles.scss
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.scss
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
Labels: lgtm, approved, jira/valid-reference

#2236 Build plugin on arm64
  .github/workflows/deploy.yml
Labels: lgtm, approved

#2237 CNV-49382: page goes blank while detaching cloudinit disk (RHEL VM) or driver disk from Windows VM
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/hooks/useVolumeOwnedResource.tsx
Labels: lgtm, approved, jira/valid-reference

#2238 CNV-48466: Changing apperance of console - part 3
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/utils/accessConsoles.tsx
  src/utils/components/Consoles/components/SerialConsole/SerialConsole.scss
  src/utils/components/Consoles/components/SerialConsole/SerialConsole.tsx
  src/utils/components/Consoles/components/SerialConsole/SerialConsoleActions.tsx
  src/utils/components/Consoles/components/SerialConsole/SerialConsoleConnector.tsx
  src/utils/components/Consoles/components/SerialConsole/utils/serialConsole.ts
  src/utils/components/Consoles/components/utils/ConsoleConsts.ts
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/consoles.scss
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.scss
  src/views/virtualmachines/details/virtual-machine-page.scss
Labels: lgtm, approved, jira/valid-reference

#2239 CNV-49872: Upgrade quickstart pkg
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference
