Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2024-09, with the labels that each got.

#2148 CNV-46660: enable disk delete on running vm
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/DeleteDiskModal.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2132 CNV-45860: Deprecate CentOS 7 and CentOS Stream 8
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ExpandSectionWithSwitch/ExpandSectionWithSwitch.tsx
  src/utils/components/SectionWithSwitch/SectionWithSwitch.tsx
  src/utils/components/badges/DeprecatedBadge/DeprecatedBadge.scss
  src/utils/components/badges/DeprecatedBadge/DeprecatedBadge.tsx
  src/utils/components/badges/NewBadge/NewBadge.tsx
  src/utils/components/badges/NewBadge/new-badge.scss
  src/utils/components/badges/PendingBadge/PendingBadge.scss
  src/utils/components/badges/PendingBadge/PendingBadge.tsx
  src/utils/resources/bootableresources/constants.ts
  src/utils/resources/bootableresources/helpers.ts
  src/views/bootablevolumes/list/components/BootableVolumesRow.scss
  src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
  src/views/bootablevolumes/list/hooks/useBootableVolumesFilters.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.scss
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeFilters.ts
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/TemplatesCatalogFilters.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/catalog/templatescatalog/utils/consts.ts
  src/views/catalog/templatescatalog/utils/helpers.ts
  src/views/catalog/templatescatalog/utils/types.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/GuestSystemLogsAccess/GuestSystemLogsAccess.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/AutoComputeCPULimits.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/KernelSamepageMerging/KernelSamepageMerging.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2149 CNV-46825: Editing Instancetype series and size
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CPUMemoryModal/components/CPUInput/components/CPUTopologyInput/components/TotalCPUHelperText/CPUTopologyHelperText.tsx
  src/utils/components/InstanceTypeModal/InstanceTypeModal.tsx
  src/utils/components/InstanceTypeModal/utils/types.ts
  src/utils/components/InstanceTypeModal/utils/util.ts
  src/utils/components/TabModal/TabModal.tsx
  src/utils/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
  src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/configuration/details/DetailsTab.tsx
  src/views/virtualmachines/details/tabs/configuration/details/utils/utils.ts
  src/views/virtualmachines/details/tabs/configuration/utils/types.ts
  start-console.sh
Labels: lgtm, approved, jira/valid-reference

#2150 CNV-45441: New VM template: Use `runStrategy` field instead of deprecated `running`
  src/templates/vm-template-yaml.ts
  src/templates/vm-yaml.ts
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2151 CNV-43592: Preference dropdown in 'Add volume' has no grouping for user/RH preferences
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/utils/utils.ts
  src/utils/components/FilterSelect/InlineFilterSelect.tsx
  src/utils/components/FilterSelect/components/InlineFilterSelectOption.tsx
  src/utils/components/FilterSelect/components/InlineFilterSelectOptionContent.tsx
  src/utils/components/FilterSelect/components/InlineFilterSelectOptions.tsx
  src/utils/components/FilterSelect/utils/types.ts
  src/utils/components/FilterSelect/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2152 CNV-47576: Headless service already exisit error message
  src/utils/utils/headless-service.ts
Labels: lgtm, approved, jira/valid-reference

#2154 CNV-47244: Missing try catch for storage checkups
  src/views/checkups/storage/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2153 Bump plugin metadata version to 4.17
  plugin-metadata.ts
Labels: lgtm, approved

#2155 CNV-47511: Editing NIC in UI uses wrong binding and does not allow changing MAC
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
Labels: lgtm, approved, jira/valid-reference

#2156 CNV-47590: Fix rhel registration apperance
  locales/en/plugin__kubevirt-plugin.json
  src/utils/hooks/useRHELAutomaticSubscription/utils/types.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionForm/AutomaticSubscriptionForm.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionType/AutomaticSubscriptionType.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionType/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2159 CNV-47104: Fix typo restore
  src/views/virtualmachines/details/tabs/snapshots/utils/helpers.ts
Labels: lgtm, approved, jira/valid-reference

#2163 CNV-46396: fix metrics order
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2162 CNV-46751: Prevent deletion of pod network on Instancetype VM
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2157 CNV-47229: Move the config of registry together in the add volume modal
  src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2165 [Snyk] Security upgrade @patternfly/quickstarts from 5.1.0 to 5.4.0
  package.json
  yarn.lock
Labels: lgtm, approved

#2166 CNV-48259: CNV-44365: fix additional design changes
  src/perspective/extensions.ts
  src/perspective/perspective.ts
  src/perspective/virtualization-icon.tsx
Labels: lgtm, approved, jira/valid-reference

#2169 CNV-48154: Namespace in bootable volume list
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
Labels: lgtm, approved, jira/valid-reference

#2170 CNV-48097: Fix tabs styling to match
  src/utils/styles/ListPageCreateButton.scss
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/disks/wizard-disk-tab.scss
  src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
  src/views/catalog/wizard/tabs/network/wizard-network-tab.scss
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/templates/details/tabs/network/template-network-tab.scss
  src/views/virtualmachines/details/tabs/configuration/network/NetworkTab.tsx
Labels: lgtm, approved, jira/valid-reference

#2167 CNV-43594: Fix bootable incloning
  src/utils/resources/bootableresources/helpers.ts
  src/utils/resources/bootableresources/hooks/useBootableVolumes.ts
  src/utils/resources/shared.ts
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
  src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
Labels: lgtm, approved, jira/valid-reference

#2174 CNV-42324: SC select is showing cluster default instead of virt default
  src/utils/components/DiskModal/DiskFormFields/StorageClass/StorageClassSelect.tsx
  src/utils/hooks/useDefaultStorage/useDefaultStorageClass.ts
Labels: lgtm, approved, jira/valid-reference

#2175 CNV-46660: show disk pvc not the original source
  src/utils/resources/vm/hooks/disk/useDisksSources.ts
  src/utils/resources/vm/hooks/disk/useDisksTableData.ts
  src/utils/resources/vm/hooks/disk/utils.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2176 CNV-47176: Disable start/pause/stop vm while snapshotting or restoring
  src/utils/resources/shared.ts
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/VMActionsIconBar/utils/utils.ts
  src/views/virtualmachines/utils/virtualMachineStatuses.ts
Labels: lgtm, approved, jira/valid-reference

#2179 CNV-48521: Remove default SATA from rootDisk - iso flow
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2177 CNV-47291: public ssh key credential does not get created
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
Labels: lgtm, approved, jira/valid-reference

#2158 CNV-45860: Select 'Hide deprecated bootable volume' filter by default
  cypress/tests/catalog/filter.spec.ts
  cypress/views/catalog.ts
  src/utils/resources/bootableresources/constants.ts
  src/utils/resources/bootableresources/hooks/useHideDeprecatedBootableVolumes.ts
  src/utils/resources/template/utils/constants.ts
  src/views/bootablevolumes/list/BootableVolumesList.tsx
  src/views/bootablevolumes/list/hooks/useBootableVolumesFilters.ts
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeFilters.ts
  src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
  src/views/catalog/templatescatalog/TemplatesCatalog.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/TemplatesCatalogFilters.tsx
  src/views/catalog/templatescatalog/hooks/useHideDeprecatedTemplateTiles.ts
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/templates/list/VirtualMachineTemplatesList.tsx
  src/views/templates/list/hooks/useHideDeprecatedTemplates.ts
  src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts
Labels: lgtm, approved, jira/valid-reference

#2183 CNV-41496: Change template details CPU/memory modal to new design
  src/utils/components/CPUMemoryModal/CPUMemoryModal.tsx
  src/utils/components/CPUMemoryModal/components/CPUInput/CPUInput.tsx
  src/utils/components/CPUMemoryModal/components/CPUInput/components/vCPUInput/components/CPUHelperText/CPUHelperText.tsx
  src/views/templates/details/tabs/details/components/CPUMemory.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal/CPUMemoryModal.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2186 CNV-48451: Windows autoattend.xml can not be created as a regular user
  src/utils/components/SysprepModal/hooks/useConfigMaps.ts
Labels: lgtm, approved, jira/valid-reference

#2184 CNV-41496: Update the Templates CPU/memory modal to use sockets
  locales/en/plugin__kubevirt-plugin.json
  src/views/templates/details/tabs/details/components/CPUMemory.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal/CPUMemoryModal.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2185 CNV-44913 missing storage settings on other disk modal
  src/utils/components/DiskModal/OtherDiskModal.tsx
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/resources/vm/utils/disk/rowData.ts
Labels: lgtm, approved

#2187 CNV-46584: Change boot disk size to disk size
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsRightGrid.tsx
Labels: lgtm, approved, jira/valid-reference

#2188 CNV-47153: Add data test ids
  src/utils/components/AddBootableVolumeModal/components/SourceTypeSelection/SourceTypeSelection.tsx
  src/utils/components/toggles/SelectToggle.tsx
Labels: lgtm, approved, jira/valid-reference

#2189 CNV-45249: Fix selecting all projects on bootable volume list IT flow
  src/utils/components/ProjectDropdown/ProjectDropdown.tsx
Labels: lgtm, approved, jira/valid-reference

#2182 CNV-46660: Enable pvc resize on vm disks
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CapacityInput/CapacityInput.tsx
  src/utils/components/DiskModal/BlankDiskModal.tsx
  src/utils/components/DiskModal/ClonePVCDiskModal.tsx
  src/utils/components/DiskModal/ContainerDiskModal.tsx
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/HTTPDiskModal.tsx
  src/utils/components/DiskModal/OtherDiskModal.tsx
  src/utils/components/DiskModal/PVCDiskModal.tsx
  src/utils/components/DiskModal/RegistryDiskModal.tsx
  src/utils/components/DiskModal/UploadDiskModal.tsx
  src/utils/components/DiskModal/VolumeSnapshotDiskModal.tsx
  src/utils/components/DiskModal/components/DiskSizeInput/DiskSizeInput.tsx
  src/utils/components/DiskModal/components/DiskSizeInput/ExpandPVC.tsx
  src/utils/components/DiskModal/components/utils/constants.ts
  src/utils/components/DiskModal/hooks/usePVCDiskSource.tsx
  src/utils/components/DiskModal/utils/submit.ts
  src/utils/components/DiskModal/utils/types.ts
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2191 CNV-43038: Improve sysprep section in quick and customize mode
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SysprepModal/SysprepDescription.tsx
  src/utils/components/SysprepModal/SysprepModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SimplifiedSysprepDescription.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SysprepDescriptionItem.tsx
  src/views/catalog/wizard/tabs/scripts/components/Sysprep.tsx
  src/views/templates/details/tabs/scripts/components/SysPrepItem/SysPrepItem.tsx
  src/views/virtualmachines/details/tabs/configuration/initialrun/components/InitialRunTabSysprep.tsx
Labels: lgtm, approved, jira/valid-reference

#2190 CNV-45815: No volumes found for nonpriv user in All projects
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
Labels: lgtm, approved, jira/valid-reference

#2192 CNV-48314: apply opt storage at beginning
  src/utils/components/DiskModal/utils/form.ts
Labels: lgtm, approved, jira/valid-reference

#2193 CNV-48785: Fix disk size
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2195 CNV-41290: Disable checkups storage install button for non cluster reader
  src/views/checkups/storage/components/hooks/useCheckupsStoragePermissions.ts
  src/views/checkups/storage/list/CheckupsStorageList.tsx
  src/views/checkups/storage/list/CheckupsStorageListEmptyState.tsx
Labels: lgtm, approved, jira/valid-reference

#2196 CNV-48839: fix virt perspective links
  src/perspective/extensions.ts
Labels: lgtm, approved, jira/valid-reference

#2198 CNV-45253: No color in the virtual machine migration graph legend
  src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/MigrationChartLegend.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/MigrationsChartDonut.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2197 CNV-42401: add runcmd if other commands defined
  src/utils/components/CloudinitModal/utils/cloudinit-utils.ts
  src/utils/components/DynamicSSHKeyInjection/DynamicSSHKeyInjection.tsx
  src/utils/components/DynamicSSHKeyInjection/utils.ts
  src/utils/components/SSHSecretModal/utils/constants.ts
  src/utils/components/SSHSecretModal/utils/utils.ts
  src/views/catalog/wizard/tabs/scripts/components/DynamicSSHKeyInjectionWizard.tsx
Labels: lgtm, approved, jira/valid-reference

#2199 CNV-48224: OpenShift Virt doc link needs to be changed in the new Guided Tour
  src/utils/components/GuidedTour/components/EndTourContent/EndTourContent.tsx
Labels: lgtm, approved, jira/valid-reference

#2202 CNV-43588: Start/Restart/Stop icon controls disappear during shutdown
  src/views/virtualmachines/actions/components/VMActionsIconBar/components/ActionIconButton.tsx
  src/views/virtualmachines/actions/components/VMActionsIconBar/utils/types.ts
  src/views/virtualmachines/actions/components/VMActionsIconBar/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2204 CNV-45733: fix metrics yaml
  src/utils/components/Charts/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2205 CNV-49040: Improve check for undefined value
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
Labels: lgtm, approved, jira/valid-reference

#2206 CNV-48195: Fix link operators
  src/views/clusteroverview/OverviewTab/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
Labels: lgtm, approved, jira/valid-reference

#2207 CNV-49306: removeEventLisnter is undefined
  src/utils/components/ListPageFilter/SearchFilter.tsx
Labels: lgtm, approved, jira/valid-reference
