Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2025-09, with the labels that each got.

#2946 CNV-68469: make sure quantityString is optional
  src/utils/utils/units.ts
Labels: lgtm, approved, jira/valid-reference

#2943 CNV-68347: Force re-creating NetworkSelect on network pre-selection
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
Labels: lgtm, approved, jira/valid-reference

#2942 CNV-61453: Use POD_NETWORK constant to detect Pod Network
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceTypeSelect.tsx
  src/utils/components/NetworkInterfaceModal/utils/helpers.tsx
  src/utils/resources/vm/utils/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2955 CNV-68329: Enable focus after pasting values to console
  src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/utils/accessConsoles.tsx
  src/utils/components/Consoles/components/vnc-console/actions.ts
Labels: lgtm, approved, jira/valid-reference

#2956 CNV-68724: fix tree view reloading
  src/utils/hooks/useKubevirtWatchResource/useKubevirtWatchResource.ts
Labels: lgtm, approved, jira/valid-reference

#2944 CNV-48181: fix CPU and memory metrics
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
  src/utils/components/Charts/utils/queries.ts
  src/utils/hooks/useVMQueries.ts
  src/utils/resources/vm/utils/utils.ts
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/metricQueries.ts
  src/views/clusteroverview/TopConsumersTab/utils/queries.ts
  src/views/virtualmachines/details/tabs/metrics/UtilizationCharts/UtilizationCharts.tsx
  src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
  src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/VirtualMachinesOverviewTabUtilization.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/UtilizationThresholdCharts.tsx
  src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
  src/views/virtualmachines/list/hooks/sortColumns.ts
  src/views/virtualmachines/list/hooks/useVMMetrics.ts
  src/views/virtualmachines/list/hooks/useVMTotalsMetrics.ts
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/list/metrics.ts
  src/views/virtualmachines/list/utils/processVMTotalsMetrics.ts
  src/views/virtualmachines/list/utils/totalsQueries.ts
Labels: lgtm, approved, jira/valid-reference

#2957 CNV-68780: fetch NADs from vm cluster
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
  src/utils/components/NetworkInterfaceModal/components/hooks/types.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/useFetchNADs.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/useNADListPermissions.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2940 CNV-68335: fix mappers identifiers by including cluster
  src/utils/hooks/usePVCMapper.ts
  src/utils/resources/constants.ts
  src/utils/resources/shared.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/MemoryPercentage.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/NetworkUsage.tsx
  src/views/virtualmachines/list/hooks/sortColumns.ts
  src/views/virtualmachines/list/hooks/useExistingSelectedVMs.ts
  src/views/virtualmachines/list/hooks/useVMListFilters/useNodesFilter.ts
  src/views/virtualmachines/list/hooks/useVMMetrics.ts
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/list/hooks/useVirtualMachineInstanceMapper.ts
  src/views/virtualmachines/list/metrics.ts
  src/views/virtualmachines/list/selectedVMs.ts
  src/views/virtualmachines/list/utils/filters/getIPFilter.ts
  src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/DefaultRightClickActionMenu.tsx
  src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/VMRightClickActionMenu.tsx
  src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/utils.ts
  src/views/virtualmachines/tree/utils/utils.tsx
  src/views/virtualmachines/utils/mappers.ts
  src/views/virtualmachines/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2958 Bump sdk version for storageclass migration name fix
  package.json
  yarn.lock
Labels: lgtm, approved

#2962 CNV-68829: use namespace and name instead of uid
  src/multicluster/components/CrossClusterMigration/components/ReadinessStep.tsx
Labels: lgtm, approved, jira/valid-reference

#2937 Makes gal approver
  OWNERS
Labels: lgtm, approved

#2970 CNV-69007: fix summary links for all cluster vm list
  src/multicluster/urls.ts
  src/utils/resources/vm/utils/utils.ts
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx
Labels: lgtm, approved, jira/valid-reference

#2966 CNV-68855: fix wizard next button text
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/VirtualizationFeaturesWizard.tsx
Labels: lgtm, approved, jira/valid-reference

#2968 CNV-68934: close menu on clicking outside in Catalog cards
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatProvidedInstanceTypesSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/hooks/useInstanceTypeCardMenuSection.ts
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/types.ts
Labels: lgtm, approved, jira/valid-reference

#2967 CNV-69002: make sure catalog works with all namespaces selected
  src/multicluster/urls.ts
  src/utils/components/SSHSecretModal/components/SSHKeyUpload/SSHKeyUpload.tsx
  src/utils/hooks/useActiveNamespace.ts
  src/utils/resources/vm/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/hooks/useGeneratedVM.ts
Labels: lgtm, approved, jira/valid-reference

#2978 CNV-69369: Fix disabling autoattachPodInterface on deleting Pod Network
  src/utils/components/NetworkInterfaceModal/utils/helpers.tsx
  src/utils/resources/vm/utils/network/selectors.ts
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatProvidedInstanceTypesSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceList.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx
  src/views/virtualmachines/details/tabs/configuration/network/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2988 CNV-63859: Fixing the virtualization perspective route for non-priv users
  plugin-extensions.ts
  plugin-metadata.ts
  src/perspective/VirtualizationLandingPage.tsx
  src/perspective/extensions.ts
  src/perspective/perspective.ts
Labels: lgtm, approved, jira/valid-reference

#2984 CNV-68471: Fixing installation CD-ROM with registry image to allow eject action
  src/utils/resources/vm/utils/disk/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2991 bump multicluster sdk version
  package.json
  yarn.lock
Labels: lgtm, approved

#2997 CNV-69444: Fixing routing to correctly display operators in the software catalog
  src/views/clusteroverview/OverviewTab/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/VirtualizationFeaturesContext/utils/hooks/useVirtualizationFeatures/useVirtualizationFeatures.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/VirtualizationFeaturesContext/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2998 CNV-69687: use state management for setting loadingDriverValue and driverImageValue in useDriversImage
  src/utils/resources/vm/utils/disk/useDriversImage.ts
Labels: lgtm, approved, jira/valid-reference

#2996 CNV-69014: fix multicluster tree view VM links
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
Labels: lgtm, approved, jira/valid-reference

#3004 CNV-69750: Fix cross cluster migration live
  src/multicluster/components/CrossClusterMigration/hooks/useCrossClusterMigrationSubmit.ts
  src/multicluster/components/CrossClusterMigration/hooks/useStorageReadiness.ts
  src/multicluster/components/CrossClusterMigration/hooks/utils.ts
  src/multicluster/components/CrossClusterMigration/types.ts
  src/multicluster/components/CrossClusterMigration/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2987 CNV-69441: infinite loading on vm with preference but no instancetype
  src/utils/components/DiskModal/utils/form.ts
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/resources/instancetype/helper.ts
  src/utils/resources/vm/hooks/useInstanceTypeExpandSpec.ts
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSectionRightGrid.tsx
Labels: lgtm, approved, jira/valid-reference

#3003 CNV-69747: fix multicluster treeview draganddrop
  src/views/virtualmachines/tree/hooks/dragndrop.ts
  src/views/virtualmachines/tree/hooks/useSelectNamespaceBasedOnPrivileges.ts
  src/views/virtualmachines/tree/hooks/utils.ts
Labels: lgtm, approved, jira/valid-reference

#3005 CNV-69308: Adding a CD-ROM drive: hotpluggable should be set to true when DeclarativeHotplugVolumes is enabled
  src/utils/components/DiskModal/AddCDROMModal.tsx
  src/utils/components/DiskModal/utils/constants.ts
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/components/HardwareDevices/hooks/useHCPermittedHostDevices.ts
  src/utils/hooks/useKubevirtHyperconvergeConfiguration.ts/index.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/MountCDROMModal.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2979 CNV-69370: Disable hot-unplug for Pod Networks
  src/utils/components/NetworkInterfaceModal/utils/helpers.tsx
  src/utils/constants/network-columns.tsx
  src/utils/resources/vm/utils/network/network-columns.tsx
  src/utils/resources/vm/utils/network/selectors.ts
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx
Labels: lgtm, approved, jira/valid-reference

#3000 CNV-69306: Disable relevant buttons when uploading a a file in mount / add cd-rom modal
  src/utils/components/DiskModal/AddCDROMModal.tsx
  src/utils/components/DiskModal/components/DiskNameInput/DiskNameInput.tsx
  src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceUploadPVC/DiskSourceUploadPVC.tsx
  src/utils/hooks/useCDIUpload/utils.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/MountCDROMModal.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
Labels: lgtm, approved, jira/valid-reference

#3002 CNV-69219: new translations for 4.20
  i18n-scripts/memsource-download-json.sh
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
Labels: lgtm, approved, jira/valid-reference

#3009 CNV-68860: Add Installing label to virt features wizard summary page
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/VirtualizationFeaturesSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/LoadBalanceSection/LoadBalanceSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/components/SummaryStep/components/SummaryStatusIcon/SummaryStatusIcon.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/components/SummaryStep/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#3008 CNV-69774: Add an oc login script, based on a local.env file
  .dockerignore
  .gitignore
  oc-login-start-console.sh
  package.json
Labels: lgtm, approved, jira/valid-reference

#3017 CNV-69617: fix axios cve
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#3006 CNV-68854: improve expandable sections indentation
  src/utils/components/ExpandSectionWithCustomToggle/ExpandSectionWithCustomToggle.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/GuestSystemLogsAccess/GuestSystemLogsAccess.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/PersistentReservationSection/PersistentReservationSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/AutoComputeCPULimits.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/KernelSamepageMerging/KernelSamepageMerging.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/VirtualizationFeaturesSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/FeaturedOperatorItem.scss
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/FeaturedOperatorItem.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/components/SummaryStep/components/FeatureSummaryItem/FeatureSummaryItem.scss
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/components/SummaryStep/components/HighAvailabilitySection/HighAvailabilitySummarySection.scss
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/components/SummaryStep/components/HighAvailabilitySection/HighAvailabilitySummarySection.tsx
  src/views/clusteroverview/SettingsTab/ExpandSection/ExpandSection.scss
  src/views/clusteroverview/SettingsTab/settings-tab.scss
Labels: lgtm, approved, jira/valid-reference

#3033 CNV-69925: enhance upstream e2e test
  cypress/utils/const/index.ts
  cypress/views/perspective.ts
  test-cypress.sh
  test-prow-e2e.sh
  test-setup.sh
Labels: lgtm, approved, jira/valid-reference

#3034 CNV-69930: update dock link for 4.19
  src/utils/constants/documentation.ts
Labels: lgtm, approved, jira/valid-reference

#3032 CNV-69917 Update to @stolostron/multicluster-sdk@0.7.5
  package.json
  yarn.lock
Labels: lgtm, approved, needs-ok-to-test

#3025 CNV-69840: Search IPv6 addresses by CIDR
  package.json
  src/utils/resources/vmi/utils/ips.ts
  src/utils/utils/utils.ts
  src/views/virtualmachines/utils/utils.ts
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#3031 CNV-69851: Automatically get current version from plugin-metadata
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  plugin-metadata.ts
  src/utils/constants/documentation.ts
  src/views/clusteroverview/OverviewTab/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
Labels: lgtm, approved, jira/valid-reference

#3040 CNV-69947: fix VirtualMachine summary filters not clearing
  src/utils/components/ListPageFilter/components/CheckboxSelectFilter.tsx
  src/utils/components/ListPageFilter/hooks/useAdvancedFiltersParameters.ts
  src/utils/components/ListPageFilter/hooks/useApplyFiltersWithQuery.ts
  src/views/virtualmachines/search/VirtualMachineFilterToolbar.tsx
Labels: lgtm, approved, jira/valid-reference
