Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2025-08, with the labels that each got.

#2857 CNV-65202: Cross cluster migration bulk action
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/multicluster/components/CrossClusterMigration/CrossClusterMigration.tsx
  src/utils/components/ActionDropdownItem/ActionDropdownItem.scss
  src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
  src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2849 Update kubevirt-api to v1.4.0
  package.json
  src/utils/components/HardwareDevices/utils/constants.ts
  yarn.lock
Labels: lgtm, approved

#2673 fix po files for memsource
  i18n-scripts/export-pos.sh
  i18n-scripts/memsource-upload.sh
Labels: lgtm, approved

#2850 CNV-63495: Select target node for VM migration
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/resources/node/utils/selectors.ts
  src/utils/resources/node/utils/types.ts
  src/utils/resources/node/utils/utils.ts
  src/utils/resources/vm/hooks/useNode.ts
  src/utils/resources/vm/hooks/useVMIForVM.ts
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/actions.ts
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/ComputeMigrationModal.scss
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/ComputeMigrationModal.tsx
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/components/FailedMigrationAlert/FailedMigrationAlert.scss
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/components/FailedMigrationAlert/FailedMigrationAlert.tsx
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/components/MigrationOptionRadioGroup.tsx
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/components/NodesTable/NodesTable.scss
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/components/NodesTable/NodesTable.tsx
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/components/NodesTable/components/NodeRow.scss
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/components/NodesTable/components/NodeRow.tsx
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/components/NodesTable/utils/hooks/useNodesColumns.ts
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/components/NodesTable/utils/utils.ts
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/utils/hooks/useNodesData.ts
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/utils/hooks/useNodesMetrics/useNodesMetrics.ts
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/utils/hooks/useNodesMetrics/utils/types.ts
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/utils/hooks/useNodesMetrics/utils/utils.ts
  src/views/virtualmachines/actions/components/VirtualMachineComputeMigration/utils/types.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
Labels: lgtm, approved, jira/valid-reference

#2843 CNV-66455: fix typo of "Edit InstanceType"
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/InstanceTypeModal/InstanceTypeModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2820 CNV-65108: Adding credentials to the add volume modal for registry source type
  src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeSource/components/RegistrySource.tsx
  src/utils/components/AddBootableVolumeModal/utils/constants.ts
  src/utils/components/AddBootableVolumeModal/utils/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/Sources/ContainerSource.tsx
Labels: lgtm, approved, jira/valid-reference

#2571 CNV-56943: Remove pending changes and live reload alerts in add/edit NIC modal
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/BridgedNICHotPlugModalAlert/NICHotPlugModalAlert.tsx
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesNetworkInterfaceModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2869 CNV-52151: add passt interface type
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.scss
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceLinkState/NetworkInterfaceLinkState.scss
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceLinkState/NetworkInterfaceLinkState.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfacePasst.tsx
  src/utils/components/NetworkInterfaceModal/utils/helpers.ts
  src/utils/components/PendingChanges/utils/helpers.ts
  src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
  src/utils/components/SectionWithSwitch/SectionWithSwitch.tsx
  src/utils/hooks/useFeatures/constants.ts
  src/utils/resources/vm/utils/constants.ts
  src/utils/resources/vm/utils/network/constants.ts
  src/utils/resources/vm/utils/network/selectors.ts
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/PasstPopoverContent.tsx
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/PreviewFeaturesTab.tsx
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/constants.ts
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/usePasstFeatureFlag.ts
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/usePreviewFeaturesData.ts
Labels: lgtm, approved, jira/valid-reference

#2852 CNV-66511: move advance search out of gating
  cypress/tests/gating.cy.ts
  cypress/tests/tier1/vm-tab.cy.ts
  cypress/tests/tier1/vm-tabs/vm-adv-search.cy.ts
Labels: lgtm, approved, jira/valid-reference

#2802 CNV-64839: Moving the copy button out of text element making it always visible
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsItem.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/InlineCodeClipboardCopy.tsx
  src/utils/components/Consoles/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2877 CNV-61755: make advanced search feature GA (general availability)
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/hooks/useFeatures/constants.ts
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/usePreviewFeaturesData.ts
  src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
  src/views/virtualmachines/search/VirtualMachineSearchResults.tsx
  src/views/virtualmachines/tree/components/TreeViewContent.tsx
  src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
  src/views/virtualmachines/tree/hooks/useFilteredTreeView.ts
Labels: lgtm, approved, jira/valid-reference

#2885 fixing the tree-view scroll to see all vm's blocked by footer
  src/views/virtualmachines/tree/VirtualMachineTreeView.scss
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
Labels: lgtm, approved

#2888 [release-4.19] CNV-66337: update axios and form-data dependency
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2889 [release-4.18] CNV-66338: update axios and form-data dependency
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2894 CNV-66909: add missing "Actions" text to menu toggle
  src/views/checkups/network/components/CheckupsNetworkActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2893 CNV-67145: Fix migration storage long vm name
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2899 CNV-66657: fix unavailable Guest system log
  src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineLogViewer/VirtualMachineLogViewer.tsx
  src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineLogViewer/constants.ts
  src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineLogViewer/hooks/useVirtualMachineLogData.ts
Labels: lgtm, approved, jira/valid-reference

#2892 CNV-56889: use IPL boot mode for s390x architecture VMs
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
  src/utils/components/FirmwareBootloaderModal/utils/constants.ts
  src/utils/components/FirmwareBootloaderModal/utils/types.ts
  src/utils/components/FirmwareBootloaderModal/utils/utils.ts
  src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2901 CNV-67463: fix "all-namespaces" project showing up in Catalog
  src/multicluster/urls.ts
  src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
Labels: lgtm, approved, jira/valid-reference

#2865 CNV-62538: Hetrogeneous cluster multi-arch
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/VolumeMetadata.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/ArchitectureSelect/ArchitectureSelect.tsx
  src/utils/components/AddBootableVolumeModal/utils/constants.ts
  src/utils/components/AddBootableVolumeModal/utils/utils.ts
  src/utils/components/ArchitectureLabel/ArchitectureLabel.tsx
  src/utils/components/ArchitectureLabel/constants.ts
  src/utils/hooks/useHcoWorkloadArchitectures.ts
  src/utils/hooks/useHyperConvergeConfiguration.ts
  src/utils/utils/architecture.ts
  src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
  src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
  src/views/bootablevolumes/list/hooks/useBootableVolumesFilters.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeFilters.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/TemplatesCatalogFilters.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogRow.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
  src/views/catalog/templatescatalog/hooks/useTemplatesCatalogColumns.ts
  src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
  src/views/catalog/templatescatalog/utils/consts.ts
  src/views/catalog/templatescatalog/utils/helpers.ts
  src/views/catalog/templatescatalog/utils/types.ts
  src/views/catalog/utils/quick-create-vm.ts
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
  src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2910 CNV-66273: create vm from template with ssh
  src/utils/components/VMSSHSecretModal/VMSSHSecretModal.tsx
  src/utils/resources/secret/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/AuthorizedSSHKey.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
  src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
  src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
Labels: lgtm, approved, jira/valid-reference

#2904 CNV-64881: fix link in Pending changes alert
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
  src/utils/components/PendingChanges/utils/types.ts
  src/utils/constants/tabs-constants.ts
  src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/constants.ts
  src/views/catalog/CustomizeInstanceType/utils/constants.ts
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/LiveMigratePendingChanges.tsx
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/RestartPendingChanges.tsx
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
  src/views/virtualmachines/details/tabs/configuration/utils/utils.ts
  src/views/virtualmachines/details/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2915 CNV-67857: PatternFly Chart hover broken due to delaunator package version conflict
  package.json
  yarn.lock
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2922 CNV-61108: Add delete protection to vm creation
  src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeDetailsTab.tsx
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/configuration/details/components/DeletionProtection/DeletionProtectionModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2924 CNV-67816: sort VirtualMachines alphabetically in tree view
  src/views/virtualmachines/tree/hooks/useTreeViewData.ts
Labels: lgtm, approved, jira/valid-reference

#2926 CNV-67816: use natural sort instead of alphabetical
  src/views/virtualmachines/tree/hooks/useTreeViewData.ts
Labels: lgtm, approved, jira/valid-reference

#2905 CNV-52151: Allow changing NIC binding to l2bridge
  src/utils/components/NetworkInterfaceModal/utils/helpers.tsx
Labels: lgtm, approved, jira/valid-reference

#2927 CNV-67947: Detect autoattached Pod Network
  src/utils/components/NetworkInterfaceModal/utils/helpers.tsx
Labels: lgtm, approved, jira/valid-reference

#2925 Disable multicluster feature flag if no fleet available
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/usePreviewFeaturesData.ts
Labels: lgtm, approved

#2928 CNV-68078: Add padding to the bottom of the tree view body
  src/views/virtualmachines/tree/VirtualMachineTreeView.scss
Labels: lgtm, approved, jira/valid-reference

#2914 CNV-58495: Separate detected pending changes from conditions set on the VM
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/tests/nic.test.ts
  src/utils/components/PendingChanges/utils/helpers.ts
  src/utils/components/PendingChanges/utils/types.ts
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/LiveMigratePendingChanges.tsx
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/PendingChanges.tsx
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/RestartPendingChanges.tsx
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/VirtualMachinePendingChangesAlert.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx
  src/views/virtualmachines/details/tabs/configuration/network/utils/utils.ts
  src/views/virtualmachines/details/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2929 CNV-68079: Add run strategy update on start VM checkbox change
  src/views/catalog/CustomizeInstanceType/components/CustomizeITVMFooter.tsx
Labels: lgtm, approved, jira/valid-reference

#2923 ACM resource routes
  package.json
  src/multicluster/constants.ts
  src/multicluster/extensions.ts
  src/multicluster/urls.ts
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  yarn.lock
Labels: lgtm, approved, ok-to-test

#2765 CNV-63729: capacity input fixes
  src/utils/components/AddBootableVolumeModal/components/VolumeSource/components/DiskSourcePVCSelect.tsx
  src/utils/components/CPUMemoryModal/components/MemoryInput/MemoryInput.tsx
  src/utils/components/CapacityInput/CapacityInput.tsx
  src/utils/components/CapacityInput/useUnitOptions.ts
  src/utils/components/CapacityInput/utils.ts
  src/utils/components/DiskModal/HTTPDiskModal.tsx
  src/utils/components/DiskModal/components/DiskSizeInput/DiskSizeInput.tsx
  src/utils/components/DiskModal/components/DiskSizeInput/ExpandPVC.tsx
  src/utils/components/DiskModal/components/DiskSizeInput/usePVCDefaultSize.ts
  src/utils/components/DiskModal/components/DiskSizeInput/usePVCSourceSize.ts
  src/utils/components/DiskModal/components/DiskSizeInput/utils.ts
  src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceClonePVCSelect/DiskSourceClonePVCSelectName.tsx
  src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceSnapshotVolumeSelect/DiskSourceSnapshotVolumeSelectName.tsx
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/resources/vm/utils/disk/size.ts
  src/utils/tests/units.test.ts
  src/utils/types/quantity.ts
  src/utils/utils/humanize.js
  src/utils/utils/unitConstants.ts
  src/utils/utils/units.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DiskSize.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/SelectSource.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/utils.ts
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCForm.tsx
  src/views/cdi-upload-provider/utils/selectors.ts
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/utils.ts
  src/views/migrationpolicies/components/MigrationPolicyConfigurations/compnents/BandwidthInput/BandwidthInput.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurations/utils/utils.ts
  src/views/migrationpolicies/components/MigrationPolicyEditModal/utils/constants.ts
  src/views/migrationpolicies/components/MigrationPolicyEditModal/utils/utils.ts
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/utils/utils.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/CreateBootableVolumeModal.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabFilesystem/VirtualMachinesOverviewTabFilesystemRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2938 CNV-66617: Refactor FQDN generation
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/components/VirtualMachinesOverviewTabNetworkFQDN.tsx
  src/views/virtualmachines/details/tabs/overview/utils/utils.tsx
Labels: lgtm, approved, jira/valid-reference
