Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2025-05, with the labels that each got.

#2617 CNV-60419: Update copy to include Oxford comma on VM Storage tab
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentFormTitle.tsx
Labels: lgtm, approved, jira/valid-reference

#2613 CNV-46341: Use controllerRevisionRef.name for preference and instance type
  src/utils/resources/instancetype/selectors.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/InstanceTypeDescription.tsx
Labels: lgtm, approved, jira/valid-reference

#2615 CNV-60945: Fix add new SSH key by file upload for Templates
  src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
Labels: lgtm, approved, jira/valid-reference

#2619 chore: bump uploader images
  src/utils/components/ExportModal/constants.ts
Labels: lgtm, approved, needs-ok-to-test

#2607 CNV-56585: Change format for Y axis tick based on max value
  src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
  src/utils/components/Charts/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2616 CNV-57803: Fix QuickStart link on the catalog Instance Types page
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/components/CreateFromInstanceTypeTitle/CreateFromInstanceTypeTitle.tsx
Labels: lgtm, approved, jira/valid-reference

#2620 CNV-61011: Remove nncs and nncp virt links and move them in nmstate plugin
  src/perspective/extensions.ts
Labels: lgtm, approved, jira/valid-reference

#2621 [release-4.18] CNV-60605: Fix rerendering all over vm details
  src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
Labels: lgtm, approved, jira/valid-reference

#2585 CNV-58541: use only MTC migrations
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/vm/utils/source.ts
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/actions.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/BulkVirtualMachineMigrationStatus.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationRollback.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationStatus.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/useMigratableStorageClasses.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/useMigrationState.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationDestinationTab.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/components/utils.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils/constants.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils/migrateVM.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils/migrateVMs.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils/utils.ts
  src/views/virtualmachines/actions/hooks/useIsMTCInstalled.ts
  src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.tsx
  src/views/virtualmachines/actions/hooks/useStorageMigrations.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/hooks/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2614 CNV-56688: Avoid CPU helper text error if CPU threads is undefined
  src/utils/components/CPUMemoryModal/components/CPUInput/components/CPUTopologyInput/components/TotalCPUHelperText/CPUTopologyHelperText.tsx
  src/utils/components/CPUMemoryModal/components/CPUInput/utils/utils.ts
  src/utils/resources/template/utils/flavor.ts
Labels: lgtm, approved, jira/valid-reference

#2580 CNV-56264: Advanced search feature preview
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/AddBootableVolumeModal/components/VolumeDestination/StorageClass/StorageClassSelect.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityEditRow.tsx
  src/utils/components/CheckboxSelect/CheckboxSelect.tsx
  src/utils/components/LabelsEditor/LabelsEditor.tsx
  src/utils/components/ListPageFilter/ListPageFilter.tsx
  src/utils/components/ListPageFilter/components/ProjectFilter.tsx
  src/utils/components/ListPageFilter/hooks/useListPageFiltersMethods.ts
  src/utils/components/NumberOperatorSelect/NumberOperatorSelect.tsx
  src/utils/components/NumberOperatorSelect/constants.ts
  src/utils/components/SelectMultiTypeahead/SelectMultiTypeahead.tsx
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
  src/utils/hooks/useFeatures/constants.ts
  src/utils/hooks/useKubevirtUserSettings/utils/types.ts
  src/utils/resources/bootableresources/hooks/useHideDeprecatedBootableVolumes.ts
  src/utils/utils/ObjectEnum.ts
  src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
  src/views/checkups/network/hooks/useCheckupsNetworkFilters.ts
  src/views/checkups/storage/components/hooks/useCheckupsStorageListFilters.ts
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/usePreviewFeaturesData.ts
  src/views/instancetypes/list/hooks/useClusterInstancetypeListColumns.ts
  src/views/search/components/AdvancedSearchModal/AdvancedSearchModal.tsx
  src/views/search/components/AdvancedSearchModal/components/DateFromToPicker.tsx
  src/views/search/components/AdvancedSearchModal/components/LabelsMultiSelect.tsx
  src/views/search/components/AdvancedSearchModal/components/MemoryUnitSelect.tsx
  src/views/search/components/AdvancedSearchModal/components/NumberInput.tsx
  src/views/search/components/AdvancedSearchModal/components/ProjectMultiSelect.tsx
  src/views/search/components/AdvancedSearchModal/constants.ts
  src/views/search/components/SaveSearchModal.tsx
  src/views/search/components/SavedSearchesDropdown.tsx
  src/views/search/components/SearchBar.tsx
  src/views/search/components/SearchSuggestBox/SearchSuggestBox.tsx
  src/views/search/components/SearchSuggestBox/components/RelatedSuggestions.tsx
  src/views/search/components/SearchSuggestBox/components/SearchSuggestBoxFooter.tsx
  src/views/search/components/SearchSuggestBox/components/SearchSuggestBoxHeader.tsx
  src/views/search/components/search-bar.scss
  src/views/search/hooks/useNavigateToSearchResults.ts
  src/views/search/hooks/useSavedSearchData.ts
  src/views/search/utils/types.ts
  src/views/templates/list/hooks/useHideDeprecatedTemplates.ts
  src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionHardware.tsx
  src/views/virtualmachines/extensions.ts
  src/views/virtualmachines/hooks/useHideNamespaceBar.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.tsx
  src/views/virtualmachines/list/hooks/useFiltersFromURL.ts
  src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
  src/views/virtualmachines/search/VirtualMachineSearchResults.tsx
  src/views/virtualmachines/search/hooks/useVirtualMachineSearchSuggestions.ts
  src/views/virtualmachines/tree/VirtualMachineTreeView.scss
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
  src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
  src/views/virtualmachines/tree/hooks/useTreeViewSelect.ts
  src/views/virtualmachines/utils/constants.ts
  src/views/virtualmachines/utils/utils.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
  tsconfig.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2627 CNV-59955: Fix alignment of state labels in the bootable volume list
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.scss
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2630 [release-4.17] CNV-60605: Fix rerendering all over vm details
  src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
Labels: lgtm, approved, jira/valid-reference

#2631 [release-4.18] CNV-60605: Fix rerendering all over vm details
  src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
Labels: lgtm, approved, jira/valid-reference

#2628 `find undefined` Make persistent fix
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/MakePersistentModal.tsx
Labels: lgtm, approved

#2636 CNV-58790: VMI migration source and target node reported incorrectly on Migrations tab
  src/utils/resources/vmim/selectors.ts
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationsRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2611 CNV-59099: test for set default storageclass
  cypress/support/nav.ts
  cypress/tests/all.cy.ts
  cypress/tests/e2e/set-default-sc.cy.ts
  cypress/views/actions.ts
Labels: lgtm, approved, jira/valid-reference

#2632 CNV-52010: Fetch VMI resource only for running VMs
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
Labels: lgtm, approved, jira/valid-reference

#2589 CNV-59371: Show metrics on running vm
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/MemoryPercentage.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/NetworkUsage.tsx
  src/views/virtualmachines/list/hooks/constants.ts
  src/views/virtualmachines/list/utils/totalsQueries.ts
Labels: lgtm, approved, jira/valid-reference

#2638 CNV-61191: Toggle autoResourceLimits feature by replacing only the flag value
  src/utils/hooks/useHyperConvergeConfiguration.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2642 CNV-61190: Use default boot mode from the preference
  src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
  src/utils/resources/preference/helper.ts
  src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
Labels: lgtm, approved, jira/valid-reference

#2648 [release-4.18] CNV-58790: VMI migration source and target nodes reported incorrectly on Migrations tab
  src/utils/resources/vmim/selectors.ts
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationsRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2646 CNV-60994: condition labels remove width limit
  src/views/virtualmachines/list/components/VMStatusConditionLabel/VMStatusConditionLabel.tsx
Labels: lgtm, approved, jira/valid-reference

#2647 CNV-61436: toolbar dropdown labels fix styling
  src/utils/components/ListPageFilter/AutocompleteInput.tsx
  src/utils/components/ListPageFilter/ListPageFilter.tsx
  src/utils/components/ListPageFilter/SuggestionLine.tsx
Labels: lgtm, approved, jira/valid-reference

#2610 CNV-55855: test interface link state
  cypress/support/commands.ts
  cypress/tests/downstream/vm-tab.cy.ts
  cypress/tests/downstream/vm-tabs/network.cy.ts
  cypress/tests/e2e/a-setup.cy.ts
  cypress/views/tab.ts
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2644 CNV-61333: fix storage class migration crash migplan no volumes
  locales/en/plugin__kubevirt-plugin.json
  src/views/storagemigrations/list/components/StorageMigrationRow.tsx
  src/views/storagemigrations/list/hooks/useStorageMigrationResources.ts
Labels: lgtm, approved, jira/valid-reference

#2649 CNV-58916: Show LiveMigratable=True label in VMs list
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2650 CNV-59121: show correct max number of columns to select
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ColumnManagementModal/ColumnManagementModal.tsx
  src/utils/components/ColumnManagementModal/constants.ts
  src/utils/components/ColumnManagementModal/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2654 CNV-58642: Add timestamps to chart tooltips on VirtualMachine Metrics tab
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
  src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChart.tsx
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChartDiskRate.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
  src/utils/components/Charts/StorageUtil/StorageIOPSTotalThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageReadThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageWriteThresholdChart.tsx
  src/utils/components/Charts/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2660 CNV-58160: Move text input under the "SSH over NodePort service" heading on the settings page
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/SSHConfiguration/SSHConfiguration.tsx
Labels: lgtm, approved, jira/valid-reference

#2640 CNV-60417: remove folder filter after VMs are moved out of folder
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/MoveVMToFolderModal/MoveBulkVMsToFolderModal.tsx
  src/utils/components/MoveVMToFolderModal/MoveVMToFolderModal.tsx
  src/utils/components/MoveVMToFolderModal/hooks/useRemoveFolderQuery.ts
  src/utils/hooks/useVMsInNamespace.ts
  src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/utils.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineBulkActionButton.tsx
  src/views/virtualmachines/tree/hooks/dragndrop.ts
  src/views/virtualmachines/tree/hooks/useTreeViewItemActions.ts
  src/views/virtualmachines/tree/hooks/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2652 CNV-60146: edit labels on multiple VMs bug fixes
  src/utils/components/LabelsModal/LabelsModal.tsx
  src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2653 CNV-61181: Surface StorageProfile options
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeDestination/VolumeDestination.tsx
  src/utils/components/AddBootableVolumeModal/utils/constants.ts
  src/utils/components/AddBootableVolumeModal/utils/utils.ts
  src/utils/components/ApplyStorageProfileSettings/AccessMode.tsx
  src/utils/components/ApplyStorageProfileSettings/ApplyStorageProfileSettings.scss
  src/utils/components/ApplyStorageProfileSettings/ApplyStorageProfileSettings.tsx
  src/utils/components/ApplyStorageProfileSettings/RecommendationLabel.tsx
  src/utils/components/ApplyStorageProfileSettings/VolumeMode.tsx
  src/utils/components/ApplyStorageProfileSettings/utils.ts
  src/utils/components/ApplyStorageProfileSettingsCheckbox/ApplyStorageProfileSettingsCheckbox.tsx
  src/utils/components/DiskModal/components/StorageClassAndPreallocation/StorageClassSelect.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/ApplyStorageProfileSettings.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/utils.ts
  src/utils/components/DiskModal/components/utils/modesMapping.ts
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormAccessMode.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormVolumeMode.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/CreateBootableVolumeModal.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2655 CNV-61535: modal buttons fix alignment
  src/utils/components/ColumnManagementModal/ColumnManagementModal.tsx
  src/utils/components/ColumnManagementModal/column-management-modal.scss
  src/utils/components/TabModal/TabModal.tsx
  src/views/checkups/components/DeleteCheckupModal.tsx
  src/views/virtualmachines/actions/components/ConfirmMultipleVMActionsModal/ConfirmMultipleVMActionsModal.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2664 CNV-61810: update doc link to 4.19
  locales/en/plugin__kubevirt-plugin.json
  src/utils/constants/documentation.ts
  src/views/clusteroverview/OverviewTab/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
Labels: lgtm, approved, jira/valid-reference

#2665 Add script for creating test translations
  i18n-scripts/dummy-locale.js
  package.json
Labels: lgtm, approved

#2635 CNV-57330: Display disk size from DataVolume over PVC for VM disks list
  src/utils/resources/bootableresources/selectors.ts
  src/utils/resources/vm/hooks/disk/useDisksSources.ts
  src/utils/resources/vm/hooks/disk/useDisksTableData.ts
  src/utils/resources/vm/hooks/disk/utils.ts
  src/utils/resources/vm/utils/disk/constants.ts
  src/utils/resources/vm/utils/disk/rowData.ts
Labels: lgtm, approved, jira/valid-reference

#2663 CNV-61532: fix clearing search results
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2669 Add missing i18n updates
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
Labels: lgtm, approved

#2671 CNV-61969: Fix resource link for VM root disk in VM disks list
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2641 CNV-60996: Hide StorageClass dropdown and settings in "Edit disk" modal
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/OtherDiskModal.tsx
  src/utils/components/DiskModal/components/AdvancedSettings/AdvancedSettings.tsx
Labels: lgtm, approved, jira/valid-reference

#2666 CNV-61733 : show migration section if forklift not installed
  src/utils/flags/consts.ts
  src/utils/flags/index.ts
  src/utils/flags/useShowMigrationSectionFlag.ts
  src/views/storagemigrations/extensions.ts
Labels: lgtm, approved

#2674 CNV-61395: fix advanced search when isProxyPodAlive
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved, jira/valid-reference

#2672 CNV-57942: Show actual storage capacity in VM disks list
  src/utils/resources/bootableresources/selectors.ts
  src/utils/resources/vm/utils/disk/constants.ts
  src/utils/resources/vm/utils/disk/rowData.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2676 [release-4.18] CNV-62082: make Selects scrollable
  src/utils/components/DurationOption/DurationDropdown.tsx
  src/utils/components/HardwareDevices/form/DeviceNameSelect.tsx
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
Labels: lgtm, approved, jira/valid-reference

#2678 CNV-62082: make Selects scrollable
  src/utils/components/DurationOption/DurationDropdown.tsx
  src/utils/components/HardwareDevices/form/DeviceNameSelect.tsx
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
Labels: lgtm, approved, jira/valid-reference

#2677 CNV-46434: Add HTTP DataSource option to the bootable volumes modal
  src/utils/components/AddBootableVolumeModal/components/SourceTypeSelection/SourceTypeSelection.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeSource/components/HTTPSource.tsx
  src/utils/components/AddBootableVolumeModal/utils/constants.ts
  src/utils/components/AddBootableVolumeModal/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2682 CNV-62160: disabling right click project menu actions when project is empty
  src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2684 CNV-62204: Stop HTTP-created bootable volumes from disappearing temporarily during import
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2685 adding batya to owners
  OWNERS
Labels: lgtm, approved

#2681 CNV-56886: fix dashboard links to VMs with status
  src/views/dashboard-extensions/Inventory.tsx
Labels: lgtm, approved, jira/valid-reference

#2686 Use latest Console 4.19 plugin SDK packages
  package.json
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/components/YamlAndCLIEditor/YamlAndCLIEditor.tsx
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/components/YamlAndCLIViewerModal/YamlAndCLIViewerModal.tsx
  yarn.lock
Labels: lgtm, approved

#2687 CNV-62226: Add missing attributes to tables and navigation.
  cypress/views/selector-common.ts
  cypress/views/selector.ts
  plugin-extensions.ts
  src/perspective/extensions.ts
  src/utils/components/AffinityModal/components/AffinityList/components/AffinityRow.tsx
  src/utils/components/HardwareDevices/list/HardwareDeviceRow.tsx
  src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceRow.tsx
  src/views/checkups/network/list/CheckupsNetworkListRow.tsx
  src/views/checkups/storage/list/CheckupsStorageListRow.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationsRow.tsx
  src/views/datasources/list/DataSourcesListRow.tsx
  src/views/instancetypes/list/components/ClusterInstancetypeRow.tsx
  src/views/instancetypes/list/components/UserInstancetypeRow.tsx
  src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
  src/views/preferences/list/components/ClusterPreferenceRow.tsx
  src/views/preferences/list/components/UserPreferenceRow.tsx
  src/views/storagemigrations/list/components/StorageMigrationRow.tsx
  src/views/storagemigrations/list/hooks/useStorageMigrationColumns.ts
  src/views/templates/details/tabs/disks/components/DiskRow.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx
  src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceRow.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotRow.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachinesinstance/list/VirtualMachinesInstancesRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2689 CNV-62150: add option to edit labels on single VM
  src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
Labels: lgtm, approved, jira/valid-reference

#2680 CNV-62175: Remove scroll bar from VM yaml & configuration tab
  src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss
  src/views/virtualmachines/details/tabs/yaml/virtual-machine-yaml-page.scss
Labels: lgtm, approved, jira/valid-reference

#2683 CNV-58804: migrations chart change Bandwidth consumption title
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/DescriptionItem/DescriptionItemHeader.tsx
  src/views/clusteroverview/MigrationsTab/MigrationsTab.tsx
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/BandwidthConsumptionCharts.tsx
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsUtilizationChart.tsx
Labels: lgtm, approved, jira/valid-reference

#2692 CNV-62313: CNV-62292: fix search by multiple labels
  src/utils/components/ListPageFilter/components/TextFiltersToolbarItem.tsx
  src/utils/components/ListPageFilter/hooks/useListPageFiltersMethods.ts
Labels: lgtm, approved, jira/valid-reference

#2701 CNV-62203: fixing bottom page display on guided tour step 6
  package.json
  src/utils/components/GuidedTour/GuidedTour.tsx
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2679 CNV-57330: Use DataVolume size for InstanceType VM creation
  src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/utils/resources/bootableresources/helpers.ts
  src/utils/resources/bootableresources/hooks/useBootableVolumes.ts
  src/utils/resources/bootableresources/selectors.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DiskSize.tsx
  src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
  src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
  src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2675 CNV-62123: Re-organize tests for downstream and upstream
  cypress/fixtures/secret.yaml
  cypress/support/commands.ts
  cypress/tests/all.cy.ts
  cypress/tests/downstream/a-setup.cy.ts
  cypress/tests/downstream/a-shared-vm.cy.ts
  cypress/tests/ds.cy.ts
  cypress/tests/e2e/b-overview.cy.ts
  cypress/tests/overview.cy.ts
  cypress/tests/upstream/a-setup.cy.ts
  cypress/tests/upstream/a-shared-vm.cy.ts
  cypress/tests/upstream/catalog-create.cy.ts
  cypress/tests/upstream/catalog-filter.cy.ts
  cypress/tests/upstream/check-tab-yaml.cy.ts
  cypress/tests/upstream/nad.cy.ts
  cypress/tests/upstream/overview-tab.cy.ts
  cypress/tests/upstream/set-default-sc.cy.ts
  cypress/tests/upstream/settings-cluster-general.cy.ts
  cypress/tests/upstream/template-list.cy.ts
  cypress/tests/upstream/top-consumers-tab.cy.ts
  cypress/tests/upstream/vm-actions-confirm.cy.ts
  cypress/tests/us.cy.ts
  cypress/tests/vm-action.cy.ts
  test-cypress.sh
  test-prow-e2e.sh
  test-setup.sh
Labels: lgtm, approved, jira/valid-reference

#2710 CNV-59145: fix tree view panel covering whole screen
  src/utils/constants/window.ts
  src/utils/hooks/useIsSmallScreen.ts
  src/views/virtualmachines/tree/VirtualMachineTreeView.scss
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
  src/views/virtualmachines/tree/components/TreeViewContent.tsx
Labels: lgtm, approved, jira/valid-reference
