Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2025-07, with the labels that each got.

#2775 CNV-61770: fix linking to User Preferences in Bootable volumes
  src/utils/resources/bootableresources/constants.ts
  src/utils/resources/bootableresources/helpers.ts
  src/utils/resources/preference/types.ts
  src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
  src/views/bootablevolumes/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/ShowAllBootableVolumesButton/ShowAllBootableVolumesButton.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsLeftGrid.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
  src/views/datasources/details/components/DataSourceDetailsGrid.tsx/DataSourceDetailsGrid.tsx
  src/views/datasources/details/components/DataSourceDetailsGrid.tsx/DataSourcePreferenceLink.tsx
Labels: lgtm, approved, jira/valid-reference

#2788 CNV-64442: fix linking to User InstanceType in DataSource details
  src/utils/resources/bootableresources/helpers.ts
  src/views/datasources/details/DataSourceDetailsPage.tsx
  src/views/datasources/details/components/DataSourceDetailsGrid/DataSourceDetailsGrid.tsx
  src/views/datasources/details/components/DataSourceDetailsGrid/DataSourceInstanceTypeLink.tsx
  src/views/datasources/details/components/DataSourceDetailsGrid/DataSourcePreferenceLink.tsx
Labels: lgtm, approved, jira/valid-reference

#2786 [release-4.18] CNV-64491: Choose volume/access mode based on recommendations from StorageProfile
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/components/StorageClassAndPreallocation/StorageClassSelect.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/AccessMode.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/ApplyStorageProfileSettings.scss
  src/utils/components/DiskModal/components/StorageProfileSettings/ApplyStorageProfileSettings.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/RecommendationLabel.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/VolumeMode.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/utils.ts
  src/utils/components/DiskModal/components/utils/modesMapping.ts
  src/utils/constants/documentation.ts
Labels: lgtm, approved, jira/valid-reference

#2791 CNV-64583: Fix error handling in re-creating features config map
  src/utils/hooks/useFeatures/createFeaturesConfigMap.ts
  src/utils/hooks/useFeatures/useFeatures.ts
  src/utils/hooks/useFeatures/useFeaturesConfigMap.ts
Labels: lgtm, approved, jira/valid-reference

#2739 CNV-61454: when creating a vm in yaml changing example to rhel9 instead of fedora
  src/templates/vm-yaml.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
  src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
Labels: lgtm, approved, jira/valid-reference

#2797 CNV-61359: fixing SSH key creation when creating vm from template
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
Labels: lgtm, approved, jira/valid-reference

#2793 ACM-20341: refactor vm metrics with acm logic
  src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
  src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChart.tsx
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChartDiskRate.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageIOPSTotalThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageReadThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
  src/utils/components/Charts/StorageUtil/StorageWriteThresholdChart.tsx
  src/utils/hooks/useVMQueries.ts
  src/utils/resources/vm/hooks/useMigrationPercentage.tsx
  src/views/virtualmachines/details/tabs/metrics/NetworkCharts/hook/useNetworkData.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
Labels: lgtm, approved, jira/valid-reference

#2794 CNV-64734: added service labels to vmi so the updated status would display in the ui
  src/utils/components/SSHAccess/components/SSHCommand.tsx
Labels: lgtm, approved, jira/valid-reference

#2790 CNV-64532: Reduce classname usage in tests
  cypress/support/selectors.ts
  cypress/tests/gating/vm-adv-search.cy.ts
  cypress/tests/setup/setup.cy.ts
  src/utils/components/EnvironmentEditor/components/EnvironmentFormActions.tsx
  src/views/clusteroverview/SettingsTab/SettingsTab.tsx
  src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/components/SSHAuthKeyRow/SSHAuthKeyRow.tsx
  src/views/search/components/AdvancedSearchModal/AdvancedSearchModal.tsx
  src/views/search/components/SaveSearchModal.tsx
  src/views/search/components/SavedSearchesDropdown.tsx
  src/views/search/components/SearchSuggestBox/SearchSuggestBox.tsx
  src/views/templates/details/tabs/details/components/CPUMemoryModal/CPUMemoryModal.tsx
  src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
Labels: approved, jira/valid-reference

#2777 ACM-20341: add treeview and standalone console page to acm
  __mocks__/multicluster-sdk.ts
  jest.config.ts
  package.json
  plugin-extensions.ts
  plugin-metadata.ts
  src/multicluster/constants.ts
  src/multicluster/extensions.ts
  src/multicluster/flags.ts
  src/multicluster/helpers/selectors.ts
  src/multicluster/hooks/useAllClusters/useAllClusters.ts
  src/multicluster/hooks/useK8sWatchData.ts
  src/multicluster/urls.ts
  src/multicluster/useIsACMPage.ts
  src/utils/components/Consoles/ConsoleStandAlone.tsx
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
  src/utils/components/Consoles/components/DesktopViewer/DesktopViewer.tsx
  src/utils/components/Consoles/components/DesktopViewer/utils/types.ts
  src/utils/components/Consoles/constants.ts
  src/utils/components/Consoles/utils/utils.ts
  src/utils/extension.ts
  src/utils/hooks/useK8sWatchData.ts
  src/utils/hooks/useKubevirtDataPod/hooks/useKubevirtDataPodHealth.ts
  src/utils/hooks/useKubevirtDataPod/useKubevirtDataPod.ts
  src/utils/hooks/useKubevirtWatchResource.ts
  src/utils/hooks/useKubevirtWatchResource/useKubevirtWatchResource.ts
  src/utils/hooks/useKubevirtWatchResource/useRedirectWatchHooks.ts
  src/utils/hooks/useMemoizedParams.ts
  src/utils/resources/shared.ts
  src/utils/resources/vm/hooks/useVMI.ts
  src/utils/resources/vm/hooks/useVMIAndPodsForVM.ts
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineOverviewTabDetailsConsoleWrapper.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/hooks/useVMMetrics.ts
  src/views/virtualmachines/list/hooks/useVMTotalsMetrics.ts
  src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
  src/views/virtualmachines/search/VirtualMachineSearchResults.tsx
  src/views/virtualmachines/tree/hooks/useTreeViewData.ts
  src/views/virtualmachines/tree/hooks/useTreeViewItemActions.ts
  src/views/virtualmachines/tree/utils/utils.tsx
  src/views/virtualmachinesinstance/details/tabs/console/VirtualMachinesInstancePageConsoleTab.tsx
  tsconfig.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2806 ACM-20341: add cluster column in vm row
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved, jira/valid-reference

#2804 ACM-20341: Fix VM list summary metrics on multicluster view
  src/multicluster/hooks/useClusterParam.ts
  src/multicluster/hooks/useIsAllClustersPage.ts
  src/multicluster/hooks/useVMListQueries.ts
  src/utils/hooks/useNamespaceParam.ts
  src/views/virtualmachines/list/hooks/useVMMetrics.ts
  src/views/virtualmachines/list/hooks/useVMTotalsMetrics.ts
  src/views/virtualmachines/list/utils/totalsQueries.ts
  tsconfig.json
Labels: lgtm, approved, jira/valid-reference

#2800 ACM-20341: Multicluster sdk odf integration
  __mocks__/multicluster-sdk.ts
  src/multicluster/components/ACMExtentionsTableData.tsx
  src/multicluster/hooks/useACMExtensionActions/constants.ts
  src/multicluster/hooks/useACMExtensionActions/useACMExtensionActions.ts
  src/multicluster/hooks/useACMExtensionActions/utils.tsx
  src/multicluster/hooks/useACMExtensionColumns/useACMExtensionColumns.tsx
  src/multicluster/hooks/useACMExtensionColumns/utils.ts
  src/multicluster/hooks/useACMExtensionsHeaders.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved, jira/valid-reference

#2809 ACM-20341: add cluster select for advanced search
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/views/search/components/AdvancedSearchModal/AdvancedSearchModal.tsx
  src/views/search/components/AdvancedSearchModal/components/ClusterMultiSelect.tsx
  src/views/search/components/AdvancedSearchModal/components/MultiSelect.tsx
  src/views/search/components/AdvancedSearchModal/components/ProjectMultiSelect.tsx
  src/views/search/hooks/useNavigateToSearchResults.ts
  src/views/search/utils/types.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/search/hooks/useVMSearchQueries.ts
  src/views/virtualmachines/utils/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2814 skipping CPU and memory adv search test
  cypress/tests/gating/vm-adv-search.cy.ts
  deploy-kubevirt-gating.sh
Labels: lgtm, approved

#2815 CNV-65960: Adapt Segment analytics code based on Console telemetry plugin
  @types/console/index.d.ts
  console-telemetry.md
  cypress/support/index.ts
  cypress/support/login.ts
  src/utils/extensions/telemetry/telemetry.ts
  src/utils/utils/utils.ts
  tsconfig.json
Labels: lgtm, approved, jira/valid-reference

#2821 CNV-62944: Fixing the disk size display in vm details to display the right size
  src/utils/resources/vm/utils/disk/rowData.ts
Labels: lgtm, approved, jira/valid-reference

#2817 CNV-64218: Project workloads view breaks on VMs
  package.json
  src/multicluster/hooks/useACMExtensionActions/useACMExtensionActions.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2811 ACM-20341: use fleet link and useK8sWatchData
  __mocks__/multicluster-sdk.ts
  src/multicluster/components/MulticlusterResourceLink/MulticlusterResourceLink.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeDestination/VolumeDestination.tsx
  src/utils/components/AddBootableVolumeModal/utils/constants.ts
  src/utils/components/AddBootableVolumeModal/utils/utils.ts
  src/utils/components/ProjectDropdown/ProjectDropdown.tsx
  src/utils/components/SSHAccess/useSSHService.tsx
  src/utils/components/SSHAccess/utils.ts
  src/utils/hooks/useDefaultStorage/useDefaultStorageClass.ts
  src/utils/resources/udn/hooks/useNamespaceUDN.ts
  src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useConvertedVolumeNames.ts
  src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/useCreateEmptyMigPlan.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/useExistingMigrationPlan.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/useProgressMigration.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationDestinationTab.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationDetails.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils/migrateVMs.ts
  src/views/virtualmachines/actions/hooks/useStorageMigrations.ts
  src/views/virtualmachines/details/tabs/configuration/initialrun/components/InitialRunTabSysprep.tsx
  src/views/virtualmachines/details/tabs/configuration/initialrun/utils/utils.ts
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/CreateBootableVolumeModal.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/hooks/useVolumeOwnedResource.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
  src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineDiagnosticTabRow.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/InstanceTypeDescription.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/TemplateDescription.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineStatusWithPopover/MigrationProgressPopover.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfaces.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabService/VirtualMachinesOverviewTabService.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotRow.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2807 CNV-31632: add a "Copy FQDN" option for each NIC
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/hooks/useFQDN/useFQDN.ts
  src/utils/hooks/useFQDN/useIsFQDNEnabled.ts
  src/utils/models/index.ts
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfacesRow.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/hooks/useVirtualMachinesOverviewTabInterfacesData.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/utils/types.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/virtual-machines-overview-tab-interfaces.scss
Labels: lgtm, approved, jira/valid-reference

#2822 CNV-61679: Add virtualization features list to cluster settings
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/ExpandSectionWithCustomToggle/ExpandSectionWithCustomToggle.scss
  src/utils/components/ExpandSectionWithCustomToggle/ExpandSectionWithCustomToggle.tsx
  src/utils/components/ExpandSectionWithSwitch/ExpandSectionWithSwitch.scss
  src/utils/components/ExpandSectionWithSwitch/ExpandSectionWithSwitch.tsx
  src/utils/models/index.ts
  src/utils/resources/descheduler/constants.ts
  src/utils/resources/descheduler/hooks/useKubeDescheduler.ts
  src/utils/resources/descheduler/selectors.ts
  src/utils/resources/descheduler/types.ts
  src/utils/resources/descheduler/utils.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/ClusterTab.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/VirtualizationFeaturesSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/FeaturedOperatorItem.scss
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/FeaturedOperatorItem.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/LoadBalanceSection/LoadBalanceSection.scss
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/LoadBalanceSection/LoadBalanceSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/LoadBalanceSection/components/DeschedulerSection.scss
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/LoadBalanceSection/components/DeschedulerSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/icons/InstalledIcon.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/icons/NotInstalledIcon.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/utils/utils.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/VirtualizationFeaturesContext/VirtualizationFeaturesContext.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/constants.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/hooks/useOperatorResources/useOperatorResources.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/hooks/useOperatorResources/utils/types.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/hooks/useOperatorResources/utils/utils.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/hooks/useVirtualizationOperators/useVirtualizationOperators.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/hooks/useVirtualizationOperators/utils/constants.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/hooks/useVirtualizationOperators/utils/types.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/hooks/useVirtualizationOperators/utils/utils.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/types.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/utils.ts
  src/views/clusteroverview/utils/types.ts
Labels: lgtm, approved, jira/valid-reference

#2826 Fix preferences loading with error
  src/utils/constants/constants.ts
  src/utils/hooks/useUserPreferences.ts
  src/utils/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
Labels: lgtm, approved

#2834 doc: include BRIDGE_BRANDING=openshift for local development
  README.md
Labels: lgtm, approved, ok-to-test

#2837 ACM-20341: Order clusters and open them by default if selected
  src/views/virtualmachines/tree/utils/utils.tsx
Labels: lgtm, approved, jira/valid-reference

#2812 ACM-20341: add created parameter to the search api
  package.json
  src/utils/hooks/useKubevirtWatchResource/useKubevirtWatchResource.ts
  src/utils/hooks/useKubevirtWatchResource/useRedirectWatchHooks.ts
  src/views/virtualmachines/search/hooks/useVMSearchQueries.ts
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2846 ACM-20341: fleet access review for vm pages
  src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
  src/utils/components/ActionsDropdown/constants.ts
  src/utils/resources/shared.ts
  src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/VMActionsIconBar/components/ActionIconButton.tsx
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/configuration/initialrun/InitialRunTab.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection.tsx
  src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabAuthorizedSSHKey.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineOverviewTabDetailsConsoleWrapper.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabGeneral/VirtualMachinesOverviewTabGeneral.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved, jira/valid-reference

#2847 CNV-65202: Fix providers select and do final fixes
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/multicluster/components/CrossClusterMigration/CrossClusterMigration.tsx
  src/multicluster/components/CrossClusterMigration/CrossClusterMigrationWizard.tsx
  src/multicluster/components/CrossClusterMigration/components/ReadinessStep.tsx
  src/multicluster/components/CrossClusterMigration/components/ReadinessStepBody.tsx
  src/multicluster/components/CrossClusterMigration/components/StorageMapping.tsx
  src/multicluster/components/CrossClusterMigration/components/TargetStep.tsx
  src/multicluster/components/CrossClusterMigration/hooks/constants.ts
  src/multicluster/components/CrossClusterMigration/hooks/useClustersAndProjects.ts
  src/multicluster/components/CrossClusterMigration/hooks/useComputeReadiness.ts
  src/multicluster/components/CrossClusterMigration/hooks/useCrossClusterMigrationSubmit.ts
  src/multicluster/components/CrossClusterMigration/hooks/useNetworkReadiness.ts
  src/multicluster/components/CrossClusterMigration/hooks/useProviderNADs.ts
  src/multicluster/components/CrossClusterMigration/hooks/useProviderStorageClasses.ts
  src/multicluster/components/CrossClusterMigration/hooks/useStorageReadiness.ts
  src/multicluster/components/CrossClusterMigration/types.ts
  src/multicluster/components/CrossClusterMigration/utils.ts
  src/utils/resources/plan/selectors.ts
Labels: lgtm, approved, jira/valid-reference

#2853 ACM-20341: make cnv hook for k8s api path
  src/multicluster/hooks/useGuestAgentURL.ts
  src/multicluster/hooks/useInstanceTypeSpecURL.ts
  src/multicluster/hooks/useK8sBaseAPIPath.ts
  src/utils/components/Consoles/ConsoleStandAlone.tsx
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
  src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineLogViewer/hooks/useVirtualMachineLogData.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
  src/views/virtualmachinesinstance/details/tabs/console/VirtualMachinesInstancePageConsoleTab.tsx
Labels: lgtm, approved, jira/valid-reference

#2840 CNV-66351: Removing Prefrences from virtualization navigation menu
  cypress/tests/gating.cy.ts
  cypress/tests/gating/check-tab-yaml.cy.ts
  plugin-extensions.ts
  src/perspective/extensions.ts
Labels: lgtm, approved, jira/valid-reference

#2862 CNV-60059: Descriptions for UEFI and UEFI (secure) are the same
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/FirmwareBootloaderModal/utils/constants.ts
Labels: lgtm, approved, ok-to-test, jira/valid-reference
