Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2025-06, with the labels that each got.

#2668 Update kubevirt-api package version to v1.3.8
  package.json
  src/utils/components/CloneVMModal/CloneVMModal.tsx
  src/utils/components/CloneVMModal/components/CloningStatus.tsx
  src/utils/components/CloneVMModal/hooks/useCloneVMModal.ts
  src/utils/components/CloneVMModal/utils/helpers.tsx
  src/utils/resources/shared.ts
  src/views/cdi-upload-provider/utils/selectors.ts
  yarn.lock
Labels: lgtm, approved

#2714 CNV-62815: DataVolume name is derived from disk name
  src/utils/components/DiskModal/utils/form.ts
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/components/DiskModal/utils/submit.ts
Labels: lgtm, approved, jira/valid-reference

#2719 CNV-62937: Use custom chart styles based on PatternFly CSS variables
  src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
  src/utils/components/Charts/ChartLabels/SubTitleChartLabel.tsx
  src/utils/components/Charts/ChartLabels/TitleChartLabel.tsx
  src/utils/components/Charts/ChartLabels/styleOverrides.ts
  src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChart.tsx
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChartDiskRate.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
  src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsTimeAxis.tsx
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsUtilizationChart.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/MigrationsChartDonut.tsx
  src/views/clusteroverview/OverviewTab/metric-charts-card/components/MetricChart.tsx
  src/views/clusteroverview/OverviewTab/vms-per-resource-card/VMsPerResourceChart.tsx
  src/views/dashboard-extensions/KubevirtHealthPopup/components/HealthPopupChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
Labels: lgtm, approved, jira/valid-reference

#2592 Make start-console script compatible with zsh
  start-console.sh
Labels: lgtm, approved

#2711 CNV-62493: hide username and password in VM Console tab
  cypress/tests/downstream/a-shared-vm.cy.ts
  cypress/tests/upstream/a-shared-vm.cy.ts
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsItem.tsx
Labels: lgtm, approved, jira/valid-reference

#2720 chore(i18n): update translations
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
Labels: lgtm, approved

#2716 CNV-56431: Add VM Details panel topology extension
  jest.config.ts
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/OwnerDetailsItem/OwnerDetailsItem.tsx
  src/utils/resources/shared.ts
  src/utils/resources/vmi/utils/guest-agent.ts
  src/utils/resources/vmi/utils/selectors.ts
  src/views/topology/components/vm/VMDetailsPanel/TopologyVMDetailsPanel.scss
  src/views/topology/components/vm/VMDetailsPanel/TopologyVMDetailsPanel.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelLeftColumn/VMDetailsPanelLeftColumn.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelLeftColumn/components/VMAnnotationsDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelLeftColumn/components/VMCreatedTimestampDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelLeftColumn/components/VMDescriptionDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelLeftColumn/components/VMLabelsDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelLeftColumn/components/VMNameDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelLeftColumn/components/VMNamespaceDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelLeftColumn/components/VMOperatingSystemDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelLeftColumn/components/VMTemplateDetailsItem/VMTemplateDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelLeftColumn/components/VMTemplateDetailsItem/VMTemplateLink.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/VMDetailsPanelRightColumn.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/HardwareDevices/VMGPUDevicesDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/HardwareDevices/VMHostDevicesDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMBootOrderDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMHostnameDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMIPAddressesDetailsItem/VMIPAddresses.scss
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMIPAddressesDetailsItem/VMIPAddresses.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMIPAddressesDetailsItem/VMIPAddressesDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMNodeDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMPodDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMStatusDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMTimezoneDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMUserCredentialsDetailsItem/VMUserCredentialsDetailsItem.scss
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMUserCredentialsDetailsItem/VMUserCredentialsDetailsItem.tsx
  src/views/topology/components/vm/VMDetailsPanel/components/VMDetailsPanelRightColumn/components/VMWorkloadProfileDetailsItem.tsx
  src/views/topology/extensions.ts
  src/views/topology/hooks/useVMSidePanelDetailsTabSection.tsx
  src/views/topology/topology-plugin.ts
  src/views/topology/topology.ts
  src/views/topology/utils/constants.ts
  src/views/topology/utils/selectors/selectors.ts
  src/views/topology/utils/types/types.ts
  src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
  src/views/virtualmachines/details/tabs/configuration/details/utils/utils.ts
  src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabAuthorizedSSHKey.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/OperatingSystem/OperatingSystem.tsx
  tsconfig.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2723 [release-4.18] CNV-62815: DataVolume name is derived from disk name
  src/utils/components/DiskModal/utils/form.ts
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/components/DiskModal/utils/submit.ts
Labels: lgtm, approved, jira/valid-reference

#2727 [release-4.18] CNV-62819: increase timeout for DataVolume to be ready to upload
  src/utils/hooks/useCDIUpload/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2725 CNV-62923: show proper error message when volume upload fails
  src/utils/components/TabModal/TabModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2726 CNV-62819: increase timeout for DataVolume to be ready to upload
  src/utils/hooks/useCDIUpload/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2724 CNV-56431: Add remaining virtualization topology extensions
  src/utils/utils/utils.ts
  src/views/topology/components/ODCBaseNode.tsx
  src/views/topology/extensions.ts
  src/views/topology/hooks/useModifyApplicationActionProvider.ts
  src/views/topology/hooks/usePodsAdapterForVM.ts
  src/views/topology/hooks/usePodsForVM.ts
  src/views/topology/hooks/useVMSidePanelDetailsTabSection.tsx
  src/views/topology/topology.ts
  src/views/topology/utils/constants.ts
  src/views/topology/utils/is-kubevirt-resource.ts
  src/views/topology/utils/kubevirt-component-factory.ts
  src/views/topology/utils/kubevirt-data-transformer.ts
  src/views/topology/utils/resource-utils.ts
  src/views/topology/utils/topology-utils.ts
  src/views/topology/utils/utils.ts
  src/views/topology/utils/vm-tab-sections.tsx
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2729 CNV-61727: Fix setting link state on already added network interface
  src/views/catalog/wizard/tabs/network/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2718 CNV-39729: show disk size in TiB and not bytes
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
  src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
  src/views/templates/details/tabs/disks/hooks/useTemplateDisksTableData.ts
  src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
  src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
Labels: lgtm, approved, jira/valid-reference

#2721 CNV-57953: fixed disk size display in storage to reflect the right size after edit
  src/utils/resources/vm/hooks/disk/useDisksSources.ts
Labels: lgtm, approved, jira/valid-reference

#2736 Cnv 62718 fix cpu display
  src/utils/components/CPUMemory/CPUMemory.tsx
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabService/VirtualMachinesOverviewTabService.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Services/Services.tsx
Labels: lgtm, approved

#2717 CNV-61063: Support user-defined network (UDN) as secondary network
  src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts
  src/utils/components/NetworkInterfaceModal/utils/helpers.ts
  src/utils/resources/udn/hooks/useNamespaceUDN.ts
  src/utils/resources/udn/types.ts
Labels: lgtm, approved, jira/valid-reference

#2733 CNV-63362: Test advanced VM search
  cypress/support/selectors.ts
  cypress/tests/upstream/vm-adv-search.cy.ts
  cypress/tests/us.cy.ts
  test-setup.sh
Labels: approved, jira/valid-reference

#2705 CNV-58161: moved guest system log above automatic subscription in settings- guest managment
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/GuestManagementSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/GuestSystemLogsAccess/GuestSystemLogsAccess.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/PersistentReservationSection/PersistentReservationSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/AutoComputeCPULimits.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/KernelSamepageMerging/KernelSamepageMerging.tsx
  src/views/clusteroverview/SettingsTab/settings-tab.scss
Labels: lgtm, approved, jira/valid-reference

#2737 CNV-63238: remove bytesFromQuantity and related helpers
  jest.config.ts
  package.json
  src/utils/components/AddBootableVolumeModal/components/VolumeSource/components/DiskSourcePVCSelect.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeSource/components/PVCSource.tsx
  src/utils/components/DiskModal/components/DiskSizeInput/DiskSizeInput.tsx
  src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceClonePVCSelect/DiskSourceClonePVCSelectName.tsx
  src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceSnapshotVolumeSelect/DiskSourceSnapshotVolumeSelectName.tsx
  src/utils/components/DiskModal/utils/submit.ts
  src/utils/resources/vm/utils/disk/rowData.ts
  src/utils/tests/units.test.ts
  src/utils/utils/humanize.js
  src/utils/utils/units.ts
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DiskSize.tsx
  src/views/catalog/utils/quantity.ts
  src/views/catalog/utils/tests/quantity.test.ts
  src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
  src/views/migrationpolicies/components/MigrationPolicyEditModal/utils/utils.ts
  src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTableRow.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTableRow.tsx
  src/views/virtualmachinesinstance/details/tabs/disks/utils/virtualMachinesInstancePageDisksTabUtils.ts
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2740 CNV-63521: rename upstream test to gating
  cypress/tests/gating.cy.ts
  cypress/tests/gating/a-setup.cy.ts
  cypress/tests/gating/a-shared-vm.cy.ts
  cypress/tests/gating/catalog-create.cy.ts
  cypress/tests/gating/catalog-filter.cy.ts
  cypress/tests/gating/check-tab-yaml.cy.ts
  cypress/tests/gating/nad.cy.ts
  cypress/tests/gating/overview-tab.cy.ts
  cypress/tests/gating/set-default-sc.cy.ts
  cypress/tests/gating/settings-cluster-general.cy.ts
  cypress/tests/gating/template-list.cy.ts
  cypress/tests/gating/top-consumers-tab.cy.ts
  cypress/tests/gating/vm-actions-confirm.cy.ts
  cypress/tests/gating/vm-adv-search.cy.ts
  cypress/tests/us.cy.ts
  test-prow-e2e.sh
Labels: lgtm, approved, jira/valid-reference

#2730 CNV-61727: Share network column definitions
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceLinkState/NetworkInterfaceLinkState.tsx
  src/utils/components/NetworkInterfaceModal/utils/helpers.ts
  src/utils/hooks/useNetworkColums.ts
  src/utils/resources/vm/utils/network/network-columns.tsx
  src/utils/resources/vm/utils/network/selectors.ts
  src/utils/resources/vm/utils/network/types.ts
  src/utils/resources/vm/utils/network/utils.ts
  src/utils/utils/typeGuards.ts
  src/utils/utils/utils.ts
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceList.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceRow.tsx
  src/views/catalog/wizard/tabs/network/hooks/useNetworkColumns.ts
  src/views/catalog/wizard/tabs/network/utils/utils.ts
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewNetworksTable/WizardOverviewNetworksTable.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceList.tsx
  src/views/templates/details/tabs/network/hooks/useNetworkColumns.ts
  src/views/templates/details/tabs/network/utils.ts
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceRow.tsx
  src/views/virtualmachines/details/tabs/configuration/network/hooks/useNetworkColumns.ts
  src/views/virtualmachines/details/tabs/configuration/network/utils/utils.ts
  src/views/virtualmachines/list/hooks/useVMListFilters/useNodesFilter.ts
  src/views/virtualmachinesinstance/details/tabs/network/VirtualMachineInstancePageNetworkTabRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2742 CNV-58719: Fix broken Alerts links in the Virtualization perspective
  src/utils/components/AlertsCard/AlertsCard.tsx
  src/utils/components/AlertsCard/utils/constants.ts
  src/utils/constants/constants.ts
  src/utils/constants/prometheus.ts
  src/views/clusteroverview/OverviewTab/status-card/StatusCard.tsx
  src/views/dashboard-extensions/KubevirtHealthPopup/KubevirtHealthPopup.tsx
  src/views/dashboard-extensions/KubevirtHealthPopup/utils/utils.ts
  src/views/virtualmachines/details/tabs/overview/utils/hook/useVMAlerts.tsx
Labels: lgtm, approved, jira/valid-reference

#2756 chore(i18n): update translations
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
Labels: lgtm, approved

#2749 CNV-63016: Add link for uncategorized VMs in VMs per Resource chart
  src/utils/resources/vm/utils/index.ts
  src/utils/resources/vm/utils/utils.ts
  src/utils/utils/utils.ts
  src/views/clusteroverview/OverviewTab/inventory-card/utils/vm-status-section/VMStatusInventoryItem.tsx
  src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx
  src/views/clusteroverview/OverviewTab/vms-per-resource-card/RunningVMsChartLegendLabel.tsx
  src/views/clusteroverview/OverviewTab/vms-per-resource-card/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2759 [release-4.18] CNV-63430: fix expanding disk size
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CapacityInput/CapacityInput.tsx
  src/utils/components/CapacityInput/utils.ts
  src/utils/components/DiskModal/components/DiskSizeInput/DiskSizeInput.tsx
  src/utils/components/DiskModal/components/DiskSizeInput/ExpandPVC.tsx
  src/utils/components/DiskModal/components/DiskSizeInput/utils.ts
  src/utils/utils/units.ts
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DiskSize.tsx
Labels: lgtm, approved, jira/valid-reference

#2752 Add notice about noVNC licence
  LICENSE
Labels: lgtm, approved

#2762 CNV-62163: Prevent refreshing details page on VM change
  src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
  src/utils/components/StateHandler/StateHandler.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
  src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
Labels: lgtm, approved, jira/valid-reference

#2764 CNV-63622: customize the migplan list page with the storage migration
  src/views/storagemigrations/actions/useStorageMigrationActions.tsx
  src/views/storagemigrations/extensions.ts
  src/views/storagemigrations/list/components/StorageMigrationRow.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationStatus.tsx
Labels: lgtm, approved, jira/valid-reference

#2768 CNV-57798: report also PVC disks in VM deletion modal
  src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useConvertedVolumeNames.ts
  src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
Labels: lgtm, approved, jira/valid-reference

#2748 CNV-57475: make disk size not editable when using volume snapshot
  locales/en/plugin__kubevirt-plugin.json
  locales/es/plugin__kubevirt-plugin.json
  locales/fr/plugin__kubevirt-plugin.json
  locales/ja/plugin__kubevirt-plugin.json
  locales/ko/plugin__kubevirt-plugin.json
  locales/zh/plugin__kubevirt-plugin.json
  src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
  src/utils/components/AddBootableVolumeModal/components/SourceTypeSelection/SourceTypeSelection.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeDestination/VolumeDestination.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeSource/components/SnapshotSource.tsx
  src/utils/components/CapacityInput/CapacityInput.tsx
  src/utils/components/SelectSnapshot/SelectSnapshot.tsx
Labels: lgtm, approved, jira/valid-reference

#2776 Add multicluster-sdk
  package.json
  src/globals.d.ts
  src/utils/hooks/useK8sWatchData.ts
  yarn.lock
Labels: lgtm, approved

#2771 CNV-64350: CNV-61710: Fix bugs in bootable volumes Preferences select menu
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/VolumeMetadata.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/InstanceTypeDrilldownSelect.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/hooks/usePreferenceSelectOptions.ts
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/utils/utils.ts
  src/utils/components/FilterSelect/components/InlineFilterSelectOptionContent.tsx
  src/utils/components/FilterSelect/utils/types.ts
  src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2780 CNV-64453: Fix and optimize documentation URLs
  src/utils/constants/documentation.ts
Labels: lgtm, approved, jira/valid-reference

#2782 CNV-59354: Use VirtualMachine route to standalone console
  src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx
Labels: lgtm, approved, jira/valid-reference
