Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2025-02, with the labels that each got.

#2411 CNV-54463: Remove memoization from CPU/Memory/Network usage columns
  src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/MemoryPercentage.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/NetworkUsage.tsx
Labels: lgtm, approved, jira/valid-reference

#2405 CNV-55049: Move Machine Type from Overview to Configuration tab
  cypress/tests/e2e/check-tab-yaml.cy.ts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/vm/utils/selectors.ts
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
  src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/components/VirtualMachinesOverviewTabNetworkFQDN.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
Labels: lgtm, approved, jira/valid-reference

#2408 CNV-55107: loading on vm change
  src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
  src/utils/components/StateHandler/StateHandler.tsx
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
Labels: lgtm, approved, jira/valid-reference

#2412 CNV-55845: Tree view flickering when it should be off
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
Labels: lgtm, approved, jira/valid-reference

#2415 OCPBUGS-44823: hide udn in virt networking
  src/perspective/extensions.ts
Labels: lgtm, approved, jira/valid-reference, jira/severity-moderate

#2409 CNV-51546: Vm not foun
  images/restricted-sign.svg
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AccessDenied/AccessDenied.tsx
  src/utils/components/StateHandler/StateHandler.tsx
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  tsconfig.json
Labels: lgtm, approved, jira/valid-reference

#2413 fix: use v4.18.0-27 uploader image
  src/utils/components/ExportModal/constants.ts
Labels: lgtm, approved, ok-to-test

#2420 CNV-55749: fix editing disk error
  src/utils/components/DiskModal/OtherDiskModal.tsx
  src/utils/components/DiskModal/utils/submit.ts
Labels: lgtm, approved, jira/valid-reference

#2417 CNV-41922: Alerts are displayed in the wrong order in the Virtualization Overview page
  src/utils/components/AlertsCard/utils/utils.tsx
Labels: lgtm, approved, jira/valid-reference

#2410 CNV-51885: fix instancetype list tabs typography
  cypress/tests/e2e/check-tab-yaml.cy.ts
  locales/en/plugin__kubevirt-plugin.json
  src/views/instancetypes/list/InstanceTypePage.tsx
  src/views/preferences/list/PreferencePage.tsx
Labels: lgtm, approved, jira/valid-reference

#2421 CNV-38560: [RFE] delete confirmation dialog checkups
  locales/en/plugin__kubevirt-plugin.json
  src/views/checkups/components/DeleteCheckupModal.tsx
  src/views/checkups/network/components/CheckupsNetworkActions.tsx
  src/views/checkups/storage/components/CheckupsStorageActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2422 CNV-55900: add/edit disk in customize VM crashes
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2423 CNV-49588: order instancetype by size (cpu and memory)
  src/utils/components/InstanceTypeModal/utils/types.ts
  src/utils/components/InstanceTypeModal/utils/util.ts
  src/utils/resources/instancetype/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2425 CNV-55840: migrate storage remove cancel button
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationStatus.tsx
Labels: lgtm, approved, jira/valid-reference

#2427 CNV-55087: Use custom chart styles based on PatternFly CSS variables
  src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
  src/utils/components/Charts/ChartLabels/SubTitleChartLabel.tsx
  src/utils/components/Charts/ChartLabels/TitleChartLabel.tsx
  src/utils/components/Charts/ChartLabels/styleOverrides.ts
  src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChart.tsx
  src/utils/components/Charts/MigrationUtil/MigrationThresholdChartDiskRate.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
  src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsTimeAxis.tsx
  src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsUtilizationChart.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/MigrationsChartDonut.tsx
  src/views/clusteroverview/OverviewTab/metric-charts-card/components/MetricChart.tsx
  src/views/clusteroverview/OverviewTab/vms-per-resource-card/VMsPerResourceChart.tsx
  src/views/dashboard-extensions/KubevirtHealthPopup/components/HealthPopupChart.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
Labels: lgtm, approved, jira/valid-reference

#2418 CNV-43411: Target node changed after the network checkup finished
  src/views/checkups/network/details/CheckupsNetworkDetailsPageSection.tsx
  src/views/checkups/network/hooks/useCheckupsNetworkListColumns.ts
  src/views/checkups/network/list/CheckupsNetworkListRow.tsx
  src/views/checkups/network/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2430 CNV-51525: Remove "Start" button from ICON action list when VM in pause
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
Labels: lgtm, approved, jira/valid-reference

#2426 CNV-49912: sort vm list by nodes, cpu, memory and network
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/MemoryPercentage.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/components/NetworkUsage.tsx
  src/views/virtualmachines/list/hooks/sortColumns.ts
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/list/metrics.ts
  src/views/virtualmachines/utils/mappers.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved, jira/valid-reference

#2428 CNV-56004: Fixing no nic in vm - adding new nic crash
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
Labels: lgtm, approved, jira/valid-reference

#2429 CNV-55086: persist vm tab on treeview vm switch
  src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/tree/hooks/useTreeViewData.ts
  src/views/virtualmachines/tree/utils/utils.tsx
Labels: lgtm, approved, jira/valid-reference

#2431 CNV-51198: Fix YAML template displayed when clicking "Add volume" -> "By YAML" on the Bootable volumes page
  src/views/bootablevolumes/list/components/BootableVolumeAddButton.tsx
Labels: lgtm, approved, jira/valid-reference

#2432 CNV-51468: Hide migration Limitations link for non-admin users
  src/views/clusteroverview/MigrationsTab/components/MigrationsLimitionsPopover/MigrationsLimitionsPopover.tsx
  src/views/clusteroverview/MigrationsTab/components/MigrationsLimitionsPopover/hooks/useHyperConvergedMigrations.ts
  src/views/clusteroverview/MigrationsTab/hooks/useMigrationCardData.ts
Labels: lgtm, approved, jira/valid-reference

#2437 [release-4.16] CNV-51123: bump kubevirt api version to handle v1beta1 version
  console-extensions.json
  package.json
  src/utils/components/AddBootableVolumeModal/utils/utils.ts
  src/utils/components/CloneTemplateModal/utils.ts
  src/utils/components/CloneVMModal/CloneVMModal.tsx
  src/utils/components/CloneVMModal/components/SnapshotContentConfigurationSummary.tsx
  src/utils/components/CloneVMModal/utils/helpers.tsx
  src/utils/components/DiskModal/utils/helpers.ts
  src/utils/resources/template/hooks/useVmTemplateSource/useVMTemplateSource.ts
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
  src/views/cdi-upload-provider/PVCDeleteAlertExtension.tsx
  src/views/cdi-upload-provider/hooks/useBaseImages.ts
  src/views/cdi-upload-provider/popover/UploadPVCPopover.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCForm.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormGoldenImage.tsx
  src/views/cdi-upload-provider/utils/selectors.ts
  src/views/cdi-upload-provider/utils/utils.tsx
  src/views/templates/actions/components/EditBootSourceModal.tsx
  src/views/templates/actions/components/SelectSource.tsx
  src/views/templates/actions/components/utils.ts
  src/views/templates/actions/editBootSource.ts
  src/views/virtualmachines/actions/components/DeleteVMModal/components/DeleteOwnedResourcesMessage.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/VirtualMachinesOverviewTabSnapshotsRow.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/component/SnapshotDeleteModal.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotRow.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/modal/RestoreModal.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/modal/SnapshotModal.tsx
  src/views/virtualmachines/details/tabs/snapshots/hooks/useSnapshotColumns.ts
  src/views/virtualmachines/details/tabs/snapshots/hooks/useSnapshotData.ts
  src/views/virtualmachines/details/tabs/snapshots/utils/helpers.ts
  src/views/virtualmachines/details/tabs/snapshots/utils/selectors.ts
  src/views/virtualmachinesinstance/details/tabs/disks/utils/virtualMachinesInstancePageDisksTabUtils.ts
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2438 CNV-56030: Projects not displayed in tree view for non-admin users
  src/views/virtualmachines/tree/hooks/useTreeViewData.ts
Labels: lgtm, approved, jira/valid-reference

#2435 CNV-55086: fix state handler loading infinite
  src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
  src/views/catalog/CustomizeInstanceType/CustomizeInstanceTypeVirtualMachine.tsx
  src/views/catalog/wizard/Wizard.tsx
Labels: lgtm, approved, jira/valid-reference

#2445 [release-4.16] CNV-56325: Fix snapshot model version
  src/views/virtualmachines/details/tabs/snapshots/hooks/useSnapshotData.ts
Labels: lgtm, approved, jira/valid-reference

#2449 fix check tab e2e tests
  cypress/tests/e2e/check-tab-yaml.cy.ts
Labels: lgtm, approved

#2442 CNV-55111: fix get bootmode bios when seelcted
  src/utils/components/FirmwareBootloaderModal/utils/utils.ts
  src/views/catalog/CustomizeInstanceType/tabs/configuration/hooks/usePreference.ts
Labels: lgtm, approved, jira/valid-reference

#2451 CNV-56376: Migration hide stop
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationStatus.tsx
Labels: lgtm, approved, jira/valid-reference

#2455 CNV-55105: remove create project within the project dropdown
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/shared/GeneralSettingsProject.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/shared/GeneralSettingsProjectSelector.tsx
Labels: lgtm, approved, jira/valid-reference

#2456 CNV-56496: use a shorter name for dv
  src/utils/components/DiskModal/utils/form.ts
Labels: lgtm, approved, jira/valid-reference

#2457 CNV-56499: fix bootmode select in template
  src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2458 CNV-56364: Update documentation links to 4.17
  src/utils/constants/documentation.ts
  src/views/clusteroverview/TopConsumersTab/utils/NoDataAvailableMessage.tsx
  src/views/clusteroverview/TopConsumersTab/utils/constants.ts
  src/views/templates/list/components/VirtualMachineTemplateSupport/VirtualMachineTemplateSupport.tsx
  src/views/templates/utils/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2462 Update novnc from 1.3.0 to 1.5.0
  package.json
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/components/AccessConsoles/utils/accessConsoles.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
  yarn.lock
Labels: lgtm, approved

#2468 Revert "[release-4.18] CNV-54461: [RFE] Add link to VM status on VM list page"
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
  src/views/virtualmachines/list/components/VirtualMachineStatus/VirtualMachineStatus.tsx
Labels: lgtm, approved, jira/valid-reference

#2470 fix: use v4.18.0-985 uploader image
  src/utils/components/ExportModal/constants.ts
Labels: lgtm, approved, ok-to-test

#2469 fix: use v4.18.0-985 uploader image
  src/utils/components/ExportModal/constants.ts
Labels: lgtm, approved, ok-to-test

#2473 fix: use v4.18.0-27 uploader image
  src/utils/components/ExportModal/constants.ts
Labels: lgtm, approved, needs-ok-to-test

#2475 CNV-56219: fix guided tour
  src/utils/components/GuidedTour/utils/constants.tsx
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
Labels: lgtm, approved, jira/valid-reference

#2443 CNV-55859: add windows drivers on windows preference
  src/utils/components/WindowsDrivers/WindowsDrivers.tsx
  src/utils/resources/vm/utils/disk/drivers.ts
  src/utils/resources/vm/utils/disk/useDriversImage.ts
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/components/ActionButtons/ActionButtons.tsx
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/hooks/useGeneratedVM.ts
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2460 CNV-55963: right click action in the treeview
  src/views/virtualmachines/list/hooks/sortColumns.ts
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/tree/VirtualMachineTreeView.scss
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
  src/views/virtualmachines/tree/components/TreeViewContent.tsx
  src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu.tsx
  src/views/virtualmachines/tree/hooks/useFilteredTreeView.ts
  src/views/virtualmachines/tree/hooks/useTreeViewData.ts
  src/views/virtualmachines/tree/hooks/useTreeViewItemRightClick.ts
  src/views/virtualmachines/tree/utils/signals.ts
  src/views/virtualmachines/utils/mappers.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved, jira/valid-reference

#2472 CNV-56274: Confirm before executing potentially impactful VM actions
  locales/en/plugin__kubevirt-plugin.json
  src/utils/hooks/useFeatures/constants.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/GeneralSettings.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/TemplatesAndImagesManagement.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/components/AutomaticImagesDownload/AutomaticImagesDownload.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/components/AutomaticImagesDownload/automatic-images-download.scss
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/components/AutomaticImagesDownload/utils/consts.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/components/BootableVolumeProjectSection/BootableVolumeProjectSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/components/BootableVolumeProjectSection/utils/utils.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/components/TemplatesProjectSection/TemplatesProjectSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/components/TemplatesProjectSection/utils/utils.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/VMActionsConfirmation/VMActionsConfirmation.tsx
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/ConfirmMultipleVMActionsModal/ConfirmMultipleVMActionsModal.scss
  src/views/virtualmachines/actions/components/ConfirmMultipleVMActionsModal/ConfirmMultipleVMActionsModal.tsx
  src/views/virtualmachines/actions/components/ConfirmMultipleVMActionsModal/components/VMsByNamespacePopover.scss
  src/views/virtualmachines/actions/components/ConfirmMultipleVMActionsModal/components/VMsByNamespacePopover.tsx
  src/views/virtualmachines/actions/components/ConfirmMultipleVMActionsModal/utils/utils.ts
  src/views/virtualmachines/actions/components/ConfirmVMActionModal/ConfirmVMActionModal.tsx
  src/views/virtualmachines/actions/components/VMActionsIconBar/VMActionsIconBar.tsx
  src/views/virtualmachines/actions/components/VMActionsIconBar/utils/utils.ts
  src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.ts
  src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
Labels: lgtm, approved, jira/valid-reference

#2419 CNV-55889: SSH over LoadBalancer creates Service with incorrect selector
  src/utils/components/SSHAccess/SSHAccess.tsx
  src/utils/components/SSHAccess/components/SSHCommand.tsx
  src/utils/components/SSHAccess/constants.ts
  src/utils/components/SSHAccess/utils.ts
  src/views/virtualmachines/details/tabs/configuration/ssh/SSHTab.tsx
  src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabSSHAccess.tsx
  src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
Labels: lgtm, approved, jira/valid-reference

#2404 US Tests - Creation of VM from Template tests
  cleanup.sh
  cypress/.eslintrc.json
  cypress/cypress.config.js
  cypress/fixtures/hco.yaml
  cypress/fixtures/secret.ts
  cypress/support/index.ts
  cypress/support/login.ts
  cypress/support/nav.ts
  cypress/support/selectors.ts
  cypress/support/views.ts
  cypress/tests/all.cy.ts
  cypress/tests/e2e/a-setup.cy.ts
  cypress/tests/e2e/b-overview.cy.ts
  cypress/tests/e2e/check-tab-yaml.cy.ts
  cypress/tests/e2e/create-vm-it.cy.ts
  cypress/tests/e2e/create-vm.cy.ts
  cypress/tests/e2e/login.cy.ts
  cypress/types/vm.ts
  cypress/utils/const/index.ts
  cypress/utils/const/template.ts
  cypress/utils/const/testVM.ts
  cypress/views/catalog-flow.ts
  cypress/views/catalog.ts
  cypress/views/instance-flow.ts
  cypress/views/perspective.ts
  cypress/views/selector-common.ts
  cypress/views/selector.ts
  cypress/views/template-flow.ts
  cypress/views/vm-flow.ts
  deploy-kubevirt-gating.sh
  setup.sh
  test-cypress.sh
Labels: lgtm

#2480 [CI] Use HPP-CSI instead of the legacy one
  deploy-kubevirt-gating.sh
Labels: lgtm, approved, ok-to-test

#2483 CNV-57034: upgrade cypress to version 14
  cypress/cypress.config.js
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2484 CNV-57039: Adjusting owners file
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#2485 SSH key/secret related tests added
  cypress/tests/e2e/a-setup.cy.ts
  cypress/tests/e2e/b-overview.cy.ts
Labels: lgtm, approved

#2490 NAD related tests added
  cypress/support/nav.ts
  cypress/tests/all.cy.ts
  cypress/tests/e2e/d-networking.cy.ts
  cypress/views/nad.ts
Labels: lgtm, approved
