Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2025-03, with the labels that each got.

#2482 CNV-56288: update deprecated Selects
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityEditRow.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityEditRowValues.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/affinity-edit-row.scss
  src/utils/components/EnvironmentEditor/components/EnvironmentSelectOption.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentSelectResource.tsx
  src/utils/components/EnvironmentEditor/utils.ts
  src/utils/components/FilterSelect/InlineFilterSelect.tsx
  src/utils/components/FilterSelect/utils/constants.ts
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
  src/utils/components/toggles/SelectToggle.tsx
  yarn.lock
Labels: lgtm, approved, needs-ok-to-test, jira/valid-reference

#2493 CNV-57150: add test for virtualization overview tab
  cypress/tests/e2e/a-setup.cy.ts
  cypress/tests/e2e/check-tab-yaml.cy.ts
  cypress/tests/overview.cy.ts
  cypress/tests/overview/overview-tab.cy.ts
Labels: lgtm, approved, jira/valid-reference

#2476 CNV-56226: migrate only migratable disks
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/components/utils.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2479 CNV-56822: add treeview to guided tour
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/GuidedTour/GuidedTour.tsx
  src/utils/components/GuidedTour/components/NewStepTitle/NewStepTitle.tsx
  src/utils/components/GuidedTour/utils/constants.tsx
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
  src/views/virtualmachines/tree/utils/utils.tsx
Labels: lgtm, approved, jira/valid-reference

#2501 CNV-57476: Fix VM action confirmation modal not closing on confirmation
  src/views/virtualmachines/actions/components/ConfirmVMActionModal/ConfirmVMActionModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2487 CNV-56281: Add deletion protection for VMs
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
  src/utils/components/ActionDropdownItem/action-dropdown-item.scss
  src/utils/resources/shared.ts
  src/views/cdi-upload-provider/utils/selectors.ts
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/configuration/details/components/DeletionProtection/DeletionProtectionModal.tsx
  src/views/virtualmachines/details/tabs/configuration/details/components/DeletionProtection/utils/constants.ts
  src/views/virtualmachines/details/tabs/configuration/details/components/DeletionProtection/utils/types.ts
  src/views/virtualmachines/details/tabs/configuration/details/components/DeletionProtection/utils/utils.ts
  src/views/virtualmachines/details/tabs/configuration/details/utils/utils.ts
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/hooks/sortColumns.ts
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved, jira/valid-reference

#2505 [release-4.12] CNV-50618: Update dompurify from 2.3.10 to 2.5.8
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2502 CNV-55956: Move the tree view feature from TP to GA
  locales/en/plugin__kubevirt-plugin.json
  src/utils/hooks/useFeatures/constants.ts
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsLeftGrid.tsx
  src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeDetailsTab.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/usePreviewFeaturesData.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
  src/views/virtualmachines/tree/hooks/useHideNamespaceBar.ts
Labels: lgtm, approved, jira/valid-reference

#2495 CNV-57354: add test for top consumers tab
  cypress/cypress.config.js
  cypress/tests/e2e/a-setup.cy.ts
  cypress/tests/overview.cy.ts
  cypress/tests/overview/overview-tab.cy.ts
  cypress/tests/overview/top-consumers-tab.cy.ts
  cypress/views/overview.ts
  cypress/views/perspective.ts
Labels: lgtm, approved, jira/valid-reference

#2471 CNV-52511: Keep formatting in VNC paste action
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/utils/util.ts
Labels: lgtm, approved, jira/valid-reference

#2507 CNV-57799: use lowercase for "Add Volume"
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeLink/AddBootableVolumeLink.tsx
  src/views/catalog/CreateFromInstanceTypes/components/CreateFromInstanceTypeTitle/CreateFromInstanceTypeTitle.tsx
Labels: lgtm, approved, jira/valid-reference

#2506 [Snyk] Security upgrade axios from 1.7.4 to 1.8.2
  package.json
  yarn.lock
Labels: lgtm, approved

#2489 Fix Form Submission Behavior for Virtual Machine Creation
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
Labels: lgtm, approved, ok-to-test

#2461 CNV-51315: Create selection dropdown
  cypress/tests/e2e/create-vm.cy.ts
  cypress/views/selector-common.ts
  locales/en/plugin__kubevirt-plugin.json
  src/utils/styles/list-managment-group.scss
  src/views/virtualmachines/list/VirtualMachinesList.scss
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineSelection/VirtualMachineSelection.tsx
  src/views/virtualmachines/list/components/VirtualMachineSelection/virtual-machine-selection.scss
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Labels: lgtm, approved, jira/valid-reference

#2504 CNV-57788: Update @console/pluginAPI dependency and other small improvements
  README.md
  package.json
  plugin-metadata.ts
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
  tsconfig.json
Labels: lgtm, approved, jira/valid-reference

#2509 CNV-57871: Change "boot source" to "bootable volume"
  locales/en/plugin__kubevirt-plugin.json
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumesPipelinesHint/BootableVolumesPipelinesHint.tsx
Labels: lgtm, approved, jira/valid-reference

#2515 CNV-57968: fix selected VMs state after delete
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2513 CNV-55963: Fix right click on expanded elements
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
  src/views/virtualmachines/tree/components/TreeViewContent.tsx
  src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu.tsx
  src/views/virtualmachines/tree/hooks/useTreeViewItemRightClick.ts
  src/views/virtualmachines/tree/utils/utils.tsx
Labels: lgtm, approved, jira/valid-reference

#2511 Visual improvements after updating to PF6
  src/utils/components/CPUMemoryModal/components/CPUInput/components/CPUTopologyInput/components/CPUComponentInput.tsx
  src/utils/components/CPUMemoryModal/components/CPUInput/components/CPUTopologyInput/components/TotalCPUHelperText/CPUTopologyHelperText.scss
  src/utils/components/CPUMemoryModal/components/CPUInput/components/CPUTopologyInput/components/TotalCPUHelperText/CPUTopologyHelperText.tsx
  src/utils/components/CPUMemoryModal/components/CPUInput/components/vCPUInput/VCPUInput.tsx
  src/utils/components/CPUMemoryModal/components/MemoryInput/MemoryInput.tsx
  src/utils/components/CPUMemoryModal/cpu-memory-modal.scss
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
  src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
  src/utils/components/Consoles/components/vnc-console/VncConnect.tsx
  src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
  src/utils/components/DiskModal/components/DiskSourceSelect/DiskSourceSelect.tsx
  src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
  src/views/checkups/network/components/form/CheckupsNetworkFormLatency.tsx
  src/views/checkups/network/components/form/CheckupsNetworkFormNodes.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/MigrationPolicyCreateFormHeader/MigrationPolicyCreateFormHeader.tsx
  src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx
  src/views/virtualmachines/actions/components/VMActionsIconBar/VMActionsIconBar.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/AddNetworkInterfaceButton.tsx
  src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
  src/views/virtualmachines/details/tabs/diagnostic/virtual-machine-diagnostic-tab.scss
  src/views/virtualmachines/details/tabs/metrics/TimeRange/TimeRange.tsx
  src/views/virtualmachines/details/tabs/metrics/virtual-machine-metrics-tab.scss
  src/views/virtualmachines/list/components/VirtualMachineSelection/virtual-machine-selection.scss
Labels: lgtm, approved

#2512 CNV-57425: DurationDropdown closes on clicking outside or pressing Escape
  src/utils/components/AddBootableVolumeModal/components/SourceTypeSelection/SourceTypeSelection.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityConditionSelect.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityTypeSelect.tsx
  src/utils/components/AffinityModal/components/AffinityList/components/AffinityRowActionsDropdown.tsx
  src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
  src/utils/components/DurationOption/DurationDropdown.tsx
  src/utils/components/FilterSelect/InlineFilterSelect.tsx
  src/utils/components/HardwareDevices/form/DeviceNameSelect.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/checkups/network/components/CheckupsNetworkActions.tsx
  src/views/checkups/storage/components/CheckupsStorageActions.tsx
  src/views/datasources/actions/DataSourceActions.tsx
  src/views/migrationpolicies/components/MigrationPolicyConfigurations/compnents/MigrationPolicyConfigurationDropdown/MigrationPolicyConfigurationDropdown.tsx
  src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/VirtualMachinesOverviewTabSnapshotsRow.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
Labels: lgtm, approved, jira/valid-reference

#2517 CNV-57788: Update @console/pluginAPI dependency for Console 4.17.0+
  plugin-metadata.ts
Labels: lgtm, approved, jira/valid-reference

#2519 CNV-57650: change "preffered" to "preferred"
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AffinityModal/AffinityModal.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/AffinityForm.tsx
  src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/PreferredAffinityWeightInput.tsx
  src/utils/components/AffinityModal/components/AffinityList/AffinityList.tsx
  src/utils/components/AffinityModal/hooks/useRequiredAndPreferredQualifiedNodes.ts
  src/utils/components/AffinityModal/utils/helpers.ts
  src/utils/components/NodeSelectorModal/components/NodeCheckerAlert.tsx
  src/utils/components/SSHSecretModal/utils/types.ts
  src/views/templates/details/tabs/scheduling/components/AffinityRulesModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2503 CNV-49608: Default to raw VM in VirtualMachineNavPageTitle
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CloneVMModal/CloneVMModal.tsx
  src/utils/components/CloneVMModal/utils/helpers.tsx
  src/utils/components/Consoles/Consoles.tsx
  src/utils/components/Consoles/utils/utils.ts
  src/utils/components/DiskModal/utils/form.ts
  src/utils/components/HardwareDevices/HardwareDevicesHeadlessMode.tsx
  src/utils/components/HardwareDevices/modal/HardwareDevicesHeadlessModeModal.tsx
  src/utils/components/HeadlessMode/HeadlessMode.tsx
  src/utils/components/InstanceTypeModal/InstanceTypeModal.tsx
  src/utils/components/InstanceTypeModal/StandaloneInstanceTypeModal.tsx
  src/utils/components/InstanceTypeModal/utils/types.ts
  src/utils/components/InstanceTypeModal/utils/util.ts
  src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
  src/utils/components/PendingChanges/utils/helpers.ts
  src/utils/resources/instancetype/constants.ts
  src/utils/resources/instancetype/helper.ts
  src/utils/resources/vm/hooks/useInstanceTypeExpandSpec.ts
  src/utils/resources/vm/utils/instanceTypes.ts
  src/utils/resources/vm/utils/selectors.ts
  src/utils/utils/typeGuards.ts
  src/views/virtualmachines/details/VirtualMachineNavPage.tsx
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/VirtualMachinePendingChangesAlert.tsx
  src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
  src/views/virtualmachines/details/tabs/configuration/details/utils/utils.ts
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSectionRightGrid.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
Labels: lgtm, approved, jira/valid-reference

#2522 CNV-55202: TreeView folders/projects right click actions
  src/views/virtualmachines/tree/components/TreeViewContent.tsx
  src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/DefaultRightClickActionMenu.tsx
  src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/TreeViewRightClickActionMenu.tsx
  src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/VMRightClickActionMenu.tsx
  src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/utils.ts
  src/views/virtualmachines/tree/hooks/useTreeViewItemActions.ts
Labels: lgtm, approved, jira/valid-reference

#2498 CNV-56322: Allow user to set interface link state in Edit NIC modal
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/FormPFSelect/FormPFSelect.tsx
  src/utils/components/NetworkIcons/LinkStateAbsentIcon.tsx
  src/utils/components/NetworkIcons/LinkStateDownIcon.tsx
  src/utils/components/NetworkIcons/LinkStateIcon.scss
  src/utils/components/NetworkIcons/LinkStateSRIOVIcon.tsx
  src/utils/components/NetworkIcons/LinkStateUpIcon.tsx
  src/utils/components/NetworkIcons/PlugCircleCheckIcon.tsx
  src/utils/components/NetworkIcons/PlugCircleMinusIcon.tsx
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceLinkState/NetworkInterfaceLinkState.scss
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceLinkState/NetworkInterfaceLinkState.tsx
  src/utils/components/NetworkInterfaceModal/utils/helpers.ts
  src/utils/components/NetworkInterfaceModal/utils/types.ts
  src/utils/resources/vm/utils/network/selectors.ts
  src/utils/resources/vm/utils/selectors.ts
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceRow.tsx
  src/views/catalog/wizard/tabs/network/components/modal/WizardEditNetworkInterfaceModal.tsx
  src/views/catalog/wizard/tabs/network/components/modal/WizardNetworkInterfaceModal.tsx
  src/views/catalog/wizard/tabs/network/hooks/useNetworkColumns.ts
  src/views/catalog/wizard/tabs/network/hooks/useNetworkRowFilters.ts
  src/views/catalog/wizard/tabs/network/utils/utils.ts
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx
  src/views/templates/details/tabs/network/components/modal/TemplatesEditNetworkInterfaceModal.tsx
  src/views/templates/details/tabs/network/components/modal/TemplatesNetworkInterfaceModal.tsx
  src/views/templates/details/tabs/network/hooks/useNetworkColumns.ts
  src/views/templates/details/tabs/network/hooks/useNetworkRowFilters.ts
  src/views/templates/details/tabs/network/utils.ts
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceRow.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesEditNetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesNetworkInterfaceModal.tsx
  src/views/virtualmachines/details/tabs/configuration/network/hooks/useNetworkColumns.ts
  src/views/virtualmachines/details/tabs/configuration/network/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2525 [Snyk] Security upgrade axios from 1.8.2 to 1.8.3
  package.json
  yarn.lock
Labels: lgtm, approved

#2526 CNV-55202: stop right click treeview propagation
  src/views/virtualmachines/tree/hooks/useTreeViewItemActions.ts
Labels: lgtm, approved, jira/valid-reference

#2440 CNV-50292: Fix conflict caused by separate namespace and template SSH secrets
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ExportModal/ExportModal.tsx
  src/utils/components/SSHSecretModal/SSHSecretModal.tsx
  src/utils/components/SSHSecretModal/components/SSHKeyUpload/SSHKeyUpload.tsx
  src/utils/components/SSHSecretModal/utils/utils.ts
  src/utils/components/VMSSHSecretModal/VMSSHSecretModal.tsx
  src/utils/resources/secret/utils.ts
  src/utils/resources/secret/utils/selectors.ts
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CustomizeInstanceType/components/CustomizeITVMFooter.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/AuthorizedSSHKey.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useTemplateSecrets/useTemplateSecrets.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useTemplateSecrets/utils/types.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useTemplateSecrets/utils/utils.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/utils/useWizardVMCreate.ts
  src/views/catalog/wizard/components/WizardFooter.tsx
  src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
  src/views/catalog/wizard/tabs/scripts/hooks/useTemplateWizardSecrets.ts
  src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/components/SSHAuthKeyRow/SSHAuthKeyRow.tsx
  src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
  src/views/templates/details/tabs/scripts/components/SSHKey/sshkey-utils.ts
Labels: lgtm, approved, jira/valid-reference

#2536 CNV-58305: Ignore storage class different than boot PVC for blank disks
  src/utils/components/DiskModal/components/StorageClassAndPreallocation/StorageClassSelect.tsx
  src/utils/components/DiskModal/components/utils/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2537 CNV-56945: Validate NetworkInterfaceModal based on values in the state
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2521 test: reenable and fix e2e tests
  cypress/fixtures/secret.ts
  cypress/fixtures/vm.yaml
  cypress/support/login.ts
  cypress/tests/all.cy.ts
  cypress/tests/e2e/a-setup.cy.ts
  cypress/tests/e2e/b-overview.cy.ts
  cypress/tests/e2e/check-tab-yaml.cy.ts
  cypress/tests/e2e/create-vm.cy.ts
  cypress/tests/e2e/d-networking.cy.ts
  cypress/tests/overview/overview-tab.cy.ts
  cypress/tests/overview/top-consumers-tab.cy.ts
  cypress/utils/const/index.ts
  cypress/views/nad.ts
  cypress/views/selector-common.ts
Labels: lgtm, approved

#2539 CNV-58163: Update custom URL with k9sPatch
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionCustomUrl/AutomaticSubscriptionCustomUrl.tsx
Labels: lgtm, approved, jira/valid-reference

#2533 CNV-58317: remove co- classes which changed styling
  src/utils/components/AccessDenied/AccessDenied.tsx
  src/utils/components/CloudinitModal/CloudInitEditor/CloudInitEditor.tsx
  src/utils/components/ColumnManagementModal/ColumnManagementModal.tsx
  src/utils/components/DetailsPageTitle/DetailsPageTitle.tsx
  src/utils/components/DetailsPageTitle/details-page-title.scss
  src/utils/components/EnvironmentEditor/components/EnvironmentFormActions.tsx
  src/utils/components/EnvironmentEditor/components/EnvironmentSelectResource.tsx
  src/utils/components/HardwareDevices/HardwareDevicesPage.tsx
  src/utils/components/PaneHeading/PaneHeading.tsx
  src/utils/styles/forms.scss
  src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVC.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCButtonBar.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCErrorMessage.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCForm.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormGoldenImage.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormMode.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormPVCName.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormPVCNamespace.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormSize.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormStorageClass.tsx
  src/views/cdi-upload-provider/upload-pvc-form/upload-pvc-form.scss
  src/views/checkups/CheckupsNetworkStatusIcon.tsx
  src/views/checkups/checkups.scss
  src/views/checkups/network/details/CheckupsNetworkDetailsPage.tsx
  src/views/checkups/network/details/CheckupsNetworkDetailsPageHeader.tsx
  src/views/checkups/network/details/hooks/useCheckupsNetworkTabs.ts
  src/views/checkups/network/details/tabs/details/CheckupsNetworkDetailsPageSection.tsx
  src/views/checkups/network/details/tabs/details/CheckupsNetworkDetailsTab.tsx
  src/views/checkups/network/details/tabs/yaml/CheckupsNetworkYAMLTab.tsx
  src/views/clusteroverview/Header/ClusterOverviewPageHeader.tsx
  src/views/datasources/dataimportcron/details/DataImportCronPageTitle.tsx
  src/views/datasources/details/DataSourcePageTitle.tsx
  src/views/migrationpolicies/details/components/MigrationPolicyBreadcrumb/MigrationPolicyBreadcrumb.tsx
  src/views/migrationpolicies/details/components/MigrationPolicyDetailsNavTitle/MigrationPolicyDetailsNavTitle.tsx
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/MigrationPolicyCreateForm.scss
  src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/MigrationPolicyCreateForm.tsx
  src/views/templates/details/CommonTemplateAlert.tsx
  src/views/templates/details/NoPermissionTemplateAlert.tsx
  src/views/templates/details/TemplateNavPage.scss
  src/views/templates/details/TemplateNavPage.tsx
  src/views/templates/details/TemplatePageTitle.tsx
  src/views/templates/details/tabs/details/TemplateDetailsPage.scss
  src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
  src/views/virtualmachines/list/components/VirtualMachineBreadcrumb/VirtualMachineBreadcrumb.tsx
  src/views/virtualmachinesinstance/details/VirtualMachinesInstancePageHeader.tsx
Labels: lgtm, approved

#2540 Provide stable reference for toggleFeature
  src/utils/hooks/useFeatures/useFeatures.ts
Labels: lgtm, approved

#2542 CNV-58912: fix aligning VM list table
  src/utils/components/NetworkIcons/LinkStateIcon.scss
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceLinkState/NetworkInterfaceLinkState.scss
  src/views/virtualmachines/list/VirtualMachinesList.scss
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/tree/icons/CollapseAllIcon.tsx
  src/views/virtualmachines/tree/icons/ExpandAllIcon.tsx
Labels: lgtm, approved, jira/valid-reference

#2535 CNV-58306: Use stricter typing for InstanceTypeModal
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
  src/utils/components/InstanceTypeModal/InstanceTypeModal.tsx
  src/utils/components/InstanceTypeModal/utils/types.ts
  src/utils/components/InstanceTypeModal/utils/util.ts
  src/utils/resources/instancetype/selectors.ts
  src/utils/resources/instancetype/types.ts
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/types.ts
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
  src/views/virtualmachines/details/tabs/configuration/utils/types.ts
Labels: lgtm, approved, jira/valid-reference

#2545 [release-4.16] CNV-56674: use v1alpha1 snapshot and restore on 4.16 plugin
  src/utils/components/CloneVMModal/utils/helpers.tsx
  src/utils/models/index.ts
  src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/component/SnapshotDeleteModal.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotRow.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/modal/RestoreModal.tsx
  src/views/virtualmachines/details/tabs/snapshots/components/modal/SnapshotModal.tsx
  src/views/virtualmachines/details/tabs/snapshots/hooks/useSnapshotData.ts
  src/views/virtualmachines/details/tabs/snapshots/utils/helpers.ts
Labels: lgtm, approved, jira/valid-reference

#2534 CNV-58596: Catalog filtering tests added
  cypress/tests/all.cy.ts
  cypress/tests/e2e/a-setup.cy.ts
  cypress/tests/e2e/catalog-filter.cy.ts
  cypress/tests/e2e/create-vm.cy.ts
  cypress/views/actions.ts
  cypress/views/selector-catalog.ts
Labels: lgtm, approved, jira/valid-reference

#2528 CNV-54573: fix drop vm with no label error
  src/views/virtualmachines/tree/hooks/dragndrop.ts
  src/views/virtualmachines/tree/hooks/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2549 CNV-55748: fix pvc size on disk table
  src/utils/resources/vm/utils/disk/rowData.ts
Labels: lgtm, approved, jira/valid-reference
