Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2025-01, with the labels that each got.

#2336 CNV-53452: VirtualMachines page crashes for nonpriv user when user hasn't created a project
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
  src/views/virtualmachines/tree/components/TreeViewContent.tsx
  src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
  src/views/virtualmachines/tree/hooks/useTreeViewData.ts
  src/views/virtualmachines/tree/utils/utils.tsx
Labels: lgtm, approved, jira/valid-reference

#2338 CNV-54221: Apply last namespace to project items in tree-view
  src/views/virtualmachines/tree/hooks/useTreeViewSelect.ts
Labels: lgtm, approved, jira/valid-reference

#2341 CNV-50766: Cannot delete NIC from VM
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceList.tsx
  src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2344 CNV-54331: do not show fqdn on udn managed namespace
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfaces.tsx
Labels: lgtm, approved, jira/valid-reference

#2343 CNV-54110: Fix object select
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
Labels: lgtm, approved, jira/valid-reference

#2345 CNV-53247: Bug registry credentials secret uses template name
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
Labels: lgtm, approved, jira/valid-reference

#2346 CNV-52237: CSICloneInProgress status for DataSource
  src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2347 CNV-50449: fix secure boot with spec.template.spec.domain.features no…
  src/views/virtualmachines/details/tabs/configuration/details/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2348 CNV-52452: Preference instancetype navbar disappear
  src/utils/flags/useEnableKubevirtMenuFlags.ts
Labels: lgtm, approved, jira/valid-reference

#2350 CNV-51386: Observe section handled by monitoring-plugin
  src/perspective/extensions.ts
Labels: lgtm, approved, jira/valid-reference

#2340 CNV-54179: Improve folder select
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/FolderSelect/FolderSelect.tsx
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
  src/utils/components/SelectTypeahead/utils/constants.ts
  src/utils/components/SelectTypeahead/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2356 CNV-51653: Fix bootable volume column sorting on create VM from IT page
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
Labels: lgtm, approved, jira/valid-reference

#2353 CNV-49026: Change 'hide deprecated bootable volumes' filter to 'show deprecated bootable volumes'
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/bootableresources/constants.ts
  src/utils/resources/bootableresources/hooks/useHideDeprecatedBootableVolumes.ts
  src/views/bootablevolumes/list/hooks/useBootableVolumesFilters.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeFilters.ts
Labels: lgtm, approved, jira/valid-reference

#2355 CNV-52557: CVE path-to-regex fixed
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2364 CNV-52642: fix nanoid cve
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2359 [release-4.17] CNV-52558: CVE path to regex backport
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2363 [release-4.15] CNV-49814: CNV-50620: solve dompurify cve
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2357 CNV-53453: disable treeview by default
  src/utils/hooks/useFeatures/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2351 US Tests - Creation of VM from InstanceType tests
  cypress/support/nav.ts
  cypress/support/resource.ts
  cypress/support/selectors.ts
  cypress/tests/e2e/create-vm-it.cy.ts
  cypress/types/vm.ts
  cypress/utils/const/index.ts
  cypress/utils/const/testVM.ts
  cypress/views/perspective.ts
  cypress/views/vm.ts
Labels: lgtm, approved

#2370 CNV-55089: l2bridge binding label
  src/utils/resources/vm/utils/network/constants.ts
  src/utils/resources/vm/utils/network/selectors.ts
Labels: lgtm, approved, jira/valid-reference

#2365 [release-4.14] CNV-50616: CNV-49873: solve dompurify cve
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2362 [release-4.17] CNV-50981: CNV-51359: CNV-52643: fix postcss, cross-spawn nanoid cves
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2367 CNV-55109: storagemigration with no fixed accessMode and volumeMode
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2366 CNV-51526: do not use headless service on udn
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
  src/views/catalog/CustomizeInstanceType/components/CustomizeITVMFooter.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
  src/views/catalog/utils/quick-create-vm.ts
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/wizard/components/WizardFooter.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabService/VirtualMachinesOverviewTabService.tsx
Labels: lgtm, approved, jira/valid-reference

#2371 CNV-52393: Fix missing storageclass in VM Details disk list
  src/utils/resources/vm/hooks/disk/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2374 CNV-55094: filter udn primary binding on nads
  src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
  src/utils/resources/vm/utils/network/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2376 CNV-55048: Fix display of default SSH settings list
  src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/hooks/useSSHAuthKeys.ts
Labels: lgtm, approved, jira/valid-reference

#2368 CNV-55113: rollback migration
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/vm/utils/constants.ts
  src/utils/resources/vm/utils/dataVolumeTemplate/selectors.ts
  src/utils/resources/vm/utils/selectors.ts
  src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/actions.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationDetails.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
  src/views/virtualmachines/actions/constants.ts
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2375 update doc link to 4.18
  locales/en/plugin__kubevirt-plugin.json
  src/utils/constants/documentation.ts
  src/views/clusteroverview/OverviewTab/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
Labels: lgtm, approved

#2378 CNV-55082: use new 4.18 image for export bootable volumes
  src/utils/components/ExportModal/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2380 CNV-50559: Wrap Snapshot tab title and action in a ListPageHeader
  src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
Labels: lgtm, approved, jira/valid-reference

#2379 CNV-55112: Limit VM name length to max k8s label length (63 characters)
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/VMNameValidationHelperText/VMNameValidationHelperText.tsx
  src/utils/components/VMNameValidationHelperText/utils/utils.ts
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsLeftGrid.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
  src/views/catalog/wizard/tabs/overview/components/VMNameModal/VMNameModal.tsx
Labels: lgtm, approved, jira/valid-reference

#2382 CNV-49438: Add 2xmedium to InstanceTypeSize
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/types.ts
Labels: lgtm, approved, jira/valid-reference

#2384 Use DescriptionList layout for displaying network details
  cypress/views/selector-common.ts
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfacesRow.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/virtual-machines-overview-tab-interfaces.scss
Labels: lgtm, approved

#2339 CNV-53248: Add registry credentials to the template wizard flow
  src/utils/components/DiskModal/ContainerDiskModal.tsx
  src/utils/components/DiskModal/DiskModal.tsx
  src/utils/components/DiskModal/RegistryDiskModal.tsx
  src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceContainer/DiskSourceContainer.tsx
  src/utils/components/DiskModal/components/DiskSourceSelect/utils/constants.ts
  src/utils/components/DiskModal/components/utils/constants.ts
  src/utils/components/DiskModal/utils/form.ts
  src/utils/components/DiskModal/utils/submit.ts
  src/utils/components/DiskModal/utils/types.ts
  src/utils/resources/secret/utils.ts
  src/utils/resources/template/utils/helpers.ts
  src/utils/resources/vm/utils/selectors.ts
  src/utils/resources/vm/utils/source.ts
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/Sources/ContainerSource.tsx
  src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
  src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
  src/views/catalog/utils/useRegistryCredentials/useRegistryCredentials.ts
  src/views/catalog/utils/useRegistryCredentials/utils/types.ts
  src/views/catalog/utils/useRegistryCredentials/utils/utils.ts
  src/views/catalog/utils/useWizardVmCreate.ts
  src/views/catalog/wizard/components/WizardFooter.tsx
  src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
  src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
  src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
  src/views/virtualmachines/actions/components/DeleteVMModal/utils/helpers.ts
Labels: lgtm, approved, jira/valid-reference

#2385 CNV-47203: Display Automatic subscription section with incomplete data
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
Labels: lgtm, approved, jira/valid-reference

#2386 CNV-55361: fix downstream upload image url
  src/utils/components/ExportModal/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2381 CNV-52101: fix pod networking from bridge to masquerade
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
Labels: lgtm, approved, jira/valid-reference

#2387 CNV-54834: add datavolume link on diagnosis table
  src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineDiagnosticTabRow.tsx
  src/views/virtualmachines/details/tabs/diagnostic/hooks/constants.ts
  src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticDataVolumeStatusTableColumns.ts
  src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabDataVolumeStatus.tsx
Labels: lgtm, approved, jira/valid-reference

#2373 CNV-52394: storage migration status
  locales/en/plugin__kubevirt-plugin.json
  src/utils/resources/vmim/selectors.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationRollback.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationStatus.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/useCurrentStorageMigration.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/virtual-machine-migration-modal.scss
Labels: lgtm, approved, jira/valid-reference

#2388 CNV-54166: Admission webhook warning about non existing properties l2bridge and deviceIndex
  src/utils/components/HardwareDevices/modal/HardwareDevicesModal.tsx
  src/utils/components/NetworkInterfaceModal/utils/helpers.ts
  src/utils/resources/vm/utils/constants.ts
  src/utils/resources/vm/utils/network/constants.ts
  src/views/catalog/wizard/tabs/overview/components/WizardOverviewNetworksTable/WizardOverviewNetworksTable.tsx
Labels: lgtm, approved, jira/valid-reference

#2391 CNV-53056: do not let user select same nad two times
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
Labels: lgtm, approved, jira/valid-reference

#2390 CNV-53951: fix crash on pvc upload storageclass with no accessMode pr…
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCForm.tsx
Labels: lgtm, approved, jira/valid-reference

#2383 CNV-55111: get preference bootmode
  package.json
  src/utils/components/DiskModal/components/StorageProfileSettings/ApplyStorageProfileSettings.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/VolumeMode.tsx
  src/utils/components/DiskModal/components/utils/modesMapping.ts
  src/utils/components/FirmwareBootloaderModal/utils/utils.ts
  src/utils/resources/preference/helper.ts
  src/utils/types/storage.ts
  src/views/catalog/CustomizeInstanceType/tabs/configuration/hooks/usePreference.ts
  src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeDetailsTab.tsx
  src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormVolumeMode.tsx
  src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
  yarn.lock
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2392 CNV-53272:Refactor instancetype vm creation create button
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/HidableTooltip/HidableTooltip.tsx
  src/utils/components/WithPermissionTooltip/WithPermissionTooltip.tsx
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/components/ActionButtons/ActionButtons.tsx
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/components/ActionButtons/useStatusActionButtons.ts
  src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/components/ActionButtons/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2400 CNV-55454: Fix metrics freezing
  src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
  src/utils/components/Charts/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2394 CNV-55042: instancetype list sort memory fixed
  src/utils/utils/utils.ts
  src/views/instancetypes/list/hooks/useClusterInstancetypeListColumns.ts
  src/views/instancetypes/list/hooks/useUserInstancetypeListColumns.ts
  src/views/instancetypes/list/hooks/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2395 CNV-55041: fix Openshift in OpenShift
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/GuidedTour/components/EndTourContent/EndTourContent.tsx
Labels: lgtm, approved, jira/valid-reference

#2396 CNV-54789: add padding for configuration tabs
  src/views/catalog/CustomizeInstanceType/tabs/configuration/CustomizeInstanceTypeConfigurationTab.scss
  src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss
Labels: lgtm, approved, jira/valid-reference

#2397 CNV-54705: fix link text on overview alert
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AlertsCard/AlertStatusItem.tsx
Labels: lgtm, approved, jira/valid-reference

#2398 CNV-54432: Fix vmi network type
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachinesinstance/details/tabs/network/VirtualMachineInstancePageNetworkTabRow.tsx
Labels: lgtm, approved, jira/valid-reference

#2399 CNV-52708: use RestartCondition on pending changes alert
  src/utils/resources/vm/utils/constants.ts
  src/utils/resources/vm/utils/selectors.ts
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/RestartPendingChanges.tsx
  src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/VirtualMachinePendingChangesAlert.tsx
Labels: lgtm, approved, jira/valid-reference

#2403 CNV-55697: Fix cpu and memory edit crash
  src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
Labels: lgtm, approved, jira/valid-reference

#2393 CNV-55088: Scale VNC console
  src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
  src/utils/components/Consoles/components/vnc-console/vnc-console.scss
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
Labels: lgtm, approved, jira/valid-reference

#2406 CNV-55050: Read dedicatedCpuPlacement status from InstanceType
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/details/tabs/configuration/scheduling/SchedulingTab.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection.tsx
  src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSectionRightGrid.tsx
Labels: lgtm, approved, jira/valid-reference

#2407 CNV-54192: Make VNC Console in the Overview page read only
  src/utils/components/Consoles/components/vnc-console/vnc-console.scss
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/virtual-machines-overview-tab-details.scss
Labels: lgtm, approved, jira/valid-reference
