Repository kubevirt-ui/kubevirt-plugin, pull requests merged in 2025-04, with the labels that each got.

#2552 CNV-58333: Enable automatic image
  src/utils/hooks/useHyperConvergeConfiguration.ts
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/components/AutomaticImagesDownload/AutomaticImagesDownload.tsx
Labels: lgtm, approved, jira/valid-reference

#2546 CNV-58541: add storageclassname column
  src/utils/resources/vm/utils/dataVolumeTemplate/selectors.ts
  src/utils/resources/vm/utils/selectors.ts
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/hooks/sortColumns.ts
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved, jira/valid-reference

#2553 CNV-59146: fix visual regression bugs after Console update
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ColumnManagementModal/ColumnManagementModal.tsx
  src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
  src/utils/styles/list-managment-group.scss
  src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
  src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.tsx
  src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
  src/views/catalog/CustomizeInstanceType/CustomizeInstanceTypeVirtualMachine.tsx
  src/views/catalog/CustomizeInstanceType/components/CustomizeITVMHeader.tsx
  src/views/catalog/CustomizeInstanceType/tabs/configuration/CustomizeInstanceTypeConfigurationTab.tsx
  src/views/catalog/templatescatalog/TemplatesCatalog.scss
  src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
  src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
  src/views/virtualmachines/details/tabs/configuration/search/virtual-machine-configuration-tab-search.scss
  src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
Labels: lgtm, approved, jira/valid-reference

#2554 Fix flaky navigation
  cypress/tests/e2e/create-vm.cy.ts
Labels: lgtm, approved

#2530 CNV-57968: fix selected VMs state after deletion from CLI
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineBulkActionButton.tsx
  src/views/virtualmachines/list/components/VirtualMachineSelection/VirtualMachineSelection.tsx
  src/views/virtualmachines/list/hooks/useExistingSelectedVMs.ts
Labels: lgtm, approved, jira/valid-reference

#2548 CNV-59150: Fix diagnostic link
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineStatusWithPopover/VirtualMachineOverviewStatus.tsx
  src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineStatusWithPopover/VirtualMachineProvisioningStatus.tsx
Labels: lgtm, approved, jira/valid-reference

#2556 CNV-59275: fix drilldown select crash
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/ComposableDrilldownSelect/ComposableDrilldownSelect.tsx
Labels: lgtm, approved, jira/valid-reference

#2550 CNV-59175: Templates filtering tests
  cypress/tests/all.cy.ts
  cypress/tests/e2e/template-list.cy.ts
Labels: lgtm, approved, jira/valid-reference

#2564 CNV-59587: skip tour after login the console
  cypress/support/login.ts
Labels: lgtm, approved, jira/valid-reference

#2543 CNV-58162: hide checkbox from "Enable predictive analytics"
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionCustomUrl/AutomaticSubscriptionCustomUrl.tsx
Labels: lgtm, approved, jira/valid-reference

#2562 CNV-58425: don't disable switch on click
  src/utils/styles/cursor.scss
  src/views/clusteroverview/SettingsTab/ClusterTab/components/PersistentReservationSection/PersistentReservationSection.tsx
Labels: lgtm, approved, jira/valid-reference

#2541 CNV-56949: tree view UI changes
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/ListPageFilter/ListPageFilter.tsx
  src/utils/components/ListPageFilter/RowFilters.tsx
  src/utils/hooks/useContainerWidth.ts
  src/utils/styles/list-managment-group.scss
  src/views/virtualmachines/list/VirtualMachinesList.scss
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineEmptyState/VirtualMachineEmptyState.tsx
  src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.tsx
  src/views/virtualmachines/list/components/VirtualMachineSelection/virtual-machine-selection.scss
  src/views/virtualmachines/list/listManagementGroupSize.ts
  src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
  src/views/virtualmachines/tree/VirtualMachineTreeView.scss
  src/views/virtualmachines/tree/components/TreeViewContent.tsx
  src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
Labels: lgtm, approved, jira/valid-reference

#2559 CNV-59109: fix closing flyout menu
  src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
  src/utils/components/ActionDropdownItem/action-dropdown-item.scss
Labels: lgtm, approved, jira/valid-reference

#2532 Rename interfacesTypes and interfaceLabels
  src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceTypeSelect.tsx
  src/utils/components/NetworkInterfaceModal/utils/helpers.ts
  src/utils/resources/vm/utils/network/constants.ts
  src/utils/resources/vm/utils/network/selectors.ts
  src/views/catalog/wizard/tabs/network/hooks/useNetworkRowFilters.ts
  src/views/templates/details/tabs/network/hooks/useNetworkRowFilters.ts
  src/views/virtualmachines/details/tabs/configuration/network/hooks/useNetworkRowFilters.ts
  src/views/virtualmachines/details/tabs/configuration/network/utils/utils.ts
Labels: lgtm, approved

#2560 CNV-57918: add bulk actions
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/LabelsModal/LabelsModal.tsx
  src/utils/components/MoveVMToFolderModal/BulkVMsPopover.tsx
  src/utils/components/MoveVMToFolderModal/MoveBulkVMsToFolderModal.tsx
  src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
  src/views/virtualmachines/actions/components/ConfirmMultipleVMActionsModal/ConfirmMultipleVMActionsModal.tsx
  src/views/virtualmachines/actions/hooks/constants.ts
  src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.tsx
  src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
  src/views/virtualmachines/actions/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2558 CNV-59302: use BulkSelect for VirtualMachine selection
  cypress/views/selector-common.ts
  locales/en/plugin__kubevirt-plugin.json
  package.json
  src/views/virtualmachines/list/components/VirtualMachineSelection/VirtualMachineSelection.tsx
  src/views/virtualmachines/list/components/VirtualMachineSelection/utils/bulkSelect.ts
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2568 CNV-56949: use PatternFly icons in tree view
  src/views/virtualmachines/tree/components/TreeViewCollapseExpand.tsx
  src/views/virtualmachines/tree/icons/CollapseAllIcon.tsx
  src/views/virtualmachines/tree/icons/ExpandAllIcon.tsx
Labels: lgtm, approved, jira/valid-reference

#2563 CNV-59276: Recognize RT series predefined instance type as Red Hat provided
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
  src/utils/resources/instancetype/types.ts
Labels: lgtm, approved, jira/valid-reference

#2555 CNV-56841: show VirtualMachine utilization summary
  src/views/clusteroverview/OverviewTab/metric-charts-card/utils/metricQueries.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.tsx
  src/views/virtualmachines/list/components/VirtualMachineUsageItem/VirtualMachineUsageItem.scss
  src/views/virtualmachines/list/components/VirtualMachineUsageItem/VirtualMachineUsageItem.tsx
  src/views/virtualmachines/list/hooks/useVMTotalsMetrics.ts
  src/views/virtualmachines/list/utils/processVMTotalsMetrics.ts
  src/views/virtualmachines/list/utils/totalsQueries.ts
Labels: lgtm, approved, jira/valid-reference

#2547 CNV-57955: Default to bundled images for storage and network checkup
  locales/en/plugin__kubevirt-plugin.json
  src/utils/hooks/useKubevirtClusterServiceVersion.ts
  src/utils/hooks/useRelatedImage.ts
  src/views/checkups/components/CheckupImageField.tsx
  src/views/checkups/network/components/CheckupsNetworkActions.tsx
  src/views/checkups/network/components/form/CheckupsNetworkForm.tsx
  src/views/checkups/network/components/form/CheckupsNetworkFormActions.tsx
  src/views/checkups/network/utils/const.ts
  src/views/checkups/network/utils/utils.ts
  src/views/checkups/storage/components/CheckupsStorageActions.tsx
  src/views/checkups/storage/components/form/CheckupsStorageForm.tsx
  src/views/checkups/storage/components/form/CheckupsStorageFormActions.tsx
  src/views/checkups/storage/utils/const.ts
  src/views/checkups/storage/utils/utils.ts
  src/views/checkups/utils/utils.ts
  src/views/clusteroverview/utils/hooks/useKubevirtCSVDetails.ts
  src/views/clusteroverview/utils/types.ts
Labels: lgtm, approved, jira/valid-reference

#2566 CNV-58240: Use built-in styling for BootableVolume table
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.scss
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.scss
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/TableData.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
  src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2569 CNV-58425: add loading state to toggle buttons
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/SectionWithSwitch/SectionWithSwitch.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/MemoryDensity/MemoryDensity.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/SSHConfiguration/SSHConfiguration.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/components/AutomaticImagesDownload/AutomaticImagesDownload.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/VMActionsConfirmation/VMActionsConfirmation.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/GuestSystemLogsAccess/GuestSystemLogsAccess.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/PersistentReservationSection/PersistentReservationSection.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/AutoComputeCPULimits.tsx
  src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/KernelSamepageMerging/KernelSamepageMerging.tsx
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/PreviewFeaturesTab.tsx
  src/views/clusteroverview/SettingsTab/SettingsTab.tsx
  src/views/clusteroverview/SettingsTab/settings-tab.scss
Labels: lgtm, approved, jira/valid-reference

#2565 CNV-59566: SelectTypeahead and FolderSelect enhancements
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/FolderSelect/FolderSelect.tsx
  src/utils/components/FolderSelect/utils/options.tsx
  src/utils/components/FolderSelect/utils/validation.tsx
  src/utils/components/MoveVMToFolderModal/MoveVMToFolderModal.tsx
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
  src/utils/components/SelectTypeahead/utils/constants.ts
  src/utils/components/SelectTypeahead/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2576 CNV-56949: tree view close button styling changes
  src/views/virtualmachines/tree/VirtualMachineTreeView.scss
  src/views/virtualmachines/tree/components/PanelToggleButton.tsx
  src/views/virtualmachines/tree/components/TreeViewContent.tsx
  src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
Labels: lgtm, approved, jira/valid-reference

#2500 CNV-57355: add test for cluster general settings
  cypress/cypress.config.js
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/tests/e2e/a-setup.cy.ts
  cypress/tests/e2e/b-overview.cy.ts
  cypress/tests/e2e/catalog-filter.cy.ts
  cypress/tests/e2e/check-tab-yaml.cy.ts
  cypress/tests/e2e/create-vm.cy.ts
  cypress/tests/e2e/d-networking.cy.ts
  cypress/tests/e2e/template-list.cy.ts
  cypress/tests/overview.cy.ts
  cypress/tests/overview/settings-cluster-general.cy.ts
  cypress/tests/overview/top-consumers-tab.cy.ts
  cypress/utils/const/index.ts
  cypress/views/nad.ts
Labels: approved, jira/valid-reference

#2572 CNV-57315: Remove unknown params from network checkup job
  src/views/checkups/network/utils/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2577 CNV-58541: add storage migration page
  locales/en/plugin__kubevirt-plugin.json
  plugin-extensions.ts
  plugin-metadata.ts
  src/utils/extension.ts
  src/utils/flags/consts.ts
  src/utils/flags/index.ts
  src/utils/flags/useStorageMigrationEnabled.ts
  src/utils/i18n.ts
  src/utils/resources/migrations/constants.ts
  src/utils/resources/migrations/utils.ts
  src/utils/utils/utils.ts
  src/views/storagemigrations/extensions.ts
  src/views/storagemigrations/list/StorageMigrationList.tsx
  src/views/storagemigrations/list/components/StorageMigrationRow.tsx
  src/views/storagemigrations/list/components/utils.ts
  src/views/storagemigrations/list/constants.ts
  src/views/storagemigrations/list/hooks/useStorageMigrationColumns.ts
  src/views/storagemigrations/list/hooks/useStorageMigrationResources.ts
  src/views/storagemigrations/list/utils.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/BulkVirtualMachineMigrationStatus.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationRollback.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/useMigrationState.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/useProgressMigration.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/utils.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils/migrateBulkVMs.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/utils/utils.ts
  src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.tsx
Labels: lgtm, approved, jira/valid-reference

#2581 Remove 1h debug sleep
  cypress/tests/all.cy.ts
  cypress/views/instance-flow.ts
  cypress/views/modals.ts
  test-cypress.sh
Labels: lgtm, approved

#2524 CNV-55151: Choose access and volume mode based on recommendations from StorageProfile
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/DiskModal/components/StorageClassAndPreallocation/StorageClassSelect.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/AccessMode.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/ApplyStorageProfileSettings.scss
  src/utils/components/DiskModal/components/StorageProfileSettings/ApplyStorageProfileSettings.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/RecommendationLabel.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/VolumeMode.tsx
  src/utils/components/DiskModal/components/StorageProfileSettings/utils.ts
  src/utils/components/DiskModal/components/utils/modesMapping.ts
  src/utils/constants/documentation.ts
Labels: lgtm, approved, jira/valid-reference

#2570 CNV-57651: Allow multiple affinity rules of the same type
  src/utils/components/AffinityModal/utils/helpers.ts
Labels: lgtm, approved, jira/valid-reference

#2583 CNV-60049: fix interface modal with udn
  src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
  src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts
  src/utils/resources/udn/constants.ts
  src/utils/resources/vm/utils/network/constants.ts
Labels: lgtm, approved, jira/valid-reference

#2591 CNV-58522: fix vm list paginations for pod proxy
  src/views/virtualmachines/list/VirtualMachinesList.tsx
Labels: lgtm, approved, jira/valid-reference

#2590 CNV-59236: hide project switch in treeview
  src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
  src/views/virtualmachines/tree/components/TreeViewContent.tsx
  src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
  src/views/virtualmachines/tree/hooks/useTreeViewData.ts
Labels: lgtm, approved, jira/valid-reference

#2588 CNV-59599: Pending changes detect nad interface
  src/utils/components/PendingChanges/utils/helpers.ts
Labels: lgtm, approved, jira/valid-reference

#2595 CNV-60420: update @patternfly/react-catalog-view-extension
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2586 CNV-56712: Fix network namespace handling in NetworkInterfaceNetworkSelect
  src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
  src/utils/components/NetworkInterfaceModal/utils/helpers.ts
Labels: lgtm, approved, jira/valid-reference

#2596 CNV-60407: folder input fix
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
Labels: lgtm, approved, jira/valid-reference

#2594 CNV-59218: disable non migratable storageclasses
  src/utils/utils/constants.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/useMigratableStorageClasses.ts
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationDestinationTab.tsx
Labels: lgtm, approved, jira/valid-reference

#2597 CNV-60448: Enable upstream runable in downstream
  cypress/support/commands.ts
  cypress/support/nav.ts
  cypress/tests/e2e/a-setup.cy.ts
  cypress/tests/e2e/check-tab-yaml.cy.ts
  cypress/tests/overview/overview-tab.cy.ts
  cypress/tests/overview/settings-cluster-general.cy.ts
  cypress/utils/const/index.ts
  test-cypress.sh
  test-prow-e2e.sh
Labels: lgtm, approved, jira/valid-reference

#2599 CNV-60409: don't hide Actions button and pagination in VM list
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineSelection/VirtualMachineSelection.tsx
Labels: lgtm, approved, jira/valid-reference

#2602 CNV-56565: Fix previewfeature canedit
  src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/PreviewFeaturesTab.tsx
Labels: lgtm, approved, jira/valid-reference

#2605 CNV-60576: show pvc storageclass
  src/utils/resources/vm/utils/selectors.ts
  src/views/virtualmachines/list/VirtualMachinesList.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
  src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
  src/views/virtualmachines/list/hooks/sortColumns.ts
  src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
  src/views/virtualmachines/utils/mappers.ts
  src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Labels: lgtm, approved, jira/valid-reference

#2574 CNV-59558: CNV-59559: fix disk modal CapacityInput
  locales/en/plugin__kubevirt-plugin.json
  src/utils/components/CapacityInput/CapacityInput.tsx
  src/utils/components/CapacityInput/utils.ts
  src/utils/components/DiskModal/components/DiskSizeInput/ExpandPVC.tsx
  src/utils/components/DiskModal/components/DiskSizeInput/usePVCDefaultSize.ts
Labels: lgtm, approved, jira/valid-reference

#2603 CNV-57378: Show completed QuickStarts in Getting Started card
  src/views/clusteroverview/OverviewTab/getting-started-card/quick-starts-section/QuickStartsSection.tsx
  src/views/clusteroverview/OverviewTab/getting-started-card/quick-starts-section/utils.ts
Labels: lgtm, approved, jira/valid-reference

#2604 CNV-60551: show no migratable pvcs in the migration list
  locales/en/plugin__kubevirt-plugin.json
  src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
  src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationDetails.tsx
Labels: lgtm, approved, jira/valid-reference

#2606 CNV-60543: Only show default columns if no kubevirtUserSettings values exist
  src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettingsTableColumns.ts
Labels: lgtm, approved, jira/valid-reference

#2593 CNV-60359: upgrade cypress version to 14.3.x
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-reference

#2601 CNV-60343: fix storagemigration link
  src/views/storagemigrations/extensions.ts
Labels: lgtm, approved, jira/valid-reference

#2608 CNV-57314: Display correct max latency value on network checkup page
  src/views/checkups/network/details/tabs/details/CheckupsNetworkDetailsPageSection.tsx
Labels: lgtm, approved, jira/valid-reference

#2612 CNV-60605: Fix rerendering all over vm details
  src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
  src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
Labels: lgtm, approved, jira/valid-reference
